### ISSUE TITLE
Homebrew version is old.

### ISSUE THREAD

**Issue by qatnonoil** [premake/premake-core#1002]
Hi.

I installed premake via Homebrew.
But version is too old.(I want to use latest premake5).
```
$ brew install premake
$ premake4 --version
premake4 (Premake Build Script Generator) 4.4-beta5
```

Thanks

**Comment by catb0t** [comment]
you'll have to download a prebuilt binary for macos from the website http://premake.github.io, or build this repository from source, since premake5 isn't released yet

**Comment by catb0t** [comment]
if you're concerned about end-user installs of people trying to use your pre-release premake5.lua, just ship 3 premake5 binaries with the distribution (32 bits, one for each major OS)

**Comment by samsinsane** [comment]
How does one update a Homebrew package that they didn't originally upload? I'm assuming that's the situation we're in at the moment?

**Comment by starkos** [comment]
Yup…I didn't set that up. Happy to add it the release procedures if someone can figure out the steps though.

**Comment by qatnonoil** [comment]
Okay, I'll ship with all binaries. Thanks.
