### ISSUE TITLE
C# SubType bug with UserControl

### ISSUE THREAD

**Issue by cosmy1** [premake/premake-core#1008]
C# projects with UserControls rebuilds everytime when re-running premake scripts.

The difference that causes the project to rebuilds is ```SubType```.
By analyzing compared files with ```int compare_file(const char* content, size_t length, const char* dst) ``` in ```os_writefile_ifnotequal.c``` I got:
![comparision](https://user-images.githubusercontent.com/1329119/36346139-1ff6eda6-1439-11e8-9855-8bbc5644a5a9.png)
_(On left ```content``` source and on the right the ```dst``` file)_

The bug seems caused by:
https://github.com/premake/premake-core/blob/0eda22c602567e8b2efb9f1ba104fa766d5adbd4/src/tools/dotnet.lua#L115-L118

Both Forms and UserControls have *.Designer.cs

**Comment by samsinsane** [comment]
You can override the `SubType` which is done just a few lines below here:
https://github.com/premake/premake-core/blob/0eda22c602567e8b2efb9f1ba104fa766d5adbd4/src/tools/dotnet.lua#L129-L135

You can do this by specifying [`buildaction "UserControl"`](https://github.com/premake/premake-core/wiki/buildaction) within a `filter` for the files. Other than that, I'm not sure if there's a change we can make other than assuming it's either `Form` or `UserControl`, do you have any suggestions for this or is being able to override enough?

**Comment by cosmy1** [comment]
Thank you! I solved my issue by specifying `buildaction "UserControl"`.
In projects with massive usage of UserControls could be annoying to filter each file.

Since the information is inside the C# file, the only way would be to analyze the class if inherits from `Form` or `UserControl` .

A way to understand which classes it inherits is to parse the C# source file.

**Comment by samsinsane** [comment]
I'm glad that resolved your issue. In projects with a massive usage of UserControls you can flip it around do:
```lua
buildaction "UserControl"
filter { "files:forms/**.cs" }
  buildaction "Form"
```

As for parsing source files, I personally think that's beyond the scope of Premake. I'm going to close this as resolved, but if any of the other core devs disagree regarding the scope, we can reopen this and discuss it more.

**Comment by tvandijck** [comment]
Yeah, I'm with Sam here... it's often easier to just structure your project accordingly...
something like this would make it really easy to distinquish things with minimal effort on the premake script side.

```lua
filter { "files:controls/**.cs" }
    buildaction "UserControl"
filter { "files:forms/**.cs" }
    buildaction "Form"
```

Pretty much what Sam suggested, but you don't want your normal C# files to all have the usercontrol build action is my guess..
