### ISSUE TITLE
Absolute Paths in Dynamic Linker

### ISSUE THREAD

**Issue by computerquip** [premake/premake-core#101]
http://stackoverflow.com/questions/30699971/how-to-prevent-absolute-paths-in-dynamic-linker

Unfortunately, this is blocking my project. Since I'm not explicitly specifying explicit paths, this is probably a bug.

**Comment by TurkeyMan** [comment]
Can you share your premake script? Hard to comment without seeing your setup.

**Comment by computerquip** [comment]
Unfortunately, I cant share much immediately. The best I can do is make a test case that causes the issue. Until then, can I ask what could be possible causes?

**Comment by computerquip** [comment]
Oh, I'll also try the suggestion on SO soon.

**Comment by computerquip** [comment]
The suggestion on SO appears to have fixed my issue. The flag "RelativeLinks" is not documented on the wiki however. I'm also not sure what the term "RelativeLinks" refers to in this case. Looking at the code, it seems to just use "-lmylibrary" instead of the other relative path of where the build occurred.

I don't think the current default behavior is very sane for Linux. Most people would be doing what I do (set an RPATH value) or installing the library into a system library path.

**Comment by starkos** [comment]
> I don't think the current default behavior is very sane for Linux

We started out using -L/-l and ran into all kinds of trouble distinguishing between static/shared libraries, and so switched to the current approach. Suggestions for improvement are always welcome.

I will take a note to document the flag, and otherwise I'll consider this one solved. Feel free to reopen if needed!
