### ISSUE TITLE
links per-project configurations

### ISSUE THREAD

**Issue by john-chapman** [premake/premake-core#1012]
Hi, I'd like to be able to link projects within a workspace with a per-project configuration setting. For example, this is possible in Visual Studio via the Configuration Manager:

![devenv_2018-02-27_16-10-06](https://user-images.githubusercontent.com/5657483/36736416-d5be3b98-1bd8-11e8-8e3e-f12b36e8b793.png)

At the solution level I can select which per-project configurations get built and linked. 

I don't see an obvious clean way to do this in premake. Is it possible? Could it be possible? Thanks in advance!

**Comment by starkos** [comment]
You can specify both configurations and platforms at both the workspace and project level, and then use configmap to map between the two. See [Configurations and Platforms](https://github.com/premake/premake-core/wiki/Configurations-and-Platforms) on the wiki for more info and examples. 

Does that help?

**Comment by john-chapman** [comment]
It's not quite what I'm after. I want to link a specific configuration of a project, something like this:
```lua
workspace "solution"
   configurations { "debug", "debug_optimized", "release", }
   project "static_lib"
      -- etc.

   project "application"
      filter { "configurations:debug" }
         links { "static_lib:debug" } -- build and link the 'debug' config of static_lib
      filter { "configurations:debug_optimized or release" }
         links { "static_lib:release" } -- build and link the 'release' config of static_lib
```
In this example I could also get what I want by creating a `debug_optimized` configuration for `static_lib` which just duplicates the `release` config. However I wondered if it was possible to target a specific config as a build dependency (since it's possible to set this up in VS).

**Comment by samsinsane** [comment]
As @starkos said, [`configmap`](https://github.com/premake/premake-core/wiki/configmap) is what you're after.

**Comment by starkos** [comment]
Untested, but I think you're looking for something like this:

```lua
workspace "solution"
   configurations { "debug", "debug_optimized", "release", }

   project "static_lib"
      -- etc.

   project "application"
      links { "static_lib" }
      -- etc.

   -- this can go in the "static_lib" or "applications" scripts, but is 
   -- commonly placed in the workspace script, since it maps workspace 
   -- configurations to a particular project
   project "static_lib"
      configmap { "debug_optimized" = "release" }
```

I'm going to mark this as closed, as I think it answers your question. But feel free to reopen with more questions or information.

**Comment by john-chapman** [comment]
Ah, this works perfectly. Thankyou!
