### ISSUE TITLE
Incorrect library path for multiple library build with gmake2 generator

### ISSUE THREAD

**Issue by alexandre-janniaux** [premake/premake-core#1027]
Hi,

I come back again because of linking issues within a project where multiple libraries are compiled, and then an executable is linked against them.

Compiling with ``make SILENT=`` and skipping the unnecessary object builds gives the following result:

```
==== Building chipmunk (debugdynamic_x64) ====
==== Building lua (debugdynamic_x64) ====
==== Building stb_image (debugdynamic_x64) ====
==== Building NazaraCore (debugdynamic_x64) ====
==== Building NazaraAudio (debugdynamic_x64) ====
==== Building NazaraUtility (debugdynamic_x64) ====
==== Building NazaraPlatform (debugdynamic_x64) ====
Linking NazaraPlatform
g++ -o "bin/x64/DebugDynamic/libNazaraPlatform-d.so"  obj/x64/DebugDynamic/NazaraPlatform/Cursor.o obj/x64/DebugDynamic/NazaraPlatform/CursorImpl.o obj/x64/DebugDynamic/NazaraPlatform/Display.o obj/x64/DebugDynamic/NazaraPlatform/Icon.o obj/x64/DebugDynamic/NazaraPlatform/IconImpl.o obj/x64/DebugDynamic/NazaraPlatform/InputImpl.o obj/x64/DebugDynamic/NazaraPlatform/Keyboard.o obj/x64/DebugDynamic/NazaraPlatform/Mouse.o obj/x64/DebugDynamic/NazaraPlatform/NewOverload.o obj/x64/DebugDynamic/NazaraPlatform/Platform.o obj/x64/DebugDynamic/NazaraPlatform/ScopedXCB.o obj/x64/DebugDynamic/NazaraPlatform/VideoMode.o obj/x64/DebugDynamic/NazaraPlatform/VideoModeImpl.o obj/x64/DebugDynamic/NazaraPlatform/Window.o obj/x64/DebugDynamic/NazaraPlatform/WindowImpl.o   -L../../../thirdparty/lib/common -L../../../lib -L../../../thirdparty/lib/common/x64 -L/usr/lib64 -m64 -shared -Wl,-soname=libNazaraPlatform-d.so -lX11 -lxcb -lxcb-cursor -lxcb-ewmh -lxcb-icccm -lxcb-keysyms -lxcb-randr -lNazaraCore-d -lNazaraUtility-d
/usr/bin/ld: cannot find -lNazaraUtility-d
collect2: error: ld returned 1 exit status
```

The link command line in a more readable fashion looks like this:

```
g++ -o "bin/x64/DebugDynamic/libNazaraPlatform-d.so"

obj/x64/DebugDynamic/NazaraPlatform/Cursor.o
obj/x64/DebugDynamic/NazaraPlatform/CursorImpl.o
obj/x64/DebugDynamic/NazaraPlatform/Display.o
obj/x64/DebugDynamic/NazaraPlatform/Icon.o
obj/x64/DebugDynamic/NazaraPlatform/IconImpl.o
obj/x64/DebugDynamic/NazaraPlatform/InputImpl.o
obj/x64/DebugDynamic/NazaraPlatform/Keyboard.o
obj/x64/DebugDynamic/NazaraPlatform/Mouse.o
obj/x64/DebugDynamic/NazaraPlatform/NewOverload.o
obj/x64/DebugDynamic/NazaraPlatform/Platform.o
obj/x64/DebugDynamic/NazaraPlatform/ScopedXCB.o
obj/x64/DebugDynamic/NazaraPlatform/VideoMode.o
obj/x64/DebugDynamic/NazaraPlatform/VideoModeImpl.o
obj/x64/DebugDynamic/NazaraPlatform/Window.o
obj/x64/DebugDynamic/NazaraPlatform/WindowImpl.o

-L../../../thirdparty/lib/common
-L../../../lib
-L../../../thirdparty/lib/common/x64
-L/usr/lib64
-m64
-shared
-Wl,-soname=libNazaraPlatform-d.so
-lX11
-lxcb
-lxcb-cursor
-lxcb-ewmh
-lxcb-icccm
-lxcb-keysyms
-lxcb-randr
-lNazaraCore-d
-lNazaraUtility-d
```

As you can see on the very first line, shared objects are built inside ``modules/bin/x64/DebugDynamic/libNazara`` whereas they are expected to be found at ``../../../lib``.

I don't know and have no real opinion about whether it should be left inside ``modules/bin/x64/DebugDynamic/libNazara`` as an independant build and would appreciate your feedback, but I can't deny the fact that premake doesn't take the library output into account at 100%, and not even right. 

With the gmake generator, libraries are built inside the ``../../../lib/gmake/x64/``` directory and correctly linked against.

Thank you for your feedback, if you agree that this is a bug, I will make a pull request to fix this behavior.

It might be linked or not to #974 but is still the same subject, and comes from this issue on Nazara: DigitalPulseSoftware/NazaraEngine#155

**Comment by tdesveauxPKFX** [comment]
I looked into it and the issue seems to originate from the project you are using.
As you can see [here](https://github.com/DigitalPulseSoftware/NazaraEngine/blob/master/build/scripts/common.lua#L16), the project configuration use filters on actions (including gmake action) but none of them include gmake2.

I tried using filters on gmake* instead of gmake so that the gmake rules applies to the gmake2 action and it seems to work as intended.

I hope this resolve your issue.

**Comment by alexandre-janniaux** [comment]
Perfect, thank you very much, I'm glad that you spent some time on the issue, it's very nice of you.

As expected, it fixes the issue.
