### ISSUE TITLE
vstudio static lib pdb

### ISSUE THREAD

**Issue by tdesveauxPKFX** [premake/premake-core#1032]
Hi,

I have a use case where we redist static libs and we want to redist pdbs for debug builds.
For this, we want to output the pdb next to our lib but the symbolspath api does not meet this use.

symbolspath will add a `ProgramDatabaseFile` element to the linker block, however staticlib projects use the librarian who does not use `ProgramDatabaseFile`.

What we do is add a `ProgramDatabaseFileName` element in the compile block for our static libs with the desired path. In the end, we have a pdb containing the needed debug infos.

This solution does not feel that "clean" to me so I'm not sure you'd want this in Premake.

If you are interested in a pull request that implement this behavior in the vstudio module, I'd be happy to submit one.

**Comment by starkos** [comment]
I have no objection to this approach, and off the top of my head am not aware of another workaround. +1 from me for a PR!
