### ISSUE TITLE
Question about Android in premake

### ISSUE THREAD

**Issue by redorav** [premake/premake-core#1038]
I was looking at the recent merge where Android support is added into premake, and quite excited about it so I went and tried it out. I created a workspace like

```lua
filter { "platforms:Android32"}
		system("android")
		toolset("clang")
		architecture("arm")
```

and the project is

```lua
project "projectname"
	kind("StaticLib")
	language("C++")
```

~~This creates a solution but the result is not the same as going to the New Project .. Cross Platform .. Native Activity Application in Visual Studio. It doesn't create a .androidproj or packaging file and also points to the Clang 3.8 compiler which is reported as not installed for me. I think this is because the ApplicationType is not set to Android in the vcxproj.~~

~~Am I doing something wrong? After exploring a bit more it seems android support in premake actually needs a Visual Studio plugin? Am I wrong in thinking this?~~

After playing a bit with it, it seems I need to add system("android") at project scope and I can't do it at workspace scope under a filter("platforms:PlatformName") condition. This is probably a bug. I've also managed to figure out kind("androidproj") is used to create the .androidproj file that builds the apk. I've gone and added that to the wiki.

**Comment by samsinsane** [comment]
> After playing a bit with it, it seems I need to add system("android") at project scope and I can't do it at workspace scope, even unconditionally.

Do you mean:
```lua
workspace "workspace"
  system "android"
```
or
```lua
system "android"

workspace "workspace"
```

I do the former in a personal project and it seems to work fine, but I'm still using the module separately. Looks like you figured out the other issues, sorry for the confusion, I should have updated the readme when I added VS2015 support.

There's still more to clean up with this module, and if I can get a chance, I'll add *some* `gmake`/`gmake2` support too - I can't replicate the `androidproj` behaviour, but in my incredibly limited experience, running ant was enough, though it required a change or two in one or more of the ant files. I haven't used the Gradle version yet, so I have no clue what's involved there.

**Comment by samsinsane** [comment]
Yeah, that's a limitation with VS. It requires a project to be classified as Android, which means it can't target any other platform at all. In the `vcxproj`, it's part of the "project" elements rather than any configuration block, like ARM/ARM64/x86/x64 would be.

**Comment by redorav** [comment]
I wonder if this is a little bit like my other question https://github.com/premake/premake-core/issues/936 where it looks like it's a global thing because VS doesn't do it through the UI but it can actually be done. I'll experiment a bit further.

**Comment by samsinsane** [comment]
Maybe? But I kind of doubt it based on how it references the project in the solution explorer, let me know how it goes though!

**Comment by redorav** [comment]
@samsinsane after playing around with the Visual Studio .vcxproj files I have figured out that this can be done, except in a slightly different way from what I thought it would be. The solution boils down to wrapping the affected properties belonging to the Globals group in a configuration condition that affects it project-wide. So instead of having a Globals label with no conditions, for this particular case one can create a new conditional Globals that sets the project type to Android, i.e. go from this

```xml
<PropertyGroup Label="Globals">
  <ProjectGuid>{972265CA-83DA-A617-ECE1-7F73D8B84108}</ProjectGuid>
  <IgnoreWarnCompileDuplicatedFilename>true</IgnoreWarnCompileDuplicatedFilename>
  <RootNamespace>unit_tests</RootNamespace>
  <ApplicationType>Android</ApplicationType>
  <ApplicationTypeRevision>3.0</ApplicationTypeRevision>
</PropertyGroup>
```

to this

```xml
<PropertyGroup Label="Globals">
  <ProjectGuid>{972265CA-83DA-A617-ECE1-7F73D8B84108}</ProjectGuid>
  <IgnoreWarnCompileDuplicatedFilename>true</IgnoreWarnCompileDuplicatedFilename>
  <RootNamespace>unit_tests</RootNamespace>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug Android|ARM'" Label="Globals">
  <ProjectGuid>{972265CA-83DA-A617-ECE1-7F73D8B84108}</ProjectGuid>
  <ApplicationType>Android</ApplicationType>
  <ApplicationTypeRevision>3.0</ApplicationTypeRevision>
</PropertyGroup>
```

and add that to all the relevant configurations. I wonder if there are perhaps other settings we think are VS limitations that may be fixable with this. I don't know how to translate this to premake code so I'd appreciate a bit of help as I think this is essential to getting a great Android experience with premake. I see there's a propertyGroup function that takes a configuration, but at the point where we call this for globals the cfg doesn't seem to be passed in. What do you think would be the best way to approach this? I'd be more than happy to tackle this with a bit of guidance.

**Comment by samsinsane** [comment]
I commented on your `systemversion` changes, I think this falls into the same category. I think it would be best to hold off on making these changes until the others have had a chance to decide if this is something that Premake should do. Thanks for looking into it though! This is definitely something I would be interested in utilizing - I have a solution that uses VS for Android, Linux, Windows and WinRT.

**Comment by tvandijck** [comment]
#1048 was merged, I'm assuming that resolves this issue?
