### ISSUE TITLE
Question about test.capture when writing tests

### ISSUE THREAD

**Issue by ratzlaff** [premake/premake-core#1047]
Is [test.capture](https://github.com/premake/premake-core/blob/master/modules/self-test/test_assertions.lua#L18) supposed to pass if what is captured() contains less lines than expected?

If I add this to [test_gmake2_file_rules](https://github.com/premake/premake-core/blob/master/modules/gmake2/tests/test_gmake2_file_rules.lua), it doesn't tell me it fails.

```lua
	function suite.IncompleteCapture()
		files { "src/hello.c", "src/test.cpp" }
		prepare()
		test.capture [[
# File Rules
# #############################################
		]]
	end
```

I am running the test action with the command:
`$ ./bin/release/premake5 test`
in the folder I clone premake-core to

I tried changing `while etxt` to `while atxt` in [test_assertions](https://github.com/premake/premake-core/blob/master/modules/self-test/test_assertions.lua#L29) but that gave me a lot more failures.

**Comment by samsinsane** [comment]
Yes, `test.capture` will check for matches until the end of your supplied string. This functionality is relied on in various places, I thought there was another function that did what you're after though. Perhaps I'm wrong.

**Comment by samsinsane** [comment]
I guess you could access `p.captured()`?
```lua
if p.captured() != [[
# File Rules
# #############################################
]] then
  test.fail(...)
end
```

**Comment by ratzlaff** [comment]
Ah alright, just making sure its intended to work like that. It was super weird when I would copy an existing test, add another file in the `file { ... }` block and nothing would fail. 

Thanks!
