### ISSUE TITLE
Generated Visual Studio 2005 projects have conflicting properties

### ISSUE THREAD

**Issue by natrist** [premake/premake-core#1051]
Using Premake 5.0.0-alpha-12 to build for vs2005 targeting Windows 7:
Everything seems to work and then VS warns that:
Warning	1	Command line warning D9025 : overriding '/MT' with '/MD'	cl
Warning	2	Command line warning D9025 : overriding '/MT' with '/MD'	cl

for both my projects...

When I debug, it says that my program wasn't built with debug information and when I try to run any of the binaries it says that I'm missing MSVCR80.dll, which I clearly have.

If I put the DLL in the bin folder I get the following error:
R6034: An application has made an attempt to load the C runtime library incorrectly.

**Comment by natrist** [comment]
premake5.lua:

`-- Generate the 'Storm' workspace (a.k.a. Visual Studio solution)
workspace "Storm"
	configurations { "Debug", "Release" }
	location "Build"

-- Generate the 'ConsoleStorm' project
-- This project is used for testing the Storm library from within the IDE
project "ConsoleStorm"
	kind ("ConsoleApp")
	language "C++"

	files "Source/ConsoleStorm.cpp"
	includedirs { "Source/H" }
	links { "StormLib" }

-- Generate the 'StormLib' project
-- This is the main library project, containing the preciouuus
project "StormLib"
	kind ("StaticLib")
	language "C++"

	-- Generic build steps
	-- This needs to be set before platform-specific steps or it will not run
	-- Possible Premake bug?
	files { "Source/*.cpp" }
	-- We include all files under Source/H to create the Visual Studio filter for header files
	files { "Source/H/**" }
	removefiles { "Source/ConsoleStorm.cpp" }
	includedirs { "Source/H" }

	-- Windows ONLY build steps
	filter "system:windows"
		files { "Source/W32/*.cpp" }
	
	-- Linux ONLY build steps
	filter "system:linux"
		files { "Source/Linux/*.cpp" }
	
	-- MacOS ONLY build steps
	filter "system:macosx"
		files { "Source/Mac/*.cpp" }
`

**Comment by samsinsane** [comment]
I don't have VS2005, so I can't verify much locally. Can you put this at the top of your premake5.lua and let me know if that resolves the issue.
```lua
require "vstudio"
premake.override(premake.vstudio.vc200x, "VCCLCompilerTool", function(oldfn, cfg, toolset)
	oldfn(cfg, iif(toolset == premake.tools.msc, nil, toolset))
end)
```

**Comment by natrist** [comment]
Thanks for responding.
I tried the line from your last message and it fixed some warnings, but I'm still getting a run-time error saying MSVCR80.dll is missing from my computer. Before you ask, if I manually create the project under Visual Studio, everything works fine.

**Comment by samsinsane** [comment]
My little snippet above doesn't solve *everything* but if you replace it with the following, it *should* fix everything for you.

```lua
require "vstudio"
premake.override(premake.vstudio.vc200x, "tools", function(oldfn, cfg)
	local toolset = premake.config.toolset(cfg)
	premake.callArray(premake.vstudio.vc200x.elements.tools, cfg, iif(toolset == premake.tools.msc, nil, toolset))
end)

filter { "configurations:debug" }
	symbols "On"
filter { }
```

There's two issues:
1. A toolset is always set now - I believe there was a Clang/GCC issue with something
2. Symbols doesn't default to being on for the debug configuration

Specifying the toolset in VS2005/2008 disables a bunch of elements and settings, I imagine this is due to the Xbox360/PS3 support. I can probably submit a patch for this, but I'm not really sure how long we'll be supporting VS2005 and VS2008 given they're both no longer supported by Microsoft.

**Comment by natrist** [comment]
@samsinsane Hey, thanks for that. I've the settings from your last comment and it works great now.
Is there any way I can apply them **only** to Windows/Visual Studio 2005 build target?

**Comment by samsinsane** [comment]
The filter can simply be changed to `filter { "configuration:debug", "action:vs2005", "system:windows" }`, as for the override changes.
```lua
premake.override(premake.vstudio.vc200x, "tools", function(oldfn, cfg)
  if _ACTION == "vs2005" and os.istarget(p.WINDOWS) then
    local toolset = premake.config.toolset(cfg)
    premake.callArray(premake.vstudio.vc200x.elements.tools, cfg, iif(toolset == premake.tools.msc, nil, toolset))
  else
    oldfn(cfg)
  end
end)
```

**Comment by natrist** [comment]
I get the following error message on Linux:
Error: [string "src/base/_foundation.lua"]:135: attempt to index a nil value (local 'scope')

**Comment by samsinsane** [comment]
That's usually what happens when you don't `require "vstudio"`, have you put this at the top of your premake5.lua? It might not be that, but that's where I usually put it and I've never had this issue.
