### ISSUE TITLE
Strange combinations of configurations and platforms

### ISSUE THREAD

**Issue by dgregorycryptic** [premake/premake-core#107]
With premake5.lua contents like this:

```lua
solution "Foo"
	location "FooDir"
	configurations {"Debug", "Release"}
	platforms {"Win32", "x64"}

	filter "platforms:Win32"
    	architecture "x86"

  	filter "platforms:x64"
	    architecture "x64"

	project "BarLib"
		location "libs/BarLib"
		kind "StaticLib"
		language "C++"
		files {"AutoGen/*AutoGen*.c", "*.c"}
```

And after running premake5 vs2012, I get the following output snippet in BarLib.vcxproj:

```xml
...
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug Win32|Win32">
      <Configuration>Debug Win32</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug Win32|x64">
      <Configuration>Debug Win32</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Win32">
      <Configuration>Debug</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release Win32|Win32">
      <Configuration>Release Win32</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release Win32|x64">
      <Configuration>Release Win32</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Win32">
      <Configuration>Release</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
...
```

And Foo.sln contains the following snippet:

```
...
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{919BEEA8-7D3D-197F-66F8-2CD35239A0CF}.Debug|Win32.ActiveCfg = Debug Win32|Win32
		{919BEEA8-7D3D-197F-66F8-2CD35239A0CF}.Debug|Win32.Build.0 = Debug Win32|Win32
		{919BEEA8-7D3D-197F-66F8-2CD35239A0CF}.Debug|x64.ActiveCfg = Debug|x64
		{919BEEA8-7D3D-197F-66F8-2CD35239A0CF}.Debug|x64.Build.0 = Debug|x64
		{919BEEA8-7D3D-197F-66F8-2CD35239A0CF}.Release|Win32.ActiveCfg = Release Win32|Win32
		{919BEEA8-7D3D-197F-66F8-2CD35239A0CF}.Release|Win32.Build.0 = Release Win32|Win32
		{919BEEA8-7D3D-197F-66F8-2CD35239A0CF}.Release|x64.ActiveCfg = Release|x64
		{919BEEA8-7D3D-197F-66F8-2CD35239A0CF}.Release|x64.Build.0 = Release|x64
	EndGlobalSection
...
```

Note what's wrong: a configuration that has the platform concatenated onto it, and then the platform again concatenated.

```
Debug Win32|Win32
Debug Win32|x64
Release Win32|Win32
Release Win32|x64
```

Am I doing something wrong, or is this a bug?

**Comment by starkos** [comment]
This does look like a bug. We do concatenate the build configuration and platform to produce unique project configuration names, but there is a special case for the Win32 and x64 identifiers to skip that step, since they will be represented by the architecture. I'll take a look into it.

**Comment by TurkeyMan** [comment]
The bit that looks weird to me, is that the project is populated with 8 configurations, but there are only 4 combinations... the solution only seems to have the appropriate 4 combinations though.

**Comment by dgregorycryptic** [comment]
To be clear, the sln is wrong also. Look on the right side.  4 of the 8 lines have the incorrect extra "Win32" on the left of the vertical bar.

**Comment by TurkeyMan** [comment]
Yeah, it's not ideal that that's there, but it's not really broken; the sln matches the project, and it will work, it's just not 'right' :)
The project emitting twice as many configurations, half of which are not referenced is definitely wrong.

**Comment by starkos** [comment]
> it's not ideal that that's there, but it's not really broken

I would like to have a look at this one, just haven't had a chance yet. This project is supposed to be generating "Debug|Win32", "Debug|x64", "Release|Win32", and "Release|x64".

**Comment by TurkeyMan** [comment]
Yeah, sorry, I accidentally pressed the 'close and comment' button, when I meant to hit the 'comment' button ;)

**Comment by dgregorycryptic** [comment]
The bug is in vstudio.projectPlatform(cfg) in _vstudio.lua.
pltarch is Win32
cfgarch is x86
They are not equal, so platform does not get set to nil.  Therefore it returns cfg.buildcfg .. " " .. platform.

**Comment by dgregorycryptic** [comment]
A little further up the chain, the bug seems to be that we're not passing true in the win32 param for the function vstudio.archFromConfig(cfg, win32).

However, there needs to be some consistifying of other callers.  I'm trying to decipher in what situations we want to pass true here.

**Comment by dgregorycryptic** [comment]
Ok, I have a fix for the problem, but the tests are not working (4 failures).  Something is making the test generate a sln with the line (for instance)
                {C9135098-6047-8142-B10E-D27E7F73FCB3}.Debug|x86.ActiveCfg = Debug x86|Win32
Seems like something about the test isn't quite valid.  Looking.

**Comment by dgregorycryptic** [comment]
My fix isn't valid according to the tests. It looks like if I pass true down to archFromConfig, x86 won't properly imply the Win32 platform.

I think there needs to be a little more information passed around if you want implicit architectures to work at the same time as explicit ones.

**Comment by TurkeyMan** [comment]
@starkos I wonder if it's related to the x32->x86 changes?

**Comment by starkos** [comment]
Those diffs look fine to me, so I don't think so. I'm trying to find a bit of time to investigate, haven't had a chance yet.

**Comment by starkos** [comment]
I think pull request #113 should fix it. Reopen if not!

**Comment by Trass3r** [comment]
> We do concatenate the build configuration and platform to produce unique project configuration names, but there is a special case for the Win32 and x64 identifiers to skip that step
It's understandable that you'd need to do that for IDEs not having a separate platforms thing but why also for VS?

If I define an actually custom platform like
```
configurations { "Debug", "Release" }
platforms { "x64", "avr" }
```

I get a weird setup with 4 configurations and Win32+x64 as platforms.
The only valid combinations then are "Win32 + avr configs" and "x64 + non-avr", becoming clear with a makefile project for example where invalid combinations are set to Application instead of makefile:
```
  project "rerunpremake"
  files { "premake5.lua" }
   kind "Makefile"
```

**Comment by starkos** [comment]
If you are experiencing an issue, please open a new ticket. This one is closed. Thanks!
