### ISSUE TITLE
Httpbin moved to https, unit tests failing

### ISSUE THREAD

**Issue by nsprljan** [premake/premake-core#1073]
In premake-core/tests/base/test_http.lua there are http-get tests that access http://httpbin.org, but that's not available any more.
In https://stackoverflow.com/questions/50068127/http-only-site-to-test-rest-requests suggestion is to use  http://eu.httpbin.org instead, so that's the easiest replacement... before that stops working too.

**Comment by nsprljan** [comment]
Well, http://httpbin.org is back so it all works again. Could be one off, could be intermittent, don't know. Tweets at https://twitter.com/search?q=httpbin&src=typd seemed to indicate it's permanent, but I am starting to suspect Twitter is not always right ;)

**Comment by starkos** [comment]
Thanks for pointing this out! It will be handy to have these links if it goes down again.
