### ISSUE TITLE
Support setting UUID for a group

### ISSUE THREAD

**Issue by tfoleyNV** [premake/premake-core#1082]
I had hoped that I could use the `uuid()` function after a `group()` to specify a stable UUID for a group:

```lua
group "tools"
uuid "ABCD-..."
```

This doesn't appear to work, and so the UUIDs for groups in the generated Visual Studio solution end up changing when I regenerate.

I'd like to be able to set the UUID of a group as in the above code, or even better have an option where premake just generates stable UUIDs for everything in the workspace based on a hash of their names and a single workspace-specific random seed.

**Comment by tfoleyNV** [comment]
Never mind. I just tried to delete and rebuild the solution now and got the same UUIDs, so this was user error.

I was trying to reproduce a hand-written VS solution using premake, and so I must have been looking at a diff of the hand-written and generated solutions, not two successive generated files. Sorry for the mistake.

**Comment by samsinsane** [comment]
No worries, easy mistake to make - I've done it too, several times.
