### ISSUE TITLE
Commit c92c7a595ee7e8a19f30bc1cb37451a9208538e3 changes the default project that Visual Studio comes up with when opening the solution

### ISSUE THREAD

**Issue by manxorist** [premake/premake-core#1088]
Commit c92c7a595ee7e8a19f30bc1cb37451a9208538e3 by @tvandijck changes the default project that Visual Studio comes up with when opening the solution.
Before that commit, it was the first project listed in the premake file. This commit supposedly wanted to improve determinism, however I fail to see why sorting would be necessary there, as the order is already determined by the order in which the projects inside a workspace/solution are listed.
I would prefer that this commit be reverted until there is some way to specify the default project, because otherwise this is a regression with regard to features: Having the wrong project selected by default requires users to manually change that inside of Visual Studio before they can even start running/debugging the project in the quite common case of a single main executable and various libraries inside of one solution.

**Comment by samsinsane** [comment]
I believe what you're looking for is [`startproject`](https://github.com/premake/premake-core/wiki/startproject).

@tvandijck could you provide a bit of context for the commit? If I remember correctly, you were dealing with a situation where hundreds of projects being added would cause the order to occasionally change? I vaguely recall there were a number of determinism patches in relatively quick succession, so I could be thinking of a different one. :+1:

**Comment by manxorist** [comment]
Thanks, `startproject` works for me. How did I miss that in the documentation?
Anyway, this issue can be closed.

**Comment by manxorist** [comment]
As I can specify the default project via `startproject`, I do not mind the projects getting ordered in whatever deterministic way that premake sees fit, thus from my side, there is no need to revert now that I'm aware of that option.

Did someone check what Visual Studio itself generates when adding multiple projects to a solution from the GUI? If Visual Studio orders them in some way, premake should probably do the same (except for the startproject).

**Comment by starkos** [comment]
> I think this particular change, came from a misunderstanding of where this random ordering came from. While it certainly fixed the problem, I think @manxorist is right in that premake by default just maintains the order in which projects are defined.

I can confirm that projects, and all child containers, are iterated as arrays under the hood, not tables. The ordering should match the order in which they were defined in the script.

Hope that helps…
