### ISSUE TITLE
v110_xp platform toolset

### ISSUE THREAD

**Issue by dgregorycryptic** [premake/premake-core#109]
I am trying to produce a .vcxproj for VS2012 that supports both Win32 and x64 targets, and produces Windows XP compatible executables for the Win32 version.  The only way this is possible is to mix both v110 and v110_xp platform toolsets in this .vcxproj.

I am looking to see if it's possible to expand the acceptable list of platform toolsets to include v110_xp.
[MSDN link describing v110_xp](https://msdn.microsoft.com/en-us/library/jj851139.aspx)

It seems like an action is bound to only provide one platform toolset for any code generation 'session', so I'm not sure the architecture of premake even would allow this as it is.

Any thoughts about this?

**Comment by tvandijck** [comment]
we just added this to our scripts.

premake.override(vc2010, "platformToolset", function(base, cfg)
                if _ACTION == "vs2012" then
                    _p(2,'<PlatformToolset>v110_xp</PlatformToolset>')
                elseif _ACTION == "vs2013" then
                    _p(2,'<PlatformToolset>v120_xp</PlatformToolset>')
                elseif _ACTION == "vs2015" then
                    _p(2,'<PlatformToolset>v140_xp</PlatformToolset>')                    
                else
                    base(cfg)
                end
            end)

which you can obviously make conditional on a setting... extend at will ;)

**Comment by starkos** [comment]
Toolsets are specified per configuration…wouldn't this work (untested)?

```lua
solution "MySolution"
   configurations { "Debug", "Release" }
   platforms { "Win32", "x64" }  -- not sure how you are actually specifying these

   filter "platforms:Win32"
      toolset "v110_xp"

   filter "platforms:x64"
      toolset "v110"  -- default, so might not actually be needed?
```

**Comment by dgregorycryptic** [comment]
That is exactly what I tried, but "v110_xp" is not a supported platform toolset out of the box.  And it looks like each version of visual studio supports one toolset only.  I can't extend it to a list.  As far as I know?

**Comment by starkos** [comment]
> That is exactly what I tried, but "v110_xp" is not a supported platform toolset out of the box.

Are you running against the latest sources? I've no trouble setting that value here.

**Comment by dgregorycryptic** [comment]
I have the latest sources as of this past Wednesday.

I worked around the issue with Tom's fix above, and some other code.

**Comment by starkos** [comment]
Okay, I'll close this out, feel free to re-open with new information. Still think my example should work.

**Comment by dgregorycryptic** [comment]
This is now working with the latest alpha release, FYI.
