### ISSUE TITLE
premake5 test run specific tests

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#1114]
`premake5 test [testnames...]` should allow to run specific test(/s).

**Comment by tdesveauxPKFX** [comment]
There is the `test-only` option. But I think it can only take one test at a time.

**Comment by samsinsane** [comment]
`test-only` will take a suite or a specific test, and it doesn't do wildcard matching. Extending `test-only` to take a comma delimited list and probably wildcard matching would be pretty cool for module testing, amongst other things.

**Comment by tvandijck** [comment]
closing, `--test-only=` works fine, it could be extended. Feel free to do so.

**Comment by starkos** [comment]
Both? The `--test-only` flag isn't really needed, and it would be handy to be able to specify a select set of tests.
