### ISSUE TITLE
Solution project paths are mapped incorrectly

### ISSUE THREAD

**Issue by JSandusky** [premake/premake-core#1121]
Occurs in master built for Win-x64, does not occur in the last release (5.0.0 Alpha 12 Windows).

Edit: for generating VS2015 sln/projects.

Given code like the following:

    workspace "Pylon"
        location "../."

    project "MathGeoLib"
        location "../Generated"

with a folder structure of:

    - Root
        - premake5.exe
        - premake5.lua
        - Premake
            - _Pylon.lua
             - ... more build scripts ...
            - MathGeoLib.lua
            - ... more build scripts ...

The intent is for the solution file to be placed in the project's root directory and the projects into a *Generated* folder in the *root*. 

With the last release of Premake5 this worked. Checked out yesterday and built from source this now emits a solution file whose paths are all written along the lines of:

    Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "MathGeoLib", "..\Generated\MathGeoLib.vcxproj", "{C19A7F90-AD52-C1DD-165A-9A3902315CCE}"
    EndProject

when it should be:

    Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "MathGeoLib", "Generated\MathGeoLib.vcxproj", "{C19A7F90-AD52-C1DD-165A-9A3902315CCE}"
    EndProject

Only the solution paths are incorrect. Everything else is working fine (include paths, link targets, etc). Manually fixing the paths works as a work-around.

**Comment by tdesveauxPKFX** [comment]
It looks like there is an issue in path.normalize with path ending with `.`

I will try to patch it but in the mean time you can simply remove the trailing `.` in your workspace location.

**Comment by samsinsane** [comment]
This should be fixed in master, @JSandusky are you able to confirm that this has resolved your issue?

**Comment by JSandusky** [comment]
@samsinsane, yes - it does fix it.
