### ISSUE TITLE
trying to cross compile for linux aarch64 / adding new target os?

### ISSUE THREAD

**Issue by joeroback** [premake/premake-core#1123]
hi. i need to need a new target, tegra, for nvidia aarch64 architecture, for cross-compiling.. it seems like the only way to reasonably do this is add another os target so I can call `premake5 --os tegra` so that when premake is perform prebuild commands, it can know its target is linux arm, knowing just "linux" is not enough, ARM vs x86_64...

Is there an easy way to add another "OS" to the `--os` flag without rebuilding premake5 from scratch? Is there another way to achieve what I am trying to do, cross compile and have premake5 know the desired target OS + architecture?

Thanks

**Comment by samsinsane** [comment]
I'm not really sure what's involved in targeting NVidia Tegra, but you could try something like:
```lua
workspace "wks"
  platforms { "ARM64" } -- I think we have this in master now
  configurations { "Debug", "Release" }
  ...
  project "prj"
    …
    filter { "platforms:ARM64" }
      -- All of your Tegra-specific settings
```

Alternatively, if you're targeting multiple aarch64 devices, you can either add new `platforms` or have a configuration for each one.

Finally, to add new values:
```lua
-- Overriding an API
premake.api.addAllowed("system", { "tegra" })

-- Overriding an option
table.insert(premake.option.get("os").allowed, { "tegra", "NVidia Tegra" })
```

**Comment by joeroback** [comment]
Awesome, that worked!
```lua
-- Overriding an API
premake.api.addAllowed("system", { "tegra" })

-- Overriding an option
table.insert(premake.option.get("os").allowed, { "tegra", "NVidia Tegra" })
```
Thanks!
