### ISSUE TITLE
Is there any convenient way to copy link libs to bin folder?

### ISSUE THREAD

**Issue by ntsjun** [premake/premake-core#1124]
My project depends some static libs. When build finished, the exe file is in "targetdir",but lib files not be copied to the targetdir. Is there any convenient way to copy libs to targetdir, just like copylocal function?

**Comment by samsinsane** [comment]
Do you need to ship your static libraries with your application? This seems like a very strange request.

Something, like this would do the job I guess:
```lua
-- I'm fairly certain you'll need to use path.translate
-- Also, these paths need to be absolute, or relative to the location of the vcxproj
postbuildcommands { 'xcopy /f /d /y "path\\to\\lib\\name.lib" "%{path.translate(cfg.targetdir)}"' }
```

**Comment by ntsjun** [comment]
@samsinsane  sorry, my description is not clear. The static libraries needs some dynamic libs, like 'libssl.dylib' etc. Thanks for you script.
