### ISSUE TITLE
VS can't find projects files

### ISSUE THREAD

**Issue by Faymoon** [premake/premake-core#1127]
When i generate a VS 2017 solution with premake5 it works, but when i want to compile it solution VS says to me that he can't find all the files of the project.
Any idea ?

**Comment by starkos** [comment]
Most likely a bug in your Premake script, but you haven't provided enough information.

- What are the file paths in the Visual Studio project?
- What are the actual paths on the file system?
- How have you specified the files in your Premake script?
- Where do the files live on the file system, relative to your Premake script?
- Can you provide a *minimal* sample that demonstrates the problem?

(That last one is where the bugs usually get found).

**Comment by samsinsane** [comment]
Closing this as there hasn't been a reply in over a month. If you're still experiencing this issue please feel free to reopen this.
