### ISSUE TITLE
Exclude %(AdditionalDependencies) from linker dependencies

### ISSUE THREAD

**Issue by mendsley** [premake/premake-core#1128]
On xb1 builds, we need a way to exclude the %(AdditionalDependencies) entry from the linker dependencies. In order to support this without having to completely re-implement the vc2010.additionalDependencies function, my initial thought was adding an additional argument to the function to control this behavior.  While this would work in our local case, I'm not sure of the wider implications on such a change.

Is there a better way to handle this that I'm missing?

https://github.com/premake/premake-core/blob/30ab62418200473203182e3f886bc09de59486bd/modules/vstudio/vs2010_vcxproj.lua#L1316

**Comment by mendsley** [comment]
That's what we've been doing - just something I noticed while cleaning up the module. Unlike the bulk of overrides, it has to copy a non-trivial amount of code from core just to strip that last bit. I'm fine leaving it as is, though.

**Comment by samsinsane** [comment]
You could override `vc2010.additionalDependencies` and inside of that override, override `m.element` and remove `%(AdditionalDependencies)` from the third parameter, then restore the original `m.element`. It's simpler than copying the entire function and then keeping it updated all of the time. Here's a quick example of what I mean:
```
premake.override(…, "additionalDependencies", function(oldfn, …)
  premake.override(…, "element", function(oldfn, element, config, value, links) -- last param is technically … but we know it's links here
    -- strip %(AdditionalDependencies) from value
    oldfn(element, config, newValue, links)
    m.element = oldfn
  end)
  oldfn(…)
end)
```
It's pretty ugly, but I personally find this to be superior to copying the entire function and keeping it updated all the time.

**Comment by starkos** [comment]
```lua
premake.override(premake.vstudio.vc2010, 'additionalDependencies', function (base, cfg, explicit)
   local result = premake.capture(function ()
      base(cfg, explicit)
   end)
   result = result:gsub(';%%%(AdditionalDependencies%)', '')
   return result
end)
```

**Comment by samsinsane** [comment]
Show off 😛 I'll have to remember this for future use!
