### ISSUE TITLE
error run premake5 on windows

### ISSUE THREAD

**Issue by kochol** [premake/premake-core#1130]
I get this error every time I execute premake5.exe
Error: [string "src/base/api.lua"]:380: bad argument #1 to 'getabsolute' (string expected, got nil)

Premake 5 works on my another pc

**Comment by starkos** [comment]
This sounds like a problem with your script, especially since it works on another system. Are you relying on any variables that could be nil on one system and not the other? Can you produce a *minimal* sample that reliably demonstrates the problem?

**Comment by kochol** [comment]
Yes, you are right the problem was with my script.
Thank you for your help.
