### ISSUE TITLE
Are there any plans to update the C++ version?

### ISSUE THREAD

**Issue by panhaowen** [premake/premake-core#1138]
Now that win/macos/linux platforms have fully supported the C++17 feature, Can you support it as soon as possible?

such as:
vs2017: std:c++latest -> std::c++17
xcode4: c++1z -> c++17

emmm...  'constexpr if' and 'variant' are too convenient to use

**Comment by samsinsane** [comment]
You mean like [this](https://github.com/premake/premake-core/blob/fec912ddac933fe96a440868f5ad5f663d1052cd/modules/vstudio/vs2010_vcxproj.lua#L1375-L1376), [this](https://github.com/premake/premake-core/blob/fec912ddac933fe96a440868f5ad5f663d1052cd/src/tools/gcc.lua#L163) and then #1003? For Xcode, if you need it now, you can just change it locally until it's merged in `premake.modules.xcode.cppLanguageStandards["C++17"] = "c++17"`.

**Comment by samsinsane** [comment]
Closing as this is now fixed.
