### ISSUE TITLE
[VS2017] Catastrophic failure after switching configuration

### ISSUE THREAD

**Issue by wobbier** [premake/premake-core#1139]
I have a few externalprojects setup in my solution and when I switch from Debug to Release or vice versa I get a "Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))" message for each external project.

After switching, restarting visual studio is the only way to build a different configuration.

My current premake script:
https://github.com/wobbier/MitchEngine/blob/master/Tools/premake.lua

**Comment by tdesveauxPKFX** [comment]
Can't see anything wrong in your Premake script.

Can you take a look to visual log files for more information? This looks like a serious issue but there is not much to track what caused it.

**Comment by wobbier** [comment]
I started visual studio with /log and I'm not getting the error now, even after I removed the /log launch param on devenv.exe 🤔

Tested with a fresh pull of my repo

**Comment by tdesveauxPKFX** [comment]
Well, that's good I guess?

I'm closing this for now. If you encounter the issue again, feel free to reopen.
