### ISSUE TITLE
premake5 download to Windows - unable to run

### ISSUE THREAD

**Issue by SMSteven** [premake/premake-core#1141]
I use a Windows 10 64-bit PC. I downloaded the premake5 Windows binary and tried to run it, but it says "unable to run". This may be a 32-bit / 64-bit issue. I don't see separate options on the premake Downloads page for these 2 versions.

premake4 runs OK.

**Comment by samsinsane** [comment]
I can't see any reason why it would be a 32/64 bit issue. I've just tried it on my machine, also Win10 and 64bit, and it worked fine. Do you happen to have an antivirus program installed? We've had issues with them before, so it's possible that's the issue.

**Comment by SMSteven** [comment]
I'm using Windows Defender (which is a Microsoft inbuilt product). I keep it up-to-date on a weekly basis.

**Comment by SMSteven** [comment]
I should also add an important fact: I'm using `msys` on Windows 10 and premake5 was invoked within `msys`. Could that be the problem?

(premake4 had also been invoked from `msys` but it worked there.)

**Comment by samsinsane** [comment]
I also use Windows Defender, but only experienced an issue once. I also use Git Bash which I believe is msys, so I don't think that's an issue. I'm quite stumped, are you able to build Premake yourself and run that?

**Comment by SMSteven** [comment]
Actually, I downloaded the binary and ran that directly. I haven't tried building premake yet.

**Comment by tdesveauxPKFX** [comment]
Just tried with the alpha12 release on a Win10 64bits with msys and everything works fine.

Maybe the issue originate from your lua configuration?
Did you try with a simple `premake5.lua`?

**Comment by SMSteven** [comment]
Well, I have tried it again. Now, it's working. I have no idea why premake5 wasn't working earlier and just premake4 was. But now, I confirm both are working. The command I tried (both times) was simply either `premake4 --help` or `premake5 --help`. This issue can be closed.
