### ISSUE TITLE
kind "None" doesn't build on Linux

### ISSUE THREAD

**Issue by RicoP** [premake/premake-core#1149]
I like to add a project that just holds config stuff for my repository. In order to achieve that I add a project with the kind flag set to "None".

that works fine for Visual Studio on windows, but with gcc and clang I get the errors 
`error: no input files`

I can explicitly exclude the config project with an if but is this necessary. I made a example repository to show what I mean.

https://github.com/RicoP/premake_bug_test
build output: https://travis-ci.org/RicoP/premake_bug_test/jobs/416303302#L495

**Comment by RicoP** [comment]
premake probably should just not create a make file for those kind of projects.

**Comment by ClxS** [comment]
We had what I think is related issues on Visual Studio even. We created a new set of "pubx" (i.e. publinks), which linking projects inherit. If we link against a project of kind `None`, it'll usually that it couldn't find the .lib for that project. Have you tried using kind `Utility` @RicoP ? That worked in our case.
