### ISSUE TITLE
VS2017 project targeting Linux

### ISSUE THREAD

**Issue by MacGamerFR** [premake/premake-core#1150]
Since VS2017 it is possible to create linux target project. I did not find anyting about it on the premake project.
How can it be handled with premake5 currently ?

**Comment by samsinsane** [comment]
I wrote [this module](https://github.com/LORgames/premake-vslinux) when I was trying it out in VS2015, it might need some work to get it working in VS2017 too. Hope this helps!

**Comment by samsinsane** [comment]
I'm going to close this, as the question has been answered and I don't think the module should be merged until the VS extension is improved greatly.
