### ISSUE TITLE
Generated make files are not compilable by MinGW

### ISSUE THREAD

**Issue by vmirgorod** [premake/premake-core#1156]
Steps:
1. Install MinGW
2. Run premake5 gmake
3. Run mingw32-make

Errors:
C:\Users\Slava\Documents\capto-sdk-cxx>mingw32-make CoreStatic clean
"==== Building CoreStatic (debug_x32) ===="
AssemblyTypes.cpp
Подпапка или файл obj\\x32\\Debug\\CoreStatic уже существует.
CoreStatic.make:253: recipe for target 'obj/x32/Debug/CoreStatic/AssemblyTypes.o' failed
mingw32-make[1]: *** [obj/x32/Debug/CoreStatic/AssemblyTypes.o] Error 1
Makefile:40: recipe for target 'CoreStatic' failed
mingw32-make: *** [CoreStatic] Error 2

System message "Подпапка или файл obj\\x32\\Debug\\CoreStatic уже существует." means that directory is already exist.

Apparently, instead of plain MKDIR (-p option is not supported on Windows) solution from there https://stackoverflow.com/questions/4165387/create-folder-with-batch-but-only-if-it-doesnt-already-exist should be used.

**Comment by samsinsane** [comment]
#1111 might be of value to you? @tdesveauxPKFX would have a better idea than myself.

**Comment by tdesveauxPKFX** [comment]
Looks to me more an issue like #1103.
Are you using alpha12 or a build from master?

**Comment by vmirgorod** [comment]
I'm using alpha12

**Comment by tdesveauxPKFX** [comment]
Nevermind, I noticed you are using the `gmake` action. Could you try with `gmake2`?
`gmake2`  is the action which will replace `gmake` in the future and it is somewhat more complete at the moment.

**Comment by vmirgorod** [comment]
Yes it seems gmake2 action produces correct files!
