### ISSUE TITLE
What Is Premake - typo?

### ISSUE THREAD

**Issue by juanPabloRamosWork** [premake/premake-core#1162]
Under "Key Features" it says that premake only supports "Microsoft Visual Studio 2008-2015". But in "Using Premake" it says you can use the action to generate Visual Studio 2017 files.

Is this a typo or intentional?

**Comment by catb0t** [comment]
The "What is Premake" Wiki page was a little out of date so I fixed it, updating the years to `2008-2015`.

**Comment by starkos** [comment]
It is out of date, it should say 2008–2017.

**Comment by starkos** [comment]
It is out of date, it should say 2008–2017.
