### ISSUE TITLE
Bad Postbuild Command Formatting CodeLite

### ISSUE THREAD

**Issue by Spirrwell** [premake/premake-core#1168]
EDIT:
Just some extra information

CodeLite Version 12.0.8
Linux Distro: Linux Mint 19 MATE x64
Tested with premake alpha 12 AND tested with premake built from master

Hello there!

So, when using gmake with premake, my post build commands to copy files and whatnot work totally fine. However, with CodeLite, it seems the formatting of the command gets a little garbled.

Fair warning, I have not built the latest premake myself, I got the latest release binary for premake5 a few days ago.

But yeah, I have post build commands that are setup like this:

`filter { "platforms:Linux64", "configurations:Release" }
		postbuildcommands { "cp \"%{cfg.targetdir}/%{cfg.targetprefix}%{cfg.targetname}%{cfg.targetextension}\" \"../lib/shared/linux64/release\"" }`

(Side note, I know there's probably a better way to copy the file in a more platform independent way, so if somebody wants to chime in on that, please do)

In CodeLite, the command ends up looking like it does in the screenshot posted.
![screenshot at 2018-09-13 20-29-59](https://user-images.githubusercontent.com/8671884/45522891-df589480-b793-11e8-8cd0-993c4e3bd270.png)

Is there any way to fix this?

**Comment by samsinsane** [comment]
Are you using alpha12 or latest master? I'm fairly certain that there was a fix for this, but it was after alpha12 was released.

**Comment by Spirrwell** [comment]
Almost I'm still left with the \&quot;
![screenshot at 2018-09-13 22-26-16](https://user-images.githubusercontent.com/8671884/45526168-1767d380-b7a4-11e8-88ea-5a09c00f0101.png)

**Comment by samsinsane** [comment]
Ok, so looks like the build commands shouldn't have the escaped characters at all. [These](https://github.com/premake/premake-core/blob/e82fc6209505c49e4eb6fcfa27cf5bf286b8fa94/modules/codelite/codelite_project.lua#L305-L327) two functions just need to have the `p.esc(command)` replaced with `command`. To get it working for you locally, you can replace the previous overload with:
```lua
require "codelite"
premake.override(premake.modules.codelite.project, "postBuild", function(oldfn, cfg)
  if #cfg.postbuildcommands > 0 then
    _p(3, '<PostBuild>')
    local commands = os.translateCommandsAndPaths(cfg.postbuildcommands, cfg.project.basedir, cfg.project.location)
    for _, command in ipairs(commands) do
      _x(4, '<Command Enabled="yes">%s</Command>', p.esc(command))
    end
    _p(3, '</PostBuild>')
  end
end)
```

**Comment by Spirrwell** [comment]
Still has \&quot;
![image](https://user-images.githubusercontent.com/8671884/45527065-d07bdd00-b7a7-11e8-99cd-755cc79f584f.png)

**Comment by samsinsane** [comment]
Strange, just to confirm you grabbed my edited version? I originally forgot to remove the `p.esc` call and edited the post. I can't see why it would do the escaping otherwise, but I'm not overly familiar with the CodeLite module so I might just be overlooking something.

**Comment by Spirrwell** [comment]
Yeah, before you edited, it simply failed to generate the projects, but I got what you meant when you said to replace p.esc(command) with just command

But yeah, it doesn't appear to be working.

This is what it looks like in the .project file with the override in place:

![image](https://user-images.githubusercontent.com/8671884/45527409-66643780-b7a9-11e8-80b2-0a5a893dd550.png)


And here is what it looks like if I manually edit the postbuild command in codelite myself:


![image](https://user-images.githubusercontent.com/8671884/45527532-35383700-b7aa-11e8-9bff-3110cd158be5.png)

**Comment by Spirrwell** [comment]
```lua
require "codelite"
premake.override(premake.modules.codelite, "esc", function(oldfn, value)
  return value
end)
```

So, this does work. I don't know why. Based on what I'm seeing, this should be the same functionality as passing in "command" raw like you were doing in the postbuild override.

**Comment by tdesveauxPKFX** [comment]
Hey @Spirrwell,

> (Side note, I know there's probably a better way to copy the file in a more platform independent way, so if somebody wants to chime in on that, please do)

Here is how you can do this with tokens:
```lua
postbuildcommands { "cp \"%{cfg.targetdir}/%{cfg.targetprefix}%{cfg.targetname}%{cfg.targetextension}\" \"../lib/shared/%{cfg.platform:lower()}/%{cfg.buildcfg:lower()}\"" }
```
