### ISSUE TITLE
How to generate the iOS FrameWork

### ISSUE THREAD

**Issue by panhaowen** [premake/premake-core#1169]
I tried the following, but to no avail
kind "SharedLib"
sharedlibtype "OSXFramework"

**Comment by neo2buha** [comment]
I''m afraid this might not work just out of the box 
Could you attach here a pbxproject generated by xcode for references ?
I'll try to look into it and  submit a merge request once i have the project and the time to look into it !

**Comment by samsinsane** [comment]
I'm going to close this and assume that the issue was resolved in the above PR. If the issue is still occurring please feel free to reopen the issue.
