### ISSUE TITLE
configurations & platforms problem for VS2017

### ISSUE THREAD

**Issue by playgithub** [premake/premake-core#1171]
In `premake5.lua`
```
solution "Premake5"
    configurations { "Debug", "Release" }
    platforms { "Win32", "Win64" }
```
![image](https://user-images.githubusercontent.com/3665590/45832970-fff59100-bd35-11e8-93ae-506266719671.png)
A native solution has only two essential options in the combo: Debug & Release.

Thanks

**Comment by catb0t** [comment]
but there is one build for each possible combination of platform and configuration, 2 * 2 = 4 total builds

**Comment by neo2buha** [comment]
Instead of win64 can you put x64 and see if that fixes your issue?

**Comment by playgithub** [comment]
> but there is one build for each possible combination of platform and configuration, 2 * 2 = 4 total builds
* 2 for configuration: Debug & Release
* 2 for Platform: x86 & x64
That's what for native VS project.

**Comment by playgithub** [comment]
> Instead of win64 can you put x64 and see if that fixes your issue?

Maybe it works, but it still should keep its integrity.
