### ISSUE TITLE
C++ Object file conflicts when .cpp files have different folder but same name

### ISSUE THREAD

**Issue by WiwilaJuicebox** [premake/premake-core#1182]
I'm having an issue on our project where two cpp with the same name, while being in different folders, generate object files that collide because output in the same folder.
Even if visual studio is a part responsible for that, it would be nice and a service we would expect from premake to auto detect these kind of conflicts and create specific build commands for the conflicting files to output the object files in different folders. (I remember that CMake does this)

**Comment by ratzlaff** [comment]
What version of premake are you using? The one I am using (some point after alpha 12) detects this case of file names being the same.

**Comment by ratzlaff** [comment]
Just verified with a build of premake-core @ ed483dd9
```lua
files {	"dir1/file.cpp"
,	"dir2/file.cpp"
}
```

produces the following in the .vcxproj
```
<ItemGroup>
  <ClCompile Include="dir1\file.cpp" />
  <ClCompile Include="dir2\file.cpp">
    <ObjectFileName>$(IntDir)\file1.obj</ObjectFileName>
  </ClCompile>
</ItemGroup>
```
