### ISSUE TITLE
Setting system version and toolset on project with kind "None"

### ISSUE THREAD

**Issue by nickclark2016** [premake/premake-core#1184]
When creating a header only library recently, I came across the issue where I set kind to "None".  For uniformity across the projects in the solution, I tried to set the toolset and system version, but those settings were ignored.  There should be some way to set the toolset and system version for header only projects as well as compiled projects.

**Comment by catb0t** [comment]
What do you use Premake for in a header-only library? Building tests?

Either you are compiling a program with a compiler (so use `kind "consoleapp", kind "staticlib"`) or you are wanting to do shell commands on the file so use `kind "makefile"`?

**Comment by nickclark2016** [comment]
There are two projects, one that has tests and is a "ConsoleApp" and another that is the header only library which is "None".  It doesn't affect the compilation, but it produces an unexpected visual studio project.

**Comment by Pitj3** [comment]
Can confirm using alpha13 fixes this issue (I'm working together with OP)

**Comment by nickclark2016** [comment]
Yup, we were out of date.  Closing issue.  Thanks!

**Comment by samsinsane** [comment]
@nickclark2016 @Pitj3 I'm glad that resolved the issue for you guys!
