### ISSUE TITLE
implibprefix and implibextension

### ISSUE THREAD

**Issue by joealam** [premake/premake-core#1195]
Hey,

I'm having issues attempting to use implibprefix and/or implibextension - which appear to have no effect.

My links are still having ".lib" appending, and no prefix.
Is there something additional that I may need to get these options to work?

**Comment by WorldofBay** [comment]
I just added some tests local and it seems to work. Can you show a premake file where it fails?

**Comment by ClxS** [comment]
Hi @WorldofBay 
Could you post an example test? If I search the repo for 'implibextension' it seems there is no place it's used at all: https://github.com/premake/premake-core/search?q=implibextension&unscoped_q=implibextension

My solution to this was to override msc.getlinks and m.ignoreDefaultLibraries to add the implibprefix + implibextension as expected. The way they are currently written doesn't care about implibextension at all, and will just append .lib if there is no existing extension on the link.

**Comment by samsinsane** [comment]
I'm going to close this issue - `implib*` APIs have no impact on `links`, see the wiki for those APIs they're for the `.lib` stub that is generated for DLLs in Visual Studio. Completely unrelated to the `links` API, and I'm not sure what connection was made between the two.

As for the comments about the `links` extensions; personally, I don't see any value in Premake attempting to support `.a` out of the box for VS or MSC, people will always be requesting more and more complicated features to handle some projects being `lib*.a` or whatever. Just using `*.lib` or `*.obj` is significantly simpler for everyone.
