### ISSUE TITLE
Exit code ignored with per-configuration prebuildcommands (xcode)

### ISSUE THREAD

**Issue by IanLilleyT** [premake/premake-core#1212]
This is a very random and minor problem, and I have a semi-ugly workaround for it.

My premake script calls a different `prebuildcommands` for each configuration (running the same build script, but with different arguments). The build script outputs errors in the form `{path}:{line}: (error|warning): {message}` so that xcode knows which file/line caused the problem. It also returns an exit code. All of this works, except xcode outputs `Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure`. Kind of annoying.

The xcode prebuild phase (generated by premake) looks something like:

```
if [ "${CONFIGURATION}" = "config1" ]; then
run_my_script --1
fi
if [ "${CONFIGURATION}" = "config2" ]; then
run_my_script --2
fi
```

I think the exit code is being ignored because of bash quirks. When I replace the above chunk with just `run_my_script --1` or `run_my_script --2` the exit code is received correctly. I tried putting a single `exit $?` at the end, but something about bash and if-statements overwrites exit codes even when only one if-statement is run. My workaround is adding an `exit $?` prebuildcommand for each configuration.

**Comment by samsinsane** [comment]
If you manually edit the script in the Xcode project and add `set -e` to the start, so that it looks like:
```
set -e
if [ "${CONFIGURATION}" = "config1" ]; then
run_my_script --1
fi
if [ "${CONFIGURATION}" = "config2" ]; then
run_my_script --2
fi
```
Does that cause the errors to emit correctly?
