### ISSUE TITLE
[RELEASE] Alpha14

### ISSUE THREAD

**Issue by tdesveauxPKFX** [premake/premake-core#1213]
Hi all,

[Alpha14](https://github.com/premake/premake-core/tree/release-5.0-alpha14) release candidate branch is up. This issue is to gather feedback on it.

Release date target is next week unless something major comes up.

**Comment by WorldofBay** [comment]
consider using that moment to look over some really old PRs and issues and close them (or reactivate them if appropriate)

#506 can most probably be closed right away and there are open issues without any movement since 2015

#1210 should be addressed before a new release
#1208 maybe figured out?

**Comment by WorldofBay** [comment]
now that i looked a bit further, #1192 and #1185 look like release candidates but that's all up to you, nothing critical yet
