### ISSUE TITLE
cppdialect / buildoptions for intellisense in VS makefile project

### ISSUE THREAD

**Issue by IanLilleyT** [premake/premake-core#1226]
I brought this up in a different issue: #670 but not sure if anyone saw.

Basically, I want intellisense to know the cpp dialect of my code in a VS makefile project. It seems like the best place to tell it that is under Project Properties -> NMake -> Additional Options. I don't know which solution is better: doing it through `cppdialect `or more manually through `buildoptions`, but support for either would be cool.

**Comment by IanLilleyT** [comment]
By the way, my workaround is

```
require "vstudio"
premake.override(premake.vstudio.vc2010.elements, "nmakeProperties", function(oldfn, cfg) 
    return table.join(oldfn(cfg), { function(cfg) 
        premake.vstudio.vc2010.element("AdditionalOptions", nil, "/std:c++17")
    end }) 
end)

```

**Comment by tdesveauxPKFX** [comment]
I'd say it should be done in the same way as with the vcxproj generation.

https://github.com/premake/premake-core/blob/00c8d53c5355326520cceb6f112f69eedbc5ec18/modules/vstudio/vs2010_vcxproj.lua#L1427-L1436
