### ISSUE TITLE
Disabling Just My Code Debugging for MS Visual Studio

### ISSUE THREAD

**Issue by nickclark2016** [premake/premake-core#1233]
Is there a way to turn remove the /JMC flag that MS Visual Studio 2017 automatically adds to the project?  I am using clang, but the toolchain doesn't support the flag.

**Comment by samsinsane** [comment]
That sounds like a bug in VS2017, have you reported it to them?

Additionally, for the version of VS2017 that I have `/JMC` is disabled by default. If they've changed this in an updated version you can disable it with:
```lua
premake.override(premake.vstudio.vc2010.elements, "clCompile", function(oldfn, cfg)
  local calls = oldfn(cfg)
  table.insert(calls, function(cfg)
    premake.vstudio.vc2010.element("SupportJustMyCode", nil, "false")
  end)
  return calls
end)
```

**Comment by redorav** [comment]
Sorry to revive this old bug but I'm having the same issue. According to this https://docs.microsoft.com/en-us/cpp/build/reference/jmc?view=vs-2019, JMC is now enabled by default on VS2017 onwards. I'm trying to add that snippet of code to my premake script but it complains that vc2010 doesn't exist, where do I need to put this snippet?

**Comment by samsinsane** [comment]
@redorav you'll probably also need `require "vstudio"` before that snippet. I'll reopen this since it seems like it's something we're going to need to add support for.
