### ISSUE TITLE
Generated link flags for debug config strip output

### ISSUE THREAD

**Issue by detly** [premake/premake-core#1238]
Using Premake 5.0.0-alpha13. Take this `premake5.lua` as an example:

```lua
workspace "test"
    configurations { "Debug", "Release" }

    project "testlib"
        kind "StaticLib"
        language "C"
        files { "lib.c" }

    project "test"
        kind "ConsoleApp"
        language "C"
        files { "main.c" }
```

Both `premake5 gmake` and `premake5 gmake2` produce makefiles where the `LDFLAGS` contain `-s` eg.

```make
ALL_LDFLAGS += $(LDFLAGS) -s
```

This has the effect of stripping debug symbols from the resulting binary, so debugging is quite hard eg. GDB will be unable to load any debugging symbols. See the GCC man page:

> -s  Remove all symbol table and relocation information from the executable.

I have checked that removing this from the makefiles allows GDB to find and load the symbols.

The `-s` flag should probably be restricted to release builds.

**Comment by detly** [comment]
I'd welcome a workaround for this by the way, I cannot figure out where in the gmake module this is done.

**Comment by detly** [comment]
It was actually in the GCC toolset. This override at the end of `premake5.lua` helps:

**Comment by detly** [comment]
It was actually in the GCC toolset code. This in `premake5.lua` seems to do the trick:

```lua
premake.override(
    premake.tools.gcc, "getldflags",
    function(base, cfg)
        premake.tools.gcc.ldflags.symbols = nil
        local flags = base(cfg)
        return flags
    end
)
```

**Comment by samsinsane** [comment]
Have you tried [`symbols "On"`](https://github.com/premake/premake-core/wiki/symbols)?

**Comment by detly** [comment]
I'm using - Og and - g3, but they definitely don't cancel out the -s.

**Comment by samsinsane** [comment]
That didn't really answer my question, have you tried using `symbols "On"`?

**Comment by detly** [comment]
Sorry, reading too many man pages. I thought you meant `On` where `n` is a placeholder.

Yes, adding `symbols "On"` to `premake5.lua` (and removing the workaround) removes this flag, thanks! IMO it should be the default when `config=Debug`, but maybe there are reasons not to?

**Comment by samsinsane** [comment]
I guess the only reason that it wouldn't default is that `configurations` just accepts a bunch of strings. I've never really noticed, there's usually a long list of differences between debug and release builds that adding `symbols` or `optimize` has never really registered with me.

I guess Premake could contain defaults for arbitrary configurations but that would create inconsistencies and confusion when users create their own configurations. Requiring all settings to be explicitly set for configurations is far more consistent and less confusing overall, just not so much right at the start.

**Comment by detly** [comment]
That's fair, I wasn't sure what conventions Premake wanted to take on or not. I was confused by the configuration being provided to the `gcc.ldflags` function, but it looks like it's switching on the OS to work around the issue on OS X, rather than on debug vs. release.
