### ISSUE TITLE
Use environment value add to output dir on Windows, make by gmake.

### ISSUE THREAD

**Issue by leeonix** [premake/premake-core#125]
I write a TotalCommander Plugins **[wlx_csv](https://github.com/leeonix/wlx_csv)**, use it's environment path `COMMANDER_PATH`, you can see my [Premake5.lua](https://github.com/leeonix/wlx_csv/blob/master/Premake5.lua).
```Lua
targetdir '$(COMMANDER_PATH)/Plugins/wlx/csv'
```

my COMMANDER_PATH value is `D:\tools\TC8\totalcmd`
But, I use `premake5 gmake` and make the project and show this
```
==== Building wlx_csv (debug) ====
Running prebuild commands
on
ragel -T1 ../csv/csv.rl
csv.c
Linking wlx_csv
d:/prog/tdm-gcc-32/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot open output file D:toolsTC8totalcmd/Plugins/wlx/csv/wlx_csv.wlx: No such file or directory
collect2.exe: error: ld returned 1 exit status
make[1]: *** [D:\tools\TC8\totalcmd/Plugins/wlx/csv/wlx_csv.wlx] Error 1
make: *** [wlx_csv] Error 2
```
the backslash isn't double backslash, so make COMMANDER_PATH invalid.

I wrote a [Makefile](https://github.com/leeonix/wlx_csv/blob/master/Makefile) and use `$@` for `-o` param. this COMMANDER_PATH is available.

I see the Premake generated Makefile
```
TARGETDIR = $(COMMANDER_PATH)/Plugins/wlx/csv
TARGET = $(TARGETDIR)/wlx_csv.wlx
...
LINKCMD = $(CC) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
```
Maybe use TARGETDIR directly make that error.
I modify  $(TARGET) to $@, it is pass.
```
LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
```
or modify $(TARGET), it is pass again
```
LINKCMD = $(CC) -o $(subst \,/,$(TARGET)) $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
```
But I think, is it `-o` problem?
```
LINKCMD = $(CC) -o "$(TARGET)" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
```
yeah~ it is pass again!

So, I wish can solve the bug.
Thx.

**Comment by starkos** [comment]
Of those options, I think I prefer this one:

```lua
LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
```

Can you submit a pull request with this change?

**Comment by leeonix** [comment]
I think it is a tiny BUG needn't to submit a PR.
if you need, I do it.

**Comment by starkos** [comment]
We do all changes through pull requests so they go through the Travis CI tests. So thanks for sending one!
