### ISSUE TITLE
compileas for vs200x is not working

### ISSUE THREAD

**Issue by Juergen-29482** [premake/premake-core#1255]
Example:
```
project "main"
      language "C++"

      files  { "src/file.c" }
      filter { "files:src/file.c" }
          compileas "C++"
```
The file.c will be always compiled as C file, not as C++ file.
As proposal to fix the problem in the vs200x_vcproj.lua script, I have changed the line 933:
from: `local value = iif(c, 2, 1)`
to: `local value = iif(p.languages.iscpp(filecfg.compileas), 2, 1)`

The whole function looks like:
```
function m.compileAs(cfg, toolset)
	local cfg, filecfg = config.normalize(cfg)
	local c = p.languages.isc(cfg.language)
	if filecfg then
		if path.iscfile(filecfg.name) ~= c then
			if path.iscppfile(filecfg.name) then
				local value = iif(p.languages.iscpp(filecfg.compileas), 2, 1)
				p.w('CompileAs="%s"', value)
			end
		end
	else
		local compileAs
		if toolset then
			compileAs = "0"
		elseif c then
			compileAs = "1"
		end
		if compileAs then
			p.w('CompileAs="%s"', compileAs)
		end
	end
end
```

**Comment by ratzlaff** [comment]
Which action are you using?

**Comment by Juergen-29482** [comment]
I’m using vs2008

 

Von: Ben Ratzlaff [mailto:notifications@github.com] 
Gesendet: Donnerstag, 14. März 2019 16:44
An: premake/premake-core <premake-core@noreply.github.com>
Cc: Juergen-29482 <hjw@aextra.de>; Author <author@noreply.github.com>
Betreff: Re: [premake/premake-core] compileas for vs200x is not working (#1255)

 

Which action are you using?

**Comment by ratzlaff** [comment]
Yea, after browsing the code in the vs200x folder I figured it had to be vs2008 or vs2005, so I edited my response but not before you got the email, sorry about that.
