### ISSUE TITLE
macOS and Premake 5

### ISSUE THREAD

**Issue by azoreseuropa** [premake/premake-core#1257]
I type brew install premake and it was premake 4.

How do I installed premake5 ?? It is in Download directory .. there is premake5. Help ?! I want to compiled Avocado for MAC. My macOS is the latest version.

**Comment by starkos** [comment]
You can [download releases from here](https://github.com/premake/premake-core/releases). Note that Premake is a command line application, which you'll need to run from Terminal. The [user guide is here](https://github.com/premake/premake-core/wiki). If you run into any trouble, you should start by contacting the Avocado project.
