### ISSUE TITLE
how to add exist props and rules

### ISSUE THREAD

**Issue by leeonix** [premake/premake-core#126]
Premake5 add [Custom Rules](https://github.com/premake/premake-core/wiki/Custom-Rules) and [rules](https://github.com/premake/premake-core/wiki/rules), it's great.

but i have exist file. how to add into my project?

for example [ragel.props](https://github.com/mozy/mordor/blob/next/mordor/ragel.props)

whish you add. Thx.

**Comment by starkos** [comment]
See [externalrule()](https://github.com/premake/premake-core/wiki/externalrule)

**Comment by leeonix** [comment]
That wiki's example is little.
I copy the example code and modify this code to use ragel's rules
```Lua
    rules { 'ragel' }
    externalrule 'ragel'
        location 'ragel'
        filename 'ragel'
        fileextension '.rl'
```

But it generate rule files.
```
D:\workshop\ragel\lua-csv-ragel>premake5 vs2010
Building configurations...
Running action 'vs2010'...
Generating build/csv.sln...
Generating build/csv.vcxproj...
Generating build/test.vcxproj...
Generating build/test.vcxproj.user...
Generating ragel/ragel.props...
Generating ragel/ragel.targets...
Generating ragel/ragel.xml...
Done.
```

**Comment by leeonix** [comment]
And I can't search `externalrule` code. where is it ?

**Comment by starkos** [comment]
It is generated in api.callback()

**Comment by leeonix** [comment]
en, plz test my code. why  externalrule() cannot use.

**Comment by leeonix** [comment]
@starkos I wish an exactly externalrule() usage.

**Comment by starkos** [comment]
The code in the example is what I'm using in a client project here, almost exactly, and it works. When I get a chance I will try to reproduce the issue you're seeing.

**Comment by leeonix** [comment]
@starkos I'll create a branch, name `use-ragel-rules` and copy [rule files](https://github.com/leeonix/lua-csv-ragel/tree/use-ragel-rules/ragel) and modify [Premake5.lua](https://github.com/leeonix/lua-csv-ragel/blob/use-ragel-rules/Premake5.lua)
You can clone one and check it out.

**Comment by leeonix** [comment]
this `externalrule` is real great.
two years ago, I want to add masm.rules for my project.
I modify `premake-4.2` source code add the rules for myself.
If `externalrule` can use, that solve many problem.

**Comment by starkos** [comment]
Haven't forgotten about this by the way, just haven't had a chance to pull your branch yet.

**Comment by leeonix** [comment]
NO, u can test my code.
[use-ragel-rules](https://github.com/leeonix/lua-csv-ragel/tree/use-ragel-rules)

**Comment by starkos** [comment]
Finally got a chance to try this out. Using your use-ratel-rules branch, and the latest premake-core, I get:

    function: 0x10012a410
    Building configurations...
    Running action 'vs2012'...
    Generating build/csv.sln...
    Generating build/csv.vcxproj...
    Generating build/test.vcxproj...
    Generating build/test.vcxproj.user...
    Done.

The project itself looks correct:

```xml
  <ImportGroup Label="ExtensionSettings">
    <Import Project="..\ragel\ragel.props" />
  </ImportGroup>
```

```xml
  <ItemGroup>
    <ragel Include="..\src\csv.rl" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
    <Import Project="..\ragel\ragel.targets" />
  </ImportGroup>
```

???

**Comment by starkos** [comment]
D'oh, hang on you were using `vs2010`, let me retry...

**Comment by leeonix** [comment]
Yeah, I working in vs2010.  
this computer buy on 2007. it is too old.  
I buy a new computer. I'll try vs2013 and vs2015.

**Comment by starkos** [comment]
Fixed the problem in [pull request #157](https://github.com/premake/premake-core/pull/157), will merge it in once it has passed all CI checks. Thank for reporting it!

**Comment by starkos** [comment]
Okay, this should be fixed now with the latest premake-core, but feel free to re-open if you are still having trouble with it!

**Comment by leeonix** [comment]
Yeah, this morning I test new code. it pass. thank you.
