### ISSUE TITLE
pchsource does not expand tokens

### ISSUE THREAD

**Issue by jonestristand** [premake/premake-core#1260]
PCHSource does not appear to expand tokens. For example, the following does not set 'Create /Yc' on pch.cpp, though the second example does.

```
project 'test'
  pchsource '%{prj.name}/pch.cpp'
```

```
project 'test'
  pchsource 'test/pch.cpp'
```

**Comment by samsinsane** [comment]
The following seems to work for me?

```lua
project "test"
  pchsource "%{prj.name}/pch.cpp"
  files { "%{prj.name}/pch.cpp" }
```

As per the wiki article [here](https://github.com/premake/premake-core/wiki/Precompiled-Headers) the `pch.cpp` needs to exist first:

> The PCH source file is just a regular old source code file containing a single line: an include statement that pulls in the header to be precompiled:
> ```
> #include "stdafx.h"
> ```
> Nothing special, but you must have this file in order for precompiled headers to work in Visual Studio. You may call this file whatever you want, and put it wherever you want in your source tree.
