### ISSUE TITLE
Error in premake-5.0.0-alpha13/src/base/_foundation.lua:235: "attempt to concatentate a table value (local 'fname')".

### ISSUE THREAD

**Issue by Geomazzix** [premake/premake-core#1268]
When I was working on my first cross platform script with premake5 it ran into this error:

 "Error: ...e/release/premake-5.0.0-alpha13/src/base/_foundation.lua:235: attempt to concatenate a table value (local 'fname')".

I have absolutely no clue what it means and cannot find any information about it on the internet, mainly because it doesnt have an error code or some kind of way to search for the error type specifically. Correct me if I am wrong on this matter though.

I have added the lua file as an attachment so you might beable to reproduce it, I certainly did hit a wall with this error and would love to hear what caused it.

Regards,
Tom
[premake5.txt](https://github.com/premake/premake-core/files/3095332/premake5.txt)

P.S. I had to put the content of my lua file into a .txt file because github didnt support the file type.

**Comment by starkos** [comment]
Line 83 should be `includedirs`, not `include`.

**Comment by Geomazzix** [comment]
Sigh seems like I need to do my research better, thanks for the quick reply.
