### ISSUE TITLE
pchsource doesn't set cpp file to Create /Yc but leaves it at the use setting

### ISSUE THREAD

**Issue by Geomazzix** [premake/premake-core#1269]
Hi all,

I have been fiddling around with premake5 in the last few days. Everything went fine until I ran into some issues with the precompiled headers. My code:

        pchheader "QyPch.h"
        pchsource "projects/qinxy/src/QyPch.cpp"
        

        includedirs
        {
            "projects/qinxy/src"
        }

Makes sure that all the files in the project are set to use the QyPch.h. This is fine, although it does not change the QyPch.cpp to "Create /Yc" instead of "Use /Yu".

My folder structure looks as followed:

premake5.exe
premake5.lua
----build (currently empty)
----dependencies (currently empty)
----generated
--------vs (hidden)
--------Qinxy.sln
----projects
--------qinxy
------------src
----------------QyPch.cpp
----------------QyPch.h
----------------Logger.h
----------------Logger.cpp
--------testProject
------------src
----------------EntryPoint.cpp

For the provided code, I used the precompiled headers documentation page.
Hope you might be able to see what the problem is with my code/foldersctructure.

Regards,
Tom

[premake5.txt](https://github.com/premake/premake-core/files/3098195/premake5.txt)

**Comment by theDiv0** [comment]
Hi, did you fix the problem? I am currently experiencing the same issue.
Thanks in advance.

**Comment by Geomazzix** [comment]
I'm unsure, since this back in the time was a pet project. I haven't touched premake in a year and was very inexperienced with the scripting language at the time. I'm afraid I won't be able to help you any further sorry.

**Comment by SiriusED** [comment]
Faced same issue. but found how to fix:
`pchsource "%{prj.location}/src/pch.cpp"`

**Comment by HenriJohansson** [comment]
@SiriusED You saved me with this one.
All I had to get figured out was what I need on front of the url and `%{prj.location}`
Is exactly what I was missing.
