### ISSUE TITLE
How to get path information into premake script

### ISSUE THREAD

**Issue by Heaven31415** [premake/premake-core#1272]
Hey, I'm using premake to build a project which is linking to an external library. I'm assuming that every user of my project has this library installed however, the location of it may vary depending on where the user installed it. Right now in my `premake5.lua` script at the top I have a variable which contains a path to the directory of this library which every user needs to modify accordingly to make it work.

Modifying a build script doesn't seem to be a good idea, but I really need this information from the user, I cannot deduce it.

Is there any better way to get path information into premake script?

**Comment by WorldofBay** [comment]
Hey.
if you can force the user to have an environment variable, you can read that via [os.getenv](https://www.lua.org/pil/22.2.html).
Premake on the other hand allows you to register command-line options via [newoption](https://github.com/premake/premake-core/wiki/newoption), so there's also that way.

**Comment by Heaven31415** [comment]
Thank you, registering a new command-line option seems like a very good idea to handle this.
