### ISSUE TITLE
Cannot create Xcode project with iOS as target

### ISSUE THREAD

**Issue by c0nd3v** [premake/premake-core#1273]
I can create a MacOS project fine, but if I want to target iOS, anything I try won't work.

**Comment by samsinsane** [comment]
You've tried using `system "ios"`?

**Comment by c0nd3v** [comment]
Yes

**Comment by ratzlaff** [comment]
What doesn't work?
Are you specifying `--os=ios` on the command line?
Are you using `filter {"system:ios"}` to configure ios specifically?
Which version of premake are you using?

**Comment by samsinsane** [comment]
I'm going to close this since it seems to work in the latest release. If it's still not working feel free to reopen with more details.
