### ISSUE TITLE
使用Premake生成vs工程的时候，如果文件夹的路径包含空格或则特殊字符，无法构建

### ISSUE THREAD

**Issue by ziyushijie** [premake/premake-core#1274]

**Comment by mercury233** [comment]
要生成的vs版本是多少？
特殊字符是什么字符？
无法构建是指无法生成解决方案还是解决方案在vs里编译不过？
具体的错误提示是什么？

**Comment by ziyushijie** [comment]
我是通过premake将一个.c文件生成vs工程，当这个.c文件位于123文件下，可以生成，单文件名是123-123或则123 123就生成失败





------------------ 原始邮件 ------------------
发件人: "Mercury233"<notifications@github.com>; 
发送时间: 2019年4月29日(星期一) 晚上6:43
收件人: "premake/premake-core"<premake-core@noreply.github.com>; 
抄送: "有点累"<2366586936@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [premake/premake-core] 使用Premake生成vs工程的时候，如果文件夹的路径包含空格或则特殊字符，无法构建 (#1274)




要生成的vs版本是多少？
 特殊字符是什么字符？
 无法构建是指无法生成解决方案还是解决方案在vs里编译不过？
 具体的错误提示是什么？

**Comment by mercury233** [comment]
具体的错误提示是什么？

**Comment by ziyushijie** [comment]
------------------ 原始邮件 ------------------
发件人: "Mercury233"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 晚上6:47
收件人: "premake/premake-core"<premake-core@noreply.github.com>;
抄送: "有点累"<2366586936@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [premake/premake-core] 使用Premake生成vs工程的时候，如果文件夹的路径包含空格或则特殊字符，无法构建 (#1274)




具体的错误提示是什么？

**Comment by ziyushijie** [comment]
如果文件路径有中文，不能使用premake5 vs2015工程，提示找不到premake5.lua




------------------ 原始邮件 ------------------
发件人: "Mercury233"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 晚上6:47
收件人: "premake/premake-core"<premake-core@noreply.github.com>;
抄送: "有点累"<2366586936@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [premake/premake-core] 使用Premake生成vs工程的时候，如果文件夹的路径包含空格或则特殊字符，无法构建 (#1274)




具体的错误提示是什么？

**Comment by ziyushijie** [comment]
已找到原因，是我自己解析文件路径错误
