### ISSUE TITLE
Incorrectly truncated path in postbuildcommands {COPY}

### ISSUE THREAD

**Issue by amc522** [premake/premake-core#1283]
**premake version**: alpha14
**last know working version**: alpha13
**action**: vs2019
**os**: Windows 10

When using the following command
```
postbuildcommands {
    "{COPY} \"..\\..\\%{prj.name}\\*.exe\" \"..\\..\\some\\other\\path\""
}
```
I expect the output in visual studio to be
```
IF EXIST "..\..\$(ProjectName)\*.exe"\ (xcopy /Q /E /Y /I "..\..\$(ProjectName)\*.exe" "..\..\some\other\path\" > nul) ELSE (xcopy /Q /Y /I "..\..\$(ProjectName)\*.exe" "..\..\some\other\path\" > nul)
```
The actual output is 
```
IF EXIST $(ProjectName)\*.exe"\ (xcopy /Q /E /Y /I $(ProjectName)\*.exe" "..\..\some\other\path\" > nul) ELSE (xcopy /Q /Y /I $(ProjectName)\*.exe" "..\..\some\other\path\" > nul)
```

The starting quote and `..\..\` is being removed. I tried several combinations and changes to the path and found some conditions.
* Its reproducible when the path is wrapped in quotes, the path leads with `..\..\`, and there must be a value token in the path (ex. `%{prj.name}`)
* If I remove the value token, the output is formatted as expected.
* If I remove `..\..\` at the beginning of the path, the output is formatted as expected.
* Replacing `..\..\` with `..\` produces correctly formatted output.
* If I remove the quotes, the output is formatted as expected.

Any help with this would be appreciated. Thanks!

**Comment by samsinsane** [comment]
Interesting, thank you for the extensive notes on this, we can make a few test cases to ensure this is fixed and stays fixed. I don't think it will make any difference but if you use `xcopy /Q /Y /I` directly instead of `{COPY}` does it still fail?

**Comment by amc522** [comment]
So I tried using xcopy straight up instead of {COPY} and the issue actually went away. Here's a small repro case:

```
workspace "HelloWorld"
   configurations { "Debug", "Release" }

project "HelloWorld"
   kind "ConsoleApp"
   language "C"
   targetdir "bin/%{cfg.buildcfg}"

   files { "**.h", "**.c" }

   postbuildcommands {
      "xcopy /Q /Y/ /I \"..\\..\\%{prj.name}\\*.exe\" \"some\\path\"",
      "{COPY} \"..\\..\\%{prj.name}\\*.exe\" \"some\\path\""
   }

   filter "configurations:Debug"
      defines { "DEBUG" }
      symbols "On"

   filter "configurations:Release"
      defines { "NDEBUG" }
      optimize "On"
```

And here's the output I'm seeing in the vcxproj file:
```
<PostBuildEvent>
  <Command>xcopy /Q /Y /I "..\..\$(ProjectName)\*.exe" "some\path"
IF EXIST $(ProjectName)\*.exe"\ (xcopy /Q /E /Y /I $(ProjectName)\*.exe" "some\path" &gt; nul) ELSE (xcopy /Q /Y /I $(ProjectName)\*.exe" "some\path" &gt; nul)</Command>
</PostBuildEvent>
```

**Comment by amc522** [comment]
@samsinsane Any update on this?

**Comment by samsinsane** [comment]
@amc522 Unfortunately, I haven't really had a chance to look into this at all.

**Comment by samsinsane** [comment]
@amc522 I've finally had a chance to look into this, it looks like you've hit a weird edge case in the `path.normalize` function, when a path is wrapped in quotes, starts with `../../` followed by a variable `$()`, `${}`, `%{}`, `%%` or a space, it will truncate the `../../`. Basically, it ends up thinking the first folder is `"..` not `..`, so this increments the folder depth and then `..` decrements the folder depth resulting in the `../../` being truncated. I'll be submitting a PR shortly.

**Comment by amc522** [comment]
@samsinsane Thanks for taking a look at this identifying the issue! Glad I could find a nice weird edge case for you 😛.
