### ISSUE TITLE
Error: no such action 'vs2019'

### ISSUE THREAD

**Issue by badryasuo** [premake/premake-core#1284]
When I type
> premake5 vs2019

I get
**`Error: no such action 'vs2019'`**

Despite it says that action is already supported in [**Premake Wiki**](https://github.com/premake/premake-core/wiki/Using-Premake)

P.s I've got the latest version.

**Comment by badryasuo** [comment]
> > P.s I've got the latest version.
> 
> Are you referring to master or the latest release?

latest release

**Comment by samsinsane** [comment]
I've downloaded the alpha14 build and it works fine? I assume you used the Windows binary?

**Comment by badryasuo** [comment]
> I've downloaded the **alpha14** build and it works fine? I assume you used the Windows binary?

I don't see any except the **alpha13** at the [Download page](https://premake.github.io/download.html); And yes, I've used the Windows binary... Can you provide me with the executable you used or from where you've got it, please?

**Comment by badryasuo** [comment]
Well, nevermind; It seems that their website wasn't updated with the latest release as it seems. I should've gotten it from the GitHub repository [here](https://github.com/premake/premake-core/releases) since I've found the alpha14 there.

**Comment by samsinsane** [comment]
I've updated the website, thanks for pointing that out.

**Comment by samsinsane** [comment]
> P.s I've got the latest version.

Are you referring to master or the latest release?
