### ISSUE TITLE
Cannot open premake4.lua: No such file or directory - building nanovg windows 10 vs2019

### ISSUE THREAD

**Issue by Switek1321313** [premake/premake-core#1286]
Hi! I want to build nanovg library. I got error: `Error: cannot open C:/Users/Micha┼é/Desktop/nanovg-master/premake4.lua: No such file or directory`

Now, I am running on vs2019, but was the same with vs2017.

I build like this:
cmd ->
`cd nanovg-master`
premake5.exe vs2019`

I have just downloaded latest nanovg and premake, so everything should work.

How to fix it? 

If you do not have the same problem, could you please upload already builded nanovg?

**Comment by Cannedfood** [comment]
If you use premake5 the command should be
```bash
cd nanovg-master
premake5.exe --file=premake4.lua vs2019
```
It should generate the project files in the `build` directory. (And spit out a lot of deprecation warnings).

**Comment by Switek1321313** [comment]
Still the same problem: `Error: cannot open C:/Users/Micha┼é/Desktop/nanovg-master/premake4.lua: No such file or directory`

**Comment by tdesveauxPKFX** [comment]
Just tried and it generate correctly (got a bunch of deprecated warnings but that's all).

It looks like the issue come from this `Micha┼é` in your path. The special characters seems to not be handled, I will take a look into it.

For now, you can just move the directory in a path without special characters.

> If you use premake5 the command should be
> 
> ```shell
> cd nanovg-master
> premake5.exe --file=premake4.lua vs2019
> ```

You don't need to do that, premake5 will look for both premake5.lua and premake4.lua (in that order).

**Comment by Switek1321313** [comment]
Yeah, it works now. Thanks
