### ISSUE TITLE
alpha14 src zip misses scripts.c

### ISSUE THREAD

**Issue by mmuman** [premake/premake-core#1288]
Trying to build on Haiku results in:
```
make[1]: *** No rule to make target '../../src/scripts.c', needed by 'obj/Release/Premake5/scripts.o'.  Stop.
```
And after checking the alpha13 and 14 zip files only the first one does have the scripts.c file.

**Comment by manxorist** [comment]
Equally affects building with `build/vs2017/Premake5.sln`.
`scripts.c` is missing from the source archive, which makes building premake impossible.

Also, https://github.com/premake/premake-core/blob/v5.0.0-alpha14/.gitattributes lists the bootstrapping scripts (https://github.com/premake/premake-core/blob/v5.0.0-alpha14/Bootstrap.bat) as `export-ignore`, which means I cannot even bootstrap alpha14 from a github zip tree download. Thus I would now have use git to bootstrap premake, which would be extremely annoying for https://github.com/OpenMPT/openmpt/, where we normally download (via scripts) the official premake release zip and build it ourselves (reason being: avoiding binary downloads for our build tools as much as possible).

However, using git to build premake also fails, because even `Bootstrap.bat` ultimately fails due to missing `scripts.c`.

How do I even build alpha14?

**Comment by WorldofBay** [comment]
have you tried a
`premake5 embed`
call?

scripts.c is a generated file and essentially contains the lua parts, so if the lua files exist you can build that file. see [Building Premake](https://github.com/premake/premake-core/wiki/Building-Premake) for infos about building.

i haven't tried building from the zips yet, i've only done so from a git clone and there isn't any scripts.c in the repo (as you should never add a generated file to the repo) yet it works.

**Comment by manxorist** [comment]
How would I run `premake5 embed` without even having any premake binary in the first place?

Requiring premake to even bootstrap any premake at all makes little sense, and for sure has not been the case for alpha13 and earlier versions. There is currently no way to bootstrap premake from source alone.

This would *force* OpenMPT to rely on externally built binaries for an open source build tool. In theory, I maybe could first download and build alpha13 from source, and use the alpha13 binary to run `premake5 embed`on the alpha14 tree, and then build premake alpha14. Frankly, I'd rather avoid such dances, and would rather see premake fixed to be buildable from its source packages alone again.

Documentation at https://github.com/premake/premake-core/wiki/Building-Premake does not work, in particular "Using a Source Code Package" fails exactly as previously described above.

**Comment by WorldofBay** [comment]
i just tested it and see the problem, however what is your workflow?

if you want to ship an executable built by yourself then as a workaround clone the git repo and follow the steps in the linked wiki article.

the other workaround is to follow the BUILD.txt:

>If your toolset is not supported by the bootstrap Makefile, you will need
>to embed the scripts into a C source file so they may be built into the
>executable, and also generate the project files for your chosen toolset. In
>order do either of these things, you will need a working Premake executable.

as apparently the defect source zip doesn't support any toolset ...

**Comment by manxorist** [comment]
**automated** workflow:
 *  download premake source
 *  unpack premake source
 *  build premake
 *  use premake

In alpha13, this worked without having a dependency on either a pre-existing premake binary or git. In alpha14, this no longer works. The behavior I am relying on is documented at https://github.com/premake/premake-core/wiki/Building-Premake:
> If you have one of the official source code packages, you'll find that project files for a variety of toolsets have already been generated for you in the build/ folder. Find the right set for your platform and toolset and build as you normally would (i.e. run make). The resulting binaries will be placed in the top-level bin/ folder.

Frankly, it makes little sense to ship release source packages with a populated build/ directory (generated by premake), but without src/scripts.c (also generated by premake).

So could someone please fix this bug and do a alpha15 release soon-ish?

**Comment by starkos** [comment]
Confirming, latest source package does not include `scripts.c`, looks like `embed` was never run during packaging process.

**Comment by tdesveauxPKFX** [comment]
I changed the packaging process to use git archive instead of zip.
I missed to add the scripts.c file, not sure how it happened...

Anyway, I will update the package and submit a fix right away. Sorry about that.

**Comment by tdesveauxPKFX** [comment]
Should be fixed now.

**Comment by manxorist** [comment]
@tdesveauxPKFX Works for me. I hope this will not happen again with the next release.

**Comment by samsinsane** [comment]
I'm going to close this as it has now been resolved.
