### ISSUE TITLE
premake5 conflicts with premake4

### ISSUE THREAD

**Issue by L4ZZA** [premake/premake-core#1291]
I'm trying to add support for premake5 to a big open source project that already uses premake4, but with some troubles.
The main premake5.lua file seems to always pick the wrong premake*.lua file in favor of the earlier version one.

`include "../../src/LinearMath"`

wherw LinearMath folder contains both premake4 and premake5 lua files

Am I trying to achieve something impossible or there is a way to do so that premake pick the right file of its given version (specified in the file name)?

**Comment by samsinsane** [comment]
[This](https://github.com/premake/premake-core/blob/cccad35b5ee6eb2c66663c58a1bba510b68632bc/src/base/_foundation.lua#L236-L238) is the code that is ultimately used to detect the files, and should stick to the priority of `<path>`, `<path>.lua`, `<path>/premake5.lua` and then `<path>/premake4.lua`. My initial reaction would be to assume a typo on the actual file, can you confirm this isn't the case?

**Comment by samsinsane** [comment]
I'm going to close this due to lack of response, if you're still encountering this issue please feel free to reopen.
