### ISSUE TITLE
Premake doesn't copy dll to output

### ISSUE THREAD

**Issue by TomerZeitune** [premake/premake-core#1293]
I need to copy a lot of DLLs from the workspace to the targetdir.

I can't create a premake project for every libary it's about 10 libs and I have no need to ever build them from source. 

I added all places with these DLLs to libdirs. for example I have a dll named glew32.dll in 
"Engine/Dependencies/dynamic". And I did :
```
libdirs {
	"Engine/Dependencies/dynamic"
}	
links {
  "glew32.dll"
}
```
Problem is premake doesn't copy the dll to my targetdir so I get a dll error. 
How can I solve this using premake ?

**Comment by ratzlaff** [comment]
Is there a reason you want to build it in one place but need it in a different directory later?
I would say you have three options:
1) Change your [targetdir](https://github.com/premake/premake-core/wiki/targetdir) of your glew project to place the dll in the executable's output directory
2) Add a [post build command](https://github.com/premake/premake-core/wiki/postbuildcommands)
3) Do nothing in premake, add Engine/Dependencies/dynamic to the PATH variable in your visual studio debugging environment. (project properties -> Configuration Properties -> Debugging -> Environment)

If you do 1), project clean actions will do the right thing without any further configuration.
If you do 2), the documentation for [cleancommands](https://github.com/premake/premake-core/wiki/cleancommands) indicates that it is only supported by makefiles.

**Comment by totoze** [comment]
The post build command seem to be the only way. 

Since number 3 won't work to the end user. And I don't have a premake glew project so number 1 won't work either.

**Comment by TomerZeitune** [comment]
The post build command seem to be the only way.

Since number 3 won't work to the end user. And I don't have a premake glew project so number 1 won't work either.
