### ISSUE TITLE
Remove outdated repositories

### ISSUE THREAD

**Issue by starkos** [premake/premake-core#1297]
I'd like to remove the old repositories that have been moved into core:

- [premake-android](https://github.com/premake/premake-android) (last updated 2017)
- [premake-xcode](https://github.com/premake/premake-xcode) (2016)
- [premake-raw](https://github.com/premake/premake-raw) (2016)
- [premake-dlang](https://github.com/premake/premake-dlang) (2016)
- [premake-codelite](https://github.com/premake/premake-codelite) (2016)

These two aren't in core, but haven't had any activity in quite a long time. I was leaning toward removing them as well, but now in discussion below:

- [premake-monodevelop](https://github.com/premake/premake-monodevelop) (2016)
- [premake-eclipse](https://github.com/premake/premake-eclipse) (2015)

This one also hasn't had any activity, and I don't believe ever fulfilled its intended purpose. The examples have fallen out of date and aren't being maintained. I'd vote to remove:

- [premake-cookbook](https://github.com/premake/premake-cookbook) (2015)

**A bit of background:** most of these modules lived most of their lives as part of the main Premake code. I had an idea a while back that it might help the project scale if they were broken out: I could focus on the core code, and others could specialize on the individual modules. It turned out to be a maintenance nightmare, and all of the code was moved back into core.

So these repositories only represent a short window of time relative to their overall development. It is confusing to have them living alongside their "real" counterparts. And I believe it gives the wrong impression, and it makes it look like those features haven't seen any improvement in years.

Thoughts or objections?

**Comment by Croydon** [comment]
I'm obviously an outsider to the premake project, but in general I'm considering deleting code history as a terrible idea.

Why not just archive them?

**Comment by starkos** [comment]
Fair question. I've gone ahead and "archived" them so folks can see what that looks like. It definitely helps, but I still question the value of their existence. I'll keep this issue open a while and see what other people think.

At the very least, I feel pretty strongly that [premake-cookbook](https://github.com/premake/premake-cookbook) needs to go, as those samples are just falling farther and farther out of date. Good idea, wrong execution.

**Comment by TurkeyMan** [comment]
I'd like my ones back if you wanna delete them from the org.
That is, `eclipse` and `monodevelop`, which aren't in core.
That eclipse one in particular was painstaking to get working as much as it is... it needs work, but the foundation is comprehensive.

**Comment by ratzlaff** [comment]
I like the idea of premake-cookbook - as in some non trivial configurations for getting certain things done or seeing how certain api features are used.

But yea, they are not maintained so its hard to justify keeping them around in their current state.

**Comment by starkos** [comment]
Apologies @TurkeyMan, I was certain MonoDevelop was in core already! I've update the issue description.

What do you think about removing the modules that are now back in core?

What do you think should happen to eclipse and monodevelop? Do they work against the latest premake-core? I see no real harm in leaving them as-is if they are functional, but if no one is able to maintain them perhaps they should be moved out?

**Comment by samsinsane** [comment]
@TurkeyMan FWIW, MonoDevelop is dead and the later versions of it used the same output as the VS generator. @starkos with that knowledge, the monodevelop module working against latest or not is irrelevant - it was also broken for over a year before anybody noticed so again, it's irrelevant as it impacts nobody.

I don't really see the point in deleting any of the repos, I think archiving them would suffice, If someone wants to fork them, or transfer them that should still be possible after they're archived. I tend to agree with the above about the history, I believe only the Android module was added with history, so we've lost the commits for other modules.

**Comment by starkos** [comment]
Cool cool, I'll leave them archived.
