### ISSUE TITLE
Adding global properties to Visual Studio projects

### ISSUE THREAD

**Issue by kevinlul** [premake/premake-core#1306]
Use case: adding two conditional properties to project configuration to target a [non-default vcpkg triplet](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#with-msbuild), i.e. not `x86-windows-static`.

**Comment by mihaisebea** [comment]
I posted the answer to this so question 
https://stackoverflow.com/questions/56620358/how-do-i-add-global-properties-to-generated-visual-studio-projects-and-solutions/56906785#56906785

see if this works if not ...try to put some prints to see what goes wrong.

**Comment by kevinlul** [comment]
Hi! I'd forgotten about the StackOverflow and to update it. Yeah, I did figure out the solution after combing through the wiki. Would this be something that is appropriate for a built-in feature or not?

**Comment by Valakor** [comment]
I'm in a similar boat - I have vcpkg installed, but I use multiple non-standard configurations that don't start with Debug or Release so I get complaints about vcpkg not knowing what's going on. In my case I added an override vc2010.elements.globalsCondition which works but isn't ideal.
Ideally there'd be a global function that let me write arbitrary properties to the Globals section with whatever conditions I require.

**Comment by L4ZZA** [comment]
please let us do this! I need to setup vcpkg boost-tests

**Comment by L4ZZA** [comment]
@Valakor @kevinlul Can you guys post your solution as I'm a newbie and I'm a bit lost. Where are you guys defining these methods and then where/how do you call them?

**Comment by L4ZZA** [comment]
based on [this](https://stackoverflow.com/a/56906785/6120464) and on some [docs](https://github.com/premake/premake-core/wiki/Overrides-and-Call-Arrays)
I found the solution. Here it is:
```
require('vstudio')

local vs = premake.vstudio.vc2010

local function premakeVersionComment(prj)
    premake.w('<!-- Generated by Premake ' .. _PREMAKE_VERSION .. ' -->')
end

local function vcpkg(prj)
    premake.w('<VcpkgTriplet>x64-windows-static</VcpkgTriplet>')
    premake.w('<VcpkgEnabled>true</VcpkgEnabled>')
end

premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
    return calls
end)

premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.globals, vcpkg)
    return calls
end)
``` 
I added it before everything else at the start of my main `premake5.lua` script and it seems to work.
I couldn't figure out a more abstracted solution as my lua and premake knowledge is minimal, but hopefully someone else will.

**Comment by kevinlul** [comment]
@L4ZZA This is what we use https://github.com/edo9300/edopro/blob/master/premake5.lua#L124

**Comment by Valakor** [comment]
@L4ZZA I use something like this (at the top of my premake5.lua) for non-standard configuration names (I have Debug, Normal, Profile, Release). Probably could be cleaned up a bit...
```
if os.istarget "Windows" then
	require "vstudio"

	local p = premake
	local vc2010 = p.vstudio.vc2010

	function vcpkgTargetConfigurations(prj, cfg)
		if cfg.name == "Normal" or cfg.name == "Profile" then
			vc2010.element("VcpkgConfiguration", nil, "Release")
		end
	end

	p.override(vc2010.elements, "globalsCondition",
		function (oldfn, prj, cfg)
			local elements = oldfn(prj, cfg)
			elements = table.join(elements, { vcpkgTargetConfigurations })
			return elements
		end)
end
```

**Comment by starkos** [comment]
@L4ZZA has already done 90% of the work to add this to core. Add `vcpkg` to `vs2010_vcxproj.lua`, following the example of the other methods like it. Add the call directly to `m.elements.globals` instead of using `p.override()`. Then you just need to come up with an API for it and add it to `_premake_init.lua`, maybe `vcxprojTriplet` and `vcpkgEnabled`? (Or maybe `VcpkgEnabled` is implied by `vcxprojTriplet`?)

Add a unit test, submit the PR, done.

**Comment by L4ZZA** [comment]
The only problem I've found is that by doing that you add it to all the generated projects, so what I did was to add a check for the project I wanted 
```
require('vstudio')
local vs = premake.vstudio.vc2010

local function vcpkg(prj)
    if prj.name == 'tests' then -- this needs better abstraction
        printf("Appended to '%s' project", prj.name)
        premake.w('<VcpkgTriplet>x64-windows-static</VcpkgTriplet>')
        premake.w('<VcpkgEnabled>true</VcpkgEnabled>')
    end
end

premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
    return calls
end)

premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.globals, vcpkg)
    return calls
end)
```

**Comment by starkos** [comment]
If someone wants to submit a PR for this, I'll approve it. Otherwise I'm going to mark this issue closed as answered.

**Comment by L4ZZA** [comment]
@starkos I wouldn't close it and I wouldn't merge it either as it hasn't been solved nor added to the API. 
Furthermore, the solution is not general enough to be added to the API in my opinion. 
It still needs a way to selectively apply the VCPKG xml elements only to the desired projects and to be able to specify the different parts of the triplets (i.e configuration `x64` or `x32`, platform `windows`, `linux`,  etc. and type `dynamic` or `static`.

The API I envision would be as such:
_premake5.lua_
```
-- Inside the project definition
project "vcpkg_proj"
    location "sandbox"
    kind "ConsoleApp"
    -- it would have this tag
    vcpkg "on" -- off by default of course
      -- and nested inside (or not) this definition for the triplet
      triplet "x64-windows-static" -- this is the string the will actually end up in the tag
```
which under the hoods will call a modified version of this code:
> The only problem I've found is that by doing that you add it to all the generated projects, so what I did was to add a check for the project I wanted
> 
> ```
> require('vstudio')
> local vs = premake.vstudio.vc2010
> 
> local function vcpkg(prj)
>     if prj.name == 'tests' then -- this needs better abstraction
>         printf("Appended to '%s' project", prj.name)
>         premake.w('<VcpkgTriplet>x64-windows-static</VcpkgTriplet>')
>         premake.w('<VcpkgEnabled>true</VcpkgEnabled>')
>     end
> end
> 
> premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
>     local calls = base(prj)
>     table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
>     return calls
> end)
> 
> premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
>     local calls = base(prj)
>     table.insertafter(calls, vs.globals, vcpkg)
>     return calls
> end)
> ```

where the `vcpkg` function will take the extra `triplet` string parameter to insert in the xml element like such: 
..
```
-- other code
if prj.name == current_project_name then
  premake.w('<VcpkgTriplet>' .. triplet .. '</VcpkgTriplet>')
  -- other code
```

**Comment by starkos** [comment]
You don't actually need a separate "enable" call. It could be as simple as…

```lua
project "vcpkg_proj"
   vcpkg "x64-windows-static"
```

If `vcpkg` is set, then it's enabled. If it's `nil`, then it isn't.

**Comment by L4ZZA** [comment]
True that, even better. Now, we just need someone confident enough to make these changes ;)
