### ISSUE TITLE
gmake2 ignores pic option

### ISSUE THREAD

**Issue by WhoseTheNerd** [premake/premake-core#1311]
It seems like the premake5 is ignoring the `pic "On"` option on ubuntu 18.04. 
Makefile linking error:
```
Linking Fusion
/usr/bin/ld: vendor/Glad/bin/Debug-linux-x86_64/Glad/libGlad.a(glad.o): relocation R_X86_64_PC32 against symbol `gladLoadGLLoader' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:120: recipe for target '../bin/Debug-linux-x86_64/Fusion/libFusion.so' failed
make[1]: *** [../bin/Debug-linux-x86_64/Fusion/libFusion.so] Error 1
Makefile:55: recipe for target 'Fusion' failed
make: *** [Fusion] Error 2
```
Software versions:
```
$ premake5 --version
premake5 (Premake Build Script Generator) 5.0.0-dev
$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by samsinsane** [comment]
[This](https://github.com/WhoseTheNerd/Fusion/blob/098e86de58e6c4eec4fd22514b944c8ed35aef17/Fusion/Makefile#L40-L41) seems to indicate that Fusion is building with `-fPIC`, so Premake isn't ignoring it. However, [this](https://github.com/WhoseTheNerd/Glad/blob/a928b177ba056f77ed768396d3a69668f121efe1/premake5.lua#L23-L24) seems to indicate that you've attempted to fix this with Glad, my assumption is that you haven't rerun `premake5 gmake2` so the Makefile isn't being updated?

**Comment by WhoseTheNerd** [comment]
rerunning that doesn't change anything.

**Comment by samsinsane** [comment]
After you added `pic "On"` to the Glad project, did you run `make clean` to ensure that you weren't attempting to link non-PIC objects?

**Comment by WhoseTheNerd** [comment]
I can't believe that worked, because I deleted bin/ and bin-int/ folders thinking that would fix it.
