### ISSUE TITLE
Enabling OpenMP in vs2017

### ISSUE THREAD

**Issue by TsarpDev** [premake/premake-core#1312]
I've seen from other projects that OpenMP can be enabled simply:
	`configuration{ "vs*",  "release" }
	buildoptions { "/openmp" }	`	
In my project this doesn't seem to work as "/openmp" goes to AdditionalOptions instead of OpenMPSupport. I know that the modules folder have the answer but I got lost and I need some help.
Thank you

**Comment by T-rvw** [comment]
Hi, @TsarpDev . Do you solve it now?

**Comment by Jarod42** [comment]
Notice that it is a "Display" issue.

Any `buildoptions` goes in `AdditionalOptions` instead of their specific field.

If you build the project, openmp would be enabled as expected.
