### ISSUE TITLE
Premake installation problem

### ISSUE THREAD

**Issue by MLGEditz** [premake/premake-core#1320]
Hi,
I just tried to install premake v5.0, but when running the exe file a batch window appeared and closed immediately. Is this a known issue or am I doing something wrong?

Kind Regards,
Jesse

**Comment by samsinsane** [comment]
Premake is a command line application, check out our [wiki](https://github.com/premake/premake-core/wiki) for how to get started.

**Comment by MLGEditz** [comment]
Oops, didnt see that. Thanks for your help.
The issue can be closed now :)
