### ISSUE TITLE
linking external libs on xcode does not work

### ISSUE THREAD

**Issue by Hemmy123** [premake/premake-core#1322]
I'm currently trying to create an xcode project with Vulkan and GLFW, however I cannot seem to link the libs. 

I'm using: 
```
      libdirs{
                  "/usr/local/lib/",
                  "/usr/local/Cellar/glfw/3.3/lib",
      }

      links{         
                  "libvulkan.1.1.114.dylib",
                  "libglfw.3.3.dylib"      
      }
``` 
I've made sure that the files exist in the directories. The error I receive is `ld: library not found for -llibvulkan.1.1.114.dylib`. After having a search around, 'links' seems to put the libraries in `Linking/Other Linker Flags`. Manually linking the libs in `Build Phase/Link Binary With Libraries` seems to work. Is premake supposed to put these libs in "Other Linker Flags?"

**Comment by samsinsane** [comment]
I think I've experienced this before, try removing the `lib` prefix from your `links` entries:
```lua
links {
  "vulkan.1.1.114.dylib",
  "glfw.3.3.dylib"
}
```

**Comment by Hemmy123** [comment]
I'm afraid that hasn't worked. I've also tried using 'syslibdirs' instead of libdirs which gives the same error

**Comment by samsinsane** [comment]
That's strange, we're doing something similar at work and haven't had an issue. I'll have a look to see if we're doing anything special, the XCode module is relatively neglected so there's a few things that aren't as they should be.

Regarding your question about "Other Linker Flags", there's a comment in the code about it:
https://github.com/premake/premake-core/blob/367b9822c099ee4c334d4a2f1721442c1cf77c06/modules/xcode/xcode_common.lua#L1433-L1435

**Comment by ratzlaff** [comment]
Try removing the .dylib as well

**Comment by Hemmy123** [comment]
That seems to work! Thanks guys!

**Comment by ratzlaff** [comment]
Mostly a note to remind myself - The documentation for [links](https://github.com/premake/premake-core/wiki/links) does say:

`When linking against system libraries, do not include any prefix or file extension. Premake will use the appropriate naming conventions for the current platform.`

**Comment by cxgslegend** [comment]
Thanks guys, this saved me!
