### ISSUE TITLE
Is there a way to specify Visual Studio specific project properties?

### ISSUE THREAD

**Issue by cos-public** [premake/premake-core#1329]
I want to specify "Debug Information Format", "Conformance Mode", "Disable Language Extensions" properties and may be some other. Generally I assume it should be possible to specify all VS project options in premake script. I can do this with buildoptions, like ```buildoptions { "/permissive-" }``` but then I don't see the value in the property pages. Is there a way to specify these options? Is there a list of all VS project options premake supports?
May be it's related to #1306

**Comment by samsinsane** [comment]
For the Debug Information Format there is `debugformat`, the other two I don't believe we have APIs for yet.

**Comment by ClxS** [comment]
There's no way to do a lot of the lesser used (non-CL compiler) properties. You can add these yourself by adding a handler for it.
[This wiki page](https://github.com/premake/premake-core/wiki/Overrides-and-Call-Arrays) demonstates how to inject into the call array, where you can place your own properties. Using that you could do something such as the following: 

```lua
require('vstudio')

premake.api.register {
  name = "someOption",
  scope = "config",
  kind = "boolean",
  default = false
}

local function doSomeProperty(cfg)
  if cfg.someOption then
    premake.w('<SomeProperty></SomeProperty>')
  end
end

premake.override(premake.vstudio.elements, "configurationProperties", function(base, cfg)
  local calls = base(cfg)
  table.insert(calls, doSomeProperty)
  return calls
end)
```
I recommend putting it and your other overrides in a file which is the first thing you include in your main premake5.lua.

Then in your regular premake scripts you would be able to just do someOption(true) to have the property applied

**Comment by starkos** [comment]
Adding to @ClxS: if you need to specify values that aren't already covered by Premake's API (e.g. `debugformat`), it is easy to create a new call. Here is how `debugformat` is declared:

```lua
api.register {
    name = "debugformat",
    scope = "config",
    kind = "string",
    allowed = {
        "Default",
        "c7",
        "Dwarf",
        "SplitDwarf",
    },
}
```

Check out `_premake_init.lua` for lots of other examples. Once declared, you can use it in override like `cfg.mynewvalue`.

Feel free to follow up here with questions. If you get something working, submit a pull request and we'll get merged!

**Comment by starkos** [comment]
I'm going to go ahead and marked this as closed for now, since your question has been answered. But feel free to reopen it if you still have questions or need help getting something working. Or you can also open a feature request for someone else to implement the specific property you need, but these are generally pretty easy to add, and you'll get what you need faster if you create the PR yourself.

**Comment by cos-public** [comment]
I believe the ConformanceMode flag in particular is important. Because premake is useful for cross-platform development, and when your primary IDE is Visual Studio, you want to ensure that you don't use any specifics of the msvc compiler.
So I'm sending you a PR for consideration.
