### ISSUE TITLE
Linking to a library project in a different workspace

### ISSUE THREAD

**Issue by sro5h** [premake/premake-core#1335]
I have a library project and want to keep it in a separate git repository from the application project using it (which includes it via git submodules). But i can't link to the library project that is in a different premake workspace.  
I tried to include the library workspace with `include "path_to_library/premake5.lua"` in the premake script of the application workspace. Then linked to it with `links { "library" }` in the application project, but the linker still can't find the library. Is this something that can be achieved with premake and if so, how?

**Comment by starkos** [comment]
Use [externalProject](https://github.com/premake/premake-core/wiki/externalproject):

```
externalproject "MyExternalProject"
   location "build/MyExternalProject"
   uuid "57940020-8E99-AEB6-271F-61E0F7F6B73B"
   kind "StaticLib"
   language "C++"
```

**Comment by sro5h** [comment]
I read the wiki page about `externalproject`. Where do i get the uuid of the library project from?

**Comment by starkos** [comment]
You can find it in the project’s .vcxproj (or .csproj for C#).

**Comment by sro5h** [comment]
I'm on linux for now, i'll have a look in the Makefile and see if i can find it.

**Comment by starkos** [comment]
Ah, I don't think you need a UUID when referencing an external makefile. If Premake complains, you can always [generate a dummy UUID](https://www.guidgenerator.com).

**Comment by sro5h** [comment]
I don't want to reference an external Makefile, maybe i am trying to solve a nonexistent problem. I'll try to explain it better.  
If i have a single premake5.lua with the two projects 'executable' (a ConsoleApp) and 'library' (a SharedLibrary). Then inside the 'executable' project i can simply put a `links { "library" }` and premake will link to the library project.  
But what if i want to put the 'library' project into its own git repository (so i can use it in multiple other git repositories). Then i have two git repositories (one for the 'executable' and one for the 'library' project) and two premake5.lua in each of them. Now i want to add the 'library' repository as a git submodule inside the 'executable' repository. How do i now link to the 'library' project inside its own premake5.lua from the premake5.lua of the 'executable' project?
I could link to the build library files of the 'library' project manually, but it would be way better if premake could resolve the dependency. Just as it does when linking to another project in the same workspace.

**Comment by sro5h** [comment]
To clarify my premake5.lua inside the repository of the 'library' project would look as following:

```lua
workspace "ws_library"
        language "C"

project "library"
        kind "SharedLib"
        files { "%{prj.name}/**.h", "%{prj.name}/**.c" }
        defines "LIBRARY_EXPORTS"

project "test"
        kind "ConsoleApp"
        files { "%{prj.name}/**.h", "%{prj.name}/**.c" }
        includedirs { "." }
        links { "library" }
```

And the premake5.lua inside the repository of the 'executable' project would look as following:

```lua
workspace "ws_executable"
        language "C"

project "executable"
        kind "ConsoleApp"
        files { "%{prj.name}/**.h", "%{prj.name}/**.c" }
        includedirs { "submodules/library" }
        links { "library" } // DOESN'T WORK. How do i link to a project inside another premake5.lua?
```

**Comment by starkos** [comment]
Ah, okay, that's is different. You need to remove the `project` blocks from your library's `premake5.lua` and put them in their own script(s). Then you can include those script(s) from the library's `premake5.lua`, and the executable's `premake5.lua`.

So your library `premake5.lua` script ends up looking like:

```lua
workspace "ws_library"
    language "C"

    include "path/to/projects.lua"
```

And your executable `premake5.lua` looks like:

```lua
workspace "ws_executable"
    language "C"

    include "ws_library/path/to/projects.lua"
```

Helpful?

**Comment by sro5h** [comment]
Very helpful, i put together a quick test and everything is working as i expect for now. Thank you very much for taking your time to help me!
