### ISSUE TITLE
Support for C++20 modules?

### ISSUE THREAD

**Issue by DethRaid** [premake/premake-core#1349]
**What's your question?**
What's the status of support for C++20 modules?

**Comment by starkos** [comment]
As far as I know, no work has been done toward supporting C++20 modules. We would certainly welcome contributions!

**Comment by saffronjam** [comment]
Any update on this? Almost 2 years later it seems as this is more relevant now. 

**What's your question?**
What's the status of support for C++20 modules?

**Comment by DethRaid** [comment]
While I'm still kinda curious, Visual Studio (including raw VS project files) has been making good progress on module support so I'll stick with that
