### ISSUE TITLE
After a project is generated is there a way to control where new files get placed?

### ISSUE THREAD

**Issue by xgalaxy** [premake/premake-core#1350]
**What's your question?**

Is there a way to control where new files are placed (using the IDE) after the project has been generated? For example, I generate Visual Studio project. I want to create a new CPP file. If I do that in the IDE it gets placed by the project file regardless.  If I were to create a Visual Studio project manually. If I create new files in the IDE, they are placed in the folders I create them in.

**Comment by starkos** [comment]
The short answer is "no". Once Premake has completed generating the projects it is no longer running. There is no interaction with Visual Studio.

This is not really a Premake question; you'd be better off learning more about the IDE in question. [Here is article on creating folders in Visual Studio](https://stackoverflow.com/questions/12989981/how-to-create-a-folder-in-visual-studio-c-2012), for instance.
