### ISSUE TITLE
Failed tests for bsd platform 

### ISSUE THREAD

**Issue by Martinfx** [premake/premake-core#1354]
**What seems to be the problem?**

I hello i ported premake for freebsd but i have issue with tests 
I dont use msc, gcc but only clang 

```
[==========] 1922 tests from 179 test suites ran. (5023 ms total)
[  PASSED  ] 1918 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] gmake2_buildcommands.postbuildcommands
...e-00052e1/modules/gmake2/tests/test_gmake2_buildcmds.lua:48: (3) expected:
	mkdir lib/www
...but was:
	mkdir ../lib/www
fulltext:
define POSTBUILDCMDS
	@echo Running postbuild commands
	mkdir ../lib/www
	mkdir ../lib/www
endef

stack traceback:
	...e-00052e1/modules/gmake2/tests/test_gmake2_buildcmds.lua:48: in function 'testFunction'
[  FAILED  ] tools_gcc.includeDirs_onSysIncludeDirs
...make5/work/premake-core-00052e1/tests/tools/test_gcc.lua:620: expected value -isystem /usr/local/include not found
[  FAILED  ] tools_msc.includeDirs_onSysIncludeDirs
...make5/work/premake-core-00052e1/tests/tools/test_msc.lua:468: expected value -I/usr/local/include not found
[  FAILED  ] tools_msc.libDirs_onSysLibDirs
...make5/work/premake-core-00052e1/tests/tools/test_msc.lua:474: expected value /LIBPATH:"/usr/local/lib" not found

 4 FAILED TESTS
*** Error code 5

```

**What did you expect to happen?**
Failed test for msc compiler on bsd 

**What have you tried so far?**
all

**How can we reproduce this?**
You can install Freebsd for your laptop
and then run it make test

**What version of Premake are you using?**
premake5 (Premake Build Script Generator) 5.0.0-dev
from commit 00052e1

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

**Comment by samsinsane** [comment]
This seems to work fine on my FreeBSD 11 VM, all 1,922 tests pass. Can you provide anymore information about what you did?

**Comment by Martinfx** [comment]
@samsinsane  I am trying premake5 porting to freebsd and here is makefile 
https://github.com/Martinfx/FreeBSD-Ports/blob/master/premake5/Makefile

**Comment by samsinsane** [comment]
Interesting, I've never used the `tests/test` script before, what happens if you just run `${WRKSRC}/bin/release/premake5 test` instead of `cd ${WRKSRC}/tests && ./test`?

**Comment by samsinsane** [comment]
@Martinfx I've submitted a fix for this, let me know if that doesn't resolve the issue.
