### ISSUE TITLE
Default targetdir is incorrect.

### ISSUE THREAD

**Issue by tvandijck** [premake/premake-core#136]
if I make a project that does not have the targetdir set.

```lua
solution 'SC2'
	configurations { 'Release', 'Debug' }
	platforms { 'x86', 'x86_64' }
	
	project 'Test'
		kind 'StaticLib'
	   
	   	files { '**.cpp' }
```

I get this in my visual studio project:

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <OutDir>.\</OutDir>
    <IntDir>obj\x86\Release\</IntDir>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutDir>.\</OutDir>
    <IntDir>obj\x86_64\Release\</IntDir>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <OutDir>.\</OutDir>
    <IntDir>obj\x86\Debug\</IntDir>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutDir>.\</OutDir>
    <IntDir>obj\x86_64\Debug\</IntDir>
  </PropertyGroup>
```

the "IntDir" properties correctly contain both platform and configuration...
but the "OutDir" are all '.\', making each build overwrite each other.
it would probably be better to make the default behave the same as "IntDir", or not set the property at all and make it use the visual studio default.

**Comment by starkos** [comment]
If we do that, then we have to propagate that behavior to every other tool which Premake supports. It can't just be a VS thing.

**Comment by tvandijck** [comment]
agreed, it seems that this behavior is coming from the 
```lua
function config.buildtargetinfo(cfg, kind, field)
```

so if we fix it there it'll propagate... interestringly the "objdir" is calculated in the oven process... so it's somewhat disconnected from the targetdir entirely...

**Comment by starkos** [comment]
Another option (untested) might be to drop into the configuration section of `_premake_init.lua`, maybe:

```lua
targetdir "%{prj.location}/%{cfg.buildcfg}/%{cfg.platform}"
```

Would have to make sure that works correctly if platforms are not set.
