### ISSUE TITLE
vectorextensions and isaextensions for gmake action

### ISSUE THREAD

**Issue by hugbed** [premake/premake-core#1366]
**Context**

Hi, I had a look at the vectorextensions and isaextensions implementations and couldn't help but notice that only the vcxproj.lua action implements this configuration. Does that mean that vectorextensions is only supported for the visual studio actions? If so, would it make sense to also populate the c / cpp flags for a toolset when this option is present for a configuration? 

**What problem will this solve?**

This would allow to have a consistent way of enabling vectorextensions `vectorextensions "AVX"` instead of having to configure `buildoptions { "-mavx" }` manually when the gmake action is used.

**What might be a solution?**

For example, this might be implemented as such in [src/tools/gcc.lua](https://github.com/premake/premake-core/blob/d561c80ed43e37aa0afd931ba21d7278deb05261/src/tools/gcc.lua):

```lua
function gcc.getcxxflags(cfg)
  local shared_flags = config.mapFlags(cfg, gcc.shared)
  local cxxflags = config.mapFlags(cfg, gcc.cxxflags)
  local flags = table.join(shared_flags, cxxflags)
  flags = table.join(flags, gcc.getwarnings(cfg))
  flags = table.join(flags, gcc.getvectorextensions(cfg))
  flags = table.join(flags, gcc.getisaextensions(cfg))
  return flags
end


function gcc.getvectorextensions(cfg)
  local result = {}
  if cfg.vectorextensions then
    table.insert(result, tostring(gcc.shared.vectorextensions[cfg.vectorextensions]))
  end
  return result
end

function gcc.getisaextensions(cfg)
  local result = {}
  if #cfg.isaextensions > 0 then
    for _, ext in ipairs(cfg.isaextensions) do
      if gcc.shared.isaextensions[ext] ~= nil then
        table.insert(result, tostring(gcc.shared.isaextensions[ext]))
      end
    end
  end
  return result
end
```
This would also be extended to clang since it's mostly using gcc flags.

This is pretty much how warnings are handled (see gcc.getwarnings()) so I suppose it would make sense.

Please tell me if there's something I overlooked. If it makes sense, I'll create a PR for it!

Thanks!

**Comment by samsinsane** [comment]
I can't see any reason why this shouldn't already be working? This provides the map between the two APIs and their output values: 
https://github.com/premake/premake-core/blob/fe962f898c99600af0bb923bf4c6f74547e200ad/src/tools/gcc.lua#L81-L102

While this performs the look up for C files: https://github.com/premake/premake-core/blob/fe962f898c99600af0bb923bf4c6f74547e200ad/src/tools/gcc.lua#L140-L141
And this performs the look up for C++ files: https://github.com/premake/premake-core/blob/fe962f898c99600af0bb923bf4c6f74547e200ad/src/tools/gcc.lua#L204-L205

Have you found that setting `vectorextensions "AVX"` doesn't work with the `gmake` or `gmake2` actions?

**Comment by hugbed** [comment]
I see, `config.mapFlags`, it looks like it does work! I believe my issue is with the filter I'm using but it's probably on my side.

Thanks for the quick reply!

**Comment by samsinsane** [comment]
> I believe my issue is with the filter I'm using but it's probably on my side.

Feel free to create an issue if you need assistance with that. If it's a filter for a specific file, the `gmake` action can't do that and you'll need to use the `gmake2` action instead. The `gmake2` action is intended to replace the `gmake` action.

**Comment by hugbed** [comment]
I'm are indeed using the `gmake` action so that would explain why file filters didn't work. Moving to `gmake2` will probably fix our issue then. Thanks!
