### ISSUE TITLE
Mac OS Catalina premake

### ISSUE THREAD

**Issue by shinerd** [premake/premake-core#1367]
**What's your question?**
I just updated Mac OS to Catalina, and premake4 doesn't work anymore. I tried premake5 too, but it says premake is made by unknown developer. So it can't run it. How can I handle this?

**Anything else we should know?**
I was trying to make SOIL2 with premake4.

**Comment by starkos** [comment]
I don't have a machine to test it on, but I'm pretty sure Apple's Gatekeeper doesn't apply to the command line. Are you running Premake from Terminal or are you trying to double-click it from Finder?

**Comment by samsinsane** [comment]
For what it's worth, I haven't encountered this issue at work since we upgraded to Catalina last week.

**Comment by shinerd** [comment]
@starkos I'm running it from terminal with `./premake4 gmake`
@samsinsane Thank you for your comment. The only difference between when it was working and now that it doesn't work is MacOS update.

+) When I try with premake4, it keeps saying `-bash: ./premake4: Bad CPU type in executable`

**Comment by shinerd** [comment]
I think I need 64bit premake4 for MacOS Catalina

**Comment by starkos** [comment]
I think @shinerd has the right answer here: you would need to rebuild your `premake4.exe` as a 64-bit executable; the prebuilt binaries are all 32-bit, which is no longer supported by macOS.
