### ISSUE TITLE
Multiple questions related to .vcxproj file generation.

### ISSUE THREAD

**Issue by hanseul1795** [premake/premake-core#1368]
**What are you trying to do?**
I'm trying to implement `.vcxproj` generation for vs 2015 and 2017.

**What problem are you having?**
I need to add and remove some of the flags in the `propertygroup` and in the `itemgroup`

**to add**
- flags
1- ` WholeProgramOptimization` 
2- `LocalDebuggerDebuggerType` 
3- `DebuggerFlavor`

- ItemGroup
<ItemGroup>
    < None   Include= "FileName/>
 (adding None)

**to remove(flags)**

1- `ImportLibrary`  in `ItemDefinitionGroup/Link`

**What have you tried so far?**

tried to use `flags` to add those flags but it's not recognized.
and for `removing flags` and `None` in itemgroup, I could not find anything on google.

**What version of Premake are you using?**
`premake5 --alpha`

**Comment by samsinsane** [comment]
I'm sorry it's not overly clear what you're wanting here, but I've tried to give replies for some of what you wanted:
- `WholeProgramOptimization` can be set via `flags { "LinkTimeOptimization" }`.
- `LocalDebuggerDebuggerType` can be set with [`debuggertype`](https://github.com/premake/premake-core/wiki/debuggertype).
- `DebuggerFlavor` can be set with [`debugger`](https://github.com/premake/premake-core/wiki/debugger) and you probably want [these extra options](https://github.com/premake/premake-core/blob/b96bc35ba1142472e06b2bbd6b6db2a6b43c51b1/modules/vstudio/_preload.lua#L27-L30).

Generally, you can search the repo for the VS elements that you want to set and you'll usually find the API that's used. `cfg.<something>` or `prj.<something>` will usually mean there's an API called `<something>`. For example, here is `debugger`: https://github.com/premake/premake-core/blob/09ee8334933e3953d96070047512820730518cc1/modules/vstudio/vs2010_vcxproj_user.lua#L81-L95

**Comment by hanseul1795** [comment]
@samsinsane  
Thank you Samuel! 
I had no idea where to search for the source code. 
I'll close this question since I could search for it in the source code, Thanx again!
Hanseul
