### ISSUE TITLE
How to properly use buildaction?

### ISSUE THREAD

**Issue by hanseul1795** [premake/premake-core#1369]
**What's your question?**
I'm trying to change all `.mm` files from `ClCompile` to `None` in `vcxproj` file. 
So in `premake5.lua` script, I've added the following line

```  
filter "files:**.mm"
   buildaction "None"
    
  files {
      "../Platform/Apple/LoadingViewController.mm"
    }
```
but `LoadingViewController.mm` file is not added to the `vcxproj` file at all.

expected result is 

```
<ItemGroup>
    <None Include="Platform\Apple\LoadingViewController.mm" />
 </ItemGroup>
```

**Comment by samsinsane** [comment]
You need to reset the `filter` before you call `files`:
```lua
filter { "files:**.mm" }
  buildaction "None"
filter {}

files {
  "../Platform/Apple/LoadingViewController.mm",
}
```
