### ISSUE TITLE
Can't generate .vcxitems

### ISSUE THREAD

**Issue by Healyd** [premake/premake-core#1382]
Hey!

I'm am using premake5 (also I'm new to using premake in general). I'm trying to generate a "SharedItems" project but I get the error "_invalid value 'SharedItems' for kind_". It looks like .vcxitems files are supported and the key word "SharedItems" is supported too, but this 'kind' isn't being recognized. Am I using it wrong or is this a bug?

Example use case:
`project "Library.Shared"`
	`kind "SharedItems"`
	`language "C++"`
	`location "source/Library.Shared"`

Thanks!

**Comment by starkos** [comment]
SharedItems projects aren't yet supported by Premake. You're welcome to take a crack at adding support, otherwise I'll leave this issue open in case someone else feels like taking it on.

**Comment by samsinsane** [comment]
@starkos this support was added in with #1351. 

@Healyd can you provide any of the information that our template requests? It's there for a reason. What action are you using? What version of premake are you using? This feature isn't in any of the alpha releases yet, so you can only use it with a master build.

**Comment by starkos** [comment]
Thanks @samsinsane, I missed that one.

**Comment by Healyd** [comment]
I was using Premake 5.0 (alpha 14). I thought it was in the alpha release, so that is my issue. Thanks!
