### ISSUE TITLE
Is CMake Still Supported?

### ISSUE THREAD

**Issue by cxgslegend** [premake/premake-core#1383]
**What's your question?**
Is Cmake still a supported module? I would love this because it enables us to work with Clion (which is one of the best cross-platform IDEs in my opinion). 

**Anything else we should know?**
I tried to follow the link on the modules page (https://github.com/premake/premake-core/wiki/Modules), and it is broken. 

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to questions like these!)*

**Comment by starkos** [comment]
That module was not developed by any of the core Premake developers. You'd need to contact the original module author with any questions.
