### ISSUE TITLE
Premake generates a Makefile with -string flag when symbols are set to symbols "On"

### ISSUE THREAD

**Issue by pvorisek25** [premake/premake-core#1389]
I am using Premake for some time but while I was testing my program on Linux, my program crashed. I googled how to debug programs on Linux and I found that there is GNU debugger called GDB. I search that I need to have debug symbols in order to debug my program so I set the symbols flag to: "On" but GDB kept saying that it can't find any debug symbols. I quickly found that you need to exclude every -s flag in order to generate debug symbols (https://stackoverflow.com/questions/1937420/how-to-generate-debug-symbols-with-makefile-for-c-linux). So I looked into Makefile generated by Premake and I found that the Makefile is full of the -s flag.
What I have to disable in order to stop the -s flags from generating?

**Comment by samsinsane** [comment]
We have a template for reporting issues that will prompt you to provide us with various bits of information we need to know to help, without this it's all guess work.

> What I have to disable in order to stop the -s flags from generating?

The `-s` flag is generated via [this function](https://github.com/premake/premake-core/blob/63a1e5ff3b66ef97392f42a8df7da91fc863ecf4/src/tools/gcc.lua#L344-L347), which is called when `symbols` is set to `Off` or `Default` defined by [this table](https://github.com/premake/premake-core/blob/63a1e5ff3b66ef97392f42a8df7da91fc863ecf4/src/tools/gcc.lua#L376-L379). If you're using `symbols "On"` and still seeing `-s`, I would assume you have applied `symbols "On"` to a random `filter`. Again, without the information requested in the issue template, I can't help you anymore than assume you've done something wrong in your `premake5.lua`.

**Comment by pvorisek25** [comment]
@samsinsane Thanks for your reply. The `symbols "On"` was in random filter. Thanks again.
