### ISSUE TITLE
Premake script fails with "bad argument #2 to 'translate' (string expected, got no value)"

### ISSUE THREAD

**Issue by Skylark13** [premake/premake-core#1393]
Hello,

**What are you trying to do?**
Use premake5 to generate project files that would contain certain files, but would not build anything.

**What problem are you having?**
If I include this section in my script:
~~~
project "../cgen/Shaders"
	kind "None"
	language "C++"

	files { "../HLSL/**.hsh", "../HLSL/**.hlsl" }

	filter "files:**.hsh,**.hlsl"
		buildaction "None"
~~~

And try to generate the projects:
~~~
.\premake5 --file=ShaderCodeGen_Projects.premake5.lua vs2017
~~~

Then premake5 fails with the following error:
~~~
Error: [string "vstudio/vstudio.lua"]:276: bad argument #2 to 'translate' (string expected, got no value)
~~~

**What have you tried so far?**
Removing this section from the script (it contains another project which includes .h, .cpp, .xml files) generates fine. The entire script will be pasted below.

**What version of Premake are you using?**
I have downloaded it today:
premake5 (Premake Build Script Generator) 5.0.0-alpha14

**Anything else we should know?**
Doing the equivalent with premake4 worked fine (but there is no vs2017 generator, so if I include the generated projects in a solution for vs2017 Visual Studio shows me "(Visual Studio 2012)" for example next to the project name. Minor annoyance...

Full premake5 script (does not generate correctly unless I remove the "Shaders" project) :
~~~
workspace "../cgen/ShaderCodeGen_Projects"
	configurations { "Debug", "Release" }

project "../cgen/ShaderCodeGen_GeneratedFiles"
	kind "None"
	language "C++"

	files { "../Src/Shaders/cgen/**.h", "../Src/Shaders/cgen/**.cpp", "../**.xml" }

	filter "files:**.h,**.cpp,**.xml"
		buildaction "None"

project "../cgen/Shaders"
	kind "None"
	language "C++"

	files { "../HLSL/**.hsh", "../HLSL/**.hlsl" }

	filter "files:**.hsh,**.hlsl"
		buildaction "None"
~~~

Full premake4 script which generates correctly :
~~~
solution "../cgen/ShaderCodeGen_Projects"
	configurations { "Debug", "Release" }
	platforms { "x64" }

	project "../cgen/ShaderCodeGen_GeneratedFiles"
		kind "ConsoleApp"
		language "C++"
		files { "../Src/Shaders/cgen/**.h", "../Src/Shaders/cgen/**.cpp", "../**.xml" }

		configuration { "**.h", "**.cpp" }
			buildaction "None"

	project "../cgen/Shaders"
		kind "ConsoleApp"
		language "C++"
		files { "../HLSL/**.hsh", "../HLSL/**.hlsl" }

		configuration { "**.hsh", "**.hlsl" }
			buildaction "None"
~~~

Thanks in advance,

J-S

**Comment by samsinsane** [comment]
I'm not sure how this worked in Premake4 as I never used it, but in Premake5 the project name and location are broken into two different APIs:
```lua
project "Shaders"
  location "../cgen"
```
and if you want the project in a folder in VS called `cgen`:
```lua
group "cgen"
  project "Shaders"
    location "../cgen"
```

**Comment by Skylark13** [comment]
It did work in premake4 but yeah I see that location is more appropriate than trying to put the path to the generated project in the project name directly... I'll try that. Still, weird that it worked for the solution and first project, but not the second project. Thanks.

**Comment by samsinsane** [comment]
> It did work in premake4 but yeah I see that location is more appropriate than trying to put the path to the generated project in the project name directly... I'll try that.

I'm not sure why this was changed and without any kind of warning when specifying names like this. It's possible it used to emit a warning and that was removed in the last several years.

> Still, weird that it worked for the solution and first project, but not the second project. Thanks.

No worries, I have no clue why it worked for the solution and first project, very weird.
