### ISSUE TITLE
premake4 generated filters have a uuid that changes every time

### ISSUE THREAD

**Issue by Skylark13** [premake/premake-core#1394]
**What seems to be the problem?**
When generating the .vcxproj.filters file, premake4 generates a uuid for each filter:
~~~
    <Filter Include="FilterName">
      <UniqueIdentifier>{F6D093E0-1E7A-0A49-A459-4CFB95BBAF8A}</UniqueIdentifier>
    </Filter>
~~~

The problem is this uuid changes every generation, so it makes the project file look like it changed each time. The project object has a uuid field which we can change so it stays the same every generation, but I don't see any way to set that for filters.

**What did you expect to happen?**
The uuid should be stable. You could, for example, generate an MD5 from the filter name, then generate a uuid from that. It would stay the same since it's based on a hash of the name.

**What have you tried so far?**
Generating the projects

**How can we reproduce this?**
Any script that includes files from multiple directories will generate a filters file with uuids that change.

**What version of Premake are you using?**
premake4 (Premake Build Script Generator) 4.4-beta5

**Anything else we should know?**
It would be even better if internally, Premake generated the build files to a buffer in memory and before writing the files, it compared to the previously-generated project files (using xml deep comparison so the order of tags doesn't matter). That way Visual Studio would not ask to reload a project when there are no significant differences (no added/removed files, no changed build options, etc.) as it does now.

Thanks in advance,

J-S

**Comment by samsinsane** [comment]
This repo is for Premake5, the Premake4 repo is [here](https://github.com/premake/premake-4.x
) but no active development takes place in that repo, you're more than welcome to open a PR and it will be reviewed and merged. I don't believe that Premake5 suffers from this issue as we use the file name/path to generate the UUID.
