### ISSUE TITLE
Custom Build Steps

### ISSUE THREAD

**Issue by redorav** [premake/premake-core#1400]
**What problem will this solve?**
I'm trying to add Custom Build Steps to my build, I can now see how they would be done in the vcxproj (via the Visual Studio interface) but now I would like to add them to premake.

**What might be a solution?**
I'm trying to find out whether premake supports this but it seems like it doesn't as I've not been able to find any mention of it in the code, so perhaps I could give it a stab.

**What other alternatives have you already considered?**
I've considered build rules and pre/post events, but they all follow the "input -> output" model, whereas I'm trying to run something only once if certain dependencies have been modified with respect to a single output file. The custom built step works at a project, not file, level. Here's the documentation for the feature. https://devblogs.microsoft.com/visualstudio/custom-build-steps-tools-and-events/ and https://docs.microsoft.com/en-us/cpp/build/how-to-add-a-custom-build-step-to-msbuild-projects?view=vs-2019

Where do you think I could start and what should the interface be? I can see how the properties would fit in MSBuild, would I find issues trying to do the same thing in XCode or gmake2?

In Visual Studio there are several properties relating to this

- command line
- description
- outputs
- dependencies (other than output)

These are the ones I'm mostly interested in. Does something like this make sense?

project("MyProject")
    buildstepcommand("mytool.exe")
    buildstepdescription("executes tool")
    buildstepoutput("file.ext")
    buildstepdependencies { "a.file", "b.file" }

**Comment by samsinsane** [comment]
There's [this](https://github.com/premake/premake-core/wiki/Custom-Build-Commands#custom-build-commands) using [`buildcommands`](https://github.com/premake/premake-core/wiki/buildcommands), [`buildmessage`](https://github.com/premake/premake-core/wiki/buildmessage), [`buildoutputs`](https://github.com/premake/premake-core/wiki/buildoutputs), and [`buildinputs`](https://github.com/premake/premake-core/wiki/buildinputs) - is this what you're looking for?

**Comment by redorav** [comment]
The problem I have with those is that build commands are run once per build input, whereas I want to run the step only once, but based on multiple dependencies which could cause that one process to run. Does what I'm looking for make sense?

**Comment by redorav** [comment]
Just a few more comments on this, it looks like in Visual Studio there are several ways to do custom build actions:

1) **Custom build tool:** This is used on a per-file basis. Essentially maps to the "Custom Build Tool" in Visual Studio.
2) **Rules:** Another mechanism for doing the above. Premake also calls them rules
3) Build Events: Perform certain actions before a project build takes place (if the build is to take place), or after. Premake calls these postbuildcommands and prebuildcommands.
4) Build Steps: Perform one command as part of the project build, taking dependencies into account. Premake doesn't expose this and this is what I would like to add.

**Comment by redorav** [comment]
@samsinsane I've managed to get this to work in Visual Studio by reusing the existing 4 keywords you showed me, but in the context of a project, that is, if there are no file filters present it will execute for the project you've selected. Other filters like config still work. I could directly send a PR or we could discuss it further?

**Comment by starkos** [comment]
A PR would probably be a good idea, since it would give us something real to discuss.

**Comment by redorav** [comment]
Thanks, I've added #1403

**Comment by remram44** [comment]
Should this be closed now that the PR is in?

**Comment by redorav** [comment]
@remram44 Indeed, thanks
