### ISSUE TITLE
Inconsistency regarding architecture in documentation

### ISSUE THREAD

**Issue by Croydon** [premake/premake-core#1405]
The architecture page lists `x86` and `x86_64` as possible values
While the Configurations and Platforms page uses `x32` and `x64`

Is one of them wrong? Are all values valid? If so, the architecture page should probably mentions this, otherwise it needs correction

https://github.com/premake/premake-core/wiki/architecture
https://github.com/premake/premake-core/wiki/Configurations-and-Platforms

**Comment by samsinsane** [comment]
You can see the possible values in the code:
https://github.com/premake/premake-core/blob/0a9844891d5cd562181bbad2dbc34daf65b7c3cc/src/_premake_init.lua#L25-L37

`x32` and `x64` are allowed but aren't the "correct" values, and as the comment indicates they should be deprecated. I've updated the page to not use those values.
