### ISSUE TITLE
Multiple targetsuffix

### ISSUE THREAD

**Issue by codecat** [premake/premake-core#1407]
**What's your question?**
Is it possible to have multiple `targetsuffix` for multiple different configurations?

**Anything else we should know?**
For example:

```lua
project 'foo'
  filter { 'platforms:x86' }
    targetsuffix '-x86'
  filter { 'configurations:Debug' }
    targetsuffix '-debug'
```

It would be great if the resulting target suffix for x86 debug builds would be `-x86-debug`, whereas right now (if I have my test case correct) it's just overridden by the last `targetsuffix` call.

**Comment by samsinsane** [comment]
> Is it possible to have multiple `targetsuffix` for multiple different configurations?

No, but you can do something like `targetsuffix "-%{cfg.platform}-%{cfg.buildcfg}"` instead.

**Comment by codecat** [comment]
Ah, nice, thank you! [The documentation](https://github.com/premake/premake-core/wiki/targetsuffix) doesn't mention this, perhaps it would be good to add it.

**Comment by samsinsane** [comment]
You raise a good point about the docs, I'll open a new issue to ensure that all APIs that can take Tokens are documented to do so.
