### ISSUE TITLE
How to add "executable file path" in VC++ direcitory

### ISSUE THREAD

**Issue by qatnonoil** [premake/premake-core#1410]
**What's your question?**
I want to add specific path to "executable file path" in VC++ directory.
There are "sysincludedirs" and "syslibdirs", but not "sysexedirs".
Why not? And How to add "executable file path".

Thanks.

**Comment by samsinsane** [comment]
Can you elaborate on exactly what this `sysexedirs` would be for?

**Comment by qatnonoil** [comment]
This is a property page of the Japanese version VisualStudio, the display position is the same as the English version (maybe).
![image](https://user-images.githubusercontent.com/8808167/76780278-14fa9580-67f0-11ea-8d8c-d80157153ed6.png)
I want to add the file path where binary (.exe) is located to this line.

**Comment by samsinsane** [comment]
It looks like you can set that with `bindirs`?

**Comment by qatnonoil** [comment]
That was exactly what I wanted!
Thanks.
