### ISSUE TITLE
CodeLite Generation Broken, Breaks with Multiple Platforms

### ISSUE THREAD

**Issue by Spirrwell** [premake/premake-core#1411]
Hello! I'm running premake5 5.0.0-alpha14

When I generate a CodeLite project with premake that has multiple platforms, generation seems to break. Specifically, if I use something like "links" to link another project. If I rebuild the workspace, everything seems to build fine, but if I build the specific project that calls "links" it gives me an error like "No rule to make target '".build-x86_64', needed by 'bin/x86_64/Debug/test_exe'"

This seems to be an old issue as I've come across something similar here: https://github.com/premake/premake-codelite/issues/17

In testing, it seems to be caused by the OR character '|' in the generated .project files.

![image](https://user-images.githubusercontent.com/8671884/77279763-ea4d8880-6c98-11ea-8b0c-0f640f7867a2.png)

I can induce the problem if I use configurations only with no platforms, and I use the '|' character.

`configurations{ "Debug|32","Release|32", "Debug|64", "Release|64" }`

If I don't use |, there are no issues.

I don't know why. But it seems like a straightforward solution is to not use |

As an extra reference, here's an example premake file (and repo) that reproduces the issue https://github.com/Spirrwell/premake-codelite-bug/blob/master/premake5.lua

**Comment by samsinsane** [comment]
It's likely we just need to escape the `|`, probably as `&verbar;` in this function https://github.com/premake/premake-core/blob/5b2f92c9ceb79aab1f7fed847871a0be1fc31b4c/modules/codelite/codelite.lua#L37-L43

If you add the following to your `premake5.lua` does it resolve the issue?
```lua
premake.override(premake.modules.codelite, "esc", function(oldfn, value)
  return oldfn(value):gsub("|", "&verbar;")
end)
```

**Comment by Spirrwell** [comment]
No, doing this seems to nuke my workspace, none of my projects show up in CodeLite. The | symbols are still there as well, but I do see &verbar; in some spots.

As far as I can tell, it seems like the issue is here on this line:
https://github.com/premake/premake-core/blob/master/modules/codelite/codelite.lua#L24

Using an underscore here instead of | works fine.

**Comment by starkos** [comment]
Out of curiosity, if you set up a similar multi-platform project by hand, using the CodeLite UI instead of Premake, what value does it put there?

Wherever possible, we try to match the "native" behavior of the tool. But our experience with CodeLite is, well, "lite" so a lot of Visual Studio behaviors carry over instead.

**Comment by Spirrwell** [comment]
I don't think CodeLite has a concept of "platforms", but instead it seems everything is a configuration. Whatever you name your configuration is what ends up in the workspace/project files.

**Comment by starkos** [comment]
To confirm, if you add the following to your `premake5.lua` does it resolve the issue?

```lua
premake.override(premake.modules.codelite, "esc", function(oldfn, value)
  return oldfn(value):gsub("|", "_")
end)
```

**Comment by Spirrwell** [comment]
The projects show up with that, but it doesn't build and gives this output:
![image](https://user-images.githubusercontent.com/8671884/77938415-b4edff80-7283-11ea-9125-3d24f5f4876f.png)

**Comment by starkos** [comment]
Thanks, one more: what if you change [`codelite.lua:24`](https://github.com/premake/premake-core/blob/master/modules/codelite/codelite.lua#L24) from this:

```lua
cfgname = string.format("%s|%s", cfg.platform, cfg.buildcfg)
```

…to this:

```
cfgname = string.format("%s&verbar;%s", cfg.platform, cfg.buildcfg)
```

If that doesn't work I'll concede and switch it to a "-" (dash).

**Comment by Spirrwell** [comment]
That doesn't work
![image](https://user-images.githubusercontent.com/8671884/77978734-d1fcef80-72d0-11ea-9363-e17668a6fe51.png)

**Comment by starkos** [comment]
Thanks for checking it, @Spirrwell. I went ahead and fixed with a dash "-".
