### ISSUE TITLE
passing args to custom actions

### ISSUE THREAD

**Issue by qaisjp** [premake/premake-core#1413]
**What's your question?**

How do you receive args passed to custom actions?

E.g. `premake5 my-action-name somearg1 somearg2` - I want to be able to get `somearg1` and `somearg2`.

**Anything else we should know?**

We have an action like this but the `arg` global is unset, and the function has no args passed to it

```

newaction {
	trigger = "install_cef",
	description = "Downloads and installs CEF",

	execute = function()
		-- First check if an arg "upgrade" was provided
		if #arg >= 1 and arg[1] == "upgrade" then
            print("upgrade cef")
            return
        end

        -- do stuff
    end
}
```

**Comment by samsinsane** [comment]
You can use the [options](https://github.com/premake/premake-core/wiki/newoption) system which will give you some control over things. If that doesn't fit your needs, you can use `_ARGS` instead of `arg`.

**Comment by qaisjp** [comment]
Aren't options globally scoped? Is it possible for an option to only apply for a specific action?

**Comment by samsinsane** [comment]
Yes, they are globally scoped, and I don't believe there's anyway to apply them for a specific action.

**Comment by qaisjp** [comment]
Cool, thanks!
