### ISSUE TITLE
Can't figure out how to do an out of tree build, is it possible? 

### ISSUE THREAD

**Issue by Sixmorphugus** [premake/premake-core#1418]
Hello, 
I'm trying to use premake for my own C project and it works great except that I cannot figure out how to make premake put the generated visual studio project files somewhere else. I can probably move the files myself once they've been generated but i'm sure there's something i've missed - having to gitignore / clean up the obj folder, visual studio bookkeeping files is very annoying.

**Comment by samsinsane** [comment]
[`location`](https://github.com/premake/premake-core/wiki/location) should be what you're looking for.

**Comment by Sixmorphugus** [comment]
Thanks very much!

**Comment by samsinsane** [comment]
No worries, I'm going to close this issue, if you have any issues please feel free to reopen it.
