### ISSUE TITLE
Add force compile or force language option?

### ISSUE THREAD

**Issue by leeonix** [premake/premake-core#142]
Today I met one question, some C99 code in msvc must compile by C++ compile.
but msvc default /TC or /TP choice by ext. so i add this code to force build by C++.

``` Lua
filter 'action:vs*'
    buildoptions '/TP'
```

I generate gmake file, also choice as cc by ext.
I think premake maybe add a `forcelanguage`.
in my memory, premake4 a prev verstion, `language` is force choice.

**Comment by starkos** [comment]
Did you try setting the project language to "C++"?

```lua
project "MyProject"
   filter "action:vs*"
      language "C++"
```

**Comment by leeonix** [comment]
Yes. i confirm it.
I search the code. `CompileAs` section not has C++ option. just C.
sometimes, use others source file, the file ext, not decide by ourselves.
If add PCH make fast, force compile as C or C++ it's important.

**Comment by starkos** [comment]
Okay, thanks for letting us know. I think that setting `language()` should do what you're asking for; if not I think it should be considered a bug.
