### ISSUE TITLE
The link of release alpha15 on windows is missing a dot

### ISSUE THREAD

**Issue by mercury233** [premake/premake-core#1428]
**What seems to be the problem?**
The link of release alpha15 on windows is missing a dot
![image](https://user-images.githubusercontent.com/13391795/80171040-f7ed8980-861b-11ea-9e00-39b15b052919.png)

**What did you expect to happen?**
Keep the filename in the same format
![image](https://user-images.githubusercontent.com/13391795/80171056-00de5b00-861c-11ea-8dfa-10d12d795fa9.png)

**Comment by starkos** [comment]
Gah, how did that happen! Fixed now, and I'll investigate…thanks for letting me know!
