### ISSUE TITLE
Error on latest version 5.0-alpha15, Error: [string "src/base/api.lua"]:146: attempt to index a nil value (local 'value')

### ISSUE THREAD

**Issue by cexer** [premake/premake-core#1429]
**What seems to be the problem?**
Downaloded latest release (alpha15) windows binary, and latest source code, run command 

`premake5 vs2017` 

on the code, didn't work, output:

`Error: [string "src/base/api.lua"]:146: attempt to index a nil value (local 'value')`

**What did you expect to happen?**
Generate vs2017 solution and project files on the command.

Please fix this ....

**Comment by starkos** [comment]
Appreciate the quick bug report—better safe than sorry if a bug got shipped.

**Comment by cexer** [comment]
> Appreciate the quick bug report—better safe than sorry if a bug got shipped.

Sorry for this false alarm, it turns out that I was running the command in bash envirement, after switch to cmd envirement, everything goes well. thanks for the quick reply.
