### ISSUE TITLE
flags{"C++11"} add --std=c++11 on .C files

### ISSUE THREAD

**Issue by cexer** [premake/premake-core#1431]
**What seems to be the problem?**
Using latest release (alpha15), want to add `-std=c++11` option to c++ files: 

`flags{"C++11"}`

But this will add -std=c++11 on .c files also, which cause compiler errror on xcode:
`invalid argument '-std=c++11' not allowed with 'C'`

**What did you expect to happen?**
`C++11` flag only affect c++ files.

**What have you tried so far?**
Tried using `buildoptions` command, but it also affect c files.

**Comment by cexer** [comment]
This worked, sorry didn't notice this language filter
`
	filter{"language:C++"}
		flags{"C++11"};
`

**Comment by samsinsane** [comment]
The flags were replaced with [`cdialect`](https://github.com/premake/premake-core/wiki/cdialect) and [`cppdialect`](https://github.com/premake/premake-core/wiki/cppdialect), I don't believe these suffer from the same problem.

**Comment by cexer** [comment]
> The flags were replaced with [`cdialect`](https://github.com/premake/premake-core/wiki/cdialect) and [`cppdialect`](https://github.com/premake/premake-core/wiki/cppdialect), I don't believe these suffer from the same problem.

Glad to know, I'll try that later.
