### ISSUE TITLE
Treat warnings as errors

### ISSUE THREAD

**Issue by GoncaloRod** [premake/premake-core#1432]
How can I enable the "Treat warnings as errors" option in visual studio? I tried this ```fatalwarnings { "warnings" }``` doesn't seem to work.

**Comment by samsinsane** [comment]
That currently falls under the [`flags`](https://github.com/premake/premake-core/wiki/flags) system, with the flag `FatalWarnings`.

**Comment by samsinsane** [comment]
Closing this as resolved.
