### ISSUE TITLE
Get include dirs of project

### ISSUE THREAD

**Issue by xahon** [premake/premake-core#1433]
I want to migrate from `cmake` to `premake` and building kind of modular solution split up by multiple projects each in their own directory. In cmake i was able to call `target_link_libraries(target myLibrary)` and all include directories are picked up automatically for current target. Is there such functionality in premake? Or at least a way to avoid path hardcoding (both relative paths via `../../Engine` and absolute `solutionRoot/Engine`)

**Comment by samsinsane** [comment]
We don't have anything like that directly but it is on our list of things to work out. However, since this is Lua you can create a workaround for this relatively easily. I have a rough idea of how you would achieve this but I haven't tested it out:
```lua
-- in solutionRoot/Engine/premake5.lua
engineProjBase = _SCRIPT_DIR
function EngineIncludeDirs()
  local incDirs = { … } -- replace … with the directories, relative to this file
  for i,v in ipairs(incDirs) do
    incDirs[i] = path.rebase(v, engineProjBase, _SCRIPT_DIR)
  end
  includedirs { incDirs }
end
```
Then anywhere you need those `includedirs` just add `EngineIncludeDirs()`.

**Comment by starkos** [comment]
To clarify on @samsinsane's answer a bit…to do this in the current version of Premake, you create a function that describes how to "use" your project, and then you call that while setting up your dependent projects to apply those settings.

```lua
project "MyEngine"
   -- configure project for building

function myEngineSettings()
   -- these needs to be absolute so they can be applied even if the
   -- target project is in a different directory
   includedirs {
      path.join(_SCRIPT_DIR, "includes/dir1"),
      path.join(_SCRIPT_DIR, "includes/dir2")
   }

   -- you can put any settings here, not just includedirs
   links { "MyEngine" }  

   -- or even do per-configuration stuff
   filter { "configurations:Debug" }
      defines { "ENGINE_DEBUG" }  

   -- just remember to clear your configuration filter before you return
   filter {}
end
```

So it's not ideal, and requires more hand-holding than I'd like, but it can express any configuration. When you want to use it from another project:

```lua
project "MyGame"
   myEngineSettings()
```

#1346 has a whole discussion on the topic if you're interested. I'm currently doing some R&D work toward this end.

Hope that helps! I'm going to close this issue as answered, but feel free to continue the discussion if you still have questions.
