### ISSUE TITLE
Add Cmake build support

### ISSUE THREAD

**Issue by Riku32** [premake/premake-core#1434]
**What problem will this solve?**
I use an IDE like CLion which only supports cmake as a build option.
This will allow CLion users to use Premake

**What might be a solution?**
Adding a cmake build option

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to requests like these!)*

**Comment by samsinsane** [comment]
This would be better suited as a 3rd party module - one already exists and you can find it [here](https://github.com/TurkeyMan/premake-cmake).

**Comment by Riku32** [comment]
That particular module does not work with premake5

**Comment by tritao** [comment]
CMake is very common place these days and used by more and more IDEs.

If stuff like CodeLite is in the core, why should not CMake support be as well?

**Comment by samsinsane** [comment]
With the current resources, we don't have the time to support something like this. If you feel strongly about this being in core, you're more than welcome to dedicate your time towards it. Alternatively, @starkos might be open to some contract work through the OpenCollective or something to get this into core - but given that CMake and Premake are competing products, it doesn't make a huge amount of sense to provide an auto-migration to CMake tool.

**Comment by Riku32** [comment]
Well the whole reason is because Premake is much easier to use than CMake so if there was a direct converter it would be incredibly easy to use it with any type of IDE.

**Comment by tritao** [comment]
> With the current resources, we don't have the time to support something like this. If you feel strongly about this being in core, you're more than welcome to dedicate your time towards it.

That's totally understandable, I think no one is expecting you or @starkos to have to do the work for this. Who knows, in the future I might even dedicate some time to implement this.

In my view the point of this feature would not be a "auto-migration", it could just emit platform specific CMake so projects load with CMake-backed IDEs (VSCode, CLion).

**Comment by samsinsane** [comment]
> That's totally understandable, I think no one is expecting you or @starkos to have to do the work for this.

Sure, but we will be expected to maintain it, and that's where the push back usually comes from with these kinds of things.

> Who knows, in the future I might even dedicate some time to implement this.

That sounds great! 😄 

> In my view the point of this feature would not be a "auto-migration", it could just emit platform specific CMake so projects load with CMake-backed IDEs (VSCode, CLion).

I don't know much about CMake, but that sounds like it could be quite complex still - every API that we support would need to map to _something_ in CMake for those IDEs. I would imagine at some point people are going to want improvements as the IDEs utilise more of the CMake settings for different things.

**Comment by starkos** [comment]
Basically: 'What @samsinsane said". Personally I think it should be a module, and any issues with distributing it that way should be addressed—i.e. we should work to improve modules rather than shove everything into core. I am definitely not taking on any new modules that don't come with an active maintainer and a good community to support it.
