### ISSUE TITLE
Alternative to cmake's generate_export_header

### ISSUE THREAD

**Issue by xahon** [premake/premake-core#1435]
I really haven't seen that command before and don't know how it works

**Comment by samsinsane** [comment]
What does `generate_export_header` do?

**Comment by xahon** [comment]
@samsinsane Not sure what exactly.
I guess it creates content like that
```C++
#ifndef CPPFS_API_H
#define CPPFS_API_H

#ifdef CPPFS_STATIC_DEFINE
#  define CPPFS_API
#  define CPPFS_NO_EXPORT
#else
#  ifndef CPPFS_API
#    ifdef cppfs_EXPORTS
        /* We are building this library */
#      define CPPFS_API __declspec(dllexport)
#    else
        /* We are using this library */
#      define CPPFS_API __declspec(dllimport)
#    endif
#  endif

#  ifndef CPPFS_NO_EXPORT
#    define CPPFS_NO_EXPORT 
#  endif
#endif

#ifndef CPPFS_DEPRECATED
#  define CPPFS_DEPRECATED __declspec(deprecated)
#endif

#ifndef CPPFS_DEPRECATED_EXPORT
#  define CPPFS_DEPRECATED_EXPORT CPPFS_API CPPFS_DEPRECATED
#endif

#ifndef CPPFS_DEPRECATED_NO_EXPORT
#  define CPPFS_DEPRECATED_NO_EXPORT CPPFS_NO_EXPORT CPPFS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef CPPFS_NO_DEPRECATED
#    define CPPFS_NO_DEPRECATED
#  endif
#endif

#endif /* CPPFS_API_H */
```

**Comment by xahon** [comment]
I've created a simple function
```Lua
function GenerateExportHeader( name, path )
    local s = [[
#ifndef $NAME$_API_H
#define $NAME$_API_H

#ifdef $NAME$_STATIC_DEFINE
#  define $NAME$_API
#  define $NAME$_NO_EXPORT
#else
#  ifndef $NAME$_API
#    ifdef cppfs_EXPORTS
        /* We are building this library */
#      define $NAME$_API __declspec(dllexport)
#    else
        /* We are using this library */
#      define $NAME$_API __declspec(dllimport)
#    endif
#  endif

#  ifndef $NAME$_NO_EXPORT
#    define $NAME$_NO_EXPORT 
#  endif
#endif

#ifndef $NAME$_DEPRECATED
#  define $NAME$_DEPRECATED __declspec(deprecated)
#endif

#ifndef $NAME$_DEPRECATED_EXPORT
#  define $NAME$_DEPRECATED_EXPORT $NAME$_API $NAME$_DEPRECATED
#endif

#ifndef $NAME$_DEPRECATED_NO_EXPORT
#  define $NAME$_DEPRECATED_NO_EXPORT $NAME$_NO_EXPORT $NAME$_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef $NAME$_NO_DEPRECATED
#    define $NAME$_NO_DEPRECATED
#  endif
#endif

#endif /* $NAME$_API_H */
    ]]
    s = string.gsub(s, "%$NAME%$", name)
    file = io.open(path, "w+")
    file:write(s)
    file:close()
end
```
but it doesn't work in `prebuildcommands`, because tokens aren't expanded
```Lua
prebuildcommands {
        GenerateExportHeader( "${prj.name}", "mypath" ),
}
```

**Comment by samsinsane** [comment]
There's a bit to respond to here. Firstly, to confirm, Premake doesn't have anything like that and I'm not really sure how it would work in Premake, we support more than C/C++ and Premake has largely avoided generating code. `prebuildcommands` takes an array of strings, your function doesn't return a string. The file is just Lua, so your function is executed before `prebuildcommands` is, so none of the tokens will expand properly/at all. `prebuildcommands` is the list of commands you want your IDE to execute.

If you want `GenerateExportHeader` to be run when you build your project in your IDE, you will need to use `newaction` or `newoption`, the former being the easier option there, and then call the function as required. If you want it to be run when you generate your solution files, you can do something like:
```lua
local prj = project "a"
GenerateExportHeader(prj.name, "mypath")
```

**Comment by starkos** [comment]
Adding to what @saminsane said: the commands you list in `prebuildcommands` are added by Premake to the tsolution/makefile/workspace it generates, which then gets loaded and evaluated by Visual Studio/GMake/Xcode. Those toolsets know nothing about Premake or your script; there is no way for them to run your code, or even know it exists.

If you know that a Premake executable will exist on your path, you could try defining a new Premake action like "GenerateHeaders" and then trigger Premake to run it in a `prebuildcommand` (untested):

```lua
prebuildcommands {
   -- note that tokens use %{}, not ${}
   'premake GenerateHeaders %{prj.name}' 
}
```

You _can_ use Lua functions at _project generation_ time, meaning when Premake is run to create the solution/makefile/workspace. If you're okay with that, @samsinsane's second option will do it.

```lua
local prj = project "a"
GenerateExportHeader(prj.name, "mypath")
```

Though, this seems like a lot of hoop jumping for a file that needs to exist in your codebase anyway. I don't really understand why you'd want to generate this out of your project scripts, rather then using a template or macro in your code editor of choice.

I'm going to make this closed as answered, but feel free to continue the discussion if you have more questions.
