### ISSUE TITLE
postbuildcommands generate duplicated & conflicated commands on XCode

### ISSUE THREAD

**Issue by cexer** [premake/premake-core#1437]
**What seems to be the problem?**
Using latest release(alpha15), to create xcode4 project files, generated duplicated & conflicated post build commands.

premake5.lua:
```
workspace "test_postbuildcmds"
	configurations {"dll-debug", "dll-release", "lib-debug", "lib-release"};
	platforms {"x32", "x64"};
	files { "**.h", "**.c" }

project "test_postbuildcmds"
	kind "ConsoleApp"
	language "C"
	targetdir "bin/%{cfg.buildcfg}"
	postbuildcommands "{COPY} %{wks.location}/lib/%{cfg.system}-%{cfg.architecture}/libtest_dll.dylib %{wks.location}/bin/"
```

Generated commands:
```
set -e
if [ \"${CONFIGURATION}\" = \"dll-debug\" ]; then
cp -rf lib/macosx-x86/libtest_dll.dylib bin
fi

if [ \"${CONFIGURATION}\" = \"dll-debug\" ]; then
cp -rf lib/macosx-x86_64/libtest_dll.dylib bin
fi

if [ \"${CONFIGURATION}\" = \"dll-release\" ]; then
cp -rf lib/macosx-x86/libtest_dll.dylib bin
fi

if [ \"${CONFIGURATION}\" = \"dll-release\" ]; then
cp -rf lib/macosx-x86_64/libtest_dll.dylib bin
fi

if [ \"${CONFIGURATION}\" = \"lib-debug\" ]; then
cp -rf lib/macosx-x86/libtest_dll.dylib bin
fi

if [ \"${CONFIGURATION}\" = \"lib-debug\" ]; then
cp -rf lib/macosx-x86_64/libtest_dll.dylib bin
fi

if [ \"${CONFIGURATION}\" = \"lib-release\" ]; then
cp -rf lib/macosx-x86/libtest_dll.dylib bin
fi

if [ \"${CONFIGURATION}\" = \"lib-release\" ]; then
cp -rf lib/macosx-x86_64/libtest_dll.dylib bin
fi
```

**What did you expect to happen?**
generate correct post build commands

**How can we reproduce this?**
Unzip this file and run `Premake5 --os=macosx xcode4` on it, it will reproduct the issue.
[test_postbuildcmds.zip](https://github.com/premake/premake-core/files/4549696/test_postbuildcmds.zip)

**What version of Premake are you using?**
premake5 (Premake Build Script Generator) 5.0.0-dev

**Anything else we should know?**
I havn't tried on `prebuildcommands,` but I think it probably has the same issue.

**Comment by samsinsane** [comment]
You haven't provided nearly enough information here, I can't see what's wrong with the snippet you've posted. The only problem that I can see is that you have 32bit builds on macOS, I was under the impression that Apple removed that in one of the last couple releases of macOS?

**Comment by cexer** [comment]
> You haven't provided nearly enough information here, I can't see what's wrong with the snippet you've posted. The only problem that I can see is that you have 32bit builds on macOS, I was under the impression that Apple removed that in one of the last couple releases of macOS?

Sorry didn't make it clear. The issue with the result snippet generated by premake is, for example , with the same condigion `${CONFIGURATION}" = "dll-debug`, there are two different `cp' commands, and the 'macosx-x86' one causes the post build step failure, because there isn't a `lib/macosx-x86` directory, and I was doing a 64bit build (not a 32bit build, actually there isn't a way to do the 32bits build as you know).
```
if [ \"${CONFIGURATION}\" = \"dll-debug\" ]; then
cp -rf lib/macosx-x86/libtest_dll.dylib bin
fi

if [ \"${CONFIGURATION}\" = \"dll-debug\" ]; then
cp -rf lib/macosx-x86_64/libtest_dll.dylib bin
fi
```

But as you said, maybe it's the `platforms {"x32", "x64"}` issues, since macOS dosen't has a 32bits support. I'll try exclude 'x32' platfrom on macOS and see.

**Comment by cexer** [comment]
> But as you said, maybe it's the `platforms {"x32", "x64"}` issues, since macOS dosen't has a 32bits support. I'll try exclude 'x32' platfrom on macOS and see.

This does work:
```
	if (os.target() ~= "macosx") then
		platforms {"x32", "x64"};
	else
		platforms {"x64"};
	end
```

By this, premake generated snippet:
```
set -e
if [ \"${CONFIGURATION}\" = \"dll-debug\" ]; then
cp -rf lib/macosx-x86_64/libtest_dll.dylib bin
fi
if [ \"${CONFIGURATION}\" = \"dll-release\" ]; then
cp -rf lib/macosx-x86_64/libtest_dll.dylib bin
fi
if [ \"${CONFIGURATION}\" = \"lib-debug\" ]; then
cp -rf lib/macosx-x86_64/libtest_dll.dylib bin
fi
if [ \"${CONFIGURATION}\" = \"lib-release\" ]; then
cp -rf lib/macosx-x86_64/libtest_dll.dylib bin
fi
```

**Comment by cexer** [comment]
Close this  issue. This isn't a bug, I used `platform` wrong, thanks @samsinsane.
