### ISSUE TITLE
Disable XP deprecation warning when compiling with msvc v141_xp toolset

### ISSUE THREAD

**Issue by withmorten** [premake/premake-core#1438]
Hi there - I often compile projects with the v141_xp toolset in VS2019 - but doing so emits the following warning:

`MSB8051: Support for targeting Windows XP is deprecated and will not be present in future releases of Visual Studio.`

This can be disabled by adding `<XPDeprecationWarning>false</XPDeprecationWarning>` within a PropertyGroup of the Project, but I haven't found a way to do so with a premake.lua script.

So then, I just now decided to just fix it rather hackily in the premake source itself, by simply adding this line to *any* vc project ... (my commit in my fork here):

https://github.com/withmorten/premake-core/commit/aedeb3273cb070b761d8bb22b6e3b4678588ab75

Now that I know it's possible, is there any better way this could be solved? I personally doubt anybody choosing this specific toolset wants to see the warning, but maybe it should be only enabled with a specific setting, but I honestly don't know how one would implement it in premake.

Any ideas?

Thanks for the great tool,
Morten

**Comment by starkos** [comment]
I would be good with always adding it by default. Could you submit a PR to add it?

**Comment by withmorten** [comment]
Of course!

**Comment by starkos** [comment]
Closed by #1439.
