### ISSUE TITLE
How to make project to use precompiled library on windows?

### ISSUE THREAD

**Issue by xahon** [premake/premake-core#1440]
Imagine I have both sources and precompiled libraries for windows. I want conditionally use precompiled headers on windows instead of building everything from sources. I did not found any similar example in wiki, please, give an appropriate example

**Comment by samsinsane** [comment]
You can read about linking libraries [here](https://github.com/premake/premake-core/wiki/Linking) and if that "precompiled headers" wasn't a mistake, you can read about them [here](https://github.com/premake/premake-core/wiki/Precompiled-Headers).

**Comment by starkos** [comment]
Marking this closed as answered. Feel free to reopen if you still have questions.

**Comment by xahon** [comment]
@samsinsane yes, i've mistaken with precompiled headers. So, if i want to use project as kind of `interface` thing i need to add `links` and pass the path to `.lib`/`.a` file? Is it correct way?

**Comment by samsinsane** [comment]
That looks like it should work fine. If you store multiple libraries in `path/to`, you can also specify that via `libdirs { "path/to" }` and then just specify `links { "library.lib". "another.lib" }`.

**Comment by xahon** [comment]
@samsinsane It does not work, at least on linux. I have experienced some issues linking SDL and precompiled a static library by myself, then in config i added
```lua
    links({
        "glad",
        "imgui",
        "-libSDL2.a",
    })
```
and linker output is: /usr/bin/ld: cannot find -l-libSDL2.a
build directory contains the library

**Comment by starkos** [comment]
That doesn't look right, should be more like:

```lua
links({
   "glad"
   "imgui"
   "SDL2"
})
```

Does that not work for you?
