### ISSUE TITLE
Linking project to project in workspace doesn't work properly.

### ISSUE THREAD

**Issue by tomxmm0** [premake/premake-core#1449]
**What are you trying to do?**
Link a project called "A" in my workspace with a type of StaticLib to another project called "B" with a type of StaticLib that is also inside the workspace.

**What problem are you having?**
The .lib output of project B does not "include" the .lib output of project A. (B.lib only contained itself and not A.lib)

**What have you tried so far?**
at first I tried doing this (linking the project):
```lua
    links {
        "A"
    }
```

but when I noticed that it does not link properly i tried linking the .lib file manually:

```lua
   libdirs {
       "path/to/A/targetdir"
  }

  links {
     "A.lib"
  }
```

This linked A to B correctly.

**What version of Premake are you using?**
5.0.0-alpha15

**Anything else we should know?**
No.

**Comment by samsinsane** [comment]
We have no intention of making `links { "A" }` do what you want in this situation. Premake is a cross-platform tool and MSVC is the only toolset that does this "linking" for static libraries. I'm going to close this issue.
