### ISSUE TITLE
Windows Defender marks premake5.exe as Trojan 

### ISSUE THREAD

**Issue by IRCSS** [premake/premake-core#1450]
Hi, as the title says Windows Defender deletes the premake5.exe. 

The exact message is: 
Threat detected: Trojan:Win32/Fuery.C!cl 
Alert level: Severe
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.  

I am going to allow it manually, just thought I should report this in case there is something that can be done about it. 

Not sure if you can reproduce this exactly, since I didn't have a problem with it, despite having used premake5 for a month now, it suddenly appeared today. Here is repo where this is happening https://github.com/IRCSS/ToyRenderer/tree/dev 

The premake5 file is in vendor/bin/premake

**Comment by dgregorius** [comment]
Just happened for me as well. It seems to happen after the latest Windows Defender update...

**Comment by xgalaxy** [comment]
Yep. Happened to me as well.

**Comment by mendsley** [comment]
Not only is Windows marking it as a Trojan, but Chrome is now blocking downloads from https://premake.github.io/download.html

**Comment by alexfonseka** [comment]
Same here :/ 
Windows Defender kept removing my premake executable...

**Comment by starkos** [comment]
I've submitted the latest Premake5 Windows binary to Microsoft's [malware analysis website](https://www.microsoft.com/en-us/wdsi/filesubmission/); that's really all I can do from here. If you're still having issues, see the Windows support article [Add an exclusion to Windows Security](https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security).

Note that this has also been reported in the past, see #899 and #1141 for more information.

Marking closed as answered, but feel free to continue the conversation if you're still having trouble.

**Comment by starkos** [comment]
Nah, actually, I'll leave this open, though I'm not sure what else I can do to resolve it from this end—open to suggestions! In the meantime, let me know if things improve.

**Comment by starkos** [comment]
FYI…the results from the MS malware analysis I linked above:

<img width="1101" alt="Screen Shot 2020-05-21 at 9 06 18 AM" src="https://user-images.githubusercontent.com/249247/82566593-26db1a80-9b4a-11ea-9875-9bd0fe763a17.png">

Presumably the definitions will get updated eventually?

**Comment by starkos** [comment]
I'm not getting any warnings from Windows Defender here. How do things look out there? Still seeing issues?

**Comment by DhirajWishal** [comment]
Yup the windows defender isn't reporting anything now.

**Comment by IRCSS** [comment]
Also ok from my side. Thanks!

**Comment by starkos** [comment]
Excellent! Closing…
