### ISSUE TITLE
removevpaths always errors

### ISSUE THREAD

**Issue by qaisjp** [premake/premake-core#1463]
**What seems to be the problem?**

Using `removevpaths` causes the following error:

```bash
➜  src git:(feature/premake) ✗ ./premake5.exe vs2019
Building configurations...
Error: [string "src/base/configset.lua"]:75: attempt to call a nil value (method 'lower')
```

**What did you expect to happen?**

It should remove stuff in the amx folder from the vpaths

**What have you tried so far?**

I checked to see if it was just that `removevpaths` did not exist, but doing something like `removeblah` resulted in a different error (`attempt to call a nil value (global 'removeblah')`) so it looks like `removevpaths` should work.

**How can we reproduce this?**

```lua
workspace "test"
	configurations { "Debug", "Release" }
	platforms { "x86", "x64" }
	cppdialect "C++17"
	location "Build"
	targetdir "Bin"

	project "test_base"
		language "C++"
		kind "SharedLib"
		vpaths {
			["Headers/*"] = {"**.h"},
			["Sources/*"] = {"**.cpp"},

			["*"] = "premake5.lua",
		}
		removevpaths "amx/*.cpp"

		files {
			"premake5.lua",
			"**.cpp",
			"**.h",
		}
```

In same folder as your premake5.lua, have `main.cpp` and `amx/test.cpp`.

**What version of Premake are you using?**
`premake5 --version` will show you the version. If you are running a "-dev" version, please make sure you are up to date with the latest master branch.

v5.0.0-alpha15

**Comment by nickclark2016** [comment]
As far as I know, there is no removevpaths in premake5.  I'm not seeing any references to that in the source code either.

**Comment by samsinsane** [comment]
All of the `remove*` functions are automatically generated. In this case, you probably need to do something like this:
```lua
removevpaths {
  ["Sources/*"] = { "amx/*.cpp" }
}
```
However, I've never used it before and I'm not sure if it will work as you intend.

**Comment by qaisjp** [comment]
> In this case, you probably need to do something like this:
> 
> ```lua
> removevpaths {
>   ["Sources/*"] = { "amx/*.cpp" }
> }
> ```

Ah, of course, my bad. The error goes away when I use the correct vpaths syntax.



> I'm not sure if it will work as you intend.

Indeed I don't think it worked as I intended, but I guess that's out of scope for this issue.

**Comment by samsinsane** [comment]
To my understanding, all of the `remove*` APIs were just autogenerated for list types, and I guess `vpaths` just accidentally falls into that and nobody has tried to what you're doing. You might be able to do `vpaths { ["*"] = { "amx/*.cpp" } }` to achieve the `removevpaths` expected behaviour? It's been a while since I've looked at how `vpaths` works, so I could be wrong about how it works there.

**Comment by starkos** [comment]
I don't think I ever implemented a `remove()` for table fields; it might be picking up the list behavior as a default.
