### ISSUE TITLE
Call default premake actions

### ISSUE THREAD

**Issue by viral32111** [premake/premake-core#1465]
**What's your question?**

Is there a way I can call a default premake action such as `vs2019` and `gmake` from within my own custom [`newaction`](https://github.com/premake/premake-core/wiki/newaction)'s function?

I would like to make an action called `generate` which will generate project files for both `vs2019` and `gmake` at once.

An example of what I'd like to do:

```lua
newaction {
    trigger = "generate",
    description = "Generate the project files for every platform.",
    execute = function()
        generateProjectFor( "vs2019" ) -- Example for VS 2019
        generateProjectFor( "gmake" ) -- Example for GMake
    end
}
```

**Comment by samsinsane** [comment]
This isn't possible directly as Premake wasn't designed to run multiple actions in a single run.

You can probably do something like `os.execute(_PREMAKE_COMMAND .. " vs2019")`.

**Comment by viral32111** [comment]
> This isn't possible directly as Premake wasn't designed to run multiple actions in a single run.

Fair enough.

> You can probably do something like `os.execute(_PREMAKE_COMMAND .. " vs2019")`.

Thanks, I'll see if I can use this instead :)
