### ISSUE TITLE
Can't get project variable already set

### ISSUE THREAD

**Issue by L4ZZA** [premake/premake-core#1471]
**What seems to be the problem?**
I've been trying to copy some folders from their location to the project target directory like so:
```
project "level_editor"
    postbuildcommands
    {
        "{COPY} assets/**.* %{prj.target}"
    }
```
the variable though, doesn't seem to be accessible and there is no nice way yo do so..

**What did you expect to happen?**
I would expect that all the prj variables as well as the cfg ones to be retrievable not just modifiable.

**What have you tried so far?**
I've tried to use post build commands 

**How can we reproduce this?**
```

-- workspace is the solution
workspace "pyro"
    architecture "x64"
    startproject "level_editor"

    configurations
    {
        "Debug",
        "Release", -- more like a faster debug
        "Dist" -- distribution build
    }

-- example: debug-win-x64
outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"
target_dir = "bin/" .. outputdir .. "/%{prj.name}"


-- level_editor application
project "level_editor"
    location "level_editor"
    kind "ConsoleApp"
    language "C++"
    cppdialect "C++17"
    staticruntime "on"

    targetdir (target_dir)
    objdir ("inter/" .. outputdir .. "/%{prj.name}")

    files
    {
        "%{prj.name}/src/**.h",
        "%{prj.name}/src/**.cpp"
    }

    postbuildcommands
    {
        "{COPY} assets/**.* ../%{prj.targetdir}"
    }
```

this is the error output:
```
Error: [string "return cfg.buildcfg"]:1: attempt to index a nil value (global 'cfg') in token: cfg.buildcfg in token: prj.targetdir
```

Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) we can use to replicate the problem in our own development environments. Use [code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to format code and console output nicely.

**What version of Premake are you using?**
`premake5 (Premake Build Script Generator) 5.0.0-alpha14`

**Comment by starkos** [comment]
That's a fair attempt, but `targetdir` gets parsed out into a number of different fields before the project is generated. You probably want either `cfg,buildtarget.directory`, or you can also reference the global you defined in script `%{target_dir}`.

Partial list of available tokens is [here](https://github.com/premake/premake-core/wiki/Tokens).

Marking as closed, but feel free to continue the conversation if you still have questions.
