### ISSUE TITLE
Is it possible to configure the way premake will call the compiler command with custom commands?

### ISSUE THREAD

**Issue by Makogan** [premake/premake-core#1475]
I am interested in ccache to speed up my compilation times.

According to the documentation: https://linux.die.net/man/1/ccache 

All that's needed is to prepend the string `ccache`   before the `g++` calls.

The documentation says you can also symlink it so that's the fallback, but it'd be a little bit more convenient if you could just set it up with premake.

Thanks in advance.

**Comment by starkos** [comment]
Untested, but if you're using the `gmake` action, you could override `premake.make.cpp.buildcommand()` and modify the command line however you liked:

```lua
premake.override(premake.make.cpp, 'buildcommand', function(base, prj, objext, node)
    local cmd = base(pro, object, node)
    -- modify the cmd line here
end
```

You can see the implementation of `buildcommand()` [here](https://github.com/premake/premake-core/blob/master/modules/gmake/gmake_cpp.lua#L181-L188).

If you're using gmake2…best bet would probably be to override [premake.modules.gmake2.cpp.outputFileRules()](https://github.com/premake/premake-core/blob/master/modules/gmake2/gmake2_cpp.lua#L776-L805) is a similar way, but you've have more cases to deal with.

Does that help?

**Comment by starkos** [comment]
Marking this as closed by inactivity. Feel free to reopen if you have more questions.

**Comment by Axilot** [comment]
Will there be implemented something like a flag to enable ccache?

**Comment by starkos** [comment]
If someone implements one, then yes.

**Comment by dstromberg** [comment]
I'm interested in this too.
