### ISSUE TITLE
targetsuffix as token

### ISSUE THREAD

**Issue by greenkalx** [premake/premake-core#1476]
**What's your question?**
I'd like to use targetsuffix from the workspace level to define links at the project level.

At my workspace level I have:
```
filter { "configurations:Debug" }
	targetname		"$(ProjectName)"
	targetsuffix	"_d"
filter { "configurations:Release" }
	targetname		"$(ProjectName)"
	targetsuffix	""
filter { "configurations:ReleaseSymbol" }
	targetname		"$(ProjectName)"
	targetsuffix	"_s"
filter {} -- language, configurations
```

This successfully puts the project name with suffix into the project files.

I'd like to use targetsuffix to reference other projects in the workspace.
Currently I do like this:
```
filter { "configurations:Debug" }
	links
	{
		"1stLibrary_d.lib",
		"2ndLibrary_d.lib",
	}
filter { "configurations:Release" }
	links
	{
		"1stLibrary.lib",
		"2ndLibrary.lib",
	}
filter { "configurations:ReleaseSymbol" }
	links
	{
		"1stLibrary_s.lib",
		"2ndLibrary_s.lib",
	}
filter {} -- configurations
```

But I'd like to do like this:
```
links
{
	"1stLibrary%{prj.targetsuffix}.lib",
	"2ndLibrary%{prj.targetsuffix}.lib",
}
```

But this always outputs an empty string for the suffix.

**Anything else we should know?**
Generating for Visual Studio.

Is this just a token that hasn't been implemented yet?
https://github.com/premake/premake-core/wiki/Tokens

**Comment by samsinsane** [comment]
`cfg.buildtarget.suffix` is probably what you're looking for? Also, if the projects are already in your workspace, you can just link them as `links { "1stLibrary", "2ndLibrary" }`, Premake will figure out how to link them for you.

**Comment by greenkalx** [comment]
Great, `cfg.buildtarget.suffix` is working.

There is a difference in linking in Visual Studio when linking as a Reference and as an Additional Dependency (.lib).
Reference:
```
links
{
	"1stLibrary",
	"2ndLibrary",
}
```
Additional Dependency:
```
links
{
	"1stLibrary_d.lib",
	"2ndLibrary_d.lib",
}
```

If the reference depth is more than one to the current project,
and a reference is included from more than one reference on the current project,
then the linker can fail on duplicate symbols.

Instead, if they are linked as Additional Dependencies ".lib", there are no duplicate symbols. In this case, the lib must also be added to 'dependson', so it is compiled before.

I'll likely end up changing them all to ".lib" for consistency.

**Comment by samsinsane** [comment]
Sounds like this is all sorted, I'll close this off. If you're still having issues please feel free to reopen.
