### ISSUE TITLE
Support a popular IDE on Linux

### ISSUE THREAD

**Issue by Enhex** [premake/premake-core#1480]
**What problem will this solve?**
Currently the only IDE generator available for linux is CodeLite, but it's not widely adopted.

According to: https://isocpp.org/files/papers/CppDevSurvey-2019-04-summary.pdf
- Linux is the most popular platform (Question 7 / page 8)
- The most popular IDEs that work on Linux are VSCode(38.22%), Qt Creator(23.46%), and CLion(18.50%) (Question 14 / page 18)
- CodeLite only got 0.61% users in the survey.

**What might be a solution?**
Officially support a widely used IDE for Linux users.
I made [CMake generator](https://github.com/Enhex/premake-cmake) for CLion, and started working on a generator for VScode.

**What other alternatives have you already considered?**
There are some outdated community generators for Linux IDEs, but these IDEs aren't that good.

**Anything else we should know?**
Adding such official support can help Premake gain lots of users.

**Comment by tritao** [comment]
@Enhex Can you give more details about generator for VS Code?

I have done some work on builtin support for generating `compile_commands.json`, with the intent to support generation for VS Code eventually (and use `clangd` as a VS Code plugin).

Would you be interested in that for your generator? It's mostly working, I have just been stuck on getting the tests to work but can push it if you think it would be interesting.

**Comment by fhoenig** [comment]
+1 to a good integrated solution with VSCode. 

XCode is very very uncomfortable especially coming from real Visual Studio on Windows.

**Comment by fhoenig** [comment]
Codelite seems to be broken. It won't generate includedir and sysinclude dir. Just "."

**Comment by Cannedfood** [comment]
VS Code support should probably be a VS Code extension.

**Comment by starkos** [comment]
I'm not sure exactly what is being requested here, but I am certain that it is too broad and open ended. If you're asking for Premake to support CMake in core, that [was discussed over here](https://github.com/premake/premake-core/issues/1434). If you're requesting that Premake support more toolsets, well yeah that would be great, we all want that. But the two of us are already doing what we can, and we need more people to contribute to make that happen. If you aren't able to contribute code, you can help triage and test new bug reports and PRs, improve the documentation, or [become a financial backer](https://opencollective.com/premake) to enable me to spend more time on Premake.

Closing as "too broad", but feel free to continue the conversation, I'll be notified of any comments.

**Comment by Enhex** [comment]
@Cannedfood @tritao one approach is to generate the `.vscode` folder's project config files + workspace file.

One of the problems is that vscode requires you to supply the build command.
in their tutorial the use gcc directly which works ok for that simple example, but once you want to create libraries and such it's better to just use make/ninja. In which case we'd want to use Premake's make generator and generate vscode command to call make instead of gcc directly.

This approach requires 2 Premake generators (gmake & vscode), so premake needs to be called twice.
It can either be done manually by the user, or automatically from the vscode generator, forwarding all the options (don't know how to do it).
Or maybe the vscode generator can directly call the gmake generator functions so there won't be need to forward options (since the configuration state is already available).

**Comment by tritao** [comment]
@Enhex That seems like a nice approach for building.

But for getting code completion and Intellisense inside VS Code there exists 2 options: 

- https://github.com/Microsoft/vscode-cpptools
- https://github.com/clangd/vscode-clangd

And both of then rely on a `compilation_commands.json` file to get all the necessary compilation information.

Details about this file: https://clang.llvm.org/docs/JSONCompilationDatabase.html

I already did some work on on getting this file generated via Premake (and it's not VS Code specific).
An eventual VS Code generator for Premake would also generate this, and setup the path to it when generating `.vscode`.

**Comment by Enhex** [comment]
Initial work on a vscode generator:
https://github.com/Enhex/premake-vscode

@tritao one of the problems is that vscode only searches inside the project folder for source files. possible solutions are:
- symbolic links to source files (kinda bad because might require admin privileges to run)
- add source folders as another workspace folder (doesn't work for individual source files)
- a vscode extension (any idea if that could work?)

**Comment by tritao** [comment]
Nice work, I've been taking a look at it and looks like a very good start.

I will push my stuff so you can take a look and maybe integrate it on your extension.

About the problem you mention, I would just generate the `.vscode` folder and workspace at the root level of the project tree, while keeping the rest of the generated build folders (`gmake`) at the usual locations.

That should work, right? Seems like the simpler solution.

About a Premake VS Code extension, it could be quite nice, these are the features that I think would be most useful:

- Premake project explorer

This would contribute a `Project Explorer` view to the file explorer, this giving a logical/virtual view of the project tree, respecting the `vpaths` setup in Premake by the user.

Visually it would work like [VS Code Solution Explorer extension](https://marketplace.visualstudio.com/items?itemName=fernandoescolar.vscode-solution-explorer).

![](https://github.com/fernandoescolar/vscode-solution-explorer/raw/master/images/vscode-solution-explorer-2.gif)

I guess this could be used to workaround that file referencing issue you discussed, but feels a bit like an hack, I would prefer if it worked fine by default with the regular Explorer as well.

- Status bar buttons for switching configurations, generators, and building / launch / debug target.

The idea here being that we can quite easily switch between Debug / Release / others configurations, even maybe between Make / Ninja generators and between toolsets.

![](https://code.visualstudio.com/assets/docs/cpp/cpp/cmake-build.png)

- Setup a file watch on Premake Lua files

So the idea is that the extension is keeping track of any changes to the Premake build files, and would automatically issue generation of updated build files on file saves. 

Let me know if you have any feedback on those ideas.

I can help set something up as I have some previous experience with VS Code extensions.

**Comment by tritao** [comment]
Here is the compilation database generator as discussed: https://github.com/tritao/premake-core/commit/64113fcb7657d3d2714221fe619d7b462d66d380

**Comment by Enhex** [comment]
I updated the vscode generator to create symlinks, and it seems to work fine (only tested on Linux).

**Comment by tritao** [comment]
Cool, I will give it a try over the weekend.

**Comment by starkos** [comment]
Just a thought, untested…what if…

1. In `gmake2/_preload.lua`, move the `onWorkspace`, `onProject` logic out into functions so you can override it
2. In your `vscode` module, look to see if `_ACTION` is `'vscode'` and, if so, replace`_ACTION` with `'gmake2'` and then override those generation functions with your own
3. In your overrides, call the original functions to generate the makefiles, and then create the VS Code artifacts

That would let you generate in a single step. The downside is configuration like this wouldn't work because you would have already changed `_ACTION` to `gmake2`:

```lua
filter { 'action:vscode' }
   -- do something
```

…but don't know if that would ever be needed?

Hoping to have a better solution for this kind of thing in the not too awfully distant future.

**Comment by Enhex** [comment]
Perhaps adding functionality for grouping generators will be a good idea.
Ideally I'd prefer to use Ninja over Make, in my current project Make can take 3-6 seconds for "do nothing" builds.
From the VSCode generator's perspective it only need to change the build command based on which build generator is used with it.

**Comment by starkos** [comment]
> Perhaps adding functionality for grouping generators will be a good idea.

It's been looked into (search for "action chaining"). The problem with doing it on the current configuration engine is that you have to run the baking process once for each action, which is a really significant performance hit on larger projects. I'm aware of and working on this problem, but it comes along slowly.
