### ISSUE TITLE
Help with premake and hlsl to NOT set it to fxcompile

### ISSUE THREAD

**Issue by MapleDropBear** [premake/premake-core#1490]
**What are you trying to do?**
In a pre vs2019 version of premake5 we used the premake feature to add out shaders to our vcproject for reference (we compile them elsewhere in the tools) With the current version it sets them to FXcompile so now it tries to compile them, I would like to add them to a project but as reference files with the compilation option None. 

**What problem are you having?**
so the output it giving us now 
` <FxCompile Include="..\..\..\game\share\raw\shaders\analoguvcolordistortion.hlsl" />`
we would like 
`  <None Include="..\..\..\game\share\raw\shaders\analoguvcolordistortion.hlsl" />`

**What have you tried so far?**
I have looked through the code but I couldn't easily build a custom version which hacks the fxcompile into None. But I was hoping there is a config option to turn this off? I tried running the project with 	buildaction "None" but it didn't make a difference

**What version of Premake are you using?**
premake-core-5.0.0-alpha15

**Anything else we should know?**
```
Premake lua script is

 project "shaders"
    uuid "0F45D591-7B24-542D-843C-DF03F09ABA8E"
    files
    {
        "../../../game/share/raw/shaders/**.hlsl",
        "../../../game/share/raw/shaders/**.h",
    }
```

**Comment by samsinsane** [comment]
I had this issue with a work project, we ended up with:
```lua
filter { "files:**.hlsl" }
  flags { "ExcludeFromBuild" }
```

**Comment by redorav** [comment]
The way I fixed it which I think is more premake-y is

```
filter { "files:**.hlsl" }
	buildaction("none")
```

**Comment by MapleDropBear** [comment]
> The way I fixed it which I think is more premake-y is
> 
> ```lua
> filter { "files:**.hlsl" }
> 	buildaction("none")
> ```

Thank you! That did the trick! I missed the filter part out I had buildaction already set but needed to set a filter for it to work! Thanks for the assist.

**Comment by samsinsane** [comment]
Closing as resolved.
