### ISSUE TITLE
Dependencies order between links and linkoptions

### ISSUE THREAD

**Issue by Jarod42** [premake/premake-core#1492]
**What are you trying to do?**

Using `linkoptions` (`llvm-config --lib`) **after** regular libs with `links` (`clang`) on Codelite. (seems to also happen with gmake)

```
links { "clang"}
linkoptions { "$(shell llvm-config --libs)" }
```

**What problem are you having?**

generator puts `linkoptions` before `links` (even if in script order is correct), so dependencies is broken for g++

**What version of Premake are you using?**
> premake5 (Premake Build Script Generator) 5.0.0-alpha15

**Anything else we should know?**

As I understand, there are 2 different tables without order relationship.
Whereas putting linksoptions after links would solve my issue (seems that premake4 did that),
I suppose than that change might break other configurations.

**Comment by Jarod42** [comment]
According to gmake(2), it seems related to:
```
-- this was $(TARGET) $(LDFLAGS) $(OBJECTS)
--   but had trouble linking to certain static libs; $(OBJECTS) moved up
-- $(LDFLAGS) moved to end (http://sourceforge.net/p/premake/patches/107/)
-- $(LIBS) moved to end (http://sourceforge.net/p/premake/bugs/279/)
```

(even if I don't have access to the links :-/)

**Comment by samsinsane** [comment]
I'm not inclined to change this back without knowing why it was changed in the first place. However, there are a number of things you can try:
- Execute `llvm-config` from Premake using [`os.outputof`](https://github.com/premake/premake-core/wiki/os.outputof), split the string and add the items to `links` - probably want to use `--libnames` instead of `--libs`.
- Put `"-lclang"` as the first item of `linkoptions`
- Use `premake.override` to change the order
- You might be able to just use `links { "clang $(shell llvm-config --libs)" }`, I think Premake might be a bit "dumb" here, but I wouldn't rely on this behaviour.

I strongly recommend the first one, it is what `links` is for after all.

**Comment by Jarod42** [comment]
Revert back might be indeed problematic for reverse cases (I don't see practical cases, but comment seems to suggest they are).
I think the "correct" fix would be that premake keeps relative order from script (and so probably uses one unique table instead of two, but requires some works to have correct transformation later :/)

so, for
```
links "A"
linkoptions "`B-config --lib`"
links "C"
```
we really have ```-lA `B-config --lib` -lC``` and not ``` `B-config --lib` -lA -lC``` (as now) nor ```-lA -lC `B-config --lib``` (as previously)

- I prefer to use `llvm-config` on generated "target" instead of on premake. In addition output might have flags which are not just libraries.
- I think I will choose this one (get rid of `links`) as workaround for now, even if hackish. Hope that I won't have project link issue.
- [premake.override](https://github.com/premake/premake-core/wiki/premake.override) seems undocumented. I have to read source directly to know what it does and how it fits my needs.
- Even more hackish as second option

[linkoptions](https://github.com/premake/premake-core/wiki/linkoptions)'s example seems to suggest that `xxx-config` might be used there and not just linker flags unsupported natively by premake.

**Comment by samsinsane** [comment]
I'm going to close this off as resolved as there's no real possible fix here. Keeping the order from the scripts would be a complete rewrite.

**Comment by Jarod42** [comment]
ok, ty.

**Comment by starkos** [comment]
I don't want to flip the order of `linkoptions` vs. `links` — there was a lot of discussion on that back in the BitBucket days which sadly didn't capture. But we _could_ introduce something like `linkoptionsafter()` to explicitly add flags at the end of the command line?
