### ISSUE TITLE
Unclear instructions for creating installation command/action

### ISSUE THREAD

**Issue by TheShoutingParrot** [premake/premake-core#1493]
The documentation doesn't really show how to make a semi-"universal" installation action/command with premake. I tried asking around and many people who (at least sometimes) use premake didn't know how to answer this question.

There should probably be some kind of tutorial on this on the wiki.

**Comment by samsinsane** [comment]
I'm not sure I really follow what you're trying to do - are you wanting to replicate `make install` but using Premake instead? Have you read through [this](https://github.com/premake/premake-core/wiki/Adding-a-new-Action) it covers creating a new action, and from what I can see would get you most of the way to doing what you want.

**Comment by TheShoutingParrot** [comment]
Yeah thanks for that @samsinsane though it would be nice if there would be a clear example for creating a `make install` like command/action. Making it system agnostic must be the hard part.

**Comment by samsinsane** [comment]
I'm not sure how useful that example would be, the difference between it and the existing example would kind of just boils down to:
```lua
if os.host() == "windows" then
  -- Do Windows install
elseif os.host() == "linux" then
  -- Do Linux install
elseif os.host() == "macosx" then
  -- Do macOS install
else
  -- Do something
end
```

**Comment by TheShoutingParrot** [comment]
OK thx!
