### ISSUE TITLE
How to use clang-cl toolset?

### ISSUE THREAD

**Issue by TrianglesPCT** [premake/premake-core#1494]
In VS2019 there are two toolsets, 

VS2019(v142)
LLVM(clang-cl)

I am trying to have a config that targets clang-cl, but it doesn't seem like this is working

I tried various things like:

	toolset("msc-llvm-clang-cl")
	toolset("msc-llvm")
	toolset("msc-llvm-vs2019")

But they just inserted  new toolset that said it wasn't installed.

 Also tried 

toolset("clang") but this didn't seem to do anything

The toolset docs here: https://github.com/premake/premake-core/wiki/toolset

Mention a toolset "msc-llvm-vs2014", so I think perhaps clang-cl is supported somehow?

**Comment by samsinsane** [comment]
According to the code it's `toolset "clang"` that does it:
https://github.com/premake/premake-core/blob/591194dfcfb5cb5325945ddf2d938fbaeb2799d9/modules/vstudio/vs2010_vcxproj.lua#L2335-L2356

It was merged in about 2 months ago with #1462, are you using a build that includes this commit? It's not in the last official release, alpha 15, so you'll need to build master yourself.

**Comment by TrianglesPCT** [comment]
thank you @samsinsane, I did not have a that commit, I will try building master

**Comment by samsinsane** [comment]
No worries, I'll leave the issue open until you can confirm that it all works as you expect.

**Comment by TrianglesPCT** [comment]
Thanks @samsinsane 

I downloaded master, and after some confusion trying the run the command mentioned in the BUILD.txt(it said to run
"nmake -f Bootstrap.mak windows", but this didn't work as my system apparently can't find nmake), I noticed the Bootstrap.bat, and ran it, which generated a exe.  

Tested it with toolset "clang" and it does work! Nice

**Comment by TrianglesPCT** [comment]
After using this some I think there might actually be an issue with the way the cppdialect works when clang-cl is used--

When I manually configure the project that was generated to be C++ latest(General section under properties), it works, and seems fine

When I use premake to set cppdialect, it appears to work in that it shows up on the general tab, but when I attempt to compile I get errors from clang-cl, about not understanding the /std:latest flag(same thing with /std:c++17 and /std::c++14)

I will check this out more and try and figure out what is going on

**Comment by TrianglesPCT** [comment]
After diffing the resulting files the only difference that stands out is that when I set c++latest from the IDE it toggles 
WindowsTargetPlatformVersion to 10.

When I use premake it does not..

**Comment by TrianglesPCT** [comment]
Ok after more investigating the only line I can find that is differetn between what premake generates, and what VS does when I toggle c++:latest in the IDE is this

 <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
