### ISSUE TITLE
clang-cl does not work correctly with cppdialect(or manually passing /std:c++17 etc), requires that WindowsTargetPlatformVersion be set to 10.0

### ISSUE THREAD

**Issue by TrianglesPCT** [premake/premake-core#1496]
It seems that clang-cl requires this be set in order to change the cppdialect

`<WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>`

If I adjust cppdialect in VS2019 it automatically adds this and sets it to 10, but premake is not doing so, so when 
attempting to use anything besides the default dialect, it spits outs errors about not understanding what /std:c++17 or /std::c++14 or /std:latest mean.

I'll see if I can figure out how to patch premake for this

**Comment by samsinsane** [comment]
You can set that with `systemversion "10.0"` I think?

**Comment by TrianglesPCT** [comment]
I don't know why, but when I do that, it does show as 10.0 in the IDE...but

When I look at the .vxcproj it does not have the line..

<WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>

.. and I still get the compilation error.

Manually inserting the line into the .vxcproj fixes it

This is really confusing, and I am also very uncertain as to why clang cares about this value at all..

I haven't been able to find an exact definition for what WindowsTargetPlatformVersion does, but its name implies this restricts the binary to windows 10. I don't know why clang would require this, and it isn't something I want :/

**Comment by TrianglesPCT** [comment]
Ok this not a premake bug I think, but something wrong with VS or clang-cl, I've given up trying to figure out why it emits this error, and decided to turn it off with -Wno-unused-command-line-argument

**Comment by samsinsane** [comment]
As far as I'm aware, it restricts the Windows SDK version you build with - if you're not calling Windows 10 APIs it should be fine right? I would imagine the Windows SDK had to be modified to not use Microsoft extensions and what not, which is why using Clang would require Windows 10.
