### ISSUE TITLE
How to set the Item Type for extensionless files? C/C++ header/compiler

### ISSUE THREAD

**Issue by nealhow** [premake/premake-core#1498]
C++ standard header files are provided without the arbitrary .h extension. In a very specific scenario, I would like to find a way to recursively set the Item Type value to what it’s intended. By default this is set to “does not participate in build” which then make MSVC ignore the files. The correct value would be C/C++ header for include files and C/C++ compiler for source files. Is it somehow possible ?

**Comment by starkos** [comment]
Untested, but can you do…?

```lua
filter 'files:include/*'
   buildaction 'Compile'
```

**Comment by nealhow** [comment]
> ```lua
> filter 'files:include/*'
>    buildaction 'Compile'
> ```

Apparently not, the filter and the build action won't change anything

**Comment by samsinsane** [comment]
Based on this:
https://github.com/premake/premake-core/blob/591194dfcfb5cb5325945ddf2d938fbaeb2799d9/modules/vstudio/vs2010_vcxproj.lua#L1097-L1099

It looks like it should be `buildaction 'ClInclude'` (if you want them treated as a header file):
https://github.com/premake/premake-core/blob/591194dfcfb5cb5325945ddf2d938fbaeb2799d9/modules/vstudio/vs2010_vcxproj.lua#L764-L776

**Comment by nealhow** [comment]
Spot-on @samsinsane! That is exactly what I was looking for. The wiki is quite misleading and perhaps a stronger separation between C# action build and C++ action build would be a lovely addition @starkos? Either way, I’m closing this issue. Thanks everyone

**Comment by samsinsane** [comment]
> The wiki is quite misleading and perhaps a stronger separation between C# action build and C++ action build would be a lovely addition

Are you talking about [this](https://github.com/premake/premake-core/wiki/buildaction) wiki entry? Which bit is misleading?

**Comment by nealhow** [comment]
> > The wiki is quite misleading and perhaps a stronger separation between C# action build and C++ action build would be a lovely addition
> 
> Are you talking about [this](https://github.com/premake/premake-core/wiki/buildaction) wiki entry? Which bit is misleading?

For those of us that would rather quickly skim the documentation, the C# build action table is the first thing to be read. This led to confusion as reflected by Starkos answer of which he provided a C# build action for my C++ question. I believe that putting the C++ MSBuild action forward (more visible) would alleviate this confusion. Below is a provided example of what's scanned first:

![Capture](https://user-images.githubusercontent.com/69689365/90524147-b6896880-e13b-11ea-8bcc-5564fec9fa04.PNG)

**Comment by samsinsane** [comment]
Thanks for the feedback on the documentation.
