### ISSUE TITLE
communication with community

### ISSUE THREAD

**Issue by continue98** [premake/premake-core#1504]
**What's your question?**
Maybe you should create chats to communicate with the community? gitter / slack / discord / telegram

**Anything else we should know?**
-

**Comment by RicoP** [comment]
Just want to add that I would appreciate a official Discord. The Maintainer of the repo can dedicate people from the community to serve as moderators. I also see the trend that more and more OS projects use discord as a communication platform and it would maybe help to minimize the amount of redundant issues when people have a single spot to ask questions. 

Alternatively https://gitter.im/premake/premake-core would be an option that would be relatively maintenance free.
