### ISSUE TITLE
Unable to link GLFW on Linux but Windows works

### ISSUE THREAD

**Issue by croaglife** [premake/premake-core#1510]
Hello guys, thanks for this tool. Unfortunately I'm having trouble linking GLFW to my project on Ubuntu Linux, yet on Windows it links perfectly.

Off the bat, this is the linker error I'm getting:
```
undefined reference to `glfwInit'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:81: ../builds/Debug-x86_64/game/game] Error 1
make: *** [Makefile:47: game] Error 2
```
This only happens when I include my game project. If I remove it from the premake lua file, it compiles the engine lib project perfectly. My project structure is very simple too:

```
- project_folder
  - engine (static lib) glfw is in a folder with this one called vendor
  - game  (executable)
```
I have one master premake5.lua file in the root directory and of course another one in the glfw git submodule.

I'm running:
**1)** premak5 gmake
**2)** make (his is where I get the compiler error)

Again this same project works beautifully on Windows. Not sure what I'm missing. Sorry about posting here, just don't know where else to ask :( Btw I also made sure to:

apt-get install build-essential
apt-get install libx111-dev
apt-get install xorg-dev 

I'll provide the master premake5.lua file below and the glfw file. Thank you very much!

**### premake5.lua file in root**
```
workspace "Engine"
	architecture "x64"
	startproject "App"

	configurations { "Debug", "Release"}
	flags { "MultiProcessorCompile" }

outputdir = "%{cfg.buildcfg}-%{cfg.architecture}"

-- Include Directories
IncludeDir = {}
IncludeDir["glfw"] = "engine/vendor/glfw/include"

group "Dependencies"
	include "engine/vendor/glfw"
group ""

-- Engine
project "engine"
	location 		"engine"
	kind 			"StaticLib"
	language 		"C++"
	cppdialect 		"C++17"
	staticruntime 	"on"

	targetdir 	("builds/" .. outputdir .. "/%{prj.name}")
	objdir 		("builds/temp/" .. outputdir .. "/%{prj.name}")

	pchheader "enginepch.h"
	pchsource "engine/src/enginepch.cpp"

	files {
		"%{prj.name}/src/**.h",
		"%{prj.name}/src/**.cpp",
	}

	includedirs {
		"%{prj.name}/src",
		"%{IncludeDir.glfw}",
	}

	links  { 
		"GLFW"
	}

	defines {
		"_CRT_SECURE_NO_WARNINGS",
		"GLFW_INCLUDE_NONE"
	}

	filter "system:linux"
		systemversion "latest"
	links { 
		"Xrandr",
		"Xi",
		"GL",
		"X11",
		"GLFW"
	}

	filter "system:windows"
		systemversion "latest"


	filter "configurations:Debug"
		defines "ENGINE_DEBUG"
		runtime "Debug"
		symbols "on"

	filter "configurations:Release"
		defines "ENGINE_RELEASE"
		runtime "Release"
		optimize "on"


-- Game
project 			"game"
	location 		"game"
	kind 			"ConsoleApp"
	language 		"C++"
	cppdialect 		"C++17"
	staticruntime 	"on"

	targetdir 	("builds/" .. outputdir .. "/%{prj.name}")
	objdir 		("builds/temp/" .. outputdir .. "/%{prj.name}")

	files {
		"%{prj.name}/src/**.h",
		"%{prj.name}/src/**.cpp"
	}

	includedirs  {
		"src/",
		"engine/src",
		"%{IncludeDir.glfw}",
	}

	links {
		"GLFW",
		"engine"
	}

	filter "system:linux"
	systemversion "latest"
	links { 
		"Xrandr",
		"Xi",
		"GL",
		"X11"
	}

	filter "system:windows"
		systemversion "latest"
		
	filter "configurations:Debug"
		defines "GAME_DEBUG"
		runtime "Debug"
		symbols "on"

	filter "configurations:Release"
		defines "GAME_RELEASE"
		runtime "Release"
		optimize "on"

```

The glfw submodule I got from The Cherno's repo [here](https://github.com/TheCherno/glfw/blob/master/premake5.lua).

**Comment by samsinsane** [comment]
At first I was going to say it's because you're linking GLFW from a static lib, which only works in VS. However, it looks like you've got GLFW linking in the game too, it's possible that it's a linking order issue, try using `linkgroups "On"` or swap GLFW and engine in the `links` call.

**Comment by nickclark2016** [comment]
Just poking to follow up on this. I have a C++ project where I include GLFW in a "core" static library, then I also link it in the "application" console app.  I link against the "core" project first, then GLFW.  Definitely recommend setting `linkgroups "On"` though.

**Comment by croaglife** [comment]
> `linkgroups "On"`

Hello Nick! Thanks for following up to this. You know, I was unable to get it working :( I'm definitely doing something wrong. I switched GLFW so it's after the engine link, and now the error changed. 

```
/usr/bin/ld: ../engine/vendor/glfw/bin/Debug-x86_64/GLFW/libGLFW.a(osmesa_context.o): in function `_glfwTerminateOSMesa':
/home/superposition/dev/superpositionquestion/engine/vendor/glfw/src/osmesa_context.c:186: undefined reference to `dlclose'
```
I've pasted my LUA file just in case you don't mind taking a quick look at it. For Windows this project works perfectly. Linux is my issue.

This is the lua file
https://gist.github.com/croaglife/24e7e05a50c9d7fcea4e1c8a2470e0cf

**Comment by nickclark2016** [comment]
I actually expected that.  Add either `dl` to the links or `-ldl` to the linkoptions of application.  That's what should give you access to `dlclose`.

**Comment by croaglife** [comment]
> I actually expected that. Add either `dl` to the links or `-ldl` to the linkoptions of application. That's what should give you access to `dlclose`.

My man! It worked! Thank you very much. I'm getting glfwInit() == 1 now!

Do I mark as solved or do you guys usually do it? Thanks again!
