### ISSUE TITLE
How can I set cppdialect to C++20?

### ISSUE THREAD

**Issue by devlexanderxyz** [premake/premake-core#1512]
**What's your question?**
How can I set my cppdialect to C++20? C++17 works but not 20, I also seen that someone made a PR adding this to premake, but it doesn't seem to be working.

**Anything else we should know?**
Nothing.

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to questions like these!)*

**Comment by Cannedfood** [comment]
It seems like the commit didn't make it into current alpha release (alpha 15), maybe you are using that version?
You can try compiling it from source, it should be pretty straight forward.

**Comment by devlexanderxyz** [comment]
Yeah. Seems so. I might give compiling from source a go then. Cheers bud!

**Comment by samsinsane** [comment]
I'm going to close this off as the question has been answered. You can also try grabbing the latest build from the Actions tab, just find the latest master build and you will see a list of artifacts. If you're still having issues please feel free to reopen.
