### ISSUE TITLE
Including shared libraries in multiple modules is not working

### ISSUE THREAD

**Issue by Makogan** [premake/premake-core#1513]
I have a system where a shared library is created and then multiple executables link to that library. The main library is a rendering engine, the smaller executables are demos.

The way I was doing things is, I had a master `.lua` file and then each group (i.e. the demos or the library) hat its own module `.lua` definition, so as to create one executable per group.

Before I was manually including the shared libraries in each file. That is to say, each `.lua` file had a copy pasted list of all teh directories that needed to be included. Which is a bad way to do thins.

I am trying to put all the includes in the `premake5.lua` master file, but it is not working. For example, it's not including `Eigen` correctly. I have tried using relative paths, absolute paths and calling the system directly but nothing seems to work.

My directory structure is:

`./premake5.lua`
`./libraries/`
`./Src/Engine/Engine.lua`
`./Src/Examples/Example1.lua`

And so on for each submodule. I want to define the following function only once in the entire program:
```
function IncludeLibraries(prefix)
    print(prefix .. "Src/Engine/")
    includedirs {prefix .. "Src/Engine/"}
    includedirs {prefix .. "libraries/Eigen/"}
    includedirs {prefix .. "libraries/stb/"}
    includedirs {prefix .. "libraries/glm/"}
    includedirs {prefix .. "libraries/backward-cpp/"}
    includedirs {prefix .. "libraries/benchmark/include/"}
    includedirs {prefix .. "libraries/magic_get/include/"}
    includedirs {prefix .. "libraries/VulkanMemoryAllocator/src/"}
    includedirs {prefix .. "libraries/shaderc/libshaderc/include/"}
    includedirs {prefix .. "libraries/googletest/googletest/include/"}
    includedirs {prefix .. "libraries/libigl/include/"}
    includedirs {prefix .. "libraries/vulkansdk-linux/1.2.135.0/source/Vulkan-Headers/include/"}
end
```

And call it once on each submdoule to avoid copy pasting it. But so far I have not been successful.

**Comment by samsinsane** [comment]
Closing as the template wasn't filled in - the templates are there to help. Furthermore, you probably want the "Get help" template, not the "Ask a question" template, given that you haven't asked a single question in this issue.
