### ISSUE TITLE
Headers include paths are written to "User Header Search Paths" instead of "Header Search Paths" in Xcode

### ISSUE THREAD

**Issue by cos-public** [premake/premake-core#1517]
**What seems to be the problem?**
`includedirs` property in premake project file writes include paths to `USER_HEADER_SEARCH_PATHS` property in `project.pbxproj` file instead of `HEADER_SEARCH_PATHS`. Which forces to use " " instead of < > in cpp files even for 3rd party libraries.

**What did you expect to happen?**
`includedirs` should create entries in `HEADER_SEARCH_PATHS` in `.pbxproj` file by default, in my opinion.

**What have you tried so far?**
Manually moving entries in Xcode IDE

**How can we reproduce this?**
Use `includedirs` and verify that directories are written to `USER_HEADER_SEARCH_PATHS` property

**What version of Premake are you using?**
`premake5 (Premake Build Script Generator) 5.0.0-alpha15`
`Xcode Version 11.7 (11E801a)`

**Comment by samsinsane** [comment]
Have you tried specifying your 3rd party libraries using `sysincludedirs` instead?

**Comment by cos-public** [comment]
Yes, thank you. Using `sysincludedirs` does work, and puts include paths into "Header Search Paths" in Xcode. But there is another entry in Xcode project - "System Header Include Paths" and it seems logical to me for `sysincludedirs` to put header paths there.

**Comment by noresources** [comment]
> Using `sysincludedirs` does work, and puts include paths into "Header Search Paths" in Xcode. But there is another entry in Xcode project - "System Header Include Paths" and it seems logical to me for `sysincludedirs` to put header paths there.

You are right,  SYSTEM_HEADER_SEARCH_PATHS is a new setting of Xcode 9+. Premake still use the old HEADER_SEARCH_PATHS setting. See also #1456
