### ISSUE TITLE
toolset "clang" changes the formatting of links from X.lib to -lX for vs2019

### ISSUE THREAD

**Issue by nothke** [premake/premake-core#1520]
**What seems to be the problem?**
As the title says, putting `toolset "clang"` changes the form of `LinkName.lib` to `-lLinkName`, resulting in linking errors. Tested only with VS 2019.

**What did you expect to happen?**
The links should have .lib suffix, as they do without `toolset "clang"`

**How can we reproduce this?**
Sample:

``` lua
workspace "premake-test"
   configurations { "Debug", "Release" }

project "premake-test"
	kind "ConsoleApp"
	language "C++"
	architecture "x64"
	cppdialect "C++17"
	toolset "clang" -- comment this line for correct links
	targetdir "bin/%{cfg.buildcfg}"
	defines{"WIN32", "_CONSOLE"}

	files { "src/**.h", "src/**.cpp" }

	postbuildcommands {
		"{COPY} deps/sdl/lib/x64/SDL2.dll %{cfg.targetdir}"
	}

	includedirs { "deps/include" }

	libdirs{ 
		"deps/sdl/lib/x64",
	}

	links{
		"SDL2", -- becomes SDL2.lib with no toolset, but -lSDL2 with toolset "clang"
		"SDL2main"
	}

	filter "configurations:Debug"
		defines{"_DEBUG"}
		symbols "On"

	filter "configurations:Release"
		defines {"NDEBUG"}
		optimize "On"
```

This premake produces this in .vcxproj:
``` xml
<AdditionalDependencies>-lSDL2;-lSDL2main;%(AdditionalDependencies)</AdditionalDependencies>
```

but without toolset line, it produces this, the correct form:
``` xml
<AdditionalDependencies>SDL2.lib;SDL2main.lib;%(AdditionalDependencies)</AdditionalDependencies>
```

**What version of Premake are you using?**
Latest dev, built today.

**Comment by samsinsane** [comment]
Thanks for the report! If you need a temporary workaround, you can override [this function](https://github.com/premake/premake-core/blob/15a07510ab689468c40d55215078e172e029de3b/modules/vstudio/vs2010_vcxproj.lua#L1394-L1410) using:
```lua
premake.override(premake.vstudio.vc2010, "additionalDependencies", function(oldfn, cfg, explicit)
  if cfg.system ~= premake.WINDOWS then
    oldfn(cfg, explicit)
  else
    local links = premake.vstudio.getLinks(cfg, explicit)
    if #links > 0 then
      links = path.translate(table.concat(links, ";"))
      premake.vstudio.vc2010.element("AdditionalDependencies", nil, "%s;%%(AdditionalDependencies)", links)
    end
  end
end)
```
I haven't tested this, so you may need make some modifications.

**Comment by nothke** [comment]
Thanks! I had to add `require("vstudio")` to the top, and now it works.

**Comment by nickclark2016** [comment]
@samsinsane Hey, I'll take a look at this and try to get out a fix, if no one has started work on this.

**Comment by nickclark2016** [comment]
This can be closed now.  This is merged into master.
