### ISSUE TITLE
Need support for Just My Code in VS2017

### ISSUE THREAD

**Issue by chrisant996** [premake/premake-core#1526]
**What problem will this solve?**
A project has some code that crashes unless `<SupportJustMyCode>false</SupportJustMyCode>` is added to the VS2017 project.  VS2017 15.8 and higher have JustMyCode debugging enabled by default, and I'm using VS2019.

The project uses a lambda to generate code that gets copied to virtual memory in another process in order to invoke `CreateRemoteThread`.  JustMyCode injects assembly code into the lambda to call functions outside the lambda itself, thus copying the lambda code to the other process results in crashing assembly code.  Repos are here: [mridgers/clink](https://github.com/mridgers/clink) and [chrisant996/clink](https://github.com/chrisant996/clink).

**What might be a solution?**
Add a config option for VS2017.

**What other alternatives have you already considered?**
After reading premake5 docs, doing internet searches, and reading source code in the premake repo, it looks like there is no realistic way to make premake emit the XML tag other than to modify the premake tool itself.  I also researched if there's a way to disable JustMyCode support via a `#pragma`, but there isn't.

I see four alternatives:
1. Ask project contributors to manually edit the vcxproj files after premake generates them.  That's not preferable because the project relies on premake to define a c++ macro with the head commit hash, and it uses the hash to identify whether it needs to copy an updated binary into place.  So the normal workflow has been to invoke premake after every git pull, and before every release or final build.
2. Create a script that post-processes the premake output.  That's not preferable because it requires multiple steps.
3. Learn how to improve premake itself.  That's not preferable because of the rampup cost.  It looks like [this SO post](https://stackoverflow.com/questions/39130550/injecting-properties-into-vs-projects-with-premake5/39151157#39151157) has rough high level directions for adding a certain kind of setting.  With some time and research, that could be a starting point for figuring out how to identify what kind of setting SupportJustMyCode is, where it should go, how to make it a no-op for other toolsets, etc.
4. Switch to a different toolset abstraction tool.  That's least preferable, because of existing build tooling that relies on premake.

Are there other options that I didn't notice?

I'm trying to revive these projects into working order, and I don't want to get sidetracked into making improvements in another project first.  So the best alternative for me right now is option 2, using a script to post-process the premake output.

**Anything else we should know?**
When a project needs to use a new VS option that premake doesn't natively support yet, there doesn't seem to be a low cost path forward for a consumer of premake.  One must become a contributor to premake, in order to become a consumer of premake.  That makes it difficult for a multi-author project to use premake in the meantime.  It could be beneficial to have some way to inject arbitrary XML tags into the premake output, so that premake consumers don't have to postpone their own project progress while waiting for premake to natively support new toolset features.

Thank you for reading this and considering the feedback!

**Comment by samsinsane** [comment]
Strange, we had another bug about this but it was re-closed just the other day. There's a workaround specified here #1233, I guess we'll leave this issue open to actually add support for it.

**Comment by chrisant996** [comment]
> There's a workaround specified here #1233

Thank you, that's very helpful.  I didn't think to remove the "is:open" clause to try searching for closed issues.

The workaround turns off SupportJustMyCode for all projects, but ideally it should be turned off for only one project.  It's a reasonable alternative for the moment, and preferable over using a script to post-process the generated project files.

**Comment by samsinsane** [comment]
There's a few ways you can turn it off for just one project, but the easiest is probably to use the following instead, replacing `MyProject` with your projects name:
```lua
premake.override(premake.vstudio.vc2010.elements, "clCompile", function(oldfn, cfg)
  local calls = oldfn(cfg)
  if cfg.project.name == "MyProject" then
    table.insert(calls, function(cfg)
      premake.vstudio.vc2010.element("SupportJustMyCode", nil, "false")
    end)
  end
  return calls
end)
```

**Comment by nickclark2016** [comment]
@samsinsane That's my bad on reclosing.  I was going through and closing issues I had open that I thought were dead across several repos.

**Comment by samsinsane** [comment]
No worries!

**Comment by chrisant996** [comment]
> There's a few ways you can turn it off for just one project, but the easiest is probably to use the following instead, replacing `MyProject` with your projects name:

Thank you very much, @samsinsane!

I generalized it for reuse:

```lua
require "vstudio"
local function add_tag(tag, value, project_name)
    premake.override(premake.vstudio.vc2010.elements, "clCompile",
    function(oldfn, cfg)
        local calls = oldfn(cfg)
        if project_name == nil or cfg.project.name == project_name then
            table.insert(calls, function(cfg)
                premake.vstudio.vc2010.element(tag, nil, value)
            end)
        end
        return calls
    end)
end

add_tag("SupportJustMyCode", "false", "clink_process")
```
