### ISSUE TITLE
 Vulkan HPP header macros cause: `ISO C++11 requires whitespace after the macro name`

### ISSUE THREAD

**Issue by Makogan** [premake/premake-core#1531]
**What seems to be the problem?**
Adding global defines through the premake `defines` directive, as opposed to defining the value in a header file started triggering the following error:

`<command-line>: warning: ISO C++11 requires whitespace after the macro name`

Platform is Linux:

**What did you expect to happen?**
No warning should be emitted when defining a command line macro.

**What have you tried so far?**
I tried manually adding whitespace in different forms, no success.

**How can we reproduce this?**
Take a vulkan project that uses the HPP headers and add:
`defines {"VULKAN_HPP_NO_EXCEPTIONS", "VULKAN_HPP_TYPESAFE_CONVERSION"}`
to the premake5.lua file.

**What version of Premake are you using?**
premake5 (Premake Build Script Generator) 5.0.0-alpha14

**Comment by Makogan** [comment]
Error disapeared after cleaning project and rebuilding. Might have been a corrupted build state. Apologies.

**Comment by starkos** [comment]
Glad you were able to get it sorted.
