### ISSUE TITLE
How can I statically link assimp to my project using Premake5? I'm so stuck :(

### ISSUE THREAD

**Issue by ItsCassieNova** [premake/premake-core#1533]
Hi! I'm learning how to use premake and it's very useful. However I'm stuck on one thing: how can I statically link Assimp to my project? All I want to do is load FBX files.  Admittedly I've copied code from The Cherno project and that's how I got GLFW and some other things to work. I want to be able to build an executable without needing to include assimp dlls.

I'll go ahead and share my main [premake file](https://gist.github.com/ItsCassieNova/39cb3df7c59470a771e1da5457d8e0b6) so far. 

For example, for glfw, I did [this](https://github.com/TheCherno/glfw), I'd love to do the same for assimp :( I don't know how he figured it out. But it would be so nice to have a premake5 file for Assimp. 

Hope there's something I can do! Thanks!

**Comment by samsinsane** [comment]
There's a few options:
1. You can write the premake5.lua for Assimp and include it like you have for GLFW.
2. You can bundle the pre-built Assimp libs and header files in your repo.
3. You can use CMake to build Assimp and link it as if it was pre-built.

Additionally, if all you want to do is load FBX files, consider using the FBX SDK instead.

**Comment by hashbrownGL** [comment]
> 
> 
> There's a few options:
> 
>     1. You can write the premake5.lua for Assimp and include it like you have for GLFW.
> 
>     2. You can bundle the pre-built Assimp libs and header files in your repo.
> 
>     3. You can use CMake to build Assimp and link it as if it was pre-built.
> 
> 
> Additionally, if all you want to do is load FBX files, consider using the FBX SDK instead.

Hello Sam, thanks for writing. I know how to build assimp with cmake. So you're saying one of the options would be including an already built assimp library? Just two quick questions if you don't mind.

Where in the documentation could I find what I need to write in order to include the the pre-built libs? Not sure what I need to write in my lua file.

Also one more thing, I noticed the glfw premake file i shared above, includes files. When I use cmake gui, I don't really know what files are getting included. There are so many. 

I'm a little confused about writing that premake.

**Comment by ItsCassieNova** [comment]
> 
> 
> There's a few options:
> 
>     1. You can write the premake5.lua for Assimp and include it like you have for GLFW.
> 
>     2. You can bundle the pre-built Assimp libs and header files in your repo.
> 
>     3. You can use CMake to build Assimp and link it as if it was pre-built.
> 
> 
> Additionally, if all you want to do is load FBX files, consider using the FBX SDK instead.

Hello Sam, thanks for writing. I know how to build assimp with cmake. So you're saying one of the options would be including an already built assimp library? Just two quick questions if you don't mind.

Where in the documentation could I find what I need to write in order to include the the pre-built libs? Not sure what I need to write in my lua file.

Also one more thing, I noticed the glfw premake file i shared above, includes files. When I use cmake gui, I don't really know what files are getting included. There are so many.

I'm a little confused about writing that premake.

**Comment by samsinsane** [comment]
> Where in the documentation could I find what I need to write in order to include the the pre-built libs? Not sure what I need to write in my lua file.

There's the [linking](https://github.com/premake/premake-core/wiki/Linking) documentation, which covers how to link projects. It's not overly different to how you link GLFW, you just need to additionally specify `libdirs` for where the Assimp binary is. So, more or less, you would have:
```lua
includedirs { "assimp_location/include" }
libdirs { "assimp_location/lib" }
links { "assimp.lib" }
```

> Also one more thing, I noticed the glfw premake file i shared above, includes files. When I use cmake gui, I don't really know what files are getting included. There are so many.

There's a few options for working this out. You can directly convert between CMake and Premake by reading the `CMakeLists.txt` files, but if you don't know CMake this can be tricky. You can also use CMake to generate a VS project or a Makefile, whichever one you're more comfortable with, and work backwards from that to the Premake script. Finally, you can just include all of the files from the right folder, in the case of Assimp I think that is the `code` folder, and just trial and error your way to a working Premake script.

**Comment by Cannedfood** [comment]
@ItsCassieNova This is how I build assimp from source: https://gist.github.com/Cannedfood/a71652022f066c8032f5a1c01919c55d

You'll have to update some paths and put your own config.h (based on `assimp/Include/config.h.in`) somewhere.

**Comment by ItsCassieNova** [comment]
Thank you guys, both suggestions worked for me. Sam's reply showed me how to include pre-built libs and CannedFood gave me the premake5 file I needed. 

Thanks again!
