### ISSUE TITLE
Is there any new stable version for this package?

### ISSUE THREAD

**Issue by darmac** [premake/premake-core#1536]
**What's your question?**
Is there any new stable version for this package?

**Anything else we should know?**
There's no any stable version from 2010...

**Comment by samsinsane** [comment]
All of our releases are here: https://github.com/premake/premake-core/releases

**Comment by darmac** [comment]
> All of our releases are here: https://github.com/premake/premake-core/releases

Is that `alpha` version is only testing version?

**Comment by samsinsane** [comment]
No, most of our users will be running one of the alpha releases or a cut of master.
