### ISSUE TITLE
c++20 support time?

### ISSUE THREAD

**Issue by yangdemin** [premake/premake-core#1537]
cppdialect "C++20" not support now.

**Comment by samsinsane** [comment]
We have issue templates for a reason, please don't waste our time. We already have C++20 support:
https://github.com/premake/premake-core/blob/c6580ff1cefa7660a0df59f3da90dff0bf1be417/src/_premake_init.lua#L772
You'll need to use a master build, as the latest alpha release pre-dates this support.
