### ISSUE TITLE
How to add extra property to PackageReference node when using nuget function

### ISSUE THREAD

**Issue by natsu1211** [premake/premake-core#1541]
**What's your question?**
I'm using premake5 to generate csproj, and recently need to add some nuget packages to my project.
so I added
```
nuget {
    "Fody:6.3.0",
    "MethodTimer.Fody:3.1.2"
}
``` 
to premake5.lua and of course I got
```
<ItemGroup>
  <PackageReference Include="Fody" Version="6.3.0"/>
  <PackageReference Include="MethodTimer.Fody" Version="3.1.2"/>
</ItemGroup>
```
but what I need is 
```
<ItemGroup>
  <PackageReference Include="Fody" Version="6.3.0"/>
  <PackageReference Include="MethodTimer.Fody" Version="3.1.2" PrivateAssets="all"/>
</ItemGroup>
```
to make the package work properly.

Is there anyway to achieve this without modify the source of premake-core? 
Thanks!

**Comment by starkos** [comment]
Best way to tell is to search the premake-core sources to see if you can find the symbol. "PrivateAssets" isn't in there, so no, it us currently not supported, and will require a code change or override.

**Comment by starkos** [comment]
Accidentally submitted too soon, finishing the thought…

One approach is to [override](https://github.com/premake/premake-core/wiki/Overrides-and-Call-Arrays) [`dotnetbase.packageReferences()`](https://github.com/premake/premake-core/blob/master/modules/vstudio/vs2005_dotnetbase.lua#L523) to add the behavior you want; you can do that right in your project script if you like.

But it really isn't much more work to [fix it properly in Premake itself](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#contributing-a-fix-or-feature). That helps the community, and offload support for the change, should the underlying code change in the future.

Marking this closed as answered, but feel free to continue the conversation if you have questions.
