### ISSUE TITLE
os.remove is not documented in wiki

### ISSUE THREAD

**Issue by KyrietS** [premake/premake-core#1543]
**What seems to be the problem?**
`os.remove` is missing in wiki but it's implemented: https://github.com/premake/premake-core/blob/master/src/base/os.lua#L479

**What did you expect to happen?**
Add it to wiki because it is the only non-source-code documentation of Premake5 at this moment. Unfortunately contributors can't make Pull Requests to wiki pages.

**Anything else we should know?**
`os.matchfiles` seems to be very similar in use so you can just copy&paste it with some minor changes. Here: https://github.com/premake/premake-core/wiki/os.matchfiles

**Comment by redorav** [comment]
Interesting. I used to be able to edit the wiki freely, now I cannot. I wonder what has changed

**Comment by samsinsane** [comment]
> I wonder what has changed

A couple of clowns were editing it talking trash about each other, eventually leaving the footer with a link to CMake. The option was leave the wiki open to these kinds of problems, or lock it down and move towards having the docs in the repo instead. The docs weren't being updated that often anyway, so we opted to lock it down. It's unfortunate that GitHub only has two options here, any kind of approval system would be significantly better.

**Comment by KyrietS** [comment]
Are there any decisions made towards having the docs in the repo? There are many great frameworks for docs that work with GitHub static pages pretty well, eg.
* MkDocs: https://www.mkdocs.org/
* Docsify: https://docsify.js.org/
* Slate: https://slatedocs.github.io/slate/#introduction
* etc.

**Comment by starkos** [comment]
@KyrietS No decisions made, but high on the priority list so any assistance would be very much appreciated! I've opened #1547 to get the documentation sorted.

**Comment by starkos** [comment]
Fixed, see [os.remove](https://github.com/premake/premake-core/wiki/os.remove).
