### ISSUE TITLE
How do I Setup a Script to Generate a Visual Studio Android Project? (Error: invalid value 'AndroidProj' for kind)

### ISSUE THREAD

**Issue by OBXS** [premake/premake-core#1544]
**What's your question?**
I'm trying to generate an android project for Visual Studio, but Premake is throwing an error saying "Error: invalid value 'AndroidProj' for kind". This is the script I used:
```
require "android"
solution "AndroidTest"
    architecture "ARM"
    startproject "AndroidTest"

    configurations
    {
        "Debug",
        "Release"
    }

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

project "AndroidTest"
    location "AndroidTest"
    kind "ConsoleApp"
    language "C++"
    cppdialect "C++17"
    staticruntime "off"
    system "android"

    targetdir ("bin/" .. outputdir .. "/%{prj.name}")
    objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

    files
    {
        "%{prj.name}/**.h",
        "%{prj.name}/**.cpp",
        "%{prj.name}/**.c",
    }

    includedirs
    {
        "%{prj.name}/",
        "%{prj.name}/inc",
        "%{prj.name}/src",
        "C:/Microsoft/AndroidNDK64/android-ndk-r16b/sources/android/support/include",
        "C:/Microsoft/AndroidNDK64/android-ndk-r16b/sysroot/usr/include",
    }

    filter "configurations:Debug"
        runtime "Debug"
        symbols "On"

    filter "configurations:Release"
        runtime "Release"
        optimize "On"

project "AndroidPackage"
    location "AndroidPackage"
    kind "AndroidProj"
    language "C++"
    cppdialect "C++17"
    staticruntime "off"
    system "android"
    
    targetdir ("bin/" .. outputdir .. "/%{prj.name}")
    objdir ("bin-int/" .. outputdir .. "/%{prj.name}")
```
and my directory is structured as such:
┗ Root
  ┣ android (copied from from premake-core/modules)
  ┃┣ tests
  ┃┣ README.md
  ┃┣ vsandroid_sln2005.lua
  ┃┣ vsandroid_vcxproj.lua
  ┃┣ vsandroid_vstudio.lua
  ┃┣ _manifest.lua
  ┃┣ _preload.lua
  ┃┣ android.lua
  ┃┣ LICENSE.txt
  ┃┗ vsandroid_androidproj.lua
  ┣ AndroidTest (Project Folder)
  ┣ Android Package (Project Folder)
  ┣ Premake5.lua (The script above)
  ┗ Premake5.exe (Premake Executable)

It doesn't seem to matter if I generate a VS2015, 2017 or 2019 file. Can you tell me what I'm missing?

**Comment by redorav** [comment]
While I can't point to the specific problem you're having, I use the following for my android projects, maybe it can help you?

https://github.com/redorav/hlslpp/blob/master/premake.lua

**Comment by OBXS** [comment]
I'll see what I can figure out, Thanks for the reference!

**Comment by OBXS** [comment]
Using "Packaging" instead of "AndroidProj" for the project kind worked perfectly, should this be updated in the wiki?

**Comment by redorav** [comment]
I am unsure, I don't know whether the wiki reflects the current state of the code (and not the latest beta) or is outdated. @samsinsane any opinions?

**Comment by samsinsane** [comment]
The wiki usually reflects the current state rather than any particular release. I'm disappointed that the rename didn't add an alias, but it's likely I reviewed and merged it without noticing, so my bad guys. I'll update the wiki to reflect this change, and put a comment in about the name change.
