### ISSUE TITLE
Support -clr:netcore for C++/CLI

### ISSUE THREAD

**Issue by ddobrev** [premake/premake-core#1545]
Add a new value to https://github.com/premake/premake-core/wiki/clr so that premake can generate C++/CLI projects which compile for .NET Core: https://docs.microsoft.com/en-us/dotnet/core/porting/cpp-cli.

**Comment by nickclark2016** [comment]
I can pick this up later this week if no one has got around to it.  Does this API change work?

```lua
clr "NetCore"
```

Under the hood, this would change

```xml
<CLRSupport>true</CLRSupport>
```
to
```xml
<CLRSupport>NetCore</CLRSupport>
```

**Comment by ddobrev** [comment]
@nickclark2016 I'm not sure if the question is directed to me but this looks just fine. Then again, I'm not at present sure this is everything that would have to change in the project file.

**Comment by nickclark2016** [comment]
Looking at the MSBuild information about this, this is all that is needed for the C++/CLI side of NetCore.  Of course, TargetFrameworks will need to be added, but this should be handled in the user premake script and not in the premake executable itself.

**Comment by ddobrev** [comment]
@nickclark2016 OK, thank you, looking forward to the feature.
