### ISSUE TITLE
targetdir in subproject not accounted for

### ISSUE THREAD

**Issue by prowley** [premake/premake-core#1546]
I have a main project with a sub project (Lua actually)
This is using premake gmake2 on Mac.
Version 5.0.0-alpha15

In the top level project (root of source tree) I do:

  configuration "Debug"
    targetdir "bin/debug"

  configuration "Release"
    targetdir "bin/release"

then later I have:

  filter {}
    links {"lua"}

which is the project name of the SharedLib.

In the Lua project (one level down) I have:

  configuration "Debug"
    targetdir "../bin/debug"

  configuration "Release"
    targetdir "../bin/release"

Before I added this config, linking was fine. But I like lowercase directory names :) 

After the config, main main app no longer can find the symbols for Lua:

  "_luaL_newstate", referenced from:
      _main in main.o
  "_luaL_openlibs", referenced from:
      _main in main.o
  "_lua_close", referenced from:
      _main in main.o

Yet it is built in the correct place ./bin/debug.. If I remove the configuration steps that change dir names in the sub-project, it links fine.
 
Am I misunderstanding something? I thought naming the project in links was supposed to fix up things like this?

**Comment by starkos** [comment]
That logic has been around forever and is in use by pretty much everyone using Premake. It's possible you found an edge case, but equally likely it's an issue with your script. It would be helpful if you followed the issue template instructions and provided a _minimal_ test case that demonstrates the issue.

I'm marking this as closed for now; feel free to reopen with the requested information.
