### ISSUE TITLE
Invalid ActiveCfg and Build0 on .NET Core projects with custom platforms

### ISSUE THREAD

**Issue by ClxS** [premake/premake-core#1550]
When generating a .NET Core project, the solution contains activeCfg/build.0 entries in this format:
> {E3D5870B-4FDF-877C-D85A-9E7C4463937C}.Debug|PcDx11_x64.ActiveCfg = Debug PcDx11_x64|x64

This format works for .NET Framework projects, but does not for .NET Core. It causes an odd bug in Visual Studio where it'll skip projects, despite it being marked for build in the configuration manager.
It seems that in .NET Core it has gotten stricter with the config and platform requirements.

My local solution is this:
```lua
premake.override(sln2005, "activeCfg", function(base, cfg, context)
	if project.iscsharp(context.prj) and dotnetbase.isNewFormatProject(context.prj) then
		if context.platform:find("Release") then
			p.w('{%s}.%s.ActiveCfg = %s|%s', context.prj.uuid, context.descriptor, "Release", context.architecture)
		else
			p.w('{%s}.%s.ActiveCfg = %s|%s', context.prj.uuid, context.descriptor, "Debug", context.architecture)
		end
	else
		base(cfg, context)
	end
end)

premake.override(sln2005, "build0", function(base, cfg, context)
	if project.iscsharp(context.prj) and dotnetbase.isNewFormatProject(context.prj) then
		if context.platform:find("Release") then
			p.w('{%s}.%s.Build.0 = %s|%s', context.prj.uuid, context.descriptor, "Release", context.architecture)
		else
			p.w('{%s}.%s.Build.0 = %s|%s', context.prj.uuid, context.descriptor, "Debug", context.architecture)
		end
	else
		base(cfg, context)
	end
end)
```

But that doesn't feel robust. Does anyone have ideas on a better solution?

**Comment by samsinsane** [comment]
Use the issue template, it's there for a reason.
