### ISSUE TITLE
Returned values of `config.getlinks(cfg, "siblings", "basename")` include targetprefix.

### ISSUE THREAD

**Issue by JoelLinn** [premake/premake-core#1553]
Returned values of `config.getlinks(cfg, "siblings", "basename")` on some architectures include the targetprefix (usually `lib`). However [if I understand it correctly it should not](https://github.com/premake/premake-core/blob/82e50368dc90292d8b698aed51b167462fe30a9b/src/base/config.lua#L59).

This is because `path.basename()` only strips the path and extension (naturally) [here](https://github.com/premake/premake-core/blob/82e50368dc90292d8b698aed51b167462fe30a9b/src/base/config.lua#L313). Shouldn't it return `prjcfg.linktarget.basename` (for siblings) instead?

Unfortunately there don't seem to be any tests for this so I'm unsure what the intended behaviour is.

**Comment by JoelLinn** [comment]
The [clang/gcc tooling strips the lib name](https://github.com/premake/premake-core/blob/82e50368dc90292d8b698aed51b167462fe30a9b/src/tools/gcc.lua#L482-L486). This is very sketchy. Imagine using clang/gcc with targetprefix="" (on windows for example) and one of the projects name begins with `lib` (although not a smart decision one may end up there when compiling `libav`/`ffmpeg` for example)

**Comment by samsinsane** [comment]
Use the issue template, it's there for a reason.
