### ISSUE TITLE
Cross-project linking of custom build outputs

### ISSUE THREAD

**Issue by Xenonic** [premake/premake-core#1561]
**What are you trying to do?**
Link with objects assembled from custom build command in another project.

**What problem are you having?**
Premake doesn't seem to recognize the build outputs produced by one project, in another. Therefore adding the producer-project as a link dependency doesn't actually link with the custom build outputs.

**What have you tried so far?**
Currently, I have two projects, the primary project and an assembly-only project. In my asm-only project build script, I have something like the following:
```lua
filter { "files:**.asm", "system:windows" }
	buildcommands "ml64.exe /c /Fo %{cfg.objdir}/%{file.basename} /D BOOST_CONTEXT_EXPORT= %{file.relpath}"
	buildoutputs "%{cfg.objdir}/%{file.basename}.obj"
```
Which assembles and outputs some asm sources, however I need to link with these outputs in my primary project, which has the following:
```lua
libdirs "Build/Intermediate/*/*/*/Boost.Context"
linkbuildoutputs "On"
links "Boost.Context"
include "Jobs/ThirdParty/boost.context"
```
When linking with `/VERBOSE`, the assembly objects are not being linked.

**What version of Premake are you using?**
5.0.0-alpha15

**Anything else we should know?**
If this isn't trivially solvable, I can remove the additional project and move the assembly sources into the main project, linking them there. However, separation would be much preferred.

**Comment by samsinsane** [comment]
It's probably easiest to just merge the two projects. However, this is Lua and you can iterate each of the `.asm` files and convert the names to their `.obj` counterpart and call either `files { "<filename>.obj" }` or `links { "<filename>.obj" }` - I don't recall if `files` will work as expected, but `links` definitely should. You can use [`os.matchfiles`](https://github.com/premake/premake-core/wiki/os.matchfiles) to match the `**.asm` pattern and iterate the result.

**Comment by Xenonic** [comment]
Thanks for letting me know, for now I've merged the two projects and everything seems to be running smoothly.
