### ISSUE TITLE
Project linked to SharedLib failed with visual 2019

### ISSUE THREAD

**Issue by Jarod42** [premake/premake-core#1563]
**What seems to be the problem?**

Project depending on sharedLibrary fails to link on vs2019

> LINK : fatal error LNK1104: cannot open file 'C:\Users\Jarod42\Code\premake-sample-projects\project-02\solution\vs2019\bin\shared.lib'

Directory contains: shared.dll, shared.ilk, shared.pdb, static.lib

**What did you expect to happen?**
Link the app properly.

**How can we reproduce this?**

With my integration test projects:
https://github.com/Jarod42/premake-sample-projects   project-02

```
local LocationDir = path.join(Root, "solution", _ACTION)

workspace "Project"
	location(LocationDir)
	configurations {"Release"}

	objdir(path.join(LocationDir, "obj")) -- premake adds $(configName)/$(AppName)
	targetdir(path.join(LocationDir, "bin"))
	targetname("app")
	startproject "app"

project "app"
	kind "ConsoleApp"
	targetname "app"

	files { path.join(Root, "src/app/main.cpp") }
	links {"staticLib", "sharedLib"}

project "staticLib"
	kind "StaticLib"
	targetname "static"

	files { path.join(Root, "src/staticlib/lib.cpp") }

project "sharedLib"
	kind "SharedLib"
	targetname "shared"

	files { path.join(Root, "src/sharedlib/lib.cpp") }
```

**What version of Premake are you using?**

Premake5 version from trunk.

**Anything else we should know?**

That config works with gmake/gmake2/codelite.

**Comment by samsinsane** [comment]
Your shared library doesn't export any symbols, so VS isn't generating an import lib because there's nothing to import.

**Comment by Jarod42** [comment]
Indeed.
