### ISSUE TITLE
Problem when compiling a .c file

### ISSUE THREAD

**Issue by Hirosam1** [premake/premake-core#1573]
**What seems to be the problem?**
After building a C++ makefile, **with the gmake2 flag**, and running _make_ while having a .c file in my project, there are errors and compilation is not able to be completed.  The following error appears:
```
"==== Building test_project (debug) ===="
Creating obj
c_file.c
process_begin: CreateProcess(NULL, cc -MMD -MP -o obj/c_file.o -MF obj/c_file.d -c c_file.c, ...) failed.
make (e=2): The sistem could not find the specific file.
make[1]: *** [test_project.make:122: obj/c_file.o] Error 2
make: *** [Makefile:27: test_project] Error 2
```

**What did you expect to happen?**
To compile the .c file as if it was a .cpp file. 

**What have you tried so far?**
Just switching the extension to .cpp works perfectly, however, this can become a cumbersome task when working with third-party libraries, and you have multiple files to rename.

**How can we reproduce this?**
I have a main.cpp and **c_file.c** and running the following the lua script:
```
workspace "test"
    configurations {"Debug"}
project "test_project"
    targetdir "./"
    kind "ConsoleApp"
    language "C++"
    files {"main.cpp", "c_file.c"}
```

**What version of Premake are you using?**
5.0.0-alpha15

**Anything else we should know?**
I am using the MinGW, g++ on **Windows**.
The makefile tries to run `cc   -MMD -MP    -o "obj/c_file.o" -MF "obj/c_file.d" -c "c_file.c"` before it fails. It uses `cc` instead of `g++`. Might be a configuration I am missing? Wasn't it supposed to use `gcc`?
I also tested a C project with only C files and I have the same problem.

**Comment by starkos** [comment]
Compiling a C file using the C compiler seems like the right behavior to me. Off the top of my head, has the `CC` environment variable been set? It sounds like for your environment it should be set to `gcc`, but check your MinGW `bin/` folder to check the exact binary name.

**Comment by Hirosam1** [comment]
Yes, you are correct, there is no cc in my  MinGW bin/ folder, I do have gcc, however. How would I solve this, when I have different type files i.e. .cpp and .c? Thanks!

**Comment by Hirosam1** [comment]
Ops, I just had to set the CC path directly to the GCC executable. That fixes the problem!
