### ISSUE TITLE
How do I set common settings for projects in a group

### ISSUE THREAD

**Issue by minh0722** [premake/premake-core#1574]
Hello, I have a bunch of external projects that stays in a [group](https://github.com/premake/premake-core/wiki/group) and they have a lot of common settings like language settings and configmap, and I don't want to repeat all of them in each of the externalproject. What I was thinking is using filter by their group and just add those common settings once, but there is no group prefix yet. If there is other ways to do this then I'm all open for suggestions. Thanks

**Comment by starkos** [comment]
There is currently no way to apply settings to a project group. The recommended approach is to define a function to contain those settings instead.

```lua
function myExternalProjectSettings()
    language 'C++'
    configmap { ... }
    -- your settings go here
end

externalproject 'MyProject1'
    myExternalProjectSettings()

externalproject 'MyProject2'
    myExternalProjectSettings()
```

Marking closed an answered, but feel free to continue the conversation if you still have questions.

**Comment by minh0722** [comment]
Yeah, using function is cleaner. Thanks
