### ISSUE TITLE
How do I make builds pass NEITHER `-g` or `-s`

### ISSUE THREAD

**Issue by LunarLambda** [premake/premake-core#1582]
I'm porting an existing project from a plain Makefile to premake 5, mainly to familiarize myself more with dealing with slightly unorthodox projects.

The project builds a Windows DLL using mingw-w64, with Linux builds needing `gccprefix "i686-w64-mingw32-"`
no issue there, however

When `symbols` is `Off`, the generated Makefile passes `-s` (strip symbols)
When `symbols` is `On`, the generated Makefile passes `-g` (generate debug info)

The *original* Makefile I'm porting passes neither.
Is there any way to match this behaviour? I saw no strip option under `flags`.

Also, another question: The project has no (needs no) distinguishing between release and debug builds, only between "am I building this on Windows or on Linux?", so I have the following

```lua
    location "build"
    configurations { "Windows", "Linux" }

    -- Always use GCC
    toolset "gcc"

    -- When building on Linux, use mingw prefix.
    filter "configurations:Linux"
        gccprefix "i686-w64-mingw32-"
        linkoptions "-static-libgcc"
```

is there a more idiomatic way to express this?

**Comment by samsinsane** [comment]
There isn't any API you can use to bypass this, but you can override the function that emits the `-g` when you have symbols on.
```lua
premake.override(premake.tools.gcc, "ldsymbols", function(oldfn, cfg) end)
```

**Comment by LunarLambda** [comment]
I see, thank you!
