### ISSUE TITLE
Is {COPYDIR} token broken on windows?

### ISSUE THREAD

**Issue by RMPowser** [premake/premake-core#1592]
**What are you trying to do?**
I want a post build event to copy everything in the ./textures directory to %{cfg.buildtarget.directory}textures directory.

**What problem are you having?**
In my premake5.lua file, I have this:
![image](https://user-images.githubusercontent.com/53650569/110013072-0a256300-7cd6-11eb-954d-662499bc1ae6.png)

After building the project files, in Visual Studio 2019, I get this in the post build events for the project which obviously isn't going to work:
![image](https://user-images.githubusercontent.com/53650569/110013128-1c070600-7cd6-11eb-9334-6e48f19730a2.png)

**What have you tried so far?**
I followed the getting started section of the wiki and as far as I can tell, I'm using the token correctly.

**What version of Premake are you using?**
5.0.0-alpha15

Please let me know if I'm doing something wrong or if it's actually broken and there's a workaround.

**Comment by samsinsane** [comment]
The `{COPYFILE}` and `{COPYDIR}` tokens were added after the alpha15 release, you'll need to use `{COPY}` (if it works for your use case) or use a master build. Alternatively, you can patch in the tokens by using:
```lua
-- Remove after alpha16 release
if not os.commandTokens._.copyfile then
  os.commandTokens._.copyfile = function(v)
    return "cp -f " .. path.normalize(v)
  end
  os.commandTokens._.copydir = function(v)
    return "cp -rf " .. path.normalize(v)
  end

  os.commandTokens.windows.copyfile = function(v)
    v = path.translate(path.normalize(v))
    return "copy /B /Y " .. v
  end
  os.commandTokens.windows.copydir = function(v)
    v = path.translate(path.normalize(v))
    return "xcopy /Q /E /Y /I " .. v
  end
end
```

**Comment by samsinsane** [comment]
Closing this as the token was not in the build being used, and alpha16 is available now.
