### ISSUE TITLE
Using clang-cl with vs2019

### ISSUE THREAD

**Issue by rtosman** [premake/premake-core#1596]
I have a build of premake5 that I made from main a few months ago with support for using toolset('clang') with vs2019 and it works fabulously, however, trying the latest *.zip, it does not generate a working *.vcxproj.

Is this expected to work yet? (not sure how to tell what the latest published zip has in it).

Here is the difference in a generated .vcxproj using the premake I built from source a few months ago vs the latest .zip.
[premake_clang.pdf](https://github.com/premake/premake-core/files/6138097/premake_clang.pdf)

**Comment by nickclark2016** [comment]
@rtosman It is in the latest release (5.0 alpha 16). I've confirmed it as functional locally with my own C/C++ projects.

**Comment by starkos** [comment]
@rtosman Could you (re-)try one of the packages listed [here](https://github.com/premake/premake-core/releases), and verify that the feature does/does not work?

**Comment by Pikachuxxxx** [comment]
I just tried it with 5.0 alpha 16 and it works fine

**Comment by nickclark2016** [comment]
Moving to close this unless I get a response from @rtosman saying that it is not resolved.

**Comment by nickclark2016** [comment]
Closing. Please reopen if this is not resolved.
