### ISSUE TITLE
Does anyone knows how to generate the MFC project ?

### ISSUE THREAD

**Issue by ccwanggl** [premake/premake-core#1605]
_Before opening a new issue, please [use the issue search feature](https://github.com/premake/premake-core/issues) to see if a similar issue already exists. If not, please help us help you by filling in the template below._

**What are you trying to do?**
A short, concise description of the outcome you are trying to achieve, ex. "Add build settings to a specific file".

**What problem are you having?**
A clear and concise description of the problem that is blocking you from your desired outcome, ex. "Premake is crashing with this error message: ..." or "I don't know how to do it."

**What have you tried so far?**
Describe any steps you've already taken to try to get past this issue.

**What version of Premake are you using?**
`premake5 --version` will show you the version. If you are running a "-dev" version, please make sure you are up to date with the latest master branch.

**Anything else we should know?**

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

**Comment by starkos** [comment]
Help us help you: please open a new issue and answer the provided questions. Closing.

**Comment by Brouilles** [comment]
I'm also interested!
