### ISSUE TITLE
add support for compiler version selection

### ISSUE THREAD

**Issue by moffel** [premake/premake-core#1612]
The current MSVC has a bug that makes it impossible to work with for me. Visual Studio has a setting called "MSVC Toolset Version" which internally sets the <VCToolsVersion> tag.  
Note that this is not the Platform Toolset but a way to select a specific version of the selected Platform Toolset.

I would like to set the msvc toolset version used for a specific platform toolset. I can imagine that this feature also applies to other project types as well.

Even more convenient would be a compiler blacklisting feature to blacklist compiler versions known to not work. But that would obviously require premake to know which compiler versions are installed.

**Comment by samsinsane** [comment]
If you need something immediately, you can try adding this to your `premake5.lua`:
```lua
require "vstudio"

premake.override(premake.vstudio.vc2010, "platformToolset", function (oldfn, cfg)
  oldfn(cfg)
  premake.vstudio.vc2010.element("VCToolsVersion", nil, "14.27.29110")
end)
```
