### ISSUE TITLE
How to replace {COPYDIR} on windows ? 

### ISSUE THREAD

**Issue by Samuel-POTTER** [premake/premake-core#1613]
Hello, I'm discovering premake. And I've planned to work on a project using QT. For this, I've created a premake5.lua linked to conan. But my issue is the next one. I need to copy a folder and past it after the build. By reading the docs, I found the famous {COPYDIR} but it seems that this doesn't work on windows. I also tried os.copy, fs.copy...nothing. Any idea on how I could manage this please. Here's my lua file. 

```lua
include "build/conanbuildinfo.premake.lua"

workspace "TileEditor"
    conan_basic_setup()

    configurations
    {
        "Debug",
        "Release",
        "Dist"
    }

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

project "TileEditor"
    location "TileEditor"
    kind "ConsoleApp"
    language "C++"

    targetdir ("bin/" .. outputdir .. "/%{prj.name}")
    objdir ("bin-obj/" .. outputdir .. "/%{prj.name}")

    linkoptions { conan_exelinkflags }

    files
    {
        "**.h", "**.cpp" 
    }

    configuration "windows"
        postbuildcommands {
            "{COPY} C:\\Qt\\6.0.3\\msvc2019_64\\bin\\Qt6Core.dll %{cfg.targetdir}",
            "{COPY} C:\\Qt\\6.0.3\\msvc2019_64\\bin\\Qt6Gui.dll %{cfg.targetdir}",
            "{COPY} C:\\Qt\\6.0.3\\msvc2019_64\\bin\\Qt6Widgets.dll %{cfg.targetdir}",
            "{COPYDIR} C:\\Qt\\6.0.3\\msvc2019_64\\plugins\\platforms %{cfg.targetdir})"
        }
```

**Comment by redorav** [comment]
Are you on alpha-15? {copydir} is a thing in alpha 16, which has only recently been released

**Comment by Samuel-POTTER** [comment]
@redorav How really..I downloaded the premake from the website and it's
```bash
(Premake Build Script Generator) 5.0.0-alpha15
```

totally my bad on that one.

**Comment by redorav** [comment]
@Samuel-POTTER not your fault at all, alpha16 was released a couple of days ago, this has tripped other people up as well :) feel free to close if it's fixed
