### ISSUE TITLE
Can't set separate buildaction for a specific file

### ISSUE THREAD

**Issue by n00bmind** [premake/premake-core#1615]
**What seems to be the problem?**
I'm trying to set up a unity-style build for one of our projects.
At first, I was simply including a single main.cpp in the project's files:
```
files
{
        "main.cpp",
}
```
which works fine, as main.cpp directly includes all the other cpps in the project.
However, this is not ideal, as then the rest of the cpp files aren't even listed in the VS project, so I want to include all the other files too but set their buildaction to "None". So I tried with
```
    files
    {
        "*.h",
        "*.cpp",
    }

    filter "files:**.cpp"
        buildaction "None"
    filter "files:main.cpp"
        buildaction "Compile"
```
but that just excludes _all_ files from the compilation, as if the filter for main.cpp was completely ignored.

**What did you expect to happen?**
I'd expect all files to be set to "Does not participate in build", except for main.cpp which would have the default build action.

**What have you tried so far?**
I've tried several variations of the above, and the behaviour is kind of strange, as if the files filter and `buildaction` didn't play well together.

**How can we reproduce this?**
Just create a new project with a couple .cpp files and the two filters above, then observe the property page (Alt+F4) for the included source files in Visual Studio.

**What version of Premake are you using?**
5.0.0-alpha14

**Comment by samsinsane** [comment]
The docs already cover this quite clearly:
> For C/C++, `action` is the name of the MSBuild action as defined by the vcxproj format; eg: `ClCompile`, `FxCompile`, `None`, etc, and may refer to any such action available to MSBuild.

You're trying to use the C# values, not the C++ values.
