### ISSUE TITLE
how to install generated so to /usr/local/lib64 just as GNU make' s install on linux?

### ISSUE THREAD

**Issue by uniqss** [premake/premake-core#1618]
Hey guys! I really love this tool because cmake is too hard to configure. Thanks for you all~ But I just got some problem using premake:
I want to generate gmake2 script which contains an install target, just to copy the generated so file to /usr/local/lib or /usr/local/lib64. I googled, main suggestion is using postbuildcommands. but I think it is not convinent enough, because sometimes we need to sudo to supress to root when executing the postbuildcommands, but we don't want to make the whole build process as a sudoer. A trick may be add a configuration named "install" and copy the generated so to /usr/local/lib64 using `make config=install_x64` . Is there a more easy way to do this? I searched the source code there is a ` settings['INSTALL_PATH'] ` , but I searched the projectsetting in https://premake.github.io/docs/objdir  nothing named install found. Any suggestions greatly appreciated~

**Comment by uniqss** [comment]
my source code is here:   [https://github.com/uniqss/uniqslib/tree/master/study/premakehelloworld/3_dynamiclib](https://github.com/uniqss/uniqslib/tree/master/study/premakehelloworld/3_dynamiclib)

**Comment by starkos** [comment]
You'll want to [define a new action](https://premake.github.io/docs/newaction/) to perform your installation steps. Then just write it as a Lua script. See the [newaction](https://premake.github.io/docs/newaction/) docs for an example.
