### ISSUE TITLE
Adding clang doesn't change compiler for visual studio

### ISSUE THREAD

**Issue by MordechaiHadad** [premake/premake-core#1620]
**What's your question?**
Adding `toolset "clang"` doesn't add `<PlatformToolset>ClangCL</PlatformToolset>` line to {prj.name}.vcxproj

**Anything else we should know?**
my entire premake lua file
```premake5.lua
workspace "Test"
   configurations { "Debug", "Release" }
   architecture "x86_64"

project "Test"
   kind "ConsoleApp"
   language "C"
   targetdir "bin/%{cfg.buildcfg}"
   objdir "bin-int/%{cfg.buildcfg}"
   
   toolset "clang"

   files { "**.h", "**.c" }

   filter "configurations:Debug"
      defines { "DEBUG" }
      symbols "On"

   filter "configurations:Release"
      defines { "NDEBUG" }
      optimize "On"
```

everything is latest version downloaded them today

**Comment by samsinsane** [comment]
This is a bug not a question. I'm going to close this, you can open a new issue using the bug template if you want help.
