### ISSUE TITLE
Precompiled headers not working with codelite generator

### ISSUE THREAD

**Issue by shadoww1028** [premake/premake-core#1621]
When making a codelite project from the generator the precompiled headers are not being set in the project file, everything else is there.

Under the project settings -> compiler -> Pre Compiled Headers    Nothing is filled out for the header

I tried to build it for Visual Studio to make sure the configuration file was correct and sure enough it did set the header in that project so I know I have it set up correctly.  (note I don't have Visual Studio I was just looking at the output)

In the configuration file set pchheader "all.hpp" and I also made a source for and set that to pchsource "all.cpp"  Both are in the root directory of the project.

I'm using Premake5 on Arch Linux.

I attached my test solution I was using to see if premake was something I was going to use. 

[example.tar.gz](https://github.com/premake/premake-core/files/6345069/example.tar.gz)

**Comment by Jarod42** [comment]
BTW `pchsource "all.cpp"` is only required for msvc.
