### ISSUE TITLE
'group' keyword on linux (gmake2) - problems surface when the group has the same name as a project

### ISSUE THREAD

**Issue by qolisipo** [premake/premake-core#1624]
Using premake5.

I am using the `group` keyword to create a virtual folder on Visual Studio 2019. It works fine.

```
group "Engine"
    include "Engine"
    include "Editor"
```

When creating the Makefile for Linux (gmake2), it lists Editor as a dependency for Engine, even though its the other way around. 
When building from the 'parent' Makefile, I get the following message and error:
`make: Circular Editor <- Engine dependency dropped.`
`make[1]: *** No rule to make target`

I found a few solutions:

1. By navigating to each directory and building from the Makefile that was generated for the specific project, it works fine.

2. Another workaround is to rename the group to something different.
Even when this is done the same line is generated but I suppose it is then ignored as there isn't a makefile for the made up name.

Example:

```
group "Bananas"
    include "Engine"
    include "Editor"
```

Bananas will have as a dependency the editor and engine but no error occurs, I assume this is ignored by the compiler as Bananas does not exist.

From the documentation, I supposed `group` would be totally ignored for gmake2, but that does not seem to be the case.

Both of these solutions are kinda hacks as the makefile line thats causing the problems should not have been generated at all. The only good solution is to remove the `group`. 
Putting `group` under a filter for the system does not seem to be supported so I cant make it system specific.

**Comment by qolisipo** [comment]
Another hacky solution is to include the Editor first and then the Engine.

```
group "Engine"
   include "Editor"    
   include "Engine" 
```

The same Makefile line is generated but this time because of the nature of the dependencies, no errors occur, although the compiler warns of Circular dependencies, it works.

**Comment by samsinsane** [comment]
> From the documentation, I supposed `group` would be totally ignored for gmake2, but that does not seem to be the case.

I didn't know this was a thing either! It seems to be used to allow you to build just the projects in that group, I don't think VS allows this, so I'm not sure why this is default behaviour. This is why you're seeing problems, there's no way to distinguish between a group and a project when they have the same name.

> Putting `group` under a filter for the system does not seem to be supported so I cant make it system specific.

You can do this:
```lua
if _ACTION ~= "gmake2" then
  group "Engine"
end
```

I guess another option would be to allow users to turn off the generation of group rules, similar to the `linkgroups` option that allows users to not worry about the ordering when using `links`.

**Comment by starkos** [comment]
I have a memory of the Blizzard folks mentioning this. Is it something we want to keep, or should I look into pulling it out to make it match Visual Studio?

**Comment by qolisipo** [comment]
> You can do this:
> 
> ```lua
> if _ACTION ~= "gmake2" then
>   group "Engine"
> end
> ```

This solved the issue, thank you!
