### ISSUE TITLE
Linking error when building.

### ISSUE THREAD

**Issue by Sidharth-Saha** [premake/premake-core#1626]
I am trying to build premake from source using the prebuilt premake binaries and I am generating a visual studio 19 solution. When I try to build the solution I am getting linking errors.

9>premake.obj : error LNK2001: unresolved external symbol registerModules
9>premake.obj : error LNK2001: unresolved external symbol builtin_scripts

**Comment by starkos** [comment]
You will need to run `premake5 embed` to link the Lua scripts into the binary. See [BUILD.txt](https://github.com/premake/premake-core/blob/master/BUILD.txt#L61-L70).
