### ISSUE TITLE
Broken links to some pages in docs

### ISSUE THREAD

**Issue by KyrietS** [premake/premake-core#1634]
I've created this issue to track the progress of fixing broken links on some pages. 

I can successfully reproduce this weird behaviour:

1. Go to https://premake.github.io/docs/Developing-Modules/
2. Links are broken, because they are referencing `/docs/Developing-Modules/*` instead of `/docs/*`
3. Use sidebar navigation and go to **Adding a New Action**
4. Use sidebar navigation and go back to **Developing Modules**
5. Links are working fine
6. Refresh the page (F5)
7. Links are broken again

I will try do debug this but at the moment I suspect that it's Docusaurus' fault.

**Comment by Jarod42** [comment]
It seems there is a difference between
https://premake.github.io/docs/Developing-Modules (working)
and
https://premake.github.io/docs/Developing-Modules/ (not working).

**Comment by KyrietS** [comment]
Similar problem has already been reported: https://github.com/facebook/docusaurus/issues/2317
The solution proposed there seems to work.

So instead of this:

```
* [Introduction](introducing-modules)
* [Adding Unit Tests](adding-unit-tests)
* [Sharing Your Module](sharing-your-module)
* [Embedding Modules](embedding-modules)
```

we should always write references to other pages like this:

```
* [Introduction](Introducing-Modules.md)
* [Adding Unit Tests](Adding-Unit-Tests.md)
* [Sharing Your Module](Sharing-Your-Module.md)
* [Embedding Modules](Embedding-Modules.md)
```
^ **case sensitive!**

Fortunately when I was migrating references I always used filenames with *.md extensions.

In my opinion it's a bug in Docusaurus. They should fix this weird behaviour of breaking links after refresh or mark those links as broken during building process.

Fun fact: I've already advised @starkos how to create links to other pages in my [migration notes](https://github.com/premake/premake-core/issues/1547#issuecomment-796287470) 😉 

> When linking to another document ALWAYS use relative path with *.md extension. Docusaurus will generate valid urls, and links will also work when browsing on GitHub. Additionally, you will get a warning message when link to a markdown file can't be resolved.

I'm working on fixing this.
