### ISSUE TITLE
Make clean is not working when using premake5

### ISSUE THREAD

**Issue by ARYANBro** [premake/premake-core#1648]
I have a simple premake5 file that creates makefiles for a small project of mine. When I run premake5 gmake2 all makefiles are created successfully and I can call make to compile to an executable and run it.

The problem is when I try to call make clean, I get an error saying: `The directory name is invalid. and make: *** [clean] Error 267`

I've narrowed it down to one line in the makefile which should remove all the object files, but causes an error and stops any more files from being removed.

`$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))`

This is the line that is causing the error. Removing it fixes the problem but causes my bin/obj folder to remain.
This issue is based on https://stackoverflow.com/questions/64414270/make-clean-is-not-working-when-using-premake5

**Comment by samsinsane** [comment]
Help us help you, fill in the issue template as requested.
