### ISSUE TITLE
Missing SSE3 (and etc.) Flags

### ISSUE THREAD

**Issue by imallett** [premake/premake-core#165]
"EnableSSE" and "EnableSSE2" are accepted by `flags` and `vectorextensions`. There is a need to also support SSE3 especially, and SSE4/AVX2 also, since e.g. GCC will not generate instructions without them (and specifying e.g. an SSE3 intrinsic will prevent that code from compiling).

**Comment by TurkeyMan** [comment]
I've been needing this too for ages. I might do this today...

**Comment by TurkeyMan** [comment]
Incidentally, AVX and AVX2 are both available for ages in premake5.

I've added the intermediates: #168
