### ISSUE TITLE
Is there any option to supprt /utf-8 ?

### ISSUE THREAD

**Issue by haolly** [premake/premake-core#1652]
To fix this issue https://developercommunity.visualstudio.com/t/warning-c4819-to-file-saved-in-utf-8-encoding/176752
there is also a SO question related to this https://stackoverflow.com/questions/49567108/c-errors-c4819-c2761-c2447

**Comment by samsinsane** [comment]
`buildoptions { "/utf-8" }`

**Comment by Jarod42** [comment]
I would even say
```
filter "toolset:msc*"
  buildoptions { "/utf-8" }
```
