### ISSUE TITLE
Always Getting Error: invalid value 'Unicode' for flags

### ISSUE THREAD

**Issue by apaly** [premake/premake-core#1660]
Hello,
I downloaded Premake5 prebuilt binary v5.0.0-alpha16 onto my Windows 10 laptop which is in German.

When I typed: **premake5 --help** at the command prompt I got this error "**Error: invalid value 'Unicode' for flags**". In fact when I type only **premake5** I get the same error.

I would appreciate your kind assistance with fixing this.

**Comment by apaly** [comment]
Hi,
I just came to reaslise that the problem is not with premake5. I am trying to build a tutorial with premake5 and the error above occurs when premake5 is copied to the build folder of the tutorial. But when I ran the command above in a non build folder premake5 worked properly.

The build file of the tutorial is premake4.lua. Could this be the cause of the error?

**Comment by nickclark2016** [comment]
Can you link us the premake file (or entire tutorial)? This will make it easier for us to assist.

**Comment by apaly** [comment]
Hi,
Thanks for the swift response. Here is the link to the tutorial: https://github.com/paroj/gltut.

**Comment by nickclark2016** [comment]
So someone else can correct me if I'm wrong, but premake4 is not compatible with premake5.  You'll need to use a premake4 build, or update the build to use premake5.

**Comment by apaly** [comment]
Thanks, but I couldn't find where to download premake4.exe.

Could you point me to a link?

**Comment by nickclark2016** [comment]
You can build this from source: https://github.com/premake/premake-core/releases/tag/4.3-rc2

As for an executable, there's none in the build artifacts for this repository.  I'd highly recommend converting the premake4 files in the repository to use premake5.

**Comment by nickclark2016** [comment]
> So someone else can correct me if I'm wrong, but premake4 is not compatible with premake5. You'll need to use a premake4 build, or update the build to use premake5.

To update, `Unicode` is not a legal value for `flags` in premake5, hence causing your error.  If you need `Unicode`, remove that from the flags and add:

```lua
charset "Unicode"
```

See https://premake.github.io/docs/characterset/

**Comment by apaly** [comment]
Thanks it worked.
