### ISSUE TITLE
is newaction.module deprecated/removed/useful

### ISSUE THREAD

**Issue by Jarod42** [premake/premake-core#1671]
_Before asking a new question, please [use the issue search feature](https://github.com/premake/premake-core/issues) to see if your question has already been asked. Help us help you!_

**What's your question?**
Trying to add premake-ninja in [my premake test repository](https://github.com/Jarod42/premake-sample-projects)

That action use `module = "ninja"` in its new action which is problematic in my configuration.
I don't see other action using `module =`, so I wonder if it is an old deprecated way, or if there are still some need.

**Anything else we should know?**
That action has warning about deprecated stuff, and removing that `module = ninja` allows the generation on my side.

**Comment by samsinsane** [comment]
Looks like it just `require`s the module: https://github.com/premake/premake-core/blob/64f1b3494a81ffc94248b3c416bc9e679838cc00/src/base/action.lua#L220-L223

I'm not really sure how removing the `module = "ninja"` line helps at all, you have to pull the module in at some point. Very strange.

This is the commit that introduces the behaviour: https://github.com/premake/premake-core/commit/ad24e41dd6142b82011d9783d20e12575aed5e93

And here's the description of the commit:
> By only registering the action, we skip the processing that would been necessary to load and evaluate the module scripts. This will allow us to improve overall performance while also scaling up the number of supported actions. To force loading of the entire module (to override specific calls, for instance), call require().

There's definitely value in this functionality.

Does this answer your question?

**Comment by Jarod42** [comment]
In `premake-system.lua`,
I have `require 'submodules/premake-ninja/ninja'"`
(and similarly for cmake and codeblocks).

The later ones don't have the `module` entry.
And they all have:

```
-- Decide when the full module should be loaded.
	return function(cfg)
		return (_ACTION == "codeblocks")
	end`
```

`module` is not in doc BTW: https://premake.github.io/docs/newaction/

> Does this answer your question?

Not really, 
Which is the configuration to use modules with module entry?

**Comment by samsinsane** [comment]
> Which is the configuration to use modules with module entry?

My previous comment contains all of my information on the module entry. Like you said, it's not documented and I'm guessing as to where it's intended to be used. The comment in the commit gives everything you need to know. Instead of `require "ninja"`, you `dofile "{where ever you put your modules}/premake-ninja/_preload.lua"`. Then when you do `premake5 ninja` it will trigger the `require "ninja"`. That might still cause issues - I don't know, I have never used the `module` member and I've never used the ninja module.

I'm going to close this issue now as there's no more information I can provide on this.

**Comment by Jarod42** [comment]
I will (already done ;) ) remove it in ninja as no other actions (even in premake' core) use it.
Previous value seems wrong anyway.

I might add it later once feature would be documented.

Thanks.
