### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by ghost** [premake/premake-core#1674]
Visual Studio 2022 preview has been released and I'd like to test it with premake.

**Comment by nickclark2016** [comment]
Right now, I'd imagine that you should be able to generate VS2019 projects, then have VS2022 migrate the project and solution files to the version it needs. Does this not work (haven't tried VS2022 yet)?

**Comment by SySDevel7** [comment]
@nickclark2016 I can convert vs2019 project to vs2022 but if I want to edit an regenerate premake scripts while developing the project I have to use vs2019 without conversion. It will be much appreciated if you add vs2022 support.

**Comment by nickclark2016** [comment]
Of course. I'll see if I can whip something up. In theory, it should just be changing version numbers, but I'm not 100% sure.

**Comment by starkos** [comment]
@SySDevel7 Any assistance you can provide in identifying the differences between the 2019 and 2022 project files would of course be a huge help.

**Comment by SySDevel7** [comment]
> @SySDevel7 Any assistance you can provide in identifying the differences between the 2019 and 2022 project files would of course be a huge help.

I just started using it this week and the best new features added for C++ development are:

- Hot reload
- C++ 20 full support
- WSL2 C++ development 

I have already added vs2022 support for premake for my fork [here](https://github.com/SySDevel7/premake-core/commit/5333a273b50a5992006a31509bcd1305f0dd0642) by just changing version numbers and I it works for both C++ and C# Hello World project but I have not tried it for bigger projects yet.

**Comment by nickclark2016** [comment]
That change looks about like what I had, the main difference being that I changed "15.0" to "17.0" in the version and added basic unit testing.  I'll clean my code up and have it for PR in a bit for introductory support to VS2022, then we can add on to that as we find differences.  I'm not seeing any major differences on my end in the project and solution files, but I only checked for C++ projects.

**Comment by SySDevel7** [comment]
@nickclark2016 The only difference I have noticed is the .csproj file for c# projects

Here what VS 2022 generates

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

</Project>
```

It doesn't use ToolsVersion="15.0" or TargetFrameworkVersion like premake does. also premake generates a lot of other properties.

**Comment by nickclark2016** [comment]
Is that a .NET core or .NET framework project that you generated (assuming core)

**Comment by SySDevel7** [comment]
> Is that a .NET core or .NET framework project that you generated (assuming core)

It is .NET framework 6.0 preview shipped with VS 2022. 

stable version .NET 4.8.* is `net48`

https://docs.microsoft.com/en-us/dotnet/standard/frameworks#latest-versions

**Comment by nickclark2016** [comment]
https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview?view=vs-2022

Hmm, it definitely feels like a mismatch between the documentation on the microsoft website and what you're seeing generated. I'm a bit cautious of touching C# until that documentation has been updated.

**Comment by gottfriedleibniz** [comment]
Here was my attempt at VS2022 https://github.com/gottfriedleibniz/premake-core/tree/vs2022 support.

It was recently updated to use [v143](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-2-is-out/) as the default toolset; also compiles my variety of projects fine.

**Comment by nickclark2016** [comment]
> 
> 
> Here was my attempt at VS2022 https://github.com/gottfriedleibniz/premake-core/tree/vs2022 support.
> 
> It was recently updated to use [v143](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-2-is-out/) as the default toolset; also compiles my variety of projects fine.

That works great for just C++ builds, but we need to think about the C# targets as well.  I'm going to try to take some time this weekend to dig into differences between the 2019 and 2022 csproj files.  I don't think there is anything, but we may want to update the C# projects to default to 6.0 starting in 2022, as that's the new default for projects generated by VS itself.

**Comment by Pirulax** [comment]
Hello, whats the status on this?

**Comment by starkos** [comment]
FWIW I’m fine with landing C++ support first, and following up C# later.

**Comment by nickclark2016** [comment]
@starkos sounds good. I've got some time this weekend, so I'll handle getting out v143 toolset and VS2022 action.
