### ISSUE TITLE
Is there a way to create multiple targets per project?

### ISSUE THREAD

**Issue by GasimGasimzada** [premake/premake-core#1676]
_Before asking a new question, please [use the issue search feature](https://github.com/premake/premake-core/issues) to see if your question has already been asked. Help us help you!_

**What's your question?**

Both Visual Studio (haven't tested, just researched) and Xcode have a concept of targets where each project can have more than one target and based on target's configuration, the output target can be anything.

For example, I can create a project that outputs a static library in one target and creates executables for another target with additional flags (e.g generating test coverage data).

Is there a way to make this in premake5?

**Comment by nickclark2016** [comment]
I'm not aware of any way to do that (I don't think you can just use filters, but someone feel free to correct me).  I could see this being useful for writing tests in the same project as the source.

**Comment by GasimGasimzada** [comment]
I believe it can solve two problems with ease. First one if the tests that you mentioned and second one is linking different library targets per project. For example, if you have a library project with two targets ("MyLibrary" and "MyLibrary-Debug"), the consumer project can do something like this:

```lua
filter { "configurations:Debug" }
  links { MyLibrary-Debug }
filter { "configurations:Release" }
  links { MyLibrary }
```

**Comment by nickclark2016** [comment]
If I'm reading this correctly, the second use case is already supported, you just link the project without any suffix.

**Comment by GasimGasimzada** [comment]
I think it works when using gmake as build tool but it doesn't really work in Xcode if the library was built using one configuration. You need to go to project schema in Xcode, change the configuration, and rebuild the library so the Release one gets used. I may be doing something wrong but had the exact same issue when testing adding a `Test` configuration that adds test symbols to all packages. The test application would use the non-test version of library if the library was built using another config (e.g Debug).

**Comment by SySDevel7** [comment]
You can create a project as static library (ex `math-lib`) and another project (ex: `math-exe`) that both has the same files but different configurations. you can add as many projects as you want as targets.

**Comment by GasimGasimzada** [comment]
Is there a way to make both of them share these configurations somehow?

**Comment by starkos** [comment]
> Both Visual Studio (haven't tested, just researched) and Xcode have a concept of targets where each project can have more than one target and based on target's configuration, the output target can be anything.

I'm only familiar with Xcode's approach to targets, and no, Premake currently doesn't support that model. We're always happy to accept community contributions though if someone wants to have a go at it.

> Is there a way to make both of them share these configurations somehow?

See [Sharing Configuration Settings](https://premake.github.io/docs/Sharing-Configuration-Settings/).

Making closed as answered, but feel free to continue the conversation.
