### ISSUE TITLE
Per-file buildoptions on Xcode availability?

### ISSUE THREAD

**Issue by somyungoh** [premake/premake-core#1678]
Hi all,

In fact, there was already an inquiry regarding this 5 years ago - https://github.com/premake/premake-xcode/issues/27, but is it possible or a way to configure a `buildoptions` per-file for `Xcode`? What I would like to do is something like:

```
filter {"action:xcode4", "files:*.c"}
    buildoptions {"foo"}
filter {"action:xcode4", "files:*.cpp"}
    buildoptions {"bar"}
```

cheers,

**Comment by samsinsane** [comment]
The XCode generator hasn't changed much at all in the last 5 years. It gets minor features added from time to time, but largely the same code as it was 5 years ago. My understanding is that it would require a large overhaul of the generator to support per file configurations. So, no it's not possible to do what you're asking unfortunately. We would be more than happy to accept PRs that move the XCode generator towards per-file config support though.

**Comment by starkos** [comment]
@somyungoh You're doing it correctly, so it does look like it isn't yet supported. FWIW, I'm painfully aware of the shortcomings of the current Xcode exporter and working on a new one.

If someone wanted to take this on for v5, you'd [probably want to start here](https://github.com/premake/premake-core/blob/master/modules/xcode/xcode_project.lua#L147-L157). `filecfg.buildoptions` should contain the per-file build options for that build configuration. Then you'd "just" have to figure out what needs to be written to the `.xcodeproj` and get it there.

**Comment by somyungoh** [comment]
I see, thank you for letting me know. I'll see if I can do some workaround for my needs from there.

Thanks,
