### ISSUE TITLE
How to embed resources at build-time?

### ISSUE THREAD

**Issue by mjessome** [premake/premake-core#1679]
**What are you trying to do?**
I'm trying to bundle resources in my application (png, text files). Cross-platform (xcode4, vs2019, gmake2).

**What problem are you having?**
Premake doesn't seem to be doing anything with the resources I'm specifying. When using Embed and Resource, I do not see any of "resources/*.png" moved into (eg.) my `EmbedProject.app/Content/Resources`, nor do I see any extra object files or headers being generated.

Perhaps I've misunderstood the documentation here: https://premake.github.io/docs/buildaction/#examples

**What have you tried so far?**
I have been trying both `buildaction "Embed"` and `buildaction "Resource"`. Here is a stripped-down example:
```lua
workspace "EmbedTest"
    configurations { "Debug", "Release" }
    platforms { "x64" }
    location "generated"
    targetdir "build/%{cfg.buildcfg}"

    project "EmbedProject"
        kind "WindowedApp"
        files {
            "source/*.cpp",
            "resources/**.png",
        }

        filter "files:**.png"
            buildaction "Embed"
```

**What version of Premake are you using?**
5.0.0-alpha16

**Anything else we should know?**
Thank you for the help!

**Comment by samsinsane** [comment]
> Perhaps I've misunderstood the documentation here

Yes, the table is a set of values for C#. You can use `xcodebuildresources` instead, it's an old API that isn't intuitive to use, and there's no documentation on it. However, your above `filter` (both lines) would be this I think:
```lua
xcodebuildresources { ".*%.png" }
```
The pattern matching is done through [Lua patterns](https://www.lua.org/pil/20.2.html) if you need to tweak the above further.

This will also only work on XCode, `gmake`/`gmake2` and VS (C++ projects) don't have a built-in system for copying files to the build directory. For those, you will want to use [custom build commands](https://premake.github.io/docs/Custom-Build-Commands), however, beware that `{COPY}` is a deprecated token and you should use `{COPYFILE}` or `{COPYDIR}` instead.

**Comment by mjessome** [comment]
I'll give the custom build commands a go, thank you for pointing me back in the right direction
