### ISSUE TITLE
vpaths and maintaining partial folder structure

### ISSUE THREAD

**Issue by ngzaharias** [premake/premake-core#1688]
What I'm trying to do
- all files present in "Code/%{prj.name}%/%{prj.name}%/" to be added to the filter "[Source/*]" and maintain any extra folders

Example:
```
-- Windows
premake5.lua -- this is the solution premake

Code/Engine/Engine/premake5.lua -- this is the project premake
Code/Engine/Engine/...
Code/Engine/Engine/GLFW/...
Code/Engine/Engine/Vulkan/...

Code/Game/Game/premake5.lua -- this is the project premake
Code/Game/Game/...
```

Desired Result:
_Notice how the GLFW/Vulkan folders were re-created as sub-filters_
```
-- Engine Project
Source/GLFW/...
Source/Vulkan...
Source/...
-- Game Project
Source/...
```

Actual Result:
_The folders GLFW/Vulkan are not maintained_
```
-- Engine Project
Source/...
-- Game Project
Source/...
```

Attached are the premake5's that currently adds ALL files to Source and trims off any folders.

// Solution
[premake5.txt](https://github.com/premake/premake-core/files/6971981/premake5.txt)
// Engine
[premake5.txt](https://github.com/premake/premake-core/files/6971988/premake5.txt)

**Comment by ngzaharias** [comment]
Attempt #1: Partial Success

My first attempt was to adjust the vpaths to the following...
```
vpaths 
{ 
["Source/*"] = {  
  "Code/Engine/Engine/**.h", 
  "Code/Engine/Engine/**.cpp", 
  "Code/Engine/Engine/**.inl" },
}
```

This works in the solution premake, however placing it inside the PROJECT premake doesn't work.

I don't mind the following at the project level, but I don't want to have such a vpath (where the project name is defined) in the solution premake.

**Comment by ngzaharias** [comment]
### Attempt 2
My second attempt was to use the %{proj.name}% tolken like so...

```
-- Solution Premake
vpaths 
{ 
["/"] = { "**premake5.lua" },
["Source/*"] = {  
  "Code/%{proj.name}%/%{proj.name}%/**.h", 
  "Code/%{proj.name}%/%{proj.name}%/**.cpp", 
  "Code/%{proj.name}%/%{proj.name}%/**.inl" },
}
```

However as specified in the documentation, tolkens don't work with vpaths.

**Comment by samsinsane** [comment]
> This works in the solution premake, however placing it inside the PROJECT premake doesn't work.

Did you change the paths to not include `Code/Engine/Engine`? You have to specify the path relative to the Premake file that it's being called from.

**Comment by ngzaharias** [comment]
> Did you change the paths to not include `Code/Engine/Engine`? You have to specify the path relative to the Premake file that it's being called from.

I'm pretty sure I tried that already but I'll do another attempt tonight and let you know how it goes.

**Comment by ngzaharias** [comment]
Sorry it took so long to respond, that was indeed the issue and it is not working exactly how I had expected it to.

For those curious, the final vpath is 

```
-- Project Premake
vpaths 
{ 
  { ["Source/*"] = {  
	  "Engine/**.h", 
	  "Engine/**.cpp", 
	  "Engine/**.inl" } },
}
```
