### ISSUE TITLE
How to link Google Test with premake?

### ISSUE THREAD

**Issue by rafalmaziejuk** [premake/premake-core#1690]
**What are you trying to do?**
Add Google Test and link it to my project.

**What problem are you having?**
Errors like this unveil:
`D:\dev\sengine\sengine\vendor\gtest\googletest\src\gtest-all.cc(38,10): fatal error C1083: Cannot open include file: 'gtest/gtest.h': No such file or directory`

I don't really know how should I change my script so I can for example include gtest.h like this:
`#include <gtest/gtest.h>`

**What have you tried so far?**
I added gtest as submodule in following directory:
`%{wks.location}/sengine/vendor/gtest`
I have following lua script in gtest directory:

```
project "gtest"
kind "StaticLib"
language "C++"

targetdir ("bin/" .. outputdir .. "/%{prj.name}")
objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

files
{
    "googletest/include/gtest/**.h",
    "googletest/src/gtest-all.cc",
}

filter "system:windows"
    systemversion "latest"
    cppdialect "C++17"
    staticruntime "On"

filter "configurations:Debug"
    runtime "Debug"
    symbols "on"

filter "configurations:Release"
    runtime "Release"
    optimize "on"
```

**What version of Premake are you using?**
premake5

**Comment by nickclark2016** [comment]
Add googletest's include directory as an includedir in the gtest project. 

```lua
includedirs {
    "googletest/include"
}```

**Comment by rafalmaziejuk** [comment]
> Add googletest's include directory as an includedir in the gtest project.
> 
> ```lua
> includedirs {
>     "googletest/include"
> }
> ```

Unfortunately it didn't help either. Moreover, I can only include gtest.h like this `#include <googletest/include/gtest/gtest.h>` and I still don't have access to testing::InitGoogleTest() function.

**Comment by nickclark2016** [comment]
You said the premake file is in the gtest directory, correct? If so, you should be making the file paths relative to the premake file.  I've got a build that looks like this:

```lua
project("googletest")
    kind("StaticLib")
    language("C++")
    cppdialect("C++17")

    targetdir(binaries)
    objdir(intermediate)

    files({
        "include/**.h",
        "src/**.cc",
    })

    includedirs({
        "include/",
        "."
    })
```
That script is placed at the root of the googletest directory.
