### ISSUE TITLE
Using "debugargs" correctly and passing command line arguments to the exe

### ISSUE THREAD

**Issue by GCourtney27** [premake/premake-core#1691]
The documentation says this list is passed to the application by the debugger. However, when I launch the application nothing is included in the command line from main(). Am I misusing this premake token? If so is there any way to pass arguments to the exe and populate the "Command Arguments" field in "Configuration Properties/Debugging/"in the project properties window?

**Comment by samsinsane** [comment]
You haven't specified a language or version of VS, but I'll assume you're talking about C/C++ VS2010+ projects. Here's the code that outputs the value into the vcxproj.user file:
https://github.com/premake/premake-core/blob/65deb619f8d5579487def157d7c369e5c6d18864/modules/vstudio/vs2010_vcxproj_user.lua#L114-L119

There's a few things could be:
- You have a `filter` set that prevents `debugargs` from being set for your VS projects (putting `filter {}` before calling `debugargs` can confirm this)
- The version of VS that you're using doesn't use that tag name anymore and we need to update (you'd have to manually set the args to something, save the project and the find what the new tag is called)
- Newer versions of VS have been moving certain settings into the `.vs` folder which Premake doesn't generate, this could be one of them and you may need to delete that folder before you'll see the setting updated in the UI. `startproject` has this issue.

If it's none of these, then I'm really not sure what it could be.

**Comment by GCourtney27** [comment]
I'm using C++ with VS 2019, sorry I should have specified that. I cleaned all of the project files and deleted the `.vs` folder and now it's working. I thought the command line args would have been stored in the `.vcxproj` but they are actually stored in the `.vcxproj.user` file. It says something similar in the documentation but I guess I misread it. 
I'll mark this as closed as it appears to be fixed now. If anyone else stumbles upon this and is having a similar issue just clear out all of the Visual Studio Project files and delete `.vs` as well, that should fix it. Thanks!
