### ISSUE TITLE
Add support for MSVC external includes

### ISSUE THREAD

**Issue by StellaASchlotter** [premake/premake-core#1692]
**What problem will this solve?**
premake has support for sysincludedirs for a long time. It works great for clang and gcc in my experience. However for visual studio the directories in sysincludedirs are threated as normal includes. This leads to warning generation in those includes. It's annoying if you want to use the FatalWarnings flag that premake provides.

**What might be a solution?**
Visual Studio has support for external includes since Visual Studio 2017 version 15.6 Preview 1: https://devblogs.microsoft.com/cppblog/broken-warnings-theory/

But premake has no support for it yet. Is it possible to add this feature? If you can point me to the right direction I can implement it myself.

**What other alternatives have you already considered?**
You can work around the missing support by using:
`buildoptions {"/experimental:external  /external:W0"}`
`buildoptions {"/external:I <include path>"}`

The downside of this approach is that the result is not clearly visible in the project settings inside visual studio. It does not show up as  external includes:
![external1](https://user-images.githubusercontent.com/1640597/130181786-6ca8358c-1fc0-4eba-a132-7002a5d91175.png)
but you can see them in the additional options:
![external2](https://user-images.githubusercontent.com/1640597/130181799-b4becae4-183f-4378-9458-a0e2cc1840d2.png)

**Comment by starkos** [comment]
>  If you can point me to the right direction I can implement it myself.

You should be able to search the code for "sysincludedirs" and just copy-paste-refactor to the correct Visual Studio element. Feel free to reach out here if you have questions. I look forward to merging it! :)

**Comment by StellaASchlotter** [comment]
@starkos i would appreciate some early feedback on https://github.com/premake/premake-core/pull/1701

It is still missing some tests. Especially for earlier versions of visual studio.
