### ISSUE TITLE
Is gcc.gettoolname function broken ?

### ISSUE THREAD

**Issue by jimon** [premake/premake-core#170]
I'm looking here https://github.com/premake/premake-core/blob/master/src/tools/gcc.lua#L355 and don't quite understand .. is it supposed to work ?

I understand part about gccprefix, but premake doesn't provide default gccprefix (empty line), so if I just pass cfg there it will return nil to me (at least on linux).

**Comment by jimon** [comment]
if not cfg.gccprefix then cfg.gccprefix = "" end

Fixes it, but not sure if it's correct or not.

**Comment by starkos** [comment]
If would be helpful to see what you're trying to do.

```lua
name = (cfg.gccprefix or "") .. gcc.tools[tool]
```

`(cfg.gccprefix or "")` means use `cfg.gccprefix` if set and an empty string otherwise. So Premake is in fact providing a default gccprefix?

**Comment by jimon** [comment]
I'm just trying to get gcc executable names : https://github.com/jimon/premake-ninja/blob/master/ninja.lua#L111

> (cfg.gccprefix or "") means use cfg.gccprefix if set and an empty string otherwise

Yes, but this branch will not be executed unless cfg.gccprefix not nil or tool name is "rc".

**Comment by starkos** [comment]
Hey @TurkeyMan, can you take a look at this? I think @jimon might have a point, but I'm not sure why you structured the conditional that way?

**Comment by TurkeyMan** [comment]
Yeah, no problem.
Which big of the logic is not making sense? I think no-prefix is the proper default...
I remember when I touched that code I felt it was already a bit mysterious, and I wasn't sure it was quite right.

**Comment by TurkeyMan** [comment]
I see what's happened... I just stuffed it up it seems >_<
Amazed no tests caught that! I'll add some this time.
It's weird, I have projects that use this (from my own build), I'm not sure how they work... I might have messed up a commit actually, it just doesn't look right.

**Comment by TurkeyMan** [comment]
It's baffling. The code makes no sense. I must have messed up a rebase, and the tests didn't complain it, so I commit. I made these changes in a fork somewhere else.
Sorry! :)

**Comment by TurkeyMan** [comment]
Fixed in #177
