### ISSUE TITLE
Debugdir doesn't work on Xcode 12.5

### ISSUE THREAD

**Issue by James51332** [premake/premake-core#1703]
When I set a project to use the debugdir option, it doesn't affect the project for Xcode 12.5. I have tried to use an absolute path and a relative path but nothing works. I'm using premake 5.0.0-alpha15.

**Comment by starkos** [comment]
Just did a quick search of the source code and it looks like `debugdir()` hasn't been ported to Xcode yet. We're working on improving that, and the documentation of what's supported and not—community assistance is appreciated!

Marking this as closed as answered; feel free to continue the conversation if you have questions though.

(Also, in the future, please help us help you and fill in the template we provide when filing issues. Thanks!)
