### ISSUE TITLE
`propertydefinition` consistency

### ISSUE THREAD

**Issue by Jarod42** [premake/premake-core#1705]
Working to implement/fix (missing) Custom rules for some generators.

I saw in https://premake.github.io/docs/propertydefinition/

> separator
For list properties, this sets the value of the list item separator in the command line.
> - gmake2: Default value is ' '. If a switch is set, the separator is ignored and instead the switch is duplicated.
> - VS201x: If set, the list is concatenated by the separator and placed behind a single switch. If not set, the switch is duplicated.

I don't see a reasons to have different behaviors, one seems sufficient:

if `separator` is provided (and different than `" "`?), use `switch value1 separator value2 .. separator valueN`
else use `switch value1 switch value2 .. switch valueN`.

I ask because I want to move specific rule code (linked to token replacement) from gmake2 into rule.lua to allow reuse in some generators (and also because it is not the job of (each) generator to do that internal logic).

Did I miss something?
Any objection I uniformize logic?

**Comment by starkos** [comment]
I agree with you on this one. We should present a consistent convention and handle any necessary translations under the hood.
