### ISSUE TITLE
Is there a way to set specific custom properties for VS2019?

### ISSUE THREAD

**Issue by GasimGasimzada** [premake/premake-core#1738]
_Before opening a new issue, please [use the issue search feature](https://github.com/premake/premake-core/issues) to see if a similar issue already exists. If not, please help us help you by filling in the template below._

**What are you trying to do?**

I am trying to add some custom project properties to VS2019 project, namely `EnableMicrosoftCodeAnalysis` and `EnableClangTidyCodeAnalysis` (excerpt form modified VS2019 project):

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <EnableMicrosoftCodeAnalysis>false</EnableMicrosoftCodeAnalysis>
    <EnableClangTidyCodeAnalysis>true</EnableClangTidyCodeAnalysis>
</PropertyGroup>
```

**What problem are you having?**

I can't find an option to set custom properties for VS project through Premake5.

**What version of Premake are you using?**

5.0.0-alpha16

**Anything else we should know?**

I already use the `xcodebuildsettings` to set properties that are only specific to Xcode and it would be nice to be able to set custom values for VS2019 (or any other project for that matter as well) if it does not exist at the moment.

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

**Comment by nickclark2016** [comment]
I don't believe that there is currently a way to do this built directly into the API.  This may be something worth us looking into.

**Comment by starkos** [comment]
Confirm that there is no way to do that currently. Adding a new API is really quite simple but I just realized that the process doesn't seem to be fully documented anywhere—putting on my to-do list.

Marking closed as answered for now; feel free to continue the conversation if you still have questions though.
