### ISSUE TITLE
cppdialect c++20 outputs c++latest on VS2019

### ISSUE THREAD

**Issue by englercj** [premake/premake-core#1746]
I use cppdialect "C++20" currently, which resolves to `/std:c++latest` but in my version of vs2019 I want it to resolve to `/std:c++20`.

Imported from this comment: https://github.com/premake/premake-core/issues/971#issuecomment-962028454

**Comment by nickclark2016** [comment]
Agreed. I think this makes more sense than the current mapping. Looking at the git history, it appears that is a remnant of the old behavior doing that for previous versions of C++.

**Comment by samsinsane** [comment]
@nickclark2016 the mapping made sense at the time because there wasn't a `/std:c++20` until VS2019 16.11 which came out ~3 months ago, see [here](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-160).
> The `/std:c++20` option enables C++20 standard-specific features and behavior. Available starting in Visual Studio 2019 version 16.11

**Comment by nickclark2016** [comment]
> 
> 
> @nickclark2016 the mapping made sense at the time because there wasn't a `/std:c++20` until VS2019 16.11 which came out ~3 months ago, see [here](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-160).
> 
> > The `/std:c++20` option enables C++20 standard-specific features and behavior. Available starting in Visual Studio 2019 version 16.11

True, I forgot about that.  I do recall 17 being mapped to latest for a while.
