### ISSUE TITLE
Dates in docs aren't localised

### ISSUE THREAD

**Issue by samsinsane** [premake/premake-core#1748]
**What seems to be the problem?**
Date formats in the docs aren't localised based on the users browser settings, and don't indicate they're hardcoded to the US locale.

**What did you expect to happen?**
I expected my locale to be used, it's literally less effort, just don't specify a locale. Alternatively, ISO 8601 would be fine.

**What have you tried so far?**
Tried another browser to confirm that the locale support in my primary browser wasn't broken or wrong.

**How can we reproduce this?**
Change your language in your browser from "English" or "English (US)" to "English (Australia)" or "English (UK)".

**What version of Premake are you using?**
N/A.

**Anything else we should know?**
I couldn't find anything in the Docusaurus config file to indicate that we set this, so it looks like Docusaurus unnecessarily hardcodes a locale.

**Comment by KyrietS** [comment]
Yes, all the pages powered by Docusaurus seem to use the `mm/dd/yyyy` format. I'll try to find a way to override that. By the way, there is a proposed feature for Docusaurus (https://github.com/facebook/docusaurus/issues/3592) for adding an API to configure metadata of a page.
