### ISSUE TITLE
CodeLite and Pre-Compiled Headers

### ISSUE THREAD

**Issue by shadoww1028** [premake/premake-core#1767]
Using the latest version of premake5  (the Beta 1) I wanted to try PCH files in code lite as it looks like it was fixed and it does indeed work but the PCH compile flags policy is set to replace.  Since it is set to replace there are no compile flags passed in causing compile errors later on.  For example if you use --std=c++17 for the project and build options for the target since this would not be used for the PCH file there would be an error later on stating that this flag was not used to compile the PCH file.

**Comment by shadoww1028** [comment]
Looks like Code Lite chagned the value from UseDifferentPCHFlags to PCHFlagsPolicy which is an enumeration.  When code lite loads the new project file it converts it to the new value in correctly.  Reported it to code.

**Comment by Jarod42** [comment]
I will look at it.
