### ISSUE TITLE
premake5 doesn't work on windows server 2019?

### ISSUE THREAD

**Issue by Dmitry1987** [premake/premake-core#1772]
Is it compatible with 2019? Maybe I can install some SDK or something to make it work?

**What are you trying to do?**
run on windows 2019 in aws 

**What problem are you having?**
error
```
dep\bin\premake5.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

**Anything else we should know?**
![image](https://user-images.githubusercontent.com/9369080/145205263-5eef6829-0e79-45cc-9de7-8fb4c724cd93.png)

**Comment by nickclark2016** [comment]
Apologies to the late follow up.  Have you tried running the compatibility troubleshooter, and if so, what output is it providing?

**Comment by nickclark2016** [comment]
I wanted to follow up on this and see if you're still having issues with Window Server 2019 Datacenter @Dmitry1987

**Comment by Dmitry1987** [comment]
hi, we built from source and it worked, thanks.
