### ISSUE TITLE
How to link static library use link() function(-Wl,-Bstatic)

### ISSUE THREAD

**Issue by lailongwei** [premake/premake-core#1775]
As title, How to link static library use link() function(-Wl,-Bstatic). Thanks

**Comment by lailongwei** [comment]
I found it, use ':static' suffix in you want to link library name.
I suggess this question keep opening to make more developers found.

**Comment by Jarod42** [comment]
Better would be to update doc https://premake.github.io/docs/links/ to add that info.

**Comment by samsinsane** [comment]
I'm going to close this as #1818 covers updating the docs.
