### ISSUE TITLE
Upgrade DocSearch To Algolia

### ISSUE THREAD

**Issue by starkos** [premake/premake-core#1776]
**What seems to be the problem?**

[DocSearch v3 requires a migration](https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration) to  [Algolia Crawler](https://www.algolia.com/products/search-and-discovery/crawler/). I've received an email indicating that legacy DocSearch crawling will be disabled sometime around Mar 1 2022. There are steps required for migration:

- [x] Create an Algolia account
- [x] Register an "Algolia Application"
- [x] Update the DocSearch frontend integration with new keys

**What did you expect to happen?**

Someone else would do this for me. ;)

**What have you tried so far?**

n/a

**How can we reproduce this?**

n/a

**What version of Premake are you using?**

n/a

**Anything else we should know?**

I'm taking care of this; logging it here for visibility and feedback if needed.

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

**Comment by KyrietS** [comment]
Would you like to add me as a team member to your "Algolia Applcation"? It's not essential so it's up to you 😉 

* Instruction [LINK](https://support.algolia.com/hc/en-us/articles/4406981838737-How-do-I-give-team-members-access-to-my-Algolia-apps-and-manage-their-authorizations-)
* Algolia Organization Settings [LINK](https://www.algolia.com/account/overview)
* Use my e-mail address from GitHub.

**Comment by starkos** [comment]
Finally getting to this…it looks like you need to have an account with Algolia first. I'm getting a "not found" when I try to add you via email address?

**Comment by KyrietS** [comment]
That's weird, because I already have an account for a week 😕

![image](https://user-images.githubusercontent.com/19170699/146649799-a33fde90-d4e2-476f-bdb9-3d36d1cfcc06.png)

Please try again and if it doesn't work, I will write a request to Algolia to check what is wrong

**Comment by starkos** [comment]
@KyrietS I responded to you directly.
