### ISSUE TITLE
project generation fails with "Error: attempt to index a function value"

### ISSUE THREAD

**Issue by somyungoh** [premake/premake-core#1795]
**What seems to be the problem?**
Premake5 raises an error during any project generation:
```
Building configurations...
Error: attempt to index a function value
stack traceback:
        [string "src/base/api.lua"]:309: in field 'checkValue'
        [string "src/base/oven.lua"]:255: in local 'base'
        (...tail calls...)
        [string "src/base/oven.lua"]:197: in field 'bakeConfigs'
        [string "src/base/oven.lua"]:44: in field 'bake'
        [string "src/base/container.lua"]:61: in field 'bake'
        [string "src/base/container.lua"]:69: in field 'bakeChildren'
        [string "src/base/global.lua"]:8: in field 'bake'
        [string "src/base/container.lua"]:61: in field 'bake'
        [string "src/base/oven.lua"]:12: in field 'bake'
        [string "src/_premake_main.lua"]:163: in field '?'
        [string "src/base/_foundation.lua"]:62: in function 'premake.callArray'
        [string "src/_premake_main.lua"]:225: in function '_premake_main'
```

**What version of Premake are you using?**
premake 5.0-alpha16

**Anything else we should know?**
Digging into the code, I've noticed that in the file `api.lua`, a `function` type is passed to `ipairs()` which is not allowed:
```lua
-- api.lua, line 661

if not canonical then
    for _, allow in ipairs(field.allowed)       <---------- here
        do
            if type(allow) == "function" then
            ...
```

I did a small patch myself, I'll create a PR that should fix this.

**Comment by nickclark2016** [comment]
Have you verified that this is an issue with the beta-1 build? Also, what in your build script is causing the issue?  I want to isolate the cause before we dive headfirst into fixing it.

**Comment by Jarod42** [comment]
From the above code, `field.allowed` might be a `function` (and from assignment, it happens for `toolset` and `uuid`).

As I understand, invalid values for those api would trigger internal lua error instead of displaying the friendly Premake error message.
