### ISSUE TITLE
C++17 ConsoleApp builds as DLL

### ISSUE THREAD

**Issue by ZENX0x2** [premake/premake-core#1797]
I'm trying to build a C++17 console application as a exe,

But it builds as a DLL/Dynamic Link Library instead.

I'm using Premake 5.0-beta1, Visual Studio 2019 16.11.8, Windows SDK 10.0.16299.0.

Here's the "Kind" snippet:

`kind "ConsoleApp"`

**Comment by nickclark2016** [comment]
Can you provide more of the premake script? I cannot reproduce this with the build you provided.

**Comment by ZENX0x2** [comment]
I fixed it 😅The issue wasn't anything to do with the "ConsoleApp" part, it was actually me just forgetting to add a include directory. Now I feel utterly stupid.

**Comment by nickclark2016** [comment]
No worries. Glad it's resolved!
