### ISSUE TITLE
setting a dialect for C language does not work for Visual Studio projects

### ISSUE THREAD

**Issue by koocur** [premake/premake-core#1799]
**What seems to be the problem?**
I am trying to generate a C project with C11 dialect for Visual Studio. When opening the project settings in VS , "C Language Standard" always defaults to "Default (Legacy MSVC)" instead of the desired dialect.

**What did you expect to happen?**
I expected to see the "C Language Standard" project option set to "ISO C11 Standard (/std:c11)"

**What have you tried so far?**
I have used this code. Tried it for both VS 2019 and 2022. 
```
-- PROJECT: SANDBOX

project "TEST_sandbox"
	location "TEST_sandbox"
	kind	"ConsoleApp" 
	language "C"
	cdialect "C11"
```

**What version of Premake are you using?**
**v5.0.0-beta1**

**Comment by alex-rass-88** [comment]
Use premake from master.

**Comment by samsinsane** [comment]
I'm going to close this as resolved, `cdialect` support was added to the VS module after the release of beta1.
