### ISSUE TITLE
C and C++ dependency rules should include system headers

### ISSUE THREAD

**Issue by IanCollins** [premake/premake-core#1801]
The compiler options emitted in gcc.getcppflags() in /src/tools/gcc.lua should include -MD rather than -MMD.  The former excludes system files which can result in bad builds or a puzzling lack of rebuilds if something deemed to be a system include changes.
 
We discovered this issue when changes to an external project (where sysincludedirs is used for its headers) were not triggering rebuilds.

System include files should be in the generated dependency files.

**Comment by samsinsane** [comment]
That's pretty strange, I'm not sure why Premake ended up using `-MMD` over `-MD`. If you'd like to submit a PR to fix this, the line is [here](https://github.com/premake/premake-core/blob/9d38e82f7bb409d1068fc5adaa21c9175b7dd04b/src/tools/gcc.lua#L24).

**Comment by nickclark2016** [comment]
Just to follow on to this, should this be an API? Is there an equivalent for MSVC or Xcode?

**Comment by LoneBoco** [comment]
The MSVC equivalent is probably the `/showIncludes` flag.  The usage seems to mainly involve around tooling support for things like incremental linking where you detect just which object files need to be recompiled.  Here is a Mozilla bug where they implemented support in their Python build system for building a dependency list for GNU make:  https://bugzilla.mozilla.org/show_bug.cgi?id=518136

**Comment by nickclark2016** [comment]
So I'm looking into this now. It appears that `/showIncludes` does not provide the same functionality as `-MMD`, as `/showIncludes` does not create a dependency file.

**Comment by samsinsane** [comment]
I don't think there's any ramifications to changing it, projects will just be rebuilt when devs update their packages whereas before it probably fell over or created very obscure bugs?

**Comment by nickclark2016** [comment]
I'll have a fix and some tests out in a few hours.
