### ISSUE TITLE
The premake Windows executable does not install on Windows 10

### ISSUE THREAD

**Issue by ncottrill** [premake/premake-core#1808]
**What seems to be the problem?**
Premake will not install on Windows 10 machine.

**What did you expect to happen?**
I expected the premake5.exe file to install premake on my machine.

**What have you tried so far?**
I downloaded the zipped Windows executable for premake from this link https://github.com/premake/premake-core/releases/download/v5.0.0-beta1/premake-5.0.0-beta1-windows.zip. 

I unzipped the directory. Inside was premake5.exe. I doubled clicked the premake5.exe from the unzipped directory. Nothing happened. Premake would not install.

I then downloaded the source code from GitHub, opened the Visual Studio 2019 .sln file from the \build\*2019 directory and built the code within that project. There was an executable created. I double-clicked that executable and nothing happened. The Premake executable that I built in Visual Studio would not install, either.

Finally, I tried running both executables as administrator and still Premake would not install.

**How can we reproduce this?**
Download premake5.exe from the website linked above. Try to install it on a Windows 10 machine.

**What version of Premake are you using?**
I can't get it to install, so I am using no version.

**Anything else we should know?**

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

**Comment by nickclark2016** [comment]
Hi @ncottrill. The `premake5.exe` executable is not an installer, but a standalone application.  In order to run it, use a command line and try running:

```sh
premake5.exe --version
```

**Comment by nickclark2016** [comment]
I just wanted to follow up on this. Does this answer your question?

**Comment by ncottrill** [comment]
I watched this video https://www.youtube.com/watch?v=bxov_ZhJoG4 that explained a way to use premake that worked for me. It was round about, but I eventually "got there."

It would be nice to have more instructions on how to use premake on the website. 

Thank you for replying.
