### ISSUE TITLE
Select Platform with Command-Line Argument?

### ISSUE THREAD

**Issue by TheEmeraldFalcon** [premake/premake-core#1813]
**What's your question?**
I would like to know how I can select the platform from the command line.

**Anything else we should know?**
The docs say that it appears in the IDE, but I don't use an IDE, I compile from the command line.
I have the platforms { "windows", "linux" } and whatnot, I just don't know how this is selected when building.

**Comment by nickclark2016** [comment]
What build tool are you using?

**Comment by Jarod42** [comment]
If you type `make help`, you should have list of configurations (which contains platform too).

so, something like:

```
make config=release_windows all
make config=debug_linux clean
```

**Comment by Jarod42** [comment]
@starkos: `make help` still refer to old wiki BTW.

**Comment by nickclark2016** [comment]
> If you type `make help`, you should have list of configurations (which contains platform too).
> 
> so, something like:
> 
> ```
> make config=release_windows all
> make config=debug_linux clean
> ```

Just realized, we'll need this for

**Comment by nickclark2016** [comment]
Wrong button. Did not mean to close.

**Comment by TheEmeraldFalcon** [comment]
Ah so it is a Make thing, that helps, thank you!

**Comment by nickclark2016** [comment]
If you ever need to see all the configurations generated by premake, just run that command.  Closing this since answered :)
