### ISSUE TITLE
Are the optimize flag for msvc right?

### ISSUE THREAD

**Issue by monamimani** [premake/premake-core#1814]
I was looking at the difference between optimize "Full" and optimize "speed"

It seems from the msvc doc the full optimization is actually /O2 and /Ox is only most optimization which could correspond to the "speed" value

[/Ox](https://docs.microsoft.com/en-us/cpp/build/reference/ox-full-optimization?redirectedfrom=MSDN&view=msvc-170)
From the link above:
`The /Ox compiler option enables a combination of optimizations that favor speed. In some versions of the Visual Studio IDE and the compiler help message, it's called full optimization, but the /Ox compiler option enables only a subset of the speed optimization options enabled by /O2.`

[/O2](https://docs.microsoft.com/en-us/cpp/build/reference/o1-o2-minimize-size-maximize-speed?redirectedfrom=MSDN&view=msvc-170)

And a stackoverflow that show the difference in flags
[stackoverflow](https://stackoverflow.com/questions/5063334/what-is-the-difference-between-the-ox-and-o2-compiler-options)

**Comment by nickclark2016** [comment]
Could you link the code you are looking at?  Per the MSVC documentation, we have:

```
O1 - Minimize Size
O2 - Maximize Speed
Od - No Optimization
Ox - Enabled most speed optimizations, Visual Studio calls it full optimization.
```

Looking [here](https://github.com/premake/premake-core/blob/9d38e82f7bb409d1068fc5adaa21c9175b7dd04b/src/tools/msc.lua#L75) at the code, the definitions provided by MSVC match the configuration outputted by Premake.

That said, you should generally favor `O2` to `Ox` per Microsoft compiler developers.

**Comment by monamimani** [comment]
> That said, you should generally favor O2 to Ox per Microsoft compiler developers.

That is my point from premake doc you get the sense that to get the most optimized code you would use Full. Even the table in the optimize doc seems to imply a progression of optimization. But Speed is more optimized than Full.

That is also error prone, you wouldn't know unless you go look into the code what each flags does for each compiler.

**Comment by nickclark2016** [comment]
If we make a change, I'd argue that we set both to `O2` rather than use `Ox`.  @starkos thoughts?

**Comment by monamimani** [comment]
> I guess it would depend on the context you view it in? In the context of MSVC this doesn't make sense as Debug is /Od which is the same as Off. Similarly, Speed isn't a progression from Size - they're different optimization targets. 
I understand that. What I understood from MSVC flags was /Ox is make it as fast as you can to the detriment of size and that /O2 was the recommended one giving a balance of size and speed which can lead to better optimized code ( depending on caches etc...). But that intuition could be out of date.

> I believe this is an important note to consider when suggesting that mappings change. While they both might be "more" optimized than Full, neither is considered to have "strict language conformance" based on that comment.
While it is sad that it could affect language conformance, /O2 is the default when you create a new project.

There is the case also that it should be homogeneous with other compiler. Selecting Speed would give the best optimization on both but selecting Full optimization would not.

@samsinsane I agree with you it is confusing both ways.

I guess, what need to be done is either
1. figure out a way to tell in the doc that the default optimize flag should be "Speed" or saying that the one that enables the most optimization opportunities is Speed as msvc, GCC and clang will use O2
2. figure out a way to say that Full is probably not what you want and that it is not enabling all optimization on all platform.
3. Changing the meaning of the code, that would be a braking change. I don't know how those changes are handled here.

@samsinsane You also made me realized that the On value is also wrong. If it intended to be the default then it should be MaxSpeed.

Here, the issue is really the confusion names that MSVC ended up with ( most likely for historical reasons)

I am also confused by the 2 files you both referenced. ( I am not that familiar with the code base) in [msc.lua](https://github.com/premake/premake-core/blob/9d38e82f7bb409d1068fc5adaa21c9175b7dd04b/src/tools/msc.lua#L75) we have On as "/Ot" but in [vs2010_vcxproj.lua](https://github.com/premake/premake-core/blob/9d38e82f7bb409d1068fc5adaa21c9175b7dd04b/modules/vstudio/vs2010_vcxproj.lua#L2404-L2410) we have On as "Full"

**Comment by samsinsane** [comment]
Our docs already point out that `Speed` is best for performance. Similarly, `On` is not intended to be the default, it's intended to be "a balanced set of optimizations."

> I am also confused by the 2 files you both referenced. ( I am not that familiar with the code base) in [msc.lua](https://github.com/premake/premake-core/blob/9d38e82f7bb409d1068fc5adaa21c9175b7dd04b/src/tools/msc.lua#L75) we have On as "/Ot" but in [vs2010_vcxproj.lua](https://github.com/premake/premake-core/blob/9d38e82f7bb409d1068fc5adaa21c9175b7dd04b/modules/vstudio/vs2010_vcxproj.lua#L2404-L2410) we have On as "Full"

VS doesn't provide a mapping for `/Ot` which is probably why it uses `Full` instead.

---

I'm going to close this issue as the discussion seems like it's going to start going in circles and I don't think there's anything for us to do here. "Full" should not be "Speed" due to the conformance concern mentioned above. Similarly, "Speed" is not enabling _all_ optimisations, it's just enabling all of the speed-related optimisations, it doesn't enable all the size-related optimisations.
