### ISSUE TITLE
`:static` and `:shared` specifiers for `links` are not documented

### ISSUE THREAD

**Issue by KyrietS** [premake/premake-core#1818]
When linking to a library you can specify additional decorators:

```lua
links { "some_syslib:static" }
links { "some_syslib:shared" }
```

It works only for GCC compiler. This feature was introduced in [5.0-alpha11](https://github.com/premake/premake-core/releases/tag/v5.0.0-alpha11) and is implemented here: https://github.com/premake/premake-core/blob/master/src/tools/gcc.lua#L571 

As pointed out in the discussion https://github.com/premake/premake-core/discussions/1817 it should be documented.

Suggested locations where documentation can be extended:
* https://premake.github.io/docs/Linking/
* https://premake.github.io/docs/links/

**Comment by nickclark2016** [comment]
Since Clang relies pretty heavily on GCC, do we know if Clang supports this as well?

**Comment by KyrietS** [comment]
I'm not the one who knows the answer 😄
I have no experience with Clang ._.

**Comment by nickclark2016** [comment]
As part of this, we should probably investigate the clang and msvc generators.
