### ISSUE TITLE
Windows pipeline upgrade to `windows-2022`

### ISSUE THREAD

**Issue by KyrietS** [premake/premake-core#1819]
Windows pipeline is failing. These lines seem to be a problem:

```yaml
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        nmake -f Bootstrap.mak MSDEV=vs2019 windows-msbuild PLATFORM=${{ matrix.platform }} CONFIG=${{ matrix.config }}
```

Recently, GitHub updated the software on their Windows virtual machines and Visual Studio cannot be found under the given path.

Currently, Visual Studio path is:

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise
```
According to [Windows2022-Readme](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022)

## Solution

Instead of hardcoding the path to the `vcvarsall.bat` script again, I suggest using the `vswhere.exe` program, which is [available globally](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#tools) on the machine running the pipeline.

For example, the following running of the `vswhere.exe` program:

```
vswhere.exe -find VC\Auxiliary\Build\vcvarsall.bat
```

should print the following result:

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
```

Which is exactly what we are looking for. But...
Unfortunately, I don't know how to run a bat script whose path is printed by another command. It would be easier in PowerShell, but our stage uses legacy cmd.exe. Maybe it's time for a change?

**Comment by samsinsane** [comment]
Weird, their docs still say `windows-2019` is the latest. For a quick fix, you can change `windows-latest` to `windows-2019` and it should all build again, and we can use this issue to discuss moving to `windows-2022` or back to `windows-latest`.

> It would be easier in PowerShell, but our stage uses legacy cmd.exe. Maybe it's time for a change?

If I set this up, there were issues running some of the commands in Powershell but I can't recall what or if it was actually this project.

**Comment by Jarod42** [comment]
> Unfortunately, I don't know how to run a bat script whose path is printed by another command.

@KyrietS: 

From https://superuser.com/questions/1020368/how-do-i-run-a-command-that-uses-the-result-of-a-nested-command-on-microsofts-w
it would be
```
FOR /F "usebackq" %P in (`vswhere.exe -find "VC\Auxiliary\Build\vcvarsall.bat"`) DO "%~P\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
```
But I didn't succeed to do it inside github action...

**Comment by KyrietS** [comment]
I saw those hacks with loops. I didn't like them. I managed to mix PowerShell with cmd.exe and it worked. See #1821

**Comment by Jarod42** [comment]
@KyrietS : thanks, I used your patch to build premake for premake-sample-projects :-)
