### ISSUE TITLE
[Visual Studio] Add /LTCG flag via premake

### ISSUE THREAD

**Issue by mrgoldengun** [premake/premake-core#1835]
### Discussed in https://github.com/premake/premake-core/discussions/1832

<div type='discussions-op-text'>

<sup>Originally posted by **mrgoldengun** March  4, 2022</sup>
Hello,

I have a question about ```flags { "LinkTimeOptimization" }```
When I turned on this flag, the Visual Studio add ```/GL``` (Whole Program Optimization) and ```/LTCG:incremental``` (Link Time Code Generation). How can I config ```/GL``` and ```/LTCG``` (without incremental) via premake? AFAIK, It seems we don't have an option to do that in premake.

If I understand correctly, ```/LTCG``` is different from ```/LTCG:incremental```
https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=msvc-170</div>

**Comment by agreppin** [comment]
a workaround is to remove that flags and add:
```
buildoptions { "/GL" }
linkoptions { "/LTCG" }
```
