### ISSUE TITLE
how to convert cmake for premake? 

### ISSUE THREAD

**Issue by one2world** [premake/premake-core#1838]
_Before asking a new question, please [use the issue search feature](https://github.com/premake/premake-core/issues) to see if your question has already been asked. Help us help you!_

**What's your question?**
A short, concise question for the community. To get the best answers, be clear about what you're asking, what kind of responses you hope to receive, and how you intend to use the information.

**Anything else we should know?**
Add any other background or context about your question here.

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to questions like these!)*

**Comment by samsinsane** [comment]
Closing this as you haven't filled out the template and I can't really tell what you're asking from the title alone.
