### ISSUE TITLE
externalincludedirs, externalwarnings, externalanglebrackets gives error

### ISSUE THREAD

**Issue by jacknicklenson** [premake/premake-core#1848]
**What are you trying to do?**
adding
```
  externalincludedirs { "dep/**" }
  externalwarnings "Off"
  externalanglebrackets "On"
```
options into the build script.

**What problem are you having?**
Premake is crashing with this error message:  Error: /home/cx/Documents/Github/cgrf/premake5.lua:16: attempt to call a nil value (global 'externalincludedirs')

**What have you tried so far?**
without these options, it works but with these options it gives error.
if i comment out `externalincludedirs`, this time it gives same error with `externalwarnings` and if comment out first two, this time it gives error with the last one which is `externalanglebrackets` one.

**What version of Premake are you using?**
`premake5 (Premake Build Script Generator) 5.0.0-beta1`

**Anything else we should know?**
here is the script
```lua
workspace "cgrf"
  configurations { "Debug", "Release" }
  platforms { "x64" }
  location "build"

project "cgrf"
  kind "ConsoleApp"
  language "C"
  cdialect "C99"
  warnings "Extra"
  targetname "cgrf"
  targetdir "build"

  buildoptions { "-pedantic" }
  includedirs { "src", "dep" }
  externalincludedirs "dep/**"
  externalwarnings "Off"
  externalanglebrackets "On"

  if os.host() == "windows" then
    links { "glfw3", "opengl32" }
  elseif os.host() == "linux" then
    links { "glfw", "GL", "m" }
  end

  files { "src/**.c", "dep/**.c" }

  filter "configurations:Debug"
    defines { "DEBUG" }
    symbols "On"

  filter "configurations:Release"
    defines { "NDEBUG" }
    optimize "On"
```

**Comment by samsinsane** [comment]
Beta1 was released before these new APIs were merged, you'll need to use a master build.

**Comment by jacknicklenson** [comment]
Okay thx.
