### ISSUE TITLE
Error: no such action 'premake5.lua'

### ISSUE THREAD

**Issue by bogez57** [premake/premake-core#1853]
I'm using premake 5.0.0 beta1. I'm trying to have premake run my premake5.lua file from the cmd line like so:

`g:/my_project/premake5.exe premake5.lua`

 and I just get the response:

`'Error: no such action 'premake5.lua'`

I've also tried

`g:/my_project/premake5.exe --file=premake5.lua`

to no avail. What am I doing wrong?

**Comment by nickclark2016** [comment]
You're not specifying an action. Try specifying `gmake2`, `vs2019`, `xcode` or whatever you're aiming to target.

**Comment by bogez57** [comment]
Awesome, thank you
