### ISSUE TITLE
Cannot configure VS2022 C++ include directories properly (W10)

### ISSUE THREAD

**Issue by smartskaft2** [premake/premake-core#1854]
**What are you trying to do?**
Setting up a Premake project for VS2022, with a non-flat file/folder hierarchy.

**What problem are you having?**
The generated VS2022 project does not have the expected include directories configured.

**What have you tried so far?**
I've re-read the Premake documentation, focusing on `files` and `includedirs`. I've tried any combination of wildcards (`*`/`**`) and different directory depths (e.g. `includedirs { ../src/*, ../src/** }` ), with and without file extensions (for `files`).

**What version of Premake are you using?**
5.0.0-beta1

**Anything else we should know?**
I have setup a GitHub repo to reproduce the issue.
https://github.com/smartskaft2/premakeIssue

**Comment by samsinsane** [comment]
Looks like it's pulling `../src/MyClass` fine, if you add `"../src"` to your `includedirs` it will include that too so you can include `MyEnum.h` as well.

**Comment by smartskaft2** [comment]
That did the trick.

I interpreted 

> You can also use wildcards to match multiple directories. The * will match against a single directory, ** will recurse into subdirectories as well.

like `../src/**` would match `../src` and any subdirectories. This is now in hindsight of course not right. We are not configuring which files to include, but the _directories_. Of course `../src/*` or `../src/**` would not pick up `../src`. 

Thank you!

**Comment by smartskaft2** [comment]
But I am a bit confused, I had to also add the header files to `files` as well, I though that only source files where needed there?

**Comment by nickclark2016** [comment]
The `includedirs` directive tells the toolset where to look for include files at.  The `files` directive informs the compiler of what to include in the project files.

**Comment by smartskaft2** [comment]
@nickclark2016 I figured as much. But thank you for confirming that out for me, I think I got a better understanding of Premake setup now.
