### ISSUE TITLE
Premake crashes when regenerating code

### ISSUE THREAD

**Issue by ItsNovaAndCrap** [premake/premake-core#1858]
_Before opening a new bug report, please read [Reporting Bugs](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#reporting-bugs) and consider if this is something [you can contribute](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#contributing-a-fix-or-feature) yourself. If this a new bug, help us help you by filling in the template below._

**What seems to be the problem?**
Whenever I try to regenerate any type of code with Premake (action is `vs2022`) it crashes and returns this error:
```
Error: [string "src/base/api.lua"]:606: bad argument #2 to 'deferredjoin' (string expected, got table)
```

**What did you expect to happen?**
I expected it to just regenerate the code properly!

**What have you tried so far?**
I didn't see any clear way to fix it since the error is coming from Premake itself and not from my premake5.lua file. I also only have downloaded the executable and I don't know how to view the source code inside a .exe file.

**How can we reproduce this?**
I honestly don't know how it happened or what caused it!

All I did was execute `premake5.exe vs2022` and it returned the error!

**What version of Premake are you using?**
I'm using Premake 5 Beta 1.

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

**Comment by ItsNovaAndCrap** [comment]
Also, `src/base/api.lua` is not part of my project.

**Comment by nickclark2016** [comment]
Can you share your `premake5.lua` file?

**Comment by ItsNovaAndCrap** [comment]
sure: (also, please don't judge me for using Cherno's code. I'm currently following his game engine series)
```
workspace "Dollop"
	architecture "x64"

	configurations
	{
		"Debug",
		"Release",
		"Dist"
	}

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

project "Dollop"
	location "Dollop"
	kind "SharedLib"
	language "C++"

	targetdir {"bin/" .. outputdir .. "/%{prj.name}"}
	objdir {"bin-int/" .. outputdir .. "/%{prj.name}"}

	files
	{
		"%{prj.name}/src/**.h",
		"%{prj.name}/src/**.cpp"
	}

	includedirs
	{
		"%{prj.name}/vendor/spdlog/include"
	}

	filter "system:windows"
		cppdialect "C++17"
		staticruntime "On"
		systemversion "latest"

		defines
		{
			"DP_PLATFORM_WINDOWS",
			"DP_BUILD_DLL",
			"_WINDLL"
		}

		postbuildcommands
		{
			("{COPY} %{cfg.buildtarget.relpath} ../bin/" .. outputdir .. "/Sandbox")
		}

	filter "configurations:Debug"
		defines "DP_DEBUG"
		symbols "On"

	filter "configurations:Release"
		defines "DP_RELEASE"
		optimize "On"

	filter "configurations:Dist"
		defines "DP_DIST"
		optimize "On"

project "Sandbox"
	location "Sandbox"
	kind "ConsoleApp"
	language "C++"

	targetdir {"bin/" .. outputdir .. "/%{prj.name}"}
	objdir {"bin-int/" .. outputdir .. "/%{prj.name}"}

	files
	{
		"%{prj.name}/src/**.h",
		"%{prj.name}/src/**.cpp"
	}

	includedirs
	{
		"Dollop/src",
		"Dollop/vendor/spdlog/include"
	}

	links
	{
		"Dollop"
	}

	filter "system:windows"
		cppdialect "C++17"
		staticruntime "On"
		systemversion "latest"

		defines
		{
			"DP_PLATFORM_WINDOWS",
			"_MBCS"
		}

	filter "configurations:Debug"
		defines "DP_DEBUG"
		symbols "On"

	filter "configurations:Release"
		defines "DP_RELEASE"
		optimize "On"

	filter "configurations:Dist"
		defines "DP_DIST"
		optimize "On"
```

**Comment by nickclark2016** [comment]
Ahh, found the problem.  Instead of doing:
```lua
targetdir {"bin/" .. outputdir .. "/%{prj.name}"}
objdir {"bin-int/" .. outputdir .. "/%{prj.name}"}
```
You should be doing
```lua
targetdir ("bin/" .. outputdir .. "/%{prj.name}")
objdir ("bin-int/" .. outputdir .. "/%{prj.name}")
```

`targetdir` and `objdir` expect a path (string), not a table, which is denoted by the `{` `}`.  The error message definitely isn't helpful here, so it may be worth investigating a better reporting mechanism.
