### ISSUE TITLE
List user defined options separated with premake system options when using "premake --help"

### ISSUE THREAD

**Issue by mercury233** [premake/premake-core#1859]
**What problem will this solve?**
When I'm using "premake --help", the options I created in premake5.lua mixed up with the options provided by premake system.

**What might be a solution?**
List user defined options separated with premake system options when using "premake --help"

**What other alternatives have you already considered?**

**Anything else we should know?**

**Comment by samsinsane** [comment]
Looks like there's already an undocumented feature for this:
https://github.com/premake/premake-core/blob/5c2a1cccd7fc70d691bba0333718e12b2572ee4a/src/base/help.lua#L18-L31

You just need to specify a `category` when calling `newoption` and it will split them out.
