### ISSUE TITLE
Support LLVMInstallDir and LLVMToolsVersion MSVC options

### ISSUE THREAD

**Issue by checkraisefold** [premake/premake-core#1864]
**What problem will this solve?**
Adds support for custom LLVM installation compiler options. This is helpful when using a version of LLVM that doesn't come with Visual Studio.

**What might be a solution?**
Something like:
```
llvmdir "C:\\a\\b\\c"
llvmversion "15.0.0"
```

**What other alternatives have you already considered?**
If this is not a significant enough option to be included, adding a patch locally.

**Anything else we should know?**
https://docs.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170

**Comment by nickclark2016** [comment]
This should be a pretty easy first issue.  If someone wants to tackle it, I'd be more than happy to review it. If not, I'll toss it on my todo backlog.

**Comment by NvSchobi** [comment]
I would be interested as well.

**Comment by nickclark2016** [comment]
Finally got to it, but I have a PR out to support this.
