### ISSUE TITLE
Incorrect nested token expansion when project kind is SharedLib

### ISSUE THREAD

**Issue by WarEagle451** [premake/premake-core#1866]
## **What seems to be the problem?**
- I have 2 projects, one is a StaticLib and the other a SharedLib. When generating a Visual Studio 2022 project file the StaticLib version expands a token to a full path while the SharedLib project token is expanded to a filename. This results in a linking error for the compiler
- The token is identical in both projects

## **What did you expect to happen?**
- I expect token expansion to work the same in a SharedLib project as a StaticLib project.
```
VULKAN_SDK = os.getenv("VULKAN_SDK")

LibraryDir = {}
LibraryDir["VulkanSDK"] = "%{VULKAN_SDK}/Lib"

Library = {}
Library["Vulkan"] = "%{LibraryDir.VulkanSDK}/vulkan-1.lib"
```
- The StaticLib project expands `"%{Library.Vulkan}"` correctly to `"%{VULKAN_SDK}/Lib/vulkan-1.lib"`
- The SharedLib project expands `"%{Library.Vulkan}"` incorrectly  to `/vulkan-1.lib`

## **What have you tried so far?**
- Using print I found that calling `premake.detoken.expand` correctly expands the token in the SharedLib version

## **How can we reproduce this?**
- StaticLib
Using code block from **What did you expect to happen?**
```
project "Project"
kind "StaticLib"
language "C++"
cppdialect "C++20"
staticruntime "Off"

links {
"%{Library.Vulkan}"
}
```
- SharedLib
Using code block from **What did you expect to happen?**
```
project "Project"
kind "SharedLib"
language "C++"
cppdialect "C++20"
staticruntime "Off"

links {
"%{Library.Vulkan}"
}
```

## **What version of Premake are you using?**
- 5.0.0-beta1

## **Anything else we should know?**
- The StaticLib repo is private
- I have a [repo](https://github.com/WarEagle451/Mythos/tree/47980e39af5b3246dd62ddbdd43f927bc4e91fb1) that contains the bug. [Mythos/premake5.lua](https://github.com/WarEagle451/Mythos/blob/47980e39af5b3246dd62ddbdd43f927bc4e91fb1/Mythos/premake5.lua) contains the issue.
### Building the repo
1. Comment out `premake.detoken.expand("%{Library.Vulkan}", Library, Library)` and uncomment `"%{Library.Vulkan}"` in [Mythos/premake5.lua](https://github.com/WarEagle451/Mythos/blob/47980e39af5b3246dd62ddbdd43f927bc4e91fb1/Mythos/premake5.lua) 
2. Run `scripts/setup.bat` (This will install Vulkan, Python and Premake, the install links are located in their respective setup files)
3. Attempt build with Visual Studio 2022

**Comment by nickclark2016** [comment]
Can you check if this works?

```lua
libdirs { "%{LibraryDir.VulkanSDK}" }
links { "vulkan-1.lib" }
```

As an aside from another dev using Vulkan, I'd recommend using something like `vk-bootstrap` instead of vulkan directly. Saves a lot of loading code and dynamically loads the functions pointers to devices, so you can easily support multiple logical devices.

**Comment by WarEagle451** [comment]
No, it produces the same link error (LNK1104 cannot open file 'vulkan-1.lib')

**Comment by WarEagle451** [comment]
I just tested it in the StaticLib version and it works for it

**Comment by nickclark2016** [comment]
Thanks for the info. I'll try to investigate in the morning :)

**Comment by nickclark2016** [comment]
Wanted to follow up, have not had the chance to hunt this down yet.  It is on my to-do list, though.

**Comment by WarEagle451** [comment]
Thanks. I've yet to find an alternative to using `premake.detoken.expand`.

**Comment by nickclark2016** [comment]
I've got news. It looks like your issue is with the `Testbed\premake5.lua` file.  You reset your `LibraryDir` variable on line 1, which causes the expansion (which doesn't happen immediately) to see a `LibraryDir` variable that doesn't have Vulkan in it.  If you comment that line out, you should be good to go (verified on my end, please verify this as a fix on your end).

**Comment by WarEagle451** [comment]
Yes it does fix it, thank you! Sorry about wasting your time

**Comment by nickclark2016** [comment]
No worries! Just a rule of thumb for ya (because I had to dig around to remember this), those "macros" that allow you to expand the set/map values aren't actually evaluated until after all the scripts have loaded and a few other under the hood things have gone on, so don't overwrite the values unless it's intentional. I've done this a few times before.

**Comment by WarEagle451** [comment]
Will do! I'll definitely remember that from now on
