### ISSUE TITLE
How to output verbose log(included every file's build command output) when build solutions

### ISSUE THREAD

**Issue by lailongwei** [premake/premake-core#1890]
How to output verbose log(included every file's build command output) when build solutions.

**Comment by nickclark2016** [comment]
What toolchain are you using?

**Comment by lailongwei** [comment]
I use premake tool to generate makefiles, I want to output detail compile&link command(eg: `g++ -g -c -o xxx.o xxx.cpp`)when run make command, like cmake `set(CMAKE_VERBOSE_MAKEFILE on)` setting

**Comment by nickclark2016** [comment]
As far as I'm aware, we don't have a 1-to-1 functionality with that.  However, if you look at the top of makefiles generated by gmake2, there is a `verbose` value that you could pass on the command line to force all output on.  Not sure if that will give you everything you need.

**Comment by lailongwei** [comment]
@nickclark2016 I found it too! thanks!!!:100:😉
