### ISSUE TITLE
how to include all child folders with specific folder name as include path

### ISSUE THREAD

**Issue by haolly** [premake/premake-core#1896]
**What's your question?**
There is a SO question here: https://stackoverflow.com/questions/72633300/how-to-include-all-child-folders-with-specific-folder-name-as-include-path-in-vs

**Anything else we should know?**
I have tried `RootDir/*/Public/**.h` in **includedirs**, but it does not work

**Comment by samsinsane** [comment]
The linked question is about VSCode which Premake doesn't support, did you link the right question?

> I have tried `RootDir/*/Public/**.h` in **includedirs**, but it does not work

Assuming the structure in the SO question, it should be `public` not `Public` unless you're only using Windows. Secondly, `**.h` won't match any folders as they don't end in `.h`. Finally, the way `**` works is that it has to match _something_, so `Root/FolderA/public` won't be matched with `Root/*/public/**`, it will be matched with `Root/*/public` though. If you want both `Root/FolderA/public` and all of the folders and subfolders it contains, just specify both `Root/*/public` and `Root/*/public/**`.
