### ISSUE TITLE
Running premake resets a property toggle.

### ISSUE THREAD

**Issue by Noobie2014** [premake/premake-core#1906]
I have no idea if this issue is fixed or just not worried about? The issue is that first i don't know the reference to toggle the Visual Studio Microsoft Code Analysis from a Lua script. I do not like the Microsoft tool. When I turn it off manually from the properties interface of Visual Studio  then run the Lua script for some other things I change, running the script will default the toggle back to yes.

Thank You

**Comment by nickclark2016** [comment]
This is because Premake is generating the solution and project files when you invoke it, which will overwrite changes you made to the files manually.

**Comment by Noobie2014** [comment]
Yes :) That is what I suspected but doesn't the generator look at the current properties and copy them back as they where? The Premake wiki doesn't enumerate or explain how to script some properties like the code analysis tool.

**Comment by nickclark2016** [comment]
No, the generator does not ready the existing config files and just "patch" them.  Here is the documentation on adding to an array call or overriding functionality: https://premake.github.io/docs/Overrides-and-Call-Arrays
