### ISSUE TITLE
cppdialect "C++20" yields "Preview - Features from the Latest C++ Working Draft (/std:c++latest)" Visual Studio

### ISSUE THREAD

**Issue by rtosman** [premake/premake-core#1911]
I am using 5.0.0 beta and generating a vs2022 solution.

Premake.lua sets {cppdialect "C++20"} 

Inside the solution this yields "Preview - Features from the Latest C++ Working Draft (/std:c++latest)" even though VS does have a specific c++20 option: "ISO C++20 Standard (/std:c++20)"

**Comment by ngzaharias** [comment]
I'm having the same issue with the same version.

**Comment by siradam7th** [comment]
It has been fixed by this pull request https://github.com/premake/premake-core/pull/1749, however, the published binaries are not up-to-date, you can try to compile from source and it should no longer be an issue.
