### ISSUE TITLE
postbuildcommands() supported running when target don't need build

### ISSUE THREAD

**Issue by lailongwei** [premake/premake-core#1924]
My project has some config files, when edited the config files, and run `make xxx`，premake tool generated makefile will not run `postbuildcommands()`, for this case, can add support?

**Comment by nickclark2016** [comment]
Post build commands produced by Premake are analogous to those in Visual Studio, which only are executed upon a build of the project.  You could try using "buildcommands".

**Comment by lailongwei** [comment]
OK, Thanks very much!
