### ISSUE TITLE
Supporting MSBuild external projects from Make backend

### ISSUE THREAD

**Issue by tritao** [premake/premake-core#193]
So I have some Premake build scripts that take advantage of the external projects feature to include some C# dependencies that already provide MSBuild csproj.

This all works great with the VS backend but with the Make backend it looks for a Makefile instead of invoking `msbuild`/`xbuild` with the already existing VS project files.

We could first search for a Makefile if using the Make backend to keep the existing behavior but if no such file exists then we probe for csproj projects and use them if found.

Any objections to add this behavior?

**Comment by TurkeyMan** [comment]
Umm, it sounds a little odd to me that you'd have a makefile that depends on MSBuild, and not just use MSBuild...
If a makefile depends on MSBuild, then it's no longer portable right? If you're comfortable to use MSBuild, why not just generate the full VS project and use MSBuild straight up?
It's not that it can't be done, or even that it's a terrible idea, but it seems kind of redundant no?

**Comment by tritao** [comment]
Well because this project is composed by a mix of C# and C++ sub-projects. As far as I know, you cannot use xbuild to build C++ MSBuild projects which is why I have to use the Make backend.

A couple years back I did contribute C++ building support to Mono's xbuild as part of Google's Summer of Code but it was never merged. Even so I'd prefer to continue using Premake-generated Makefiles since I think they're much easier to debug than the MSBuild XML mess.

Since some of the dependencies I'm trying to use already provide their own build files I'd rather use them directly than writing my own Premake scripts to build them.

**Comment by TurkeyMan** [comment]
Oh okay. Sorry, I never heard of xbuild before.
This all makes good sense now. If you want to contribute the patch, I don't see any reason why it wouldn't be accepted.

It's probably something that should be generally possible. It may be convenient in various circumstances for external projects of non-makefile types to be possible to invoke by makefiles.
