### ISSUE TITLE
Premake visual studio sln doesn't work on macOS

### ISSUE THREAD

**Issue by reckfullol** [premake/premake-core#1933]
Visual studio solution generated by premake doesn't seem to work on macOS.

Here is the error message while building on Visual studio:
`/Users/Reckful/Code/llbc/build/vs2022/llbc.vcxproj: Error: This project type is not supported by Visual Studio Community 2022 for Mac.`

Here is the error message while builing on Jetbrains Rider:
`  The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "/Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.  /Users/Reckful/Code/llbc/build/vs2022/llbc.vcxproj`

Is there a way that visual studio solution generated by premkae can be build on macOS?

Thanks in advance.

![image](https://user-images.githubusercontent.com/16449130/185903312-f7545a89-d0a9-4cd6-a70b-47eb682fad17.png)
![image](https://user-images.githubusercontent.com/16449130/185903339-b303412d-d2e1-42b4-8610-9de8909b03be.png)

**Comment by nickclark2016** [comment]
On mac, I believe Visual Studio is for .NET and does not support C++.  As for importing in JetBrains Rider, I'm not sure if that stems from the same isssue.

**Comment by reckfullol** [comment]
> On mac, I believe Visual Studio is for .NET and does not support C++. As for importing in JetBrains Rider, I'm not sure if that stems from the same isssue.

Thanks for your response. It looks like Visual Studio on Mac doesn't have visual c++, Jetbrains Rider also can not find **$(VCTargetsPath)**.
