### ISSUE TITLE
Use VS2022 with v5 Build Batch File

### ISSUE THREAD

**Issue by mehdi07987** [premake/premake-core#1934]
How can I change the batfile to vs2022.

**Comment by nickclark2016** [comment]
I _think_ you can provide vs2022 as a parameter (just looking at the contents of the file), but I could be mistaken.

**Comment by samsinsane** [comment]
Closing this off, as @nickclark2016 mentioned passing `vs2022` as a parameter will control which VS is used, otherwise it uses the latest one.
