### ISSUE TITLE
The binary download of premake-5.0.0-beta2 don't has exec permission

### ISSUE THREAD

**Issue by mercury233** [premake/premake-core#1944]
_Before opening a new bug report, please read [Reporting Bugs](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#reporting-bugs) and consider if this is something [you can contribute](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#contributing-a-fix-or-feature) yourself. If this a new bug, help us help you by filling in the template below._

**What seems to be the problem?**
download and extract and run `./premake5` , it says `Permission denied`

**What did you expect to happen?**
the binary has exec permission as previous releases

**What have you tried so far?**
`chmod +x ./premake5` and it works

**How can we reproduce this?**
download and extract and run [premake-5.0.0-beta2-linux.tar.gz](https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz) or [premake-5.0.0-beta2-macosx.tar.gz](https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-macosx.tar.gz)

**What version of Premake are you using?**
5.0.0-beta2

**Anything else we should know?**
The previous build with 5.0.0-beta1 works without `chmod +x ./premake5` :
https://app.circleci.com/pipelines/github/mercury233/ygopro/137/workflows/dcd2eccd-caad-4618-84f6-647ba220252e/jobs/81
Failed with 5.0.0-beta2 :
https://app.circleci.com/pipelines/github/mercury233/ygopro/139/workflows/8514fa3f-0060-4e6f-8e91-dd11f75545f1/jobs/82
Fixed with manually permission :
https://app.circleci.com/pipelines/github/mercury233/ygopro/140/workflows/d52486a1-3d82-4a3a-89af-28528045c1e7/jobs/83

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

**Comment by nickclark2016** [comment]
Appreciate the heads up. I'll fix that later tonight!

**Comment by nickclark2016** [comment]
Should be good to go. Let me know if that fixes it and I'll close it.

**Comment by mercury233** [comment]
Fixed, thank you!
