### ISSUE TITLE
Error: [string "vstudio/vs2005.lua"]:9: attempt to index a nil value (field 'sln2005'), what does it mean?

### ISSUE THREAD

**Issue by haolly** [premake/premake-core#1955]
**What's your question?**
what's the meaning of this error? how can I fix it?

I'm following [this](https://youtu.be/al-GQVLfaWE?list=PLlrATfBNZ98dC-V-N3m0Go4deliWHPFwT&t=1055) video and encounter the same problem

**Comment by nickclark2016** [comment]
Instead of a video, could you share your premake files?

**Comment by haolly** [comment]
Close this. I just tried the latest version, it fix this issue
