### ISSUE TITLE
Mixing C and C++

### ISSUE THREAD

**Issue by crazyjul** [premake/premake-core#198]
When working with single file library, it easier to include them in the project as sources ( e.g. sqlite3.c, duktape.c, ... )

The problem is there's no way to specify c++ specific build options (similar to CFLAGS and CPPFLAGS )

I propose to add a cppbuildoption that would only apply to c++ files, and I can implement it.

Any remarks before I start?

**Comment by starkos** [comment]
I think that is probably the way to go. Maybe it should be `cxxbuildoptions` to match Make's `CXX` environment convention and to differentiate it from the CPP preprocessor? And perhaps a `ccbuildoptions` to target C files?

**Comment by TurkeyMan** [comment]
This necessarily applies to `dcbuildoptions` too.
So `buildoptions` will remain a generic one that applies to all things?

The alternative would be to filter `buildoptions` on `*.c` and/or `*.cpp`. That should work right now no?
It's pretty lame though, create a zillion file-specific build options.

**Comment by starkos** [comment]
> The alternative would be to filter `buildoptions` on `*.c` and/or `*.cpp`…It's pretty lame though, create a zillion file-specific build options.

That's a good point, and easy enough to do:

```lua
filter "files:**.c"
   buildoptions { "c specific options" }
```

I don't think this works, but it would be a nice alternative if it did:

```lua
filter "language:C"
   buildoptions { "…" }
```

**Comment by crazyjul** [comment]
I like the idea of language filtering, it makes it easier to extend to
objective-C for example.

I can have a look at implementing it this week

**Comment by TurkeyMan** [comment]
I don't think it's so simple. I can foresee a lot of problems with where the language specific settings actually live in such a way that you can get at them in a non-file-specific way.
I think the situation runs into an existing problem where languages are usually assigned per project, not per file. If you assign language per-file, and then filter for that language, you're effectively duplicating whatever language-specific settings for every file of that type.
Maybe language needs to be a container for settings or something.

**Comment by starkos** [comment]
Agree, getting that working is going to be decidedly not trivial.

The "right" solution is to provide the ability to ask for the settings unique to a particular scope. So "what flags/values are set for this file that are not set for its project" or "what flags/value are set for this project that are not set for its solution". There are some pull requests sitting in the queue that begin moving things in that direction, but more work is needed.

If we had *that*, then things get simpler pretty much everywhere, we really only need to deal with a single type of "configuration" instead of the solution/project/file configs we have now, and the whole API gets more generic.

**Comment by starkos** [comment]
So…would it be okay to close this ticket with the suggestion to use the file extension based filtering above? And if you want to tackle the more sophisticated solution, perhaps open a thread on the developer forum to ask questions and share progress?

**Comment by computerquip** [comment]
I'm having issues using the file extension based filtering. I actually can't figure out what premake is doing in this case... 

If I use: 
    filter { "language:C++" }
it applies to ALL files in my project, indicating all files are under affect of the filter. However, this doesn't work when mixing C and C++. 

If I use:
    filter{ "files:**.cpp" }
It works on none. 

I'd like to create a test case here soon. I've tried this filter as per the solution and as per project. Neither seem to work. Unfortunately, I can't provide my specific scenario with more details.

**Comment by computerquip** [comment]
https://github.com/computerquip/premake5-test-case

The test case (in test/main.cpp) uses a basic C++ feature that will fail to compile if GCC is not provided the -std=c++11 flag. If need be, I can also post the generated makefile. Am I doing something wrong here?

**Comment by starkos** [comment]
Right, so now we're at the second part of the problem: the makefile exporter does not currently support per-file flags. Reworking that exporter is on my to-do list, but it's a really long list.

**Comment by ocornut** [comment]
I'm running into similar issues and stomped as to how I could provide specific parameters (aka typically `-std=c++11`) only to .cpp files but not to .c files. Currently emitting Makefile but I could work with xcode projects too.

I tried various filters with same result as https://github.com/premake/premake-core/issues/198#issuecomment-132429625 with no success getting the filtering to behave.

Any ideas how I could do it? Thanks!

**Comment by starkos** [comment]
The Makefile exporter does not currently support per-file settings—one of many things I'm trying to get to.

**Comment by ocornut** [comment]
> The Makefile exporter does not currently support per-file settings—one of many things I'm trying to get to.

Is there any way we could help?

FYI I couldn't get it to wok either for xcode.
Note that (at least for my case) I'll perfectly be happy with a directive like `cxxbuildoptions`. The Genie fork https://github.com/bkaradzic/genie added a similar feature "Added buildoptions_c, buildoptions_cpp, buildoptions_objc for configuring language specific build options.".

**Comment by tvandijck** [comment]
Certainly for the makefile backend having some sort of ability to seperate the ALL_CXXFLAGS and ALL_CFLAGS options would be nice indeed...

That said, the genie fork went in a very different direction, so it's often not as easy to share code. I would also argue that a "buildoptions_c" or any derivation of that is hardly extendable. What about buildoptions_cuda, etc, etc...

I'd rather have the ability to write:
```lua
buildoptions
{
   ['.cpp'] = {'somestuff here'}
   ['.c']     = {'someother stuff here'}
}
```

this we can easily achieve, while maintaining backwards compatibility of the buildoptions API. If you specified it the normal way it simply applies to everything.

**Comment by tvandijck** [comment]
That said btw...

```lua
filter {file:*.cpp}
   buildoptions{...}
```

is obviously supposed to do the same thing, so extending the buildoptions, instead of just fixing the per file settings, kind of makes no sense... I'd rather fix the per-file settings.

**Comment by starkos** [comment]
> Is there any way we could help?

It would be helpful if someone could figure out what a Makefile with per-file rules looks like. I suspect it will end up rather different from what we are exporting currently.

**Comment by timbeaudet** [comment]
I am also running into this issue, and since it has been 6 months, I'm wondering if there has there been any progress?

**Comment by tvandijck** [comment]
https://github.com/premake/premake-core/pull/516

any help towards fixes for this pull request would be greatly appreciated... it adds support for per file configurations to the gmake backend, as well as implements rules, and bunch of other stuff.

**Comment by realvictorprm** [comment]
I need to pass the `-std=c++1z` flag to clang 😿

**Comment by realvictorprm** [comment]
@tvandijck shouldn't we rename this issue to `Seperating C and C++ build flags`?

**Comment by tvandijck** [comment]
Semantics... but the 
```lua
filter "file:*.cpp"
   buildoptions { ... }
```

would work with the gmake2 action.

**Comment by pjohalloran** [comment]
Hi,

Is it possible to apply different options to c and cpp files in the 5.0 alpha? I notice in the filter wiki, there is a possibility to filter by language?

Thanks.

**Comment by samsinsane** [comment]
@pjohalloran Alpha12 should support per file filters for the gmake2 and VS2010-VS2017 actions. The comment above yours shows an example of how to apply different options to c and cpp files.

**Comment by samsinsane** [comment]
Given that `gmake2` supports per-file filters, can this issue be considered resolved? I believe additional work went into ensuring that C++ flags weren't applied to the C flags listing and vice versa. Seems like this issue is resolved to me, but perhaps I'm missing something?

**Comment by tigert1998** [comment]
Any ideas to mix `C` and `C++` with `premake4`?

**Comment by c-smile** [comment]
> ```lua
> filter "file:*.cpp"
> ```

Correct  way of defining that is
```
filter "files:*.cpp"
   buildoptions { ... }
```
Note plural "files"

**Comment by samsinsane** [comment]
I'm going to close this as it seems to be resolved now by `gmake2` and the `filter` usage mentioned numerous times above.
