### ISSUE TITLE
How can I get a project's executable file from another project within the same workspace?

### ISSUE THREAD

**Issue by GasimGasimzada** [premake/premake-core#1988]
**What's your question?**

I have two projects in the same workspace:

```lua
project "Runtime"
  kind "ConsoleApp"
  basedir "../workspace/runtime"
  -- Other stuff

project "Editor"
  kind "ConsoleApp"
  basedir "../workspace/editor"
  -- Otherstuff
```

For the example above, I need a way to use the output target of "Runtime" in the "Editor". I either want to copy it to "Editor"'s target output (using `postbuildscripts`) or automatically set it as a preprocessor definition. I want this to happen at toolchain level and automatically. If I change Runtime's base directory to another place, it should immediately update the paths on next build. I want this to be platform independent as well (on Windows, it should provide the ".exe" or ".dll" while on Linux/macOS it provides executable or ".so" files)

How can I reference or achieve this?

**Comment by samsinsane** [comment]
Assuming you're changing the path in the Premake script, you could use a variable to store the information. Something like this (untested, may need some adjustment):
```lua
local runtimeLocation "../workspace/runtime"

-- In Runtime project
  basedir(runtimeLocation)

-- In Editor project
  postbuildscripts { "{COPYFILE} " .. runtimeLocation .. "/Runtime%{ iif(cfg.system=='windows', '.exe', '') } ./Runtime%{ iif(cfg.system=='windows', '.exe', '') }" }
```

**Comment by GasimGasimzada** [comment]
@samsinsane Thank you for the suggestion. In the code above, how can I find the configuration name such as "Debug" or "Release"

**Comment by GasimGasimzada** [comment]
I found a way to do the way I liked it:

I created a function that copies runtime to any project 

```lua
function getTargetExtension(targetName)
    return targetName .. "%{iif(cfg.system == 'windows', '.exe', '')}"
end

function copyRuntime()
  runtimeTargetName = 'Runtime';
  runtimeTargetLocationRelativeToProjects = '../../workspace/runtime';

  -- Equals:
  postbuildcommands {
    "{COPYFILE} "..runtimeTargetLocationRelativeToProjects.."/bin/%{cfg.buildcfg}/"..getTargetExtension(runtimeTargetName).." %{cfg.buildtarget.directory}/"
  }
end
```


Thank you for the help!!
