### ISSUE TITLE
[REQUESTED]: Add Force file input

### ISSUE THREAD

**Issue by harshfeudal** [premake/premake-core#1991]
Hello there,

I think premake5 will be awesome if you include more linker setups. I wish this feature will be added in the near future so that I can make this pre-setup

If you have it already, please give feedback to me about what the command is or where it is on the document.

Thank you for listening!

Best regards,
Harshfeudal.

![image](https://user-images.githubusercontent.com/87577447/197384849-c19cb480-cedb-4d92-a928-ac7b51d64a97.png)

**Comment by Jarod42** [comment]
You can already have:

```
filter("toolset:msc")
  linkoptions("/FORCE:MULTIPLE")
```
Note that it won't be reflected there in the GUI,
but it would actually be in link options (You can check in "Command Line" tab).

**Comment by harshfeudal** [comment]
Oh okay, thank you very much for your response!
