### ISSUE TITLE
Error when running generated Makefile "make (e=2): The system cannot find the file specified."

### ISSUE THREAD

**Issue by stwupton** [premake/premake-core#1999]
**What are you trying to do?**
I'm trying to build a program from a generated Makefile which uses the clang compiler on Windows.

**What problem are you having?**
Running `$ premake5 --cc=clang --os=windows gmake2` seems to generate the Makefile correctly, but when I cd into the build directory and run `$ make`, it results in the following output:
```
==== Building chip8-emulator (debug_win64) ====
main.cpp
process_begin: CreateProcess(NULL, echo Linking chip8-emulator, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [chip8-emulator.make:84: bin/Win64/Debug/chip8-emulator.exe] Error 2
make: *** [Makefile:30: chip8-emulator] Error 2
```

**What have you tried so far?**
- Made sure MinGW Make is up to date (4.2.1).
- Created the `bin/Win64/Debug/` and `obj/Win64/Debug/` directories manually, but the same error occurs. 

**What version of Premake are you using?**
5.0.0-beta2

**Anything else we should know?**
premake5.lua file: https://github.com/stwupton/chip8-emulator/blob/master/premake5.lua
Generated .make file: https://gist.github.com/stwupton/522a5c2c2a5c269c41cfdcc162e961a4

**Comment by Jarod42** [comment]
Have you also error for `make clean`?
Is `echo` work in your shell?
Not sure how `--os=windows` interact with mingw (which use "linux" shell).

**Comment by stwupton** [comment]
@Jarod42 After doing some tests to answer your questions, I found out that everything works fine if I run `make` in a bash shell (before I was running it in Windows CMD or Powershell).

Is that expected behaviour?

**Comment by Jarod42** [comment]
I don't know how different should be the makefile to run with cmd/powershell. Is adjusting PATH to have expected utility enough (so user side), or makefile should be adjusted (so premake-side)(if possible to be compatible with any shell)?

I don't know the expected behavior, but I suspect the answer is yes as it is working in bash shell...

**Comment by stwupton** [comment]
Ok, I just remember Make working fine from Windows CMD before. But running it in bash is ok too. Thanks!
