### ISSUE TITLE
Gmake2: `symbols "On"` doesn't generate .pdb

### ISSUE THREAD

**Issue by stwupton** [premake/premake-core#2007]
**What seems to be the problem?**
Running a makefile that was generated with `symbols "On"` defined in the config, doesn't build a .pdb file.

**What did you expect to happen?**
A .pdb file to be created with the same name and in the same directory as the built .exe.

**What have you tried so far?**
I'm able to create the .pdb file after manually adding the `-g` flag to `LINKCMD` in the makefile.

**How can we reproduce this?**
Generate a build using the `gmake2` action and set `symbols 'On'` in premake5.lua.

**What version of Premake are you using?**
5.0.0-beta2

**Comment by Jarod42** [comment]
pdb files are for msvc... gcc/clang add symbols directly in executable normally...

**Comment by stwupton** [comment]
I'm building my program with Clang on Windows. I believe .pdb is used only for debugging on Windows.

Again, if I go into the generated .make file and manually add the `-g` option to `LINKCMD`, the .pdb is successfully created when I run the build. 

So both MinGW and Clang compilers are capable of creating the .pdb file, it's just that premake isn't adding the `-g` option to the build command when `symbols "On"` is set.

**Comment by Jarod42** [comment]
It seems clang can produce pdb file since 2017...

I dig in premake source, and `Symbol xxx` is only handled by cflags/cppflags, not linker flags.

I don't know what `-g` (or `-g -gcodeview`) would do on non-windows platform :/

As workaround, you might add:

```
-- filter "platform:windows" -- if needed
linkoptions "-g" -- generate pdb file (on windows)
```

**Comment by stwupton** [comment]
That works, thanks!
