### ISSUE TITLE
How to use object file with premake?

### ISSUE THREAD

**Issue by sniper00** [premake/premake-core#2012]
**What's your question?**

I want override malloc with the mimalloc single object file:

```shell
gcc -o myprogram mimalloc-override.o  myfile1.c ...
```

**Anything else we should know?**

Use cmake link object libraries:
https://cmake.org/cmake/help/latest/command/target_link_libraries.html#linking-object-libraries-via-target-objects

**Comment by Jarod42** [comment]
`linkoptions { "mimalloc-override.o" }` should do the job.

**Comment by nickclark2016** [comment]
@sniper00 did that resolve your issue?

**Comment by sniper00** [comment]
> @sniper00 did that resolve your issue?

yes，thanks
