### ISSUE TITLE
Build message for C/C++ source files

### ISSUE THREAD

**Issue by MohitSethi99** [premake/premake-core#2014]
**What are you trying to do?**
Add build message for .cpp and .c files

**What problem are you having?**
I don't know how to do it.

**What have you tried so far?**
Project level:
```lua
filter "files:**.cpp"
	buildmessage "Compiling C++ source file: %{file.relpath}"
filter "files:**.c"
	buildmessage "Compiling C source file %{file.relpath}"
```

**What version of Premake are you using?**
5.0.0-beta2

**Anything else we should know?**
N/A

**Comment by Jarod42** [comment]
Which generator are you using?
Most generator should produce advancement when building file (even if message is not customized).

**Comment by MohitSethi99** [comment]
VS2022 with clang toolset is not producing any output per file except for warnings and errors

**Comment by nickclark2016** [comment]
It may be possible that it's not something supported for Clang.  Could you check and see if it works for Clang + vs2022 if you add a build message by hand?

**Comment by MohitSethi99** [comment]
I added the above mentioned snippet but message is not customized, but is default when I use MSVC:
![image](https://user-images.githubusercontent.com/29519295/210413109-4845801a-081e-43a2-9c3b-7cc000a18be9.png)

And with clang-cl no message shows up for compiling files:
![image](https://user-images.githubusercontent.com/29519295/210413446-256bd237-9613-44b6-87c4-9f0ffe59478b.png)

**Comment by Jarod42** [comment]
From what I see, visual project doesn't have a field to customize message.
I think "add a build message by hand" was about configuring directly from IDE. (But I think you cannot).
Even the regular msvc doesn't customize files list.

**Comment by nickclark2016** [comment]
> From what I see, visual project doesn't have a field to customize message. I think "add a build message by hand" was about configuring directly from IDE. (But I think you cannot). Even the regular msvc doesn't customize files list.

Good to know. If that's the case, then no, there's no way to do this for VS solution/project exports.

**Comment by MohitSethi99** [comment]
Okay, I should close the issue then. Thanks for the support!
