### ISSUE TITLE
Nightly builds links are incorrect

### ISSUE THREAD

**Issue by kjk** [premake/premake-core#203]
http://premake.github.io/download.html#v5, links to nightly builds on sourceforge (e.g. http://sourceforge.net/projects/premake/files/Premake/nightlies/premake-dev-macos.zip/download) are incorrect.

The files do not exist there (and due to sourceforge UI, it's rather hard to figure it out).

It's even more unfortunate given that the latest alpha4 is out-of-sync with wiki docs ("workspace" doesn't exist there).

**Comment by starkos** [comment]
Okay, I've removed the nightlies section on the download page until we can figure out what happened to them (I'm guessing they were broken when we redirected the 5.0 files from SourceForge). 

I've also just released 5.0-alpha5, which will hopefully help with the workspace naming issue.

I'm going to close this one for now, but feel free to reopen if you feel more work is needed!
