### ISSUE TITLE
"build instructions" link on http://premake.github.io/download.html#v5 incorrect

### ISSUE THREAD

**Issue by kjk** [premake/premake-core#204]
It points to https://github.com/premake/premake-core/wiki/Building_Premake, which doesn't exist.

I guess until that page exists, it could point to https://github.com/premake/premake-core/blob/master/BUILD.txt instead.

**Comment by kjk** [comment]
Actually, it seems it should be: https://github.com/premake/premake-core/wiki/Building-Premake

**Comment by starkos** [comment]
Thanks for letting us know (though it is a wiki, so you can just go ahead and fix it if you like).
