### ISSUE TITLE
How do we install premake5 on a linux system that doesn't have it backported yet?

### ISSUE THREAD

**Issue by Shadowblitz16** [premake/premake-core#2041]
**What's your question?**
How do we install premake5 on a linux system that doesn't have it backported yet?

**Anything else we should know?**
- I'm on kubuntu 22.04
- I build it from the downloadable source but when i run `sudo make install` it says no rule exists

**Comment by nickclark2016** [comment]
Have you followed the steps outlined in the BUILD.txt file at the repo's root?

**Comment by Shadowblitz16** [comment]
> 

yes I didn't see anything related to actually installing it onto my system

**Comment by nickclark2016** [comment]
You should just need to add the directory where premake is built to your path.  Premake is standalone, and we don't provide an installer.

**Comment by Shadowblitz16** [comment]
> You should just need to add the directory where premake is built to your path. Premake is standalone, and we don't provide an installer.

the problem is I have 3 versions of premake for each operating systems and I don't want to have to type.. 
`./premake/premake.<some os dependent extension> build` everytime I want to build my project

I would rather do `premake5 build`, and `premake5 install` but to do that I need to install it and add it to my path.

I should be able to build premake5 from source and do `make install` and install premake and add it to my path

**Comment by nickclark2016** [comment]
To my knowledge, this is not supported, as we don't provide an installer (or install script).

**Comment by nickclark2016** [comment]
Feel free to open an issue for a feature request.  Not sure where it'll fall in the priority list, but at least it'll stay on our radar.
