### ISSUE TITLE
[macOS] [Arm] Build fails due to architecture mismatch. 

### ISSUE THREAD

**Issue by shinra-electric** [premake/premake-core#2049]
**What's your question?**
I am trying to build premake5 on an Arm Mac with the following instructions: 
```
git clone https://github.com/premake/premake-core
cd premake-core
make -f Bootstrap.mak osx
```
I would then normally follow this up with: 
```
cd build/bootstrap
make config=release
```

However, it will not run correctly without Rosetta installed.

 I noticed this line in the script: 
`./build/bootstrap/premake_bootstrap --arch=x86 --to=build/bootstrap gmake2`

- Is building on Arm on macOS fully supported? 
- Is there any way to specify the architecture to build for? 

**Anything else we should know?**
 I tested on another Arm Mac with Rosetta and it works fine.

**Comment by samsinsane** [comment]
This line?
https://github.com/premake/premake-core/blob/31f81fc1a1864162642ae2eb4fe14c45612fe1f6/Bootstrap.mak#L103

Have you tried setting `PLATFORM`? This is how we do it in the CI jobs:
https://github.com/premake/premake-core/blob/31f81fc1a1864162642ae2eb4fe14c45612fe1f6/.github/workflows/ci-workflow.yml#L37

Here's the set of values you're probably looking for:
https://github.com/premake/premake-core/blob/31f81fc1a1864162642ae2eb4fe14c45612fe1f6/premake5.lua#L107-L111

**Comment by shinra-electric** [comment]
Thanks, using `make -f Bootstrap.mak osx PLATFORM=ARM` fixed it. 

I came across another problem, but it's unrelated so I'll open a new issue.
