### ISSUE TITLE
Not link against the corresponding dylib on Xcode when calling `links` api

### ISSUE THREAD

**Issue by SjMxr233** [premake/premake-core#2054]
**What seems to be the problem?**
I used `links` to link the SharedLib project like the following:
```
workspace "Wks"
    configurations {"Debug", "Release"}
    targetname "%{prj.name}-%{cfg.buildcfg}"

project "Project1"
    kind "ConsoleApp"
    links "Project2"

project "Project2"
    kind "SharedLib"
```
It works well on Visual Studio, but does not correctly link against dylib on Xcode when the target name contains the build configuration. Project1 consistently links against "libProject2-Debug.dylib" even if I change the build configuration to "Release".

**What did you expect to happen?**
Project1 should link against "libProject2-Debug.dylib" when the configuration is "Debug".
Project1 should link against "libProject2-Release.dylib" when the configuration is "Release".

**How can we reproduce this?**
- [x] XCode (xcode)

**What version of Premake are you using?**
Premake5.0-beta2

**Anything else we should know?**
MacOS 13.1, Xcode 14.2

**Comment by crazydef** [comment]
Why was this closed?  I've noticed the same problem.  Did you figure this out?
