### ISSUE TITLE
Can't include an xcode project in multiple workspaces

### ISSUE THREAD

**Issue by crazydef** [premake/premake-core#2073]
**What seems to be the problem?**
I have half a dozen or so common library projects which are pulled into application projects when they're needed.

This is achieved by having a skeleton premake5.lua file for the solution and including each required project as follows:
```
include( path.join( os.getenv( "WorkDir" ), "Build", "common.lua" ))

workspace "TFG"
	OsoSetupWorkspace()

	include( path.join( coredir, "Core", "Build", "core.lua" ))
	include( path.join( coredir, "Carbon", "Build", "carbon.lua" ))
	include( path.join( coredir, "Gwee", "Build", "gwee.lua" ))

	if os.host() == "windows" then
		include( path.join( coredir, "DX11", "Build", "dx11.lua" ))
		include( path.join( coredir, "Windows", "Build", "windows.lua" ))
	elseif os.host() == "macosx" then
		include( path.join( coredir, "Apple", "Build", "apple.lua" ))
		include( path.join( coredir, "Metal", "Build", "metal.lua" ))
	elseif os.host() == "linux" then
		include( path.join( coredir, "Linux", "Build", "linux.lua" ))
		include( path.join( coredir, "OpenGL", "Build", "opengl.lua" ))
	end

	include "engine.lua"
	include "game.lua"
```

Each included lua file then defines a single project, for example:
```
project "Core"
	OsoSetupProject()

	kind "StaticLib"
	targetdir( path.join( os.getenv( "WorkDir" ), "Oso", "Lib" ))

	files
	{
		"../**.cpp",
		"../**.h"
	}
```

This gives me the ability to pick and match the common libraries I need for any given application.

On Windows, this works fine.  I get a solution file with the self contained projects that build and work as expected.

However, this only worked for the first xcode workspace I set up.  Subsequent workspaces have the shared projects listed, but they're empty.  Clicking on one of them updates the information pane on the right, (and even that is mostly empty) but nothing else.  I can't view/change any settings, and they have no contents so subsequently don't contribute anything to the build, which then fails with a bazillion linker errors.

**What did you expect to happen?**
I would have expected the xcode projects to work in any workspace that includes them.  (Maybe xcode is even worse than it first seems and this isn't supported?)

**How can we reproduce this?**
It's a bit hard to include a complete example here, but the above shows roughly what my project structure is.

- [x] XCode (xcode)

**What version of Premake are you using?**
5.0.0-dev

**Comment by Jarod42** [comment]
`include` by itself shouldn't change behavior depending of generator, so it should be content/features used by project.

Hard to be sure with given info, but some things to check/test:

- You talk about several **workspaces** ("sharing"/generating same projects), do you use [`uuid`](https://premake.github.io/docs/uuid/) (those identifiers are used by visual studio and xcode)? [`externalproject`](https://premake.github.io/docs/externalproject)/[`includeexternal`](https://premake.github.io/docs/includeexternal/) might interest you too.

- Do you use different `location` for project and workspace? xcode has difficulty when there are not at the same place.
-

**Comment by crazydef** [comment]
The directory structure I have is something like this:

```
Build (common build scripts and premake files)
Core (common shared projects)
    Core
        Build (core.lua)
        sources, etc...
    Carbon
        Build (carbon.lua)
        sources, etc...
    etc...
TFG
    Build (premake5.lua + premake files for TFG projects)
    sources, etc...
OMP
    Build (premake5.lua + premake files for OMP projects)
    sources, etc...
```

So the idea is that the common project files should be created and built in the same location regardless of the workspace that includes them.  When building a project, I run Premake from the Build directory of that project.

As I mentioned, this worked fine for the first application, but failed miserably (for xcode only) for the second I tried to set up.  Premake itself doesn't complain about anything, and technically the projects are in the workspace - they're just useless - which does suggest it might be an xcode limitation more than a Premake bug.

**Comment by crazydef** [comment]
Ok, problem solved.  You can't have the same xcode project open in multiple workspaces at the same time.
