### ISSUE TITLE
Extra files in premake-5.0.0-beta2-windows.zip

### ISSUE THREAD

**Issue by learn-more** [premake/premake-core#2085]
**What seems to be the problem?**
The default Windows distribution seems to contain files that are not needed at all, or not needed for regular users.
- `*.exp`, `*.lib` - These files are used for linking against the library they belong to, but considering there are no headers present in the archive, they serve no purpose at all. (`example.dll` is not something that should be linked to from code, and probably neither should `luasocket.dll`)?
- `example.dll` - This file does not seem to be useful in a release distribution at all?
- `luasocket.dll`, `*.pdb` - These files are for debugging, should they be included in the default download?

In my opinion the `*.pdb` and `luasocket.dll` should rather go into a `premake-debug` archive or something like that, to keep the default distribution simple?

**Comment by Jarod42** [comment]
See https://github.com/premake/premake-core/discussions/1982

**Comment by learn-more** [comment]
Sorry, I did not find this question.

The 'package' command seems to work just fine (it results in a zip file with only premake5.exe).
@nickclark2016 did you not use the 'package' script?

**Comment by nickclark2016** [comment]
Honestly, it has been so long that I can't remember.  We really need to automate the release process.

**Comment by learn-more** [comment]
@nickclark2016 it should be possible to create a github action that runs when a tag is created, 
that will automatically create a release and push files to that release.

Would that be something that you are interested in?

**Comment by nickclark2016** [comment]
Closing this for now, as there are no actionable items.

**Comment by Jarod42** [comment]
@nickclark2016 : Possible actionable items is to have an automatic way to create the release/zip (github action?) for the future.

**Comment by nickclark2016** [comment]
Sure. The issue that I was running into is that the branch is made on a fork, which makes things a bit wonky (at least it was when I tried to automate it).  Would love to see someone with knowledge on GitHub actions take a stab at it, but it's beyond my knowledge.
