### ISSUE TITLE
Error: [string "src/actions/make/make_cpp.lua"]:59: attempt to perform arithmetic on a string value

### ISSUE THREAD

**Issue by kjk** [premake/premake-core#209]
Using premake locally build premake5 rev 97fc2a0a38bd37a51735ec67519aca4a8272d899 on osx.

Repro file:
* https://github.com/sumatrapdfreader/sumatrapdf/blob/7c3142a05486ead73bf2f71d7459462856b57453/premake5.lua
* https://github.com/sumatrapdfreader/sumatrapdf/blob/7c3142a05486ead73bf2f71d7459462856b57453/premake5.files.lua

I get the following error:
```
premake5 --verbose gmake
** Warning: the flags value NoExceptions has been deprecated.
   Use `exceptionhandling "Off"` instead
** Warning: the flags value NoRTTI has been deprecated.
   Use `rtti "Off"` instead
Building configurations...
Running action 'gmake'...
Generating gmake/Makefile...
Generating gmake/zlib.make...
Error: [string "src/actions/make/make_cpp.lua"]:59: attempt to perform arithmetic on a string value
```

This file works when generating vs2015 action and I just started porting it to generate makefile. 

It doesn't surprise me it doesn't generate something useful, but the error message mystifies me. Is "59" a line number in `make_cpp.lua` ? (the line is a return so I don't see how it could generate that error message).

**Comment by tvandijck** [comment]
the code in make_cpp.lua that causes this:
```lua
 			local toolset = premake.tools[cfg.toolset or "gcc"]
 			if not toolset then
				error("Invalid toolset '" + cfg.toolset + "'")
```
is not actually LUA.... should be using the '..' operator for that string concatenation.

https://github.com/Blizzard/premake-core/commit/81a39ae03e99c89f4c5a2e92e3b2e657b78418ca

I'll make a pull request for that one...

**Comment by tvandijck** [comment]
https://github.com/premake/premake-core/pull/213

**Comment by kjk** [comment]
It looks like the same problem exists in codelite_project.lua and gmake.lua.

Any idea why line reported in error message was off?

**Comment by tvandijck** [comment]
Yes, that is a side effect of the embedding of the scripts in release mode...
in a debug build you would get proper line information as well as callstack..

**Comment by starkos** [comment]
I believe this is fixed now. Feel free to reopen if you are still having the issue!
