### ISSUE TITLE
Issue `targetname` with gmake2 generator

### ISSUE THREAD

**Issue by diamante0018** [premake/premake-core#2100]
**What seems to be the problem?**
`gmake2` generator does not correctly use `targetname`

**What did you expect to happen?**
In my main premake.lua script I specify the `targetname` of my project. Premake5 will generate a make file containing the following keyword (taken from the release block generated by `configuration:Release filter)

...
else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/my_project_name.dll
OBJDIR = obj/Release/my_project_name
...

I suspect the issue is that the `TARGET` is not used in the `ALL_LDFLAGS`.
This causes that despite my project being marked as a shared lib, and having specified the target name, the mingw-64 compiler will assign a default name to the resulting file.
I will not get `my_project_name.dll`, instead the compiler defaults to `libmy_project_name.so`.
I have no indication this is a compiler bug.

**What have you tried so far?**
The GNU LD linker can accept the -o linker options to modify the filename and extension the outputted file should have. It can be forced using the following trick which works for me:

...
filter {"toolset:not msc*"}
linkoptions "-o output my_project_name.dll" -- or %{prj.name} ?
filter {}
...

I suspect Premake5 should generate a make file that does something similar with the linker flags or compiler flags in respect of the `targetname` directive.

**How can we reproduce this?**
https://pastebin.com/raw/DtZCgmGf

- [X ] GNU Makefile 2 (gmake2)

**What version of Premake are you using?**
v5.0.0-beta2

**Anything else we should know?**
I am available to provide my make file as well that was generated by premake5 without the source file names.

**Comment by Jarod42** [comment]
In which OS do you run premake?

`TARGET` should appears in rule

```
$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking sharedLib
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)
```
and so `LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)`
`$@` is to refer to target.

And `ALL_LDFLAGS` also contains `-Wl,--out-implib=""` or `-Wl,-soname=..` depending on os. (which might so create extra files).

**Comment by diamante0018** [comment]
I run it on a Debian OS. I am using the Linux binaries. I can check in a few.

**Comment by Jarod42** [comment]
Do you wish to generate makefile for windows? `premake5 --os=windows` might help in that regard.

Else, if it is for cross compilation, I can't help.

**Comment by diamante0018** [comment]
I have found the bug I believe.
This is when generating without --os=windows
```
...
else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/libt6-gsc-utils.so
OBJDIR = obj/Release/t6-gsc-utils
DEFINES += -DNDEBUG -DZLIB_CONST -DASMJIT_STATIC
...
```

**Comment by diamante0018** [comment]
I can confirm this behaviour is not documented and contradicts the default behaviour windows has (no special addition to the default name if the targetname is specified or specified w/ "SharedLib").
https://premake.github.io/docs/targetname/

**Comment by Jarod42** [comment]
Notice there is also [`targetextension`](https://premake.github.io/docs/targetextension) (".dll"/".so"/".exe"/..) and [`targetprefix`](https://premake.github.io/docs/targetprefix) ("lib"/"") which handle full name.
