### ISSUE TITLE
Toggling Visual Studio's new C++ Modules on/off in premake lua script

### ISSUE THREAD

**Issue by HerrDingenz** [premake/premake-core#2105]
**What problem will this solve?**
I have an issue with Visual Studio projects using "c++latest" and precompiled headers. Visual Studio has some new options for projects regarding their C++modules which can be found in the project's properties under `C/C++ -> Language`. They are `Enable Experimental C++ Standard Library Modules` and `Build ISO C++23 Standard Library Modules`.

Whenever I make changes to the premake script and regenerate the project these options are set to the standard (enabled) and the code won't compile because of missing include of my precompiled header in their files. I always have to manually set those options again after generating the solution/project.

**What might be a solution?**
Two new commands for the premake lua script that describes the project which can be used to set those values.

```
enablemodules "yes"
buildstlmodules "yes"
```
```
enablemodules "no"
buildstlmodules "no"
```

This way I can set those values already when generating the project via premake.

**What other alternatives have you already considered?**
I don't see any alternatives, but to set those values manually in the project settings.

**Anything else we should know?**
Not really.

**Comment by nickclark2016** [comment]
Can you share which settings that you are toggling so we can hunt down what in the project file would need to change?

**Comment by HerrDingenz** [comment]
Yeah sure. They are - like stated in my opening post - inside the Project settings under C/C++ -> Language
![module_settings](https://github.com/premake/premake-core/assets/52625955/473da693-26a0-4755-91bb-a5fc6e01a966)
Inside the project file itself it creates this `<BuildStlModules>false</BuildStlModules>` when the option is set to `No`.

**Comment by vulcan-dev** [comment]
I'm also stuck right now with this, it would be great to see this implemented soon

**Comment by nickclark2016** [comment]
I've got some time to sink my teeth into it, so I should be able to do that this week.
