### ISSUE TITLE
 Invalid toolset 'clang-14'

### ISSUE THREAD

**Issue by x3nb63** [premake/premake-core#2111]
**What seems to be the problem?**

running `premake5 gmake` says

```
Building configurations...
Running action 'gmake'...
Error: [string "gmake/gmake_cpp.lua"]:100: Invalid toolset 'clang-14'

```

this is after adding `toolset "clang-14"` to my workspace (for using this for all projects)

**What did you expect to happen?**

That it uses the clang 14 binaries such as `clang++-14`, `clang-cl-14`, ... `lld-link-14` ...

This is on Ubuntu Kinetic, which has clang packages this way. There is clang 11, 13, 14, 15 ... and I need 14 specifically. 

**What have you tried so far?**

It works with ``toolset "clang"`` but then compiling (`make`) fails cause it tries the `clang++` command, which does not exist in Ubuntu.

(and it would be 15, which may not compile my code anyways ...)

**How can we reproduce this?**

use `toolset "clang-14"` on  a Ubuntu Kinetic system with

- [X ] GNU Makefile (gmake)

**What version of Premake are you using?**

premake5 (Premake Build Script Generator) 5.0.0-dev

(the pre-built binary for Linux which I just download from https://premake.github.io/download)

**Anything else we should know?**

_(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)_

I'll look into that. This far I am evaluating whether premake is practial for what I have to build.

**Comment by Jarod42** [comment]
In trunk, we have warning:
> Warning: Unsupported toolset 'clang-14' used for language 'C++' for project 'app'...

**before** generator is launched. So "unrelated" to gmake action.

From code, it seems only msc support version.

Generated makefiles (both from gmake/gmake2) allow to overwrite `CC`, `CXX`, `AR`.
So, as workaround, you might use "normal" toolset, and passing the correct toolset when launching `make`, something like:
```
make CC=clang-14 CXX=clang++-14 AR=ar-14 config=release all
```

**Comment by x3nb63** [comment]
ah, thanks!

With this method it compiles my stuff for Linux like so:
 
`make CC=clang-14 CXX=clang++-14 AR=llvm-ar-14 LD=lld-14 config=release_linux`

adopting to compile for Windows like this fails...

`make CXX=clang-cl-14 CXXFLAGS="/EHsc -fms-compatibility -fms-compatibility-version=19" AR=llvm-ar-14 LD=lld-link-14 config=release_win64`

... after compile, when linking: LD appears not be respected and so the GNU linker `/usr/bin/ld` is used and that wont work.

However, when compiling manually I use `clang-cl-14 /c ...` to just compile and then run `lld-link-14` as subsequent step - would this be possible to tell premake?  (perhaps with a filter on `platform:Win64`?)

Can you estimate what it takes to complete the `clang-14` toolset support?

**Comment by Jarod42** [comment]
I think there are no LD (Makefile generated doesn't support msc toolset), link is done with CXX/CC IIRC.

The fix that I have in mind seems relatively easy. I will give it a try.

PRs take some time to be validated and merged though...

**Comment by Jarod42** [comment]
Just created a [PR](https://github.com/premake/premake-core/pull/2113). (you might be able to retrieve artefact from action to test it).

Wonder if `windres` has also a suffix `windres-14`?

`LD` stuff not fixed...

**Comment by x3nb63** [comment]
sorry for late reply, was busy. I see the test job but not where to download the artifact - perhaps I cant as non-project member.

I have a `llvm-windres-14` on my Ubuntu.

**Comment by Jarod42** [comment]
Not all artifacts was available because of a random failure in a network test :/
https://github.com/premake/premake-core/actions/runs/5700306822 have non-windows artefact though.

**Comment by x3nb63** [comment]
ok, so the `toolset "clang-14"` setting works with this PR and it shortens my Linux build to just `make  config=release_linux` - so far so good.

the Windows build is also shorter now and `clang-cl-14` appears to get called, as there is no `clang-cl` on my machine. But it still fails due to the wrong LD being used. And it would not even work with the correct LD cause clang-cl needs different options.... 
```
$ make CXX=clang-cl-14 config=release_win64
==== Building hello (release_win64) ====
Linking hello
clang: warning: unknown argument ignored in clang-cl: '-L/usr/local/lib' [-Wunknown-argument]
clang: warning: unknown argument ignored in clang-cl: '-L/usr/local/opt/SXNUMLIBS/lib' [-Wunknown-argument]
clang: warning: unknown argument ignored in clang-cl: '-L/usr/lib64' [-Wunknown-argument]                                                                                                       clang: warning: unknown argument ignored in clang-cl: '-shared' [-Wunknown-argument]                                                                                                            clang: warning: unknown argument ignored in clang-cl: '-lpcre2-8' [-Wunknown-argument]                                                                                                          /usr/bin/ld: Error: unable to disambiguate: -nologo (did you mean --nologo ?)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [hello.make:171: bin/Win64/Release/hello.dll] Error 1
make: *** [Makefile:37: hello] Error 2
```

... **and** its not so easy to do in one command, which is why my current build script does two commands

1. to compile: `clang-cl-14 /c <flags> <some>.cpp` 
2. to link a .exe:  `lld-link-14 /libpath:"/path/A" /libpath:"/path/B" ... /out:"<some>.exe" <some>.lib> <some>.obj ` 
3. to link a .dll:  `lld-link-14 /dll ... <paths> <some>.obj`

Perhaps `clang-cl` needs to be yet another toolset?  (that also allows a version like `clang-cl-14`)

**Comment by x3nb63** [comment]
after some more attempts I give up on the Windows build by "tricking" it to use `clang-cl`. What I tried is:

```
make CXX=clang-cl-14 \
   CXXFLAGS="/EHsc /Zc:dllexportInlines-"  \
   LDFLAGS="-fuse-ld=lld-link /link /libpath:/path/A /libpath:/path/B " \
   config=release_win64
```

the `LDFLAGS` are respected by the generated *.make files and so `lld-link` gets called. However, the command thats _presumably_ generated must be wrong cause the flags don't work as written above: `/link` must be the last argument because _everything_ after it gets passed to `lld-link`! Guess that somehow creates mess...

in my shell script I had to use it like so: `clang-cl-14 -fuse-ld=lld-link  <more flags> source.cpp /link /linkpath:/pathA`. If `source.cpp` is last the build is broken.

...

Whats with this issue? Should I close it? Split it? Or wait for a rc-release build?

(don't know how your workflow is)

**Comment by Jarod42** [comment]
I'm simple contributor here ;-) (with often divergent opinions than owners ^_^ )

The long term solution, IMO, would be
- apply version selection PR (or equivalent)
- the addition of new toolset `clang-cl`,
- change gmake/gmake2 to use `LD` and support extra toolset (as above one).

So the split in several ticket seems appropriate.
Keeping the one which need all fixes might be appropriate for the final goal.

**Comment by nickclark2016** [comment]
I'm a fan of splitting when it makes sense and there are discrete actions that can be closed with each PR.  Thank you for tackling this @Jarod42

**Comment by x3nb63** [comment]
all right, I made #2119 for the clang-cl part

this one right here can be closed along with the PR as far as I am concerned - it works for me ;-)

**Comment by Jarod42** [comment]
Associated [PR](https://github.com/premake/premake-core/pull/2113) is not yet merged though ;-)

**Comment by nickclark2016** [comment]
i misread the comment. reopening
