### ISSUE TITLE
os.outputof and filter; commands are executed regardless?

### ISSUE THREAD

**Issue by fzwoch** [premake/premake-core#212]
Considering the following snipped

```
filter "system:windows"
    local tmp = os.outputof("windowscommand -x -y -z")

filter "system:linux"
    local tmp = os.outputof("linuxcommand -x -y -z")
```

The local variable ```tmp``` seems to be correctly set depending on the platform that is being generated. However it looks like both commands are run. Since these commands are often platform specific these results in a couple of error messages during premake generation.

It this by design? Is there a way to avoid this?

**Comment by tvandijck** [comment]
this is a side effect of the design for sure.... just remember... lua has no scoping ,and "filter "..."" is just a call to a function, that has no effect on the execution order...

really what this looks like is:

```lua
filter("system:windows")
local tmp = os.outputof("windowscommand -x -y -z")
filter("system:linux")
local tmp = os.outputof("linuxcommand -x -y -z")
```

which may make it a little more obvious that really all we do is execute 4 lines of function calls.
what the function "filter" does is add a "block" to the internal premake tree... your tmp variable isn't even registered into that tree, so other then using it in the place right here you can't really do much with it...

The one thing to remember with premake is that the lua scripts are pretty much executed right there and then when loading a particular file... however, the expectation is that you call API's from premake to build up a tree of information for the premake action to inspect and output the right stuff...

I know this is a little bit of a generic answer, but without seeing the full script, and seeing what you are using tmp for... it is somewhat hard to give a suggested approach...

**Comment by fzwoch** [comment]
I thought it would be a side effect. The classic use case is of course the infamous ```pkg-config``` case. Assume I don't want to go the posix makefile way with back ticks but for example I aim for a xcode project file. Back ticks are not an option so I have to query the required flags at the premake step. It works quite well but of course when a windows user wants to create its visual studio project file there will be errors about pkg-config not being found as this is not really a command installed on the typical windows host..

It isn't a real blocker for me as the things work as I intended.. it is just that these "errors" just can pile up and in the end are no "real" errors as the result is not being used in this configuration.

**Comment by tvandijck** [comment]
yeah, so the way you can fix this in place is by doing:
that at least get you the right tmp value on each platform...

```lua
local tmp
if (os.get() == "windows") then
    tmp = os.outputof("windowscommand -x -y -z")
else
    tmp = os.outputof("linuxcommand -x -y -z")
end
```

**Comment by fzwoch** [comment]
Ah yes, I understand. That will work. I'm closing this then. Thanks.
