### ISSUE TITLE
Unable to compile current build using nmake

### ISSUE THREAD

**Issue by Nuclearfossil** [premake/premake-core#214]
As per the instructions in build.txt I ran the following in a VS 2013 command prompt in the locally cloned premake folder:

nmake -f Bootstrap.mak windows

This results in the following compile error:

.\build\bootstrap\lzio.obj
        .\build\bootstrap\premake_bootstrap.exe embed
Error: D:/dev/premake-core/src/_premake_main.lua:118: module 'xcode' not found:
        no field package.preload['xcode']
        no file '.\xcode.lua'
        no file 'D:\dev\premake-core\build\bootstrap\lua\xcode.lua'
        no file 'D:\dev\premake-core\build\bootstrap\lua\xcode\init.lua'
        no file 'D:\dev\premake-core\build\bootstrap\xcode.lua'
        no file 'D:\dev\premake-core\build\bootstrap\xcode\init.lua'
        no file '.\xcode.dll'
        no file 'D:\dev\premake-core\build\bootstrap\xcode.dll'
        no file 'D:\dev\premake-core\build\bootstrap\loadall.dll'
stack traceback:
        [C]: in function 'error'
        D:/dev/premake-core/src/base/globals.lua:79: in function <D:/dev/premake-core/src/base/globals.lua:76>
        (tail call): ?
        D:/dev/premake-core/src/_premake_main.lua:118: in function '?'
        D:/dev/premake-core/src/base/_foundation.lua:104: in function 'callArray'
        D:/dev/premake-core/src/_premake_main.lua:361: in function <D:/dev/premake-core/src/_premake_main.lua:360>
NMAKE : fatal error U1077: '.\build\bootstrap\premake_bootstrap.exe' : return code '0x1'
Stop.

**Comment by tvandijck** [comment]
Did you execute a "git submodule update --init" after cloning the repository?
the xcode module is a different repo, that is setup as a submodule, just cloning premake-core does not also clone the submodules...

**Comment by Nuclearfossil** [comment]
No, I didn't - missed that part in the readme.  I'll try again.

**Comment by Nuclearfossil** [comment]
Yeah, that did it
