### ISSUE TITLE
Warning when trying to create a project for vs2022 with toolset

### ISSUE THREAD

**Issue by hanagasira** [premake/premake-core#2140]
**What seems to be the problem?**

```lua
workspace "Examples"
    configurations {"Debug", "Release"}
    project "ExampleCpp"
        kind "ConsoleApp"
        language "C++"
        toolset "v143"
```

Execute the following command against this project file
```
premake5.exe vs2022 --file=premake5.lua
```

The following warning appears. The content of the generated project file is normal
```
** Warning: Unsupported toolset 'msc-v143' used for language 'C++' for project 'ExampleCpp'
```

**What did you expect to happen?**

No warnings are displayed.

**What have you tried so far?**

Changing the value of toolset to `v142` or `msc-v143` will give the same warning

**How can we reproduce this?**

- [x] Visual Studio 2022 (vs2022)
- [ ] Visual Studio 2019 (vs2019)
- [ ] Visual Studio 2017 (vs2017)
- [ ] Visual Studio 2015 (vs2015)
- [ ] Visual Studio 2012 (vs2012)
- [ ] Visual Studio 2010 (vs2010)
- [ ] Visual Studio 2008 (vs2008)
- [ ] Visual Studio 2005 (vs2005)
- [ ] GNU Makefile (gmake)
- [ ] GNU Makefile 2 (gmake2)
- [ ] XCode (xcode)
- [ ] Codelite
- [ ] Other (Please list below)

**What version of Premake are you using?**

561f9a97d3f68fce1f0340bf33213ba8aa588806

**Anything else we should know?**

Row added in #1997

https://github.com/premake/premake-core/blob/561f9a97d3f68fce1f0340bf33213ba8aa588806/src/base/action.lua#L297

The value of `valid_tools` is `{ "msc", "clang" }`
The value of `toolset` is `"msc-v143"`

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

**Comment by Jarod42** [comment]
Should be fixed by https://github.com/premake/premake-core/pull/2113
