### ISSUE TITLE
How to modify the Clang executable value via CLI?

### ISSUE THREAD

**Issue by GasimGasimzada** [premake/premake-core#2159]
**What's your question?**

I am installing LLVM using the [llvm.sh file](https://apt.llvm.org/):

```sh
./llvm.sh 16 all
```

This creates versioned executables for clang and clang++ files: `clang-16` and `clang++-16` respectively. Is there a way to define the version in premake5 via CLI. Currently, I am setting the toolset using `--cc` flag:

```sh
premake5 --cc=clang gmake
```

and manually creating a link for clang that points to the default version:

```sh
sudo update-alternatives /usr/bin/clang clang /usr/bin/clang-16 0
sudo update-alternatives /usr/bin/clang++ clang++ /usr/bin/clang++-16 0
```

But I would rather use premake for this without modifying executable paths. Is there any way to set these values? I tried ot use `--cc=clang-16` but it says the value is invalid.

**Comment by Jarod42** [comment]
(Merged) https://github.com/premake/premake-core/pull/2113 should allow to select toolset version with `-cc=clang-16`.

**Comment by GasimGasimzada** [comment]
Amazing thank you!
