### ISSUE TITLE
Concurrency problem of prebuildcommands() function 

### ISSUE THREAD

**Issue by lailongwei** [premake/premake-core#2161]
**What seems to be the problem?**
When using `make -jxxx` and xxx > 1, building jobs running but `prebuildcommands()` has not been finished, see below config:
```lua
project 'test_proj'
   prebuildcommands("echo 'sleeping...' && sleep 10 && echo 'end sleep")
   -- add some files to build
   -- ... 
```
when using `make -j8 -f test_proj.mak`，will see source file compiling will be start but the prebuildcommands() has not been finish.

**What did you expect to happen?**
real build command running after all prebuild commands execute finished.

**What have you tried so far?**
see above.

**How can we reproduce this?**
Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) we can use to replicate the problem in our own development environments. Use [code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to format code and console output nicely.

- [ ] Visual Studio 2022 (vs2022)
- [ ] Visual Studio 2019 (vs2019)
- [ ] Visual Studio 2017 (vs2017)
- [ ] Visual Studio 2015 (vs2015)
- [ ] Visual Studio 2012 (vs2012)
- [ ] Visual Studio 2010 (vs2010)
- [ ] Visual Studio 2008 (vs2008)
- [ ] Visual Studio 2005 (vs2005)
- [x] GNU Makefile (gmake)
- [x] GNU Makefile 2 (gmake2)
- [ ] XCode (xcode)
- [ ] Codelite
- [ ] Other (Please list below)

**What version of Premake are you using?**
5.0.0-dev

**Anything else we should know?**
...

**Comment by nickclark2016** [comment]
Can you share the generated makefile from gmake2?

**Comment by Jarod42** [comment]
Whereas gmake creates only
```
all: prebuild prelink $(TARGET)
```
gmake2 seems to be correct:

```
prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

$(OBJECTS): | prebuild
```
