### ISSUE TITLE
how to set /Zc:__cplusplus command line in premake5?

### ISSUE THREAD

**Issue by Intervel** [premake/premake-core#2163]
hello guys! im still new at premake5, how to set /Zc:__cplusplus command line?
![1](https://github.com/premake/premake-core/assets/86478025/e61e04c3-4304-4e58-a413-e6aec29fb879)
![2](https://github.com/premake/premake-core/assets/86478025/9ac056b2-5f8a-4b76-991b-ac2770908455)

i want to set /Zc:__cplusplus. how to do that?

**Comment by nickclark2016** [comment]
You can pass build options, like so:
```lua
buildoptions { "/Zc:__cplusplus" }
```

**Comment by Jarod42** [comment]
Even better, protect it with correct filter:

```lang-lua
filter "toolset:msc*"
  buildoptions { "/Zc:__cplusplus" }
filter {} -- reset filter
```
