### ISSUE TITLE
How can I create subgroups within a group?

### ISSUE THREAD

**Issue by luizfernandonb** [premake/premake-core#2164]
I have a project with the following folders: `src/admin/base`

The solution is inside the `src` folder, and I have already created the group for the `admin` folder, but how do I also create a group in the `base` folder?

I've tried
```
group "admin"
    group "base"
        project "..."
```
but it doesn't work, any ideas on how to solve this?

**Comment by Jarod42** [comment]
indentation is just aesthetic in Lua

So you create an empty `group "admin"` followed by a `group "base"`.

Maybe [`vpaths`](https://premake.github.io/docs/vpaths/) or directly `group "admin/base"`...
