### ISSUE TITLE
Command line arguments?

### ISSUE THREAD

**Issue by crazydef** [premake/premake-core#2173]
**What's your question?**
Is there a reference page detailing all the standard command line arguments for Premake?

https://premake.github.io/docs/Command-Line-Arguments only explains how to create new ones.

`premake5 --help` just throws an error.

**Comment by Jarod42** [comment]
`premake5 --help` should do the job...
But if you have an "invalid" premake5.lua, error might happen.

I recommend to have
```
if (_ACTION == nil) then
	return
end
```
at the beginning of the script, after potential `newaction`/`newoption`.

**Comment by crazydef** [comment]
I didn't have any premake5.lua file in the directory where I was running it.  I just wanted to check the command line args to confirm my suspicions about a different script I was looking at.

**Comment by nickclark2016** [comment]
Can you confirm what version of premake you are using and the operating system? Running 5.0.0-beta2 from a folder without premake files on Windows 11, I am not able to reproduce.

**Comment by crazydef** [comment]
Hmm, I just tried again and it also works for me now.  (On Linux.)  Not sure how I managed to break it earlier.

But well, it's clearly not a problem.  Sorry for the confusion.  :)

**Comment by nickclark2016** [comment]
No worries!

**Comment by crazydef** [comment]
Follow up question:  If I have a working `premake5.lua` file that loads extension modules, will the help text be updated with new options and parameters added by an extension?

(I.e., can I use `premake5 --help` to confirm that a module is being loaded correctly?)

**Comment by Jarod42** [comment]
Yes (as long as `newaction`/`newoption` is called).
but as I said previously, script should be valid.
I (wrongly) used to use `_ACTION` which is `nil` with `--help`, so dereferencing it might be problematic...
