### ISSUE TITLE
[VS] Source Build Help

### ISSUE THREAD

**Issue by OfficialModdz** [premake/premake-core#2179]
**What are you trying to do?**
I opened the Premake5.sln in VS 2022, I set my path to my scripts and then tried to build it in Debug x64, was I not supposed to do that?

**What problem are you having?**
My issue is that the binary Premake5 doesn't even open when I click on it, and I don't know how to add it to my PATH if it doesn't open...

**What have you tried so far?**
I've tried to use where.exe (CMD & Shell failed to locate my nmake.exe) and did a few more steps like trying the previous version but to no avail I still land here..

**What version of Premake are you using?**
`premake5 5.0.0`

**Anything else we should know?**
I can't use this if I can't build it let alone add it to my PATH, some in depth help would be grand!

**Comment by Jarod42** [comment]
> Premake5 doesn't even open when I click on it

It is a command line tool, so instead of a terminal where the exe is and type `premake5.exe --help`

> I set my path to my scripts

Unsure what you mean here...

Do you want to improve/modify premake5, or use it for your project?
For the later, you might just download the executable.

To build it, `Bootstrap.bat vs2022` should work.
generated solutions should also work.

**Comment by OfficialModdz** [comment]
![image](https://github.com/premake/premake-core/assets/155321100/646f24c0-6283-4b51-87fd-9b8f4bf3eb43)
This is what I was instructed to do and I was wondering how cause premake5 wasn't operating the way I thought it was supposed to. How exactly would I add it to my sys PATH?

**Comment by Jarod42** [comment]
> run prebuild script `premake5 vs2022`
It should be done in a terminal (You might open it with Win+R cmd or in a system explorer, shift right click, open in a terminal).

An alternative is to create a script you can double click:

run_premake.bat
```
premake5.exe vs2022
@pause
```

> How exactly would I add it to my sys PATH?
Simpler would be to copy paste premake5.exe near premake5.lua
(as current directory is in PATH by default).

> I can't use this if I can't build it

In fact, you can, just download appropriate binaries (even official one or "nightly" ones)

**Comment by OfficialModdz** [comment]
I have successfully fixed my issue. I found my sys PATH and put the premake5 binary into it, then I compiled my project and am able to use it. Thank you for your help!!
