### ISSUE TITLE
Issue trying to fix x86 Linux build

### ISSUE THREAD

**Issue by redorav** [premake/premake-core#2185]
I'm trying to fix the x86 Linux build as was reported [here](https://github.com/premake/premake-core/commit/897b6469bfe5a6a7fc1a6b6bc9b46ee28f18f9a9#commitcomment-138286566), as well as some other small issues I have. I found the bit of code that does the remapping, it's a function archFromConfig that looks like this:
```lua
function vstudio.archFromConfig(cfg, win32)
	local isnative = project.isnative(cfg.project)

	local arch = architecture(cfg.system, cfg.architecture)
		
	if not arch then
		arch = iif(isnative, "x86", "Any CPU")
	end

	if win32 and isnative and arch == "x86" then
		arch = "Win32"
	end

	return arch
end
```

It looked like it should be pretty easy to change, but it turns out it's more complicated for some reason. I tried doing

```lua
if win32 and isnative and arch == "x86" and cfg.system ==p.WINDOWS then
```

and also tried

```lua
if win32 and isnative and arch == "x86" and cfg.system ~=p.LINUX then
```

but neither of those work, they break the windows platform that appears as <Platform>x86</Platform> instead of the current <Platform>Win32</Platform>

I notice that this function function vstudio.archFromConfig(cfg, win32) gets called with win32 set to true in many places, and I'm not sure what it means or why the system doesn't match what I'm trying to do. Any advice on how to move forward?

**Comment by samsinsane** [comment]
Yeah, this Win32 hack is a massive pain, here's how it was resolved in the Android module: https://github.com/premake/premake-core/blob/fa2405d4857c13b625bce8159e0d03cbb058aa43/modules/android/vsandroid_vstudio.lua#L32-L38

I also resolved it in my VSLinux module in a [similar way](https://github.com/LORgames/premake-vslinux/blob/29649321c3ddd2fe14dec7ac9f50da279f66c65d/vslinux.lua#L14-L20).

**Comment by redorav** [comment]
This should be fixed already
