### ISSUE TITLE
Premake interaction with source control

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#221]
We need to think of strategies to make premake work nice with various source control systems.
The classic problem with premake is that the user does a pull and forgets to re-run premake, resulting in a build with a stale project. Happens way too often to ignore! (in the order of a couple of times a day at my work)

With Git, it's possible to run premake with even hooks, but it's pretty awkward and requires configuration by each user manually. There's no way to commit that to the repo.
Another option I've seen is to re-run premake as a pre-build step, but that just sucks; it's a slow step before every build.

What other strategies have people tried?

I'm wondering if we may be able to improve the situation in premake? Perhaps we could have premake detect that there's no work to do and skip the rebuild if nothing is dirty (making it more viable to run as a pre-build step), but this is hard to detect, and it's still pretty lame.

**Comment by tvandijck** [comment]
One of the things I would like to see is 'caching' of the baked step in premake. The biggest problem I'm seeing with premake is that it always needs to load and process the entire solution, even though maybe only one cpp file got removed/added in one project (out of 83 in our case). And with the recently merged "write only when something changes" change, it really then only writes out that one project that changed....

it would be awesome, if we could somehow figure out what has changes (by hashing the filelists and settings or whatnot) and don't do all the expensive stuff for projects that have not changed. Our premake times are up to 29 seconds now, and that is definitely a big cost. Part of that is the communication with our packageserver over http, but I'd say at least 25 seconds is in premake allocating memory and building tables.... lots and lots of tables.. (over 1.2Gb of it).

**Comment by TurkeyMan** [comment]
Jeezus! What do you do in your scripts that could lead to 1.2gb of tables? How many platforms/configs are in your builds?

**Comment by tvandijck** [comment]
Uhm... let me have a look:

- 4 configs (DebugSlow, DebugFast, ReleaseProfile and ReleaseCandidate).
- 2 platforms... x86 and x86_64.
- 122 projects, spanning a total of ~38,000 files out of 181,343 files that exist in the project folder.

Peak premake5.exe in just the "windows task manager" sits at 1,227,234 K (So about ~1.2Gb)
And it takes 26,288ms for it to figure out that no files have changed...

**Comment by tvandijck** [comment]
That said, I need to make a premake profiler to profile performance and memory usage, so we can better investigate this... 

I did this one:
https://github.com/Blizzard/premake-core/commit/9d173fae0ac9f9b7a9e5a7c05df9d2c5c9b32f5a

for performance, but I have not used it too much yet..

**Comment by starkos** [comment]
These issues don't really effect me, so I'm going to spectate this discussion. But I would be surprised if there weren't some really easy memory gains to be had in the baking code.

**Comment by starkos** [comment]
Oh, and in case you haven't seen it: I keep a copy of the pepperfish profiler in the `tests/` folder. I think you can add the `--profile` flag to produce a time report for the unit tests, and I *think* for project generation too? Haven't looked at since I did the last performance pass last year…two years? It's all blurry.

Pepperfish doesn't do memory reports though, as far as I know.

**Comment by TurkeyMan** [comment]
Perhaps we can we spin off a separate issue for looking into memory consumption? That's kinda OT here.

**Comment by starkos** [comment]
Is this still an issue? I believe some optimizations were done since this was asked.

**Comment by TurkeyMan** [comment]
I don't think this was a question of optimisation, but a question of strategy, or better, and OOTB recommendation for users. I don't think we're there.
I think this is something that could be discussed and worked on as a feature?

**Comment by unusual-aspect** [comment]
The only way i see that can be solved is 'custom shell/batch' file like: load.cmd|sh

Where you have (pseudo code):
if(repo exist)
  git update ...
  premake .
else
  git get
  premake .

load solution file ...

**Comment by Jarod42** [comment]
About the files addition/removal, CMake's strategy is to ask user to list files without globbing, and they have a working [`editorintegration`](https://premake.github.io/docs/editorintegration/) (Our is only partially working with visual Studio and requires extra (obsolete) module/plugin)
That strategy would allow to re-run premake only when premake5.lua has changed.

That won't solve globbing usage though.

Another usage/issue when changing branch or adding new tag is that premake5.lua might have file generation from git info
(a "version.h" filled with current reachable tag) and here, files architecture doesn't change, neither premake5.lua content.


> With Git, it's possible to run premake with even hooks, but it's pretty awkward and requires configuration by each user manually. There's no way to commit that to the repo.

I think it is the way to go.

With a `gitintegration "On"` we may generate `.git/hook/post-checkout` with content to relaunch premake
