### ISSUE TITLE
Is CodeCoverage Flags working for gmake2 g++

### ISSUE THREAD

**Issue by kawaegle** [premake/premake-core#2223]
_Before asking a new question, please [use the issue search feature](https://github.com/premake/premake-core/issues) to see if your question has already been asked. Help us help you!_

**What's your question?**
Is the CodeCoverage flag enable for gmake2 gcc g++ ? 
on the documentation it say Needs documentation [flags doc](https://premake.github.io/docs/flags/#parameters) and the edit date is on 2021. 

**Anything else we should know?**
trying to make some CICD on my project that use premake as build solutions

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to questions like these!)*

**Comment by nickclark2016** [comment]
No. Code Coverage is only available in D.
