### ISSUE TITLE
How to build arm64 arch premake tool?

### ISSUE THREAD

**Issue by lailongwei** [premake/premake-core#2229]
Hi, I try to compile arm64 arch premake tool, but failed(in m3 macbook)

by default, use `make -f Bootstrap.mak osx` output file arch format is x64, so i try to add `CONFIG=arm64` option to build, see below:

> cmd:make -f Bootstrap.mak PLATFORM=arm64 osx
> error: 
>> ./build/bootstrap/premake_bootstrap --arch=arm64 --to=build/bootstrap gmake2
>> Error: invalid value 'arm64' for option 'arch'

**Comment by samsinsane** [comment]
I don't have a mac to test with, but I was able to reproduce the `invalid value` issue and specifying `ARM64` instead of `arm64` appears to resolve the issue. Does this also work for you?

**Comment by Codinablack** [comment]
You need to make it all caps. Here is an example of how I use ARM64 in my premake for builds

![image](https://github.com/user-attachments/assets/66fdfeef-59fa-4257-ac0a-371308d20fb9)
![image](https://github.com/user-attachments/assets/48516628-c301-4dad-8c74-a2a13a3eeacc)

I ran into the same issue myself when trying to get it running, its really just as simple as capitalizing all the letters.

**Comment by lailongwei** [comment]
> I don't have a mac to test with, but I was able to reproduce the `invalid value` issue and specifying `ARM64` instead of `arm64` appears to resolve the issue. Does this also work for you?

Thanks, it worked!
