### ISSUE TITLE
Support per-file flags in gmake action

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#223]
gmake doesn't support per-file flags.

**Comment by tvandijck** [comment]
Use gmake2 module: https://github.com/premake/premake-core/pull/803

**Comment by samsinsane** [comment]
Given that we're planning to drop `gmake` for `gmake2`, I see no reason to keep this open as `gmake2` does support per-file flags. Please feel free to reopen if you guys disagree.
