### ISSUE TITLE
VS does not set stdafx.cpp as `Create (/Yc)`

### ISSUE THREAD

**Issue by Luieitalian** [premake/premake-core#2234]
**What are you trying to do?**
I'm trying to generate precompiled headers for a VS2022 project.

**What problem are you having?**
When I generate a VS2022 project with `premake5 vs2022`, It sets the **Precompiled Header** option to `Use (/Yu)` instead of `Create (/Yc)` for stdafx.cpp file.

When I check the properties of `stdafx.cpp` via right-click and properties -> C/C++ -> Precompiled Headers:
- Precompiled header has option: `Use (/Yu)`
- Precompiled header file is: stdafx.h
- Precompiled header output file is: `$(IntDir)$(TargetName).pch`

I think `stdafx.cpp` should have the option `Create (/Yc)`.

**What have you tried so far?**
I have tried changing `Use (/Yu)` to `Create (/Yc)` in the VS settings and it generated the pch file properly when built. Is there a way to do this in premake script? Or am I missing something?

Also I want to ask if there is a way to change the name of the pch file to whatever I want in premake script?

**My premake script**
```lua
-- premake5.lua

local includeDir = "include"
local libDir = "lib"
local sourceDir = "src"

workspace "LearningOpenGL"
    configurations { "Debug", "Release" }

project "Example"
    kind "ConsoleApp"
    language "C++"
    cppdialect "C++17"
    architecture "x86_64"
    targetdir "bin/%{cfg.buildcfg}"

    pchsource (sourceDir .. "stdafx.cpp")
    pchheader "stdafx.h"

    libdirs { libDir }
    includedirs { includeDir }

    files { includeDir .. "/**.h", sourceDir .. "/**.cpp" }
    -- removefiles { "src/glad.cpp", "src/main.cpp" }

    links { "glfw3" }

    filter { "system:windows" }
    links { "gdi32" }

    filter "configurations:Debug"
    defines { "DEBUG", "Wall", "pedantic" }
    symbols "On"

    filter "configurations:Release"
    defines { "NDEBUG" }
    optimize "On"
```

**What version of Premake are you using?**
 Premake version: 5.0.0-beta2

**Comment by Jarod42** [comment]
You have a typo:

```
local sourceDir = "src"
-- ...
pchsource (sourceDir .. "stdafx.cpp")
```
It results in `pchsource ("srcstdafx.cpp")` and not `pchsource ("src/stdafx.cpp")`

It should be:
```
pchsource (sourceDir .. "/stdafx.cpp")
```
or
```
pchsource (path.join(sourceDir, "stdafx.cpp"))
```
or
```
local sourceDir = "src/" -- extra / for easy concatenation
```

**Comment by Luieitalian** [comment]
Oh yes, thank you.
