### ISSUE TITLE
Postbuild commands don't run again after the first build

### ISSUE THREAD

**Issue by N1CK1111** [premake/premake-core#2236]
**The main issue**
Upon running make a second time in any premake project that uses gmake2 postbuild commands don't run.

**My Workaround**
Despite postbuild commands not running again after the first build of a project prebuild commands are completely unaffected so using prebuild commands worked just fine for me.
Another workaround is to just run make clean and run make again everytime you want your postbuild commands to run.

**How can we reproduce this?**
Simply run make in any gmake2 premake project that has postbuild commands twice.

- [ ] Visual Studio 2022 (vs2022)
- [ ] Visual Studio 2019 (vs2019)
- [ ] Visual Studio 2017 (vs2017)
- [ ] Visual Studio 2015 (vs2015)
- [ ] Visual Studio 2012 (vs2012)
- [ ] Visual Studio 2010 (vs2010)
- [ ] Visual Studio 2008 (vs2008)
- [ ] Visual Studio 2005 (vs2005)
- [ ] GNU Makefile (gmake)
- [x] GNU Makefile 2 (gmake2)
- [ ] XCode (xcode)
- [ ] Codelite
- [ ] Other (Please list below)

**What version of Premake are you using?**
5.0.0-beta2

**Comment by Jarod42** [comment]
With gmake2 exporter, postbuild command is run when target is built.
If target doesn't need to be regenerated (i.e re-link), then, we consider there are no build, so no postbuild commands to execute.
