### ISSUE TITLE
How to open c++20 modules feature?

### ISSUE THREAD

**Issue by ericyonng** [premake/premake-core#2239]
Env: linux/clang15
Premake Version: dev latest
Hello, I'm building my projects using premak5, an error occurred: 
HelloFoo.cppm
TestConceptModules.cpp
../../testsuit/testsuit/testinst/TestConceptModules/TestConceptModules.cpp:32:8: fatal error: module 'HelloFoo' not found.

My project: https://github.com/ericyonng/CrystalNet

parts of premake5.lua
![image](https://github.com/user-attachments/assets/a29f936c-1a8d-4fdc-9cb3-7c2307089002)
![image](https://github.com/user-attachments/assets/3af2989b-0b3b-4510-9df3-866f4c6c29d4)

HelloFoo module code:
file:HelloFoo.cppm
![image](https://github.com/user-attachments/assets/af15f7d6-bf1b-4927-ae58-3ba78a5eb701)

TestConceptModules.cpp file:

![image](https://github.com/user-attachments/assets/39567953-d610-46df-af12-ec6e64e0613f)

Thanks!

**Comment by Jarod42** [comment]
As stated in doc, [`enablemodules`](https://premake.github.io/docs/enablemodules/) is only available for visual studio.

**Comment by ericyonng** [comment]
> As stated in doc, [`enablemodules`](https://premake.github.io/docs/enablemodules/) is only available for visual studio.

That's it, thanks!
