### ISSUE TITLE
libdirs  specifies the library search paths for visual studio

### ISSUE THREAD

**Issue by kinsung** [premake/premake-core#224]
When build a windows application:
kind (WindowedApp)

case 1.  usr_lib_dirs = { "../../3rd_usr_lib",  "../lib"}
libdirs  (usr_lib_dirs)  -- specifies the library search paths

Error: .../premake5.lua:119: attempt to concatenate global 'usr_lib_dirs' (a table value)

case 2. usr_lib_dirs = "../../3rd_usr_lib; ../lib "

No error occurs, but in the vcproj file, AdditionalLibraryDirectories="..\..\lib  ", thus, "../../3rd_usr_lib" is not exist.

**Comment by TurkeyMan** [comment]
Can you show some more code?
'case 1' is correct, and working for me with no error:
```
		usr_lib_dirs = { "../../3rd_usr_lib", "../lib"}
		libdirs (usr_lib_dirs)
```
'case 2' is wrong code.

Maybe you have another error nearby?

**Comment by starkos** [comment]
Case 1 works okay for me too. I'm going to close this one for now; if you can provide a different example feel free to reopen!
