### ISSUE TITLE
attempt to call a nil value (global 'clangtidy')

### ISSUE THREAD

**Issue by goldsphere48** [premake/premake-core#2286]
Here is part of my config:

```
workspace "Wismut"

-- Some other stuff

    clangtidy("On")
    runcodeanalysis("On")

```
    
After run premake generator I get an error:
`attempt to call a nil value (global 'clangtidy')`
These commands were written in the workspace scope, but they also did not work in the project scope. I checked the documentation and made sure that I wrote the command correctly and used the correct argument values, I also checked the source code and made sure that everything is as stated in the documentation. I can't figure out where I went wrong. Please help.

**Comment by nickclark2016** [comment]
What version of Premake are you on? This is something that you'll need a source build for, as it's not in a release yet.

**Comment by Jarod42** [comment]
From [doc](https://premake.github.io/docs/clangtidy/)

> Availability
> Premake 5.0.0 beta 3 or later for Visual Studio 2019 and later.

That one is not yet released,
so require a nightly build (or build it yourself)

**Comment by goldsphere48** [comment]
I builded it from master, everything worked, thanks!

**Comment by samsinsane** [comment]
Closing based on previous comment.

**Comment by 2vidb51h** [comment]
@Jarod42 Where to get a nightly build? I can't find it on the releases page!

**Comment by nickclark2016** [comment]
Check GitHub Actions

**Comment by 2vidb51h** [comment]
I can't find the artifacts to download!

**Comment by Jarod42** [comment]
I saw several artefacts from https://github.com/premake/premake-core/actions/runs/11350222290

**Comment by 2vidb51h** [comment]
It turns out that I need to click into a specific job and expand `Uploads Artifacts` section to see the download link :facepalm:
