### ISSUE TITLE
Android Visual Studio changes

### ISSUE THREAD

**Issue by redorav** [premake/premake-core#2308]
Hi,

I've been using the Android integration in Premake for a while now for my projects. The Android integration creates what VS used to call a "Native Activity" and with a bit of glue code it worked fine. Fast forward a few months and MS has removed the native activity completely as everything that was ant-based is deprecated, and while compiling the native activity works (in VS2019) you cannot install it anymore because the way applications used to be installed in debug mode (copying to the tmp folder and running the apk) doesn't work now due to permissions.

The only way to create an application in VS2022 these days is using Gradle, but I've struggled to make sense of it and even a basic clean project doesn't compile, it gives all sorts of Java, Gradle and combinations of those errors. There is very little information out there regarding this change.

Can anyone with more Android experience know what's up with the Android situation on VS2022? Does the Premake backend need to change to accommodate Gradle projects?

I've found out in the meantime that Google supplies an official [Android GDK](https://developer.android.com/games/agdk/overview) for C/C++ projects. Would it make sense to integrate that as well as part of core?

Many thanks

**Comment by redorav** [comment]
Hmm does this work with visual studio? I'll try it out

**Comment by redorav** [comment]
Hi, I generated the project but it's clearly not intended for use with Visual Studio, it still reports as being Win32, doesn't know anything about Gradle, etc. I think the intention there is for people who already use Premake to use the Android Studio IDE instead for Android development

**Comment by redorav** [comment]
Right I see what you mean now, I'll investigate to see what it is they're generating and how it works. One thing I noticed is that Android Studio is a lot more dynamic about fixing configuration errors than Visual Studio is, it starts downloading and updating plugins and updates automatically without me really knowing what's going on. Android is a difficult ecosystem

The VS hello world is meant to work out of the box but I've noticed that any local modifications to e.g. the Java JDK or the Android SDK throw it off quite a bit, perhaps I just need to understand this a bit better. In any case, an extension to the current core plugin is probably necessary

**Comment by ifarbod** [comment]
> Can anyone with more Android experience know what's up with the Android situation on VS2022? Does the Premake backend need to change to accommodate Gradle projects?

Android MDD (the MSBuild integration) is pretty much abandonware. Microsoft is only interested in .NET, and they didn't keep up with NDK releases well enough. The last version with a working Ant/MDD is Visual Studio 2022 v17.2—that's an out-of-date version, but you can install it side by side. It's in the LTSC branch. The last version of NDK that works well with it is R22, but you can also use R23 with a few `.props` tweaks in the VS installation folder.

**Comment by redorav** [comment]
Have you had this experience with it as well then? For my immediate purposes I rooted a spare phone I had and went ahead with VS2019 and the Ant-based workflow, I just need it for the unit tests of a library I have. I wasn't able to get the gradle version going yet, I think I was getting relatively close though, the library was being packed into the apk but I wasn't able to run the native activity. The debugger was crashing too but I think it's because it wasn't bundling the gdb library as well (which I can see inside the ant-based one). Overall it does look like they mostly care about .NET and the Xamarin stuff so I may be out of luck. Android Studio was a bit of a mess too, I couldn't get it to compile in a reasonable timeframe, looks like you need to understand Gradle properly before getting anything out of it

**Comment by ifarbod** [comment]
@redorav The GDB debugger included in Visual Studio didn't work for Android 14 the last time I tried. I have several older devices running Android 8, 11, and 13, and they work fine with these. It seems to be related to scoped storage restrictions that LLDB, the newer debugger, has fixed. If Microsoft's native Android integration were open-source, I'd attempt to fix it myself.

You also mentioned running unit tests on an Android phone for a library. If you don't need to run an Activity, you can compile the test runner as a standalone binary, copy it to /data/local/tmp, apply chmod +x, and run it there.

Regarding Android Studio, I have a minimal project that uses Gradle with XMake. Maybe give this a try?
[example-xmake-android-project](https://github.com/ifarbod/example-xmake-android-project)

Also about Gradle being slo, to compile faster, you can enable these Gradle flags:

```properties
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
```

**Comment by redorav** [comment]
@ifarbod interesting find about the Visual Studio debugger not being compatible.

As for my library, I do run a native activity as my project is in C++, and I've been able to debug and put breakpoints all along in the Ant-based version of this, which is why I'd like this Gradle-based thing to work properly :/

I've not tried xmake but as far as I can tell it bypasses all the Visual Studio project properties and does its own thing? I might take a deeper look, are you experienced with it? So far I really like Premake because it integrates with the tools instead of doing its own thing via command lines

**Comment by ifarbod** [comment]
@redorav If you want the Gradle-based version to work on your rooted (preferably SELinux-permissive) phone, you can try bundling the `gdbserver` manually in the generated APK, take the binary out and place it in `jniLibs` or so.

As for XMake, it is well developed, on par with CMake/Meson, and even better in some aspects. I highly suggest trying it out, especially if your projects are multi-platform. Maybe pick it up for a newer project you start? Or try porting your build system to it if you have the time/resources to do so.
I successfully maintain a single codebase that runs on Windows, Linux, Android, and WASM. **I've previously used Premake for 5+ years** but sadly I ran into many issues and [Premake-next (the v6.x branch)](https://github.com/premake/premake-core/tree/6.x) being canceled was the final nail in the coffin for me, personally.

**Comment by redorav** [comment]
@ifarbod I gave xmake a fair shot and I was not impressed. I created a straightforward Visual Studio project and not only does it not respect the properties that you set on the project (which I guessed it wouldn't based on it calling an external build), it didn't set breakpoints or debug properly on a simple executable. I may come revisit when I have a bit of time but overall I'd much rather Premake is improved.

I don't much like CMake to be honest, a pretty terrible syntax. As for Premake 6 I don't really know where it's at at the moment, I don't think I would immediately jump as I've always been very happy with Premake as it is and the contributors are doing an amazing job with it.

**Comment by ifarbod** [comment]
@redorav I love Premake and I've been using it for more than 8 years, if you run a serious multi-platform project, you'll eventually run into **limits**, I had to fork Premake to continue using it. I can elaborate more if you want me to.

For my needs alone, Xmake is a better option right now, if you've ever used languages with serious ecosystems like Rust with Cargo, you'd love to have something like that in the C++ world.

**Comment by redorav** [comment]
Yeah please elaborate, are they things you find that are not possible to fix? I haven't dabbled too much into Rust so I cannot say

**Comment by ifarbod** [comment]
@redorav Alright, picture this: you’ve got a project that needs to be compiled for all sorts of platforms—Windows, Linux, Android, and WASM.
Each platform comes with its own compilers and toolchains. For example, on Windows, you can pick from a bunch of options like MSVC, MinGW, Clang, and even GCC from Msys2/Cygwin.

Now, throw in multiple configurations (debug, release, final, you name it) and different architectures (x86, arm64, etc.), and things can get a bit crazy. You end up writing a lot of `filter { ... }` blocks in your Premake script.

The thing is, Premake mainly supports just Windows and Linux out of the box. It usually sticks to the more common setups—like Windows with MSVC—so other options often get overlooked.

Where it falls short, there are some community plugins you can try, like the one for Android Studio. But honestly, from what I’ve seen, these tend to be one-and-done projects (see https://github.com/TurkeyMan/premake-emscripten for example). They also don't follow the same quality standards as core Premake so they usually contain bugs.

Plus, the Android Studio plugin still generates Gradle projects with the old Groovy DSL, and the NDK support leaves a lot to be desired. When I was still using Premake, I had to add quite a few missing features myself! However, I can see they’re _probably_ [working on it again](https://github.com/polymonster/premake-android-studio/commits/master) - which is good.

**Comment by nickclark2016** [comment]
Definitely agree that we should have a larger discussion. @tritao @Jarod42 if you are both Discord users, drop your usernames here and I'll get you both invited to a Discord server with @samsinsane, @starkos, and myself, and we can have more detailed discussions there.

For 6.x, my current plan is to get out 5.0 stable before I go back to work on 6.x.  We do still plan on it being a breaking change, mainly the updated scoping mechanism.

As for 2 and 3, let's all tag up to have a more detailed discussion

**Comment by nickclark2016** [comment]
Also, same to anyone in the @premake/full-team

**Comment by Jarod42** [comment]
Mine is unsurprising jarod42 (#8590)

**Comment by redorav** [comment]
Mine is redorav #2387 I'd love to engage

**Comment by nickclark2016** [comment]
@tritao @Jarod42 @redorav sent all of you friend requests (DragonSlayer0531). Shoot me a DM once you add me back and I'll get you server access 👍

**Comment by nickclark2016** [comment]
@KyrietS want in?

**Comment by KyrietS** [comment]
Since you asked so nicely, then why not 😄 but no promises that I'll be able to follow and attend all the meetings 😅 My nickname is `kyriet`

**Comment by nickclark2016** [comment]
What is a meeting ;)
