### ISSUE TITLE
LinkTimeOptimization does not add the LinkTimeCodeGeneration xml tag to Visual Studio projects

### ISSUE THREAD

**Issue by StanleySweet** [premake/premake-core#2312]
**What seems to be the problem?**
`LinkTimeOptimization` does not add the `<LinkTimeCodeGeneration>`  XML tag. This causes the `/LTCG` flag not to be added to executables or dynamic link libraries projects. (One can add it manually)

**What did you expect to happen?**
When adding the following option to premake
```lua
flags { "LinkTimeOptimization" }
```
I expect /LCTG to be set / configurable (in my case it should not be incremental)

**What have you tried so far?**

Tried to generate projects with the above snippet. Compared when adding an explicit LTCG and when setting it in Visual Studio directly

**How can we reproduce this?**

Just generate a MSVC project with

```lua
flags { "LinkTimeOptimization" }
```

for a static lib, a dll and an executable. Or clone the 0 A.D. source and run `build/workspaces/update-workspaces.bat` on this branch 

```
git clone https://gitea.wildfiregames.com/0Ad/0ad
git fetch -u https://gitea.wildfiregames.com/andy5995/0ad with-lto:andy5995-with-lto
git checkout andy5995-with-lto
```

- [x] Visual Studio 2017 (vs2017)

**What version of Premake are you using?**
`premake5 alpha-15` (There [does not seem to be](https://github.com/search?q=repo%3Apremake%2Fpremake-core+LinkTimeCodeGeneration&type=code) any reference to that tag in the current source)

**Anything else we should know?**

This showed up when trying to add LTO to the 0 A.D. project in this [issue](https://gitea.wildfiregames.com/0ad/0ad/pulls/7143).

**Comment by Jarod42** [comment]
From https://learn.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation
there are several options:
- `/LTCG`
- `/LTCG:INCREMENTAL`
- `/LTCG:NOSTATUS`
- `/LTCG:STATUS`
- `/LTCG:OFF`

`flags { "LinkTimeOptimization" }` set in msc toolset `/LTCG`, but in visual `/LTCG:INCREMENTAL` (via `<WholeProgramOptimization>true</WholeProgramOptimization>`)
it requires additional `<LinkTimeCodeGeneration>UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>` in `<Link>`
