### ISSUE TITLE
C/C++ additional options

### ISSUE THREAD

**Issue by iqifa** [premake/premake-core#2318]
Hello, I would like to know how to add additional options in the command line for C/C++ in the project properties. I have searched a lot but haven't found a solution.

just like this,  add \utf-8

![image](https://github.com/user-attachments/assets/f19b33e7-90d5-43c5-98b9-0178422258e8)

**Comment by DenysenkoIvan** [comment]
Hi! You can add platform specific flag just like this
```
filter { "system:windows", "action:vs2022" }
        buildoptions { "/utf-8" }
```

**Comment by iqifa** [comment]
> Hi! You can add platform specific flag just like this
> 
> ```
> filter { "system:windows", "action:vs2022" }
>         buildoptions { "/utf-8" }
> ```
> 
> `filter` is optional here

cool,thanks
