### ISSUE TITLE
Executing gmake2 generated Makefiles via the Windows command prompt

### ISSUE THREAD

**Issue by BuildMonkey** [premake/premake-core#2330]
I was hoping you can confirm my understanding of the gmake2 action. 

I am interested in using the generated Makefiles with GNU make via the Windows command prompt, cmd.exe. 

From the premake5 --help, the instructions give the impression the generated Makefiles are used with Mingw and Cygwin, stating
  "gmake2    Generate GNU makefiles for POSIX, MinGW, and Cygwin"
In addition, many of the questions about the generated Makefile on Windows discuss the usage with Mingw and Cygwin, giving the impressions these additional tools are required.

It would great if you can confirm the generated Makefiles are compatible outside a Unix-like environment on Windows and that it runs in via the Windows command prompt.

Thank you for your help.

**Comment by BuildMonkey** [comment]
Thanks for the quick response. I am curious why the instructions state "Generate GNU makefiles for POSIX". This gives the impression that the Makefiles are not compatible with non-POSIX environments, like Windows command prompt. Are the Makefiles generated portable to non-POSIX environments?

When you say, "toolset tools in your PATH", are you assuming we include Unix-like environment tools to support the build? We are not using any of these tools.

I am trying to be precise to rule out POSIX issues when we further investigate the use of gmake2 via the Windows command prompt. Thanks again!

**Comment by Jarod42** [comment]
> I am curious why the instructions state "Generate GNU makefiles for POSIX".
I would say that first versions were really only for POSIX, and when non-POSIX support was added, documentation was not been updated

**Comment by BuildMonkey** [comment]
Thank you for the clarification. We will proceed forward with the understanding the generated makefiles from gmake2 work in non-POSIX environments. Thanks again!

**Comment by BuildMonkey** [comment]
Closing out ticket. My question has been addressed.
