### ISSUE TITLE
Premake-5.0.0-beta3-windows.zip Reported as Virus

### ISSUE THREAD

**Issue by Ehren1337** [premake/premake-core#2332]
Windows 10 22H2 (OS Build 19045.5121)

I download latest build: https://github.com/premake/premake-core/releases/download/v5.0.0-beta3/premake-5.0.0-beta3-windows.zip

using virustotal.com
![image](https://github.com/user-attachments/assets/dc24f33c-9034-4f3e-b262-7b9e21aba4dc)

when i extract it with 7zip and i get this result on Bitdefender
![image](https://github.com/user-attachments/assets/361efa79-96bf-4a6d-9ec4-d5bc30dfe125)

**Comment by nickclark2016** [comment]
Huh. Will investigate.

**Comment by nickclark2016** [comment]
Went ahead and updated the windows artifact. Appears to be an issue with the file generated by the runner, not sure what to make of it. For some reason, Microsoft is still flagging the zip as a lazy trojan, but the exe contained is not being flagged. Let me know if this does not resolve your issue.
