### ISSUE TITLE
Optimizing for debugging is turned off for Clang with `gmake2`

### ISSUE THREAD

**Issue by SirNickolas** [premake/premake-core#2336]
### What seems to be the problem?

With `--cc=clang` and `gmake2` generator, if you put `optimize "Debug"` in the config, the compiler is invoked with `-O0`.

### What did you expect to happen?

It should result in `-Og`. Clang + old `gmake` generator as well as GCC + any of them do exactly that, hence I suspect this is an oversight rather than a deliberate decision.

### What have you tried so far?

I found this in the sources:

https://github.com/premake/premake-core/blob/7463784f6c57a8233a5ba0714c8fd71dbd96dd85/src/tools/clang.lua#L53-L60

No explanation _why_ it is set to `-O0`. If I monkey-patch it in my `premake5.lua`, everything seems to work fine.

### How can we reproduce this?

- [ ] Visual Studio 2022 (vs2022)
- [ ] Visual Studio 2019 (vs2019)
- [ ] Visual Studio 2017 (vs2017)
- [ ] Visual Studio 2015 (vs2015)
- [ ] Visual Studio 2012 (vs2012)
- [ ] Visual Studio 2010 (vs2010)
- [ ] Visual Studio 2008 (vs2008)
- [ ] Visual Studio 2005 (vs2005)
- [ ] GNU Makefile (gmake)
- [x] GNU Makefile 2 (gmake2)
- [ ] XCode (xcode)
- [x] Codelite
- [ ] Other (Please list below)

```lua
-- premake.tools.clang.shared.optimize.Debug = "-Og"

workspace "Og Test"

configurations "Debug"

project "main"
  kind "ConsoleApp"
  language "C++"

  files "main.cpp"
  optimize "Debug"
```

```cpp
int main() { }
```

```sh
$ premake5 --cc=clang gmake2
Building configurations...
Running action 'gmake2'...
Done (35ms).
$ make verbose=1
==== Building main (debug) ====
Creating obj
mkdir -p obj
Creating bin/Debug
mkdir -p bin/Debug
main.cpp
clang++   -MD -MP   -O0  -o "obj/main.o" -MF "obj/main.d" -c "main.cpp"
Linking main
clang++ -o "bin/Debug/main" obj/main.o
$ # Uncomment the first line in `premake5.lua`.
$ premake5 --cc=clang gmake2
Building configurations...
Running action 'gmake2'...
Generated main.make...
Done (37ms).
$ make clean
Cleaning main
$ make verbose=1
==== Building main (debug) ====
Creating obj
mkdir -p obj
main.cpp
clang++   -MD -MP   -Og  -o "obj/main.o" -MF "obj/main.d" -c "main.cpp"
Linking main
clang++ -o "bin/Debug/main" obj/main.o
```

### What version of Premake are you using?

`5.0.0-beta3`

**Comment by nickclark2016** [comment]
Looks like this landed about the time that Clang actually added `-Og` flags. Easy fix.
