### ISSUE TITLE
documentationfile(true) does not generate in beta3

### ISSUE THREAD

**Issue by lolrobbe2** [premake/premake-core#2339]
documentationfile is not generated in csproj (capitilization issue) documentationFile vs documentationfile (for some reason it works in the unit tests but not with the beta?)

**What seems to be the problem?**
i messed up

**What did you expect to happen?**

**How can we reproduce this?**
use documentationfile(true) works in the tests but not in release build!

- [ ] Visual Studio 2022 (vs2022)
- [ ] Visual Studio 2019 (vs2019)
- [ ] Visual Studio 2017 (vs2017)
- [ ] Visual Studio 2015 (vs2015)
- [ ] Visual Studio 2012 (vs2012)
- [ ] Visual Studio 2010 (vs2010)
- [ ] Visual Studio 2008 (vs2008)
- [ ] Visual Studio 2005 (vs2005)
- [ ] GNU Makefile (gmake)
- [ ] GNU Makefile 2 (gmake2)
- [ ] XCode (xcode)
- [ ] Codelite
- [ ] Other (Please list below)

**What version of Premake are you using?**
`premake5 beta3` will show you the version. If you are running a "-dev" version, please make sure you are up to date with the latest master branch.

**Anything else we should know?**
how does it work in tests

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

**Comment by nickclark2016** [comment]
The API also specifies that it should be a string, not boolean.
