### ISSUE TITLE
Incorrect Search Links to Non-Direct Descendants of "docs" Folder

### ISSUE THREAD

**Issue by nickclark2016** [premake/premake-core#2345]
If you go to search on the website, results to non-direct descendants of the "docs" folder (i.e. things in "globals", "http", etc.) have broken links.  I'm not really familiar with Docusaurus, or I would fix it myself.

**Comment by samsinsane** [comment]
Looks like the Algolia crawler isn't working anymore - searching for `mfc` doesn't return the dedicated API either. I'm not sure how the Algolia account was setup, might need @KyrietS to check it out.

**Comment by KyrietS** [comment]
A big shame on me for not seeing this earlier. Our crawler was stopped (blocked) for over a year now! 😱

I receive a weekly summary of Algolia Search usage but it seems they forgot to mention that the crawler was stopped 🤔

The website is reindexed now. Please check it. Later today I'll try to find out what went wrong. My suspicion is that after the auto-migration to their new generation crawler, it was stopped by default and needed manual activation.

**Comment by nickclark2016** [comment]
Verified the fix! Thanks @KyrietS
