### ISSUE TITLE
Referencing sources on parent folders

### ISSUE THREAD

**Issue by j-a-y-c-e-e** [premake/premake-core#235]
Hi,

I am introducing premake to my build system and would like no changes to the directory layout. I am trying to add some sources that are in the parent folder of the project file. Please look at the directory layout below. I have no problem adding the source files but when I try to build, the location indicated in the VS project file starts from the project file root dir. Hence, it is expecting files from common to be located in "project\common\utility.cpp". Am I missing something? Or is it a limitation?

**Comment by starkos** [comment]
It would be helpful to see that portion of your Premake script.

**Comment by j-a-y-c-e-e** [comment]
Hi @starkos,

Here is the simple version of the premake file. I run the premake script in the root folder.

location ("../root")

solution "project.sln"

configurations {    "Release", 	"Debug"}
platforms {         "Win32", "x64"}

project "project/project"
kind "WindowedApp"
language "C++"

files{"../root/project/main.cpp", "../root/common/utility.cpp" }

Also, please let me correct my directory layout.
![image](https://cloud.githubusercontent.com/assets/1073216/9594502/a9449284-5096-11e5-8ec9-ab16852b9f04.png)

**Comment by starkos** [comment]
Try this:

```lua

solution "project.sln"
location "../root"

configurations { "Release", "Debug"}
platforms { "Win32", "x64"}

project "project"
location "../root/project"
kind "WindowedApp"
language "C++"

files{"../root/project/main.cpp", "../root/common/utility.cpp" }
```

**Comment by j-a-y-c-e-e** [comment]
That worked! Thank you very much!
I see, explicitly specifying the location of the project file using "location" will solve it.
