### ISSUE TITLE
Static & Dynamic Builds determined by command line arg

### ISSUE THREAD

**Issue by Codinablack** [premake/premake-core#2353]
I wish to request the ability to produce the project files with specific configurations depending on a command line option sent when using premake, for the ability to create a solution/project file which can be statically linked (with that information in the premake5.lua), or dynamically linked, depending on the command/arg passed.

To be clear. I have a project that I want to be able to produce a solution for that will contain statically linked libs for the includes/libs. I also want to be able to produce the solution with a dynamically linked version. 

So something like 

```premake5.exe vs2022 -static```

and

```premake5.exe vs2022 -dynamic```

Which without specification, it should default to either dynamic or what is specified inside the premake file.

The premake file should have special keywords or filters used to setup/configure the information needed for the different build types.

**Comment by nickclark2016** [comment]
Would `newoption` provide you with the functionality you would need to implement this?

**Comment by Codinablack** [comment]
> `newoption`

I wouldn't know, as the documentation just provides a table as an example like that is supposed to mean something... There is no clear instructions on how to use that correctly.. in fact, they provide an "example" but don't show how to use that example, nor explain what happens when you do...

**Comment by nickclark2016** [comment]
https://premake.github.io/docs/newoption/
https://premake.github.io/docs/Command-Line-Arguments

The second link is likely more useful, but you can add an option something like:

```lua
newoption {
  trigger = "linktype",
  value = "type",
  description = "Type of linkage to use for library",
  allowed = {
    { "default", "Default Linkage" },
    { "static", "Static Linkage" },
    { "shared", "Shared Linkage" },
  },
  default = "default"
}
```

Then in your script, you can filter based on options, like:
```lua
filter { "options:linktype=default" }
  -- Default Behavior
filter { "options:linktype=static" }
  kind "StaticLib"
filter { "options:linktype=shared" }
  kind "SharedLib"
filter {} 
```

**Comment by Codinablack** [comment]
> https://premake.github.io/docs/newoption/ https://premake.github.io/docs/Command-Line-Arguments
> 
> The second link is likely more useful, but you can add an option something like:
> 
> ```lua
> newoption {
>   trigger = "linktype",
>   value = "type",
>   description = "Type of linkage to use for library",
>   allowed = {
>     { "default", "Default Linkage" },
>     { "static", "Static Linkage" },
>     { "shared", "Shared Linkage" },
>   },
>   default = "default"
> }
> ```
> 
> Then in your script, you can filter based on options, like:
> 
> ```lua
> filter { "options:linktype=default" }
>   -- Default Behavior
> filter { "options:linktype=static" }
>   kind "StaticLib"
> filter { "options:linktype=shared" }
>   kind "SharedLib"
> filter {} 
> ```

Thanks for the example code, much appreciated! I only have one question... I know I would pass "trigger" and I would pass "static" to the command line, but exactly how would that look?

```premake5 vs2022 -trigger --static```
or
```premake5 vs2022 trigger static```
or
```premake5 vs2022 --trigger --static```
or... I'm sure there are many other variations this could be, but which is correct?
