### ISSUE TITLE
"language" doesn't work in monodevelop action

### ISSUE THREAD

**Issue by kjk** [premake/premake-core#236]
Tested with https://github.com/premake/premake-core/commit/aeca0bb3fdd73a4c8142a3f39462e269a9bb1615

A `premake5.lua` like this:
```
workspace "Volante"
  configurations { "Debug", "Release" }
  platforms { "Any CPU" }
  flags { "Symbols" }

  filter "action:vs*"
    location "vs2015"
  filter "action:monodevelop"
    location "monodevelop"
    defines { "MONO" }
  filter {}

  project "Volante"
    kind "SharedLib"
    language "C#"
    files { "src/*.cs", "src/impl/*.cs" }
```

will work with `premake5 vs2015` but not with `premake monodevelop`, where it fails with:
```
Building configurations...
Running action 'monodevelop'...
Generated monodevelop/Volante.sln...
Generated monodevelop/Volante.csproj...
Error: [string "src/base/premake.lua"]:48: attempt to call upvalue 'callback' (a nil value)
```

After commenting out `language "C#"` line it works, which leads me to believe it's triggered by it.

A full example is https://github.com/kjk/volante/blob/4c9d116233f2be904c21ff82b2e71c97120bf41b/premake5.lua

**Comment by TurkeyMan** [comment]
Happy to check it out, but I've been afk a lot recently, sorry if it takes a little while! >_<

**Comment by samsinsane** [comment]
@TurkeyMan sorry if you'd already started to look into this, I had some spare time and figured I'd have a look :)

**Comment by TurkeyMan** [comment]
Thanks Sam!
