### ISSUE TITLE
Inconsistent line endings in source code and tarball.

### ISSUE THREAD

**Issue by Leoforever123** [premake/premake-core#2365]
**What seems to be the problem?**
I encountered  some problems when I added a patch to PKGBUILD. I got a *different line endings* error when I patched a patch file(using LF as line endings) to premake.  I used the dos2unix tool to check both the source code and unzipped tarball files and found inconsistent line endings. This force us to use unix2dos tool to patch before new releases. This should not have any functional impact, but it might cause some inconvenience for backporting. I'm wondering why does this inconsistency occur.

**What did you expect to happen?**

Adjust the packaging process to ensure consistency of line endings.

**What have you tried so far?**

**How can we reproduce this?**

- [ ] Visual Studio 2022 (vs2022)
- [ ] Visual Studio 2019 (vs2019)
- [ ] Visual Studio 2017 (vs2017)
- [ ] Visual Studio 2015 (vs2015)
- [ ] Visual Studio 2012 (vs2012)
- [ ] Visual Studio 2010 (vs2010)
- [ ] Visual Studio 2008 (vs2008)
- [ ] Visual Studio 2005 (vs2005)
- [ ] GNU Makefile (gmake)
- [ ] GNU Makefile 2 (gmake2)
- [ ] XCode (xcode)
- [ ] Codelite
- [ ] Other (Please list below)

**What version of Premake are you using?**
5.0beta3-1

**Anything else we should know?**

This inconsistency only causes inconveniences without affecting functionality. If you believe fixing it would be overly difficult, it might be reasonable to leave it unchanged .

**Comment by nickclark2016** [comment]
Because I ran the process on a Windows machine instead of a Linux machine. I'll take some time today to fix it.

**Comment by nickclark2016** [comment]
Resolved. I updated the source zip. As for the sources "tar.gz" and "zip" generated by default by the GitHub release, we recommend against using those.

**Comment by Leoforever123** [comment]
Thx for the quick fix. However, during build process, the SHA check for `premake-5.0.0-beta3-src.zip` is failing. I suspect that after re-exporting the package, you might have forgotten to update the SHA value.

**Comment by nickclark2016** [comment]
To my knowledge, we don't do any SHA checks. I built it with no problem earlier on Linux.

**Comment by nickclark2016** [comment]
Just confirmed a build on a fresh zip archive. Can you walk me through the process you're doing to build it?

**Comment by Leoforever123** [comment]
![image](https://github.com/user-attachments/assets/a2406be5-ecbd-4f14-bdbe-5f4a29362e9a)
This sha512sum check failed on my arch linux.

**Comment by Leoforever123** [comment]
I'll try it again.

**Comment by nickclark2016** [comment]
Yeah, I've got a different sha512sum result on my system. Where did you get that SHA to verify against?

**Comment by nickclark2016** [comment]
4baac5120d194d19fa9ba7a279e2bf12bc2b819e81868836e415341726a1e5b38d33b21e31aa16a5d2e28e69dbf44d824faf71e5ae96a8c78328cae9af6c051a` is my result, based off of the latest zip.

**Comment by Leoforever123** [comment]
4baac5120d194d19fa9ba7a279e2bf12bc2b819e81868836e415341726a1e5b38d33b21e31aa16a5d2e28e69dbf44d824faf71e5ae96a8c78328cae9af6c051a

is my result, same with u

**Comment by Leoforever123** [comment]
> ![image](https://private-user-images.githubusercontent.com/114008189/393657338-a2406be5-ecbd-4f14-bdbe-5f4a29362e9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDU0MjMsIm5iZiI6MTczMzcwNTEyMywicGF0aCI6Ii8xMTQwMDgxODkvMzkzNjU3MzM4LWEyNDA2YmU1LWVjYmQtNGYxNC1iZGJlLTVmNGEyOTM2MmU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQwMDQ1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmVhN2JhOGRhODdjMzAxZDE4NGYyODYxZWRiMTY4ZDk5ZDIxMjk1YTFhNGQ3YmY2MjRkOWE1ZDdlM2FjMmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7TmxYNHEPyEvqH1gmUXnYDWqXbptpchS5vJmSLavaXE) This sha512sum check failed on my arch linux.

I got this file on [archlinux](https://gitlab.archlinux.org/archlinux/packaging/packages/premake)

**Comment by Leoforever123** [comment]
It's in the PKGBUILD file

**Comment by nickclark2016** [comment]
@svenstaro Apologies if I'm pinging the wrong person, but would you be able to update the sha512sum in the Arch repo?

**Comment by svenstaro** [comment]
I'm the right person. However, I wonder what happened here. Did you replace `premake-5.0.0-beta3-src.zip` without making a new release? The checksum mechanism is supposed to guard exactly against these kinds of things as they could be signs of something nefarious going on. I will check the differences and update the checksums.

However, it is generally advisable to create a new release for these kinds of things and treat past releases as immutable.

**Comment by nickclark2016** [comment]
That is exactly what happened here (probably should have just made a new release). The differences are just fixing line endings in the tar ball.

**Comment by svenstaro** [comment]
Still, I have to treat these kinds of things as if they were made by bad actors and so it takes a bit more time than regular releases. :/

**Comment by nickclark2016** [comment]
Completely understandable. If anything is needed from our end, just let me know.

**Comment by Leoforever123** [comment]
Thx for ur effort. It seems I might have caused you some trouble.🥹

**Comment by svenstaro** [comment]
Something's fishy. The differences, as far as I can tell, are far more than just the line-endings. I'm uploading the diff generated by `diff -w -r old new`. This should ignore all whitespaces changes. As you can see, there are more changes than just whitespaces. 
[diff.txt](https://github.com/user-attachments/files/18054970/diff.txt)

**Comment by nickclark2016** [comment]
Well this is interesting. I wonder if this has to do with the fact that I generated this zip on windows the first time and Ubuntu the latest time. @svenstaro would it just be easier for me to switch back to the original zip archive?

**Comment by svenstaro** [comment]
You should really take a look at the diff. It's frankly somewhat suspicious. Especially due to the fact that there are changes in the `src/scripts.c` file.

**Comment by nickclark2016** [comment]
Yeah, I definitely see the difference, but as the person who generated both of these zip archives (from the same git commit), the only difference here is that one is generated on Windows 11, the other was generated on Ubuntu 24.04. I'll replace the original zip file, since I still have it and the sha512sum matches what is in the Arch package repo.

**Comment by nickclark2016** [comment]
@Leoforever123 reverted back the zip in the package so Arch no longer fails. Next release (probably within the next month), I'll run the zip package generation on Linux so you won't have any line ending issues.

**Comment by svenstaro** [comment]
So I looked at the GitHub-generated tarball and for the tag and that is really close to the new release zip you uploaded whereas the old one has significant differences. I think I'll use GitHub-generated tarballs from now on.

I hope you can see how in a post-xz world we maintainers need to be extra careful.

**Comment by nickclark2016** [comment]
Oh I 100% agree with the abundance of caution here. I also think that's a good course of action to use the GH generated tarballs. They are different and don't contain those Makefiles. You should be able to just run `./Bootstrap.sh` from the root of the repo and it'll generate a `premake5` binary at the same location.  I'm happy to assist in migration in any way possible, so feel free to open an issue or discussion as necessary and ping me directly.

As an aside, one of our internal goals is to actually get that "package" job to run automatically, rather than us having to do it manually any time we want to prep a release. Hopefully, that'll help alleviate any issues in the future.

**Comment by svenstaro** [comment]
Arch package is now using GitHub-generated sources.
