### ISSUE TITLE
clang toolset for Visual Studio not supported

### ISSUE THREAD

**Issue by kjk** [premake/premake-core#238]
This should work:
```
toolset "LLVM-vs2014_xp"
```
but premake5 complains with: `Error: C:/Users/kkowalczyk/src/sumatrapdf/premake5.lua:71: invalid value 'LLVM-vs2014_xp' for toolset`

Recent versions of Clang (http://llvm.org/releases/download.html) provide cl.exe compatibility which can be selected in Visual Studio projects by selecting a toolset. For LLVM 3.7, available toolsets are: LLVM-vs2014, LLVM-vs2014_xp,  LLVM-vs2013, LLVM-vs2013_xp,  LLVM-vs2012, LLVM-vs2012_xp,

A good lax check would be to allow "LLVM-vs\*" toolset for vs* actions.

**Comment by TurkeyMan** [comment]
Perhaps you missed PR #169?

**Comment by starkos** [comment]
Closing this as pull request #169 has merged. Feel free to reopen with additional information!
