### ISSUE TITLE
Why Premake cannot find the header in include folder?

### ISSUE THREAD

**Issue by DPthang411** [premake/premake-core#2389]
I am trying to link raylib with premake but It doesnt work.
error:
main.cpp:1:10: fatal error: raylib.h: No such file or directory
    1 | #include <raylib.h>
      |          ^~~~~~~~~~
compilation terminated.

link to the project:
https://github.com/DPthang411/raylib-learning

**Comment by nickclark2016** [comment]
Try specifying your paths relative to the premake5.lua file.

**Comment by DPthang411** [comment]
yes, the folder library is the same level as the premake5. Did u look at the project?

**Comment by nickclark2016** [comment]
I did. You specify everything relative to the parent, not the current directory. Try changing `../` to `./`.

**Comment by DPthang411** [comment]
oh ok, i will report to u later. Thx u!

**Comment by DPthang411** [comment]
Still not working

**Comment by DPthang411** [comment]
```
# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MainApp_config = debug
endif
ifeq ($(config),release)
  MainApp_config = release
endif

PROJECTS := MainApp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

MainApp:
ifneq (,$(MainApp_config))
	@echo "==== Building MainApp ($(MainApp_config)) ===="
	@${MAKE} --no-print-directory -C . -f MainApp.make config=$(MainApp_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f MainApp.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MainApp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"
	```
seems like nothing involves raylib

**Comment by nickclark2016** [comment]
At this point, I can't see anything immediately wrong in your premake file, and I'm away from my machines for the holidays. I'll try to remember to look when I get back, if you haven't fixed it by then.

**Comment by nickclark2016** [comment]
> ```
> # GNU Make workspace makefile autogenerated by Premake
> 
> ifndef config
>   config=debug
> endif
> 
> ifndef verbose
>   SILENT = @
> endif
> 
> ifeq ($(config),debug)
>   MainApp_config = debug
> endif
> ifeq ($(config),release)
>   MainApp_config = release
> endif
> 
> PROJECTS := MainApp
> 
> .PHONY: all clean help $(PROJECTS) 
> 
> all: $(PROJECTS)
> 
> MainApp:
> ifneq (,$(MainApp_config))
> 	@echo "==== Building MainApp ($(MainApp_config)) ===="
> 	@${MAKE} --no-print-directory -C . -f MainApp.make config=$(MainApp_config)
> endif
> 
> clean:
> 	@${MAKE} --no-print-directory -C . -f MainApp.make clean
> 
> help:
> 	@echo "Usage: make [config=name] [target]"
> 	@echo ""
> 	@echo "CONFIGURATIONS:"
> 	@echo "  debug"
> 	@echo "  release"
> 	@echo ""
> 	@echo "TARGETS:"
> 	@echo "   all (default)"
> 	@echo "   clean"
> 	@echo "   MainApp"
> 	@echo ""
> 	@echo "For more information, see https://github.com/premake/premake-core/wiki"
> 	```
> seems like nothing involves raylib
> 

This is the top level build file. You need to investigate MainApp.make

**Comment by DPthang411** [comment]
thx u!

**Comment by DPthang411** [comment]
![image](https://github.com/user-attachments/assets/3a7102ac-9f21-444f-9637-3ff0bb91872c)

**Comment by DPthang411** [comment]
thats the path inside the Mainapp.make

**Comment by DPthang411** [comment]
But whats the reason why premake cannot see the paths?

**Comment by nickclark2016** [comment]
Can you share your command to run the makefile?

**Comment by DPthang411** [comment]
make?

**Comment by Jarod42** [comment]
You have extra wildcard (`**`), it should simply be:
```
includedirs { "library/raylib/include" } -- Path to raylib headers
libdirs { "library/raylib/lib" }        -- Path to raylib library files
```
Wrong `..` removed, and suggesting replacement to `./` whereas not wrong is unneeded, as path is already relative to `./` :)

**Comment by DPthang411** [comment]
I tried it also but it didnt work

**Comment by DPthang411** [comment]
can you see any problem with the folder that includes my header and the path I put on the premake?

**Comment by Jarod42** [comment]
I clone your repo, applied our suggest change, and it works.
Created PR https://github.com/DPthang411/raylib-learning/pull/1 and CI.

**Comment by Jarod42** [comment]
BTW, OP asked the question also on stackoverflow
https://stackoverflow.com/questions/79305066/why-premake-cant-find-my-header-inside-a-folder

**Comment by nickclark2016** [comment]
Closing due to lack of action.
