### ISSUE TITLE
#2291 Breaks Windows Builds with bootstrap

### ISSUE THREAD

**Issue by Codinablack** [premake/premake-core#2393]
_Before opening a new bug report, please read [Reporting Bugs](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#reporting-bugs) and consider if this is something [you can contribute](https://github.com/premake/premake-core/blob/master/CONTRIBUTING.md#contributing-a-fix-or-feature) yourself. If this a new bug, help us help you by filling in the template below._

**What seems to be the problem?**
Bootstrap.bat fails

**What did you expect to happen?**
Bootstrap.bat should build premake and output solution files as well.

**What have you tried so far?**
I have tried use a commit that precedes #2291 and was able to successfully achieve expected result

**How can we reproduce this?**
Use a windows system:
git clone premake (or manually download and extract)
run bootstrap.bat

- [x ] Visual Studio 2022 (vs2022)
- [ ] Visual Studio 2019 (vs2019)
- [ ] Visual Studio 2017 (vs2017)
- [ ] Visual Studio 2015 (vs2015)
- [ ] Visual Studio 2012 (vs2012)
- [ ] Visual Studio 2010 (vs2010)
- [ ] Visual Studio 2008 (vs2008)
- [ ] Visual Studio 2005 (vs2005)
- [ ] GNU Makefile (gmake)
- [ ] GNU Makefile 2 (gmake2)
- [ ] XCode (xcode)
- [ ] Codelite
- [ ] Other (Please list below)

**What version of Premake are you using?**
Latest from main branch for testing and finding bug. To fix the bug and prove its fixed I used this version
490686ceb24b29f16c1ec817ed05c07c5cce89c6

**Anything else we should know?**
Yes. I already reported this bug previously, but apparently it didn't get approved as an issue... I can only assume its because template rules weren't followed or something, and it was very discouraging because I was quite thorough in my explanation without the need in a template.

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to issues like these!)*

**Comment by nickclark2016** [comment]
Can you show the output? Also, issues aren't auto rejected, so if the issue was never posted, that's due to something on your end.

**Comment by Codinablack** [comment]
![image](https://github.com/user-attachments/assets/a7f88aa7-2c94-4e09-9e2c-190150d45721)

**Comment by Codinablack** [comment]
I don't know how or why that could happen, I saw the entire issue created and my original screenshots posted and everything... but moving along...

The VsWhereVisualBootstrap wasn't even altered really in the commit that caused this break which is what is super weird.. I mean you can clearly still see it defined in the script... idk I read in a guide for batch that whitespace and all sorts of things make it behave weirdly.. but right now I'm running my scripts to call that commit I referenced earlier in this issue, for my end users to clone that specific version of premake, so that my scripts can continue forward after premake has been built to go ahead and generate the project files for my users.

**Comment by nickclark2016** [comment]
In our CI, we run it as "./Bootstrap.bat vs2022". Does this resolve your issue?

**Comment by Codinablack** [comment]
> In our CI, we run it as "./Bootstrap.bat vs2022". Does this resolve your issue?

No it does not
![image](https://github.com/user-attachments/assets/fb7f3a28-b932-4b3b-8b4f-0568e5d750af)

**Comment by nickclark2016** [comment]
This is definitely a bit weird, as this is how our CI job  runs, and we don't have any issues with the Windows + MSVC builds.

**Comment by Codinablack** [comment]
Well I have been using premake just fine in CI on github for awhile now, but that is using nmake and msbuild... when trying the last few days with utilizing the bootstraps that both premake and vcpkg provide (both provide a .bat and .sh) I realized I should probably do the same thing for my projects for my end users, so I set about creating bootstrap.bat and came across this problem.... I think this is a big problem if others are also having this issue..

![image](https://github.com/user-attachments/assets/4f1fce72-679e-41f5-9e83-54fdb1296865)

**Comment by redorav** [comment]
Isn't it just that you are using cmd.exe to run it and you are adding a '.'? Do you need to just run bootstrap.exe without the ./ ?

**Comment by Codinablack** [comment]
> Isn't it just that you are using cmd.exe to run it and you are adding a './'? Do you need to just run bootstrap.exe without the ./ ?
> 
> ./ is a powershell thing as far as I understand it

Uhm, no. Read all of the terminal, and also the posts above whatever was the last thing you read... and you will see it doesn't run when using ./ and it does run when I don't use ./... but that is when it fails... I also have already mentioned it fails just by running the bat script, double click and it instantly opens and closes too fast to catch the error, which is the reason I used cmd to call the batch script and see the error for the screenshot.



> It seems to be failing to find `VsWhereVisualBootstrap`, even though its here: https://github.com/premake/premake-core/blob/master/Bootstrap.bat#L92
> 
> No idea why it fails tbh,

Me either, I feel like it has to be something to do with white-space or formatting or something, according to this [guide](https://gist.github.com/nicolasdao/1b1e5d043b5296ad7c58ca71e00719cd) those kinds of things make batch scripts act up and work sometimes but also fail sometimes

**Comment by Jarod42** [comment]
It is probably off topic, but I suggest to use released version for dependencies, unless you really need feature/bugfix from trunk.

In your case you can even download executable directly (so currently [Premake 5.0-beta3](https://github.com/premake/premake-core/releases/tag/v5.0.0-beta3)

**Comment by Codinablack** [comment]
> It is probably off topic, but I suggest to use released version for dependencies, unless you really need feature/bugfix from trunk.
> 
> In your case you can even download executable directly (so currently [Premake 5.0-beta3](https://github.com/premake/premake-core/releases/tag/v5.0.0-beta3)

Yes I could, but then you know how users are.. they will find anything to complain about. Besides that, I prefer to "live at the head" myself. For now it's not a big deal for me to just lock into a specific version of premake, but it is a bug that resides here, so I figured I would report it... I imagine that the bootstrap.bat and bootstrap.sh are both pretty important, as I find them to be for my own project... not dire, but still, quite important if one has already invested the time in making them.

**Comment by Codinablack** [comment]
Confirmed working when initiated with cmd, didn't try with a script (calling this script), but I expect the results to be the same

![image](https://github.com/user-attachments/assets/d32e5891-ad72-4bcf-bdf0-3793005c5054)

Thanks for the prompt attention to this matter!
