### ISSUE TITLE
img.shields.io - `financial contributors` display card is broken

### ISSUE THREAD

**Issue by Dat-Pudding** [premake/premake-core#2398]
**What seems to be the problem?**
The ` financial contributors `  "banner" in lines 22 & 23 of [Readme](https://github.com/premake/premake-core/blob/master/README.md) shows an error instead of its supposed content.

Error message:
` rate limited by upstream service ` 

**What did you expect to happen?**

**What have you tried so far?**
- Opening the Readme in the mobile app
- Opening the Readme on the mobile page in mobile mode
- Opening the Readme on the mobile page in desktop mode

**How can we reproduce this?**
 1. Open the repository 
 2. Scroll down to the [Readme](#README.md)

**Software versions**
- [x] GitHub Mobile v1.190.0
- [x] Opera GX mobile v2.6.8
- [x] Chrome mobile v131.0.6778.200

**Anything else we should know?**
Nothing major, perhaps the donators are just too numerous

**Comment by nickclark2016** [comment]
It appears to be working fine for me. If the badge is not working, that is beyond the control of Premake to resolve, since it's provided via a third party.
