### ISSUE TITLE
gmake and ${CUSTOMFILES} is kinda awkward

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#251]
I'm building a Qt app, the Moc steps on the Qt headers are among `${CUSTOMFILES}`, and the output of which (.cpp files) are compiled among `$(OBJECTS)`.

Here is the target rule as written by premake:
```
$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES) ${CUSTOMFILES}
```

If I manually rearrange such that:
```
$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES)
```
This builds fine.

I have other custom build rules that should come before compiling too like this one for example:
```
	filter "files:shaders/**"
		buildmessage 'text2c.sh %{file.relpath} %{cfg.objdir}/shaders/%{file.basename}.inc'
		buildcommands { path.getabsolute('.') .. '/text2c.sh "%{file.relpath}" "%{cfg.objdir}/shaders/%{file.basename}.inc"' }
		buildoutputs { '%{cfg.objdir}/shaders/%{file.basename}.inc' }
```
Since these generate `.inc` files that are are used by the compiler, they must be produced beforehand.

Simply moving the `${CUSTOMFILES}` dependency would fix this for me, but it might break someone else... I wonder what we can do instead to control ordering of custom build rules...?

I'd suggest that we do change the order in the short term though, I think it's far more likely to break peoples projects the way it is currently.

**Comment by starkos** [comment]
I'm fine with changing it and seeing what (if anything) breaks. 

Makefile generation needs some serious love; wish I could get to it.

**Comment by TurkeyMan** [comment]
Okay, I'll submit a PR with that change. I'll have to have to give the makefile gen a little love for my project at work right now, I'll try and isolate any good that comes from it, but I have almost no time I can allocate at the moment past just "get it working" >_<
