### ISSUE TITLE
gmake link order failing

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#255]
Just putting this here so it doesn't get lost.

I'm having troubles with gmake, where LIBS is populated with libs in a bad order that doesn't actually link (ld is notoriously fussy about lib link order).
I haven't looked into this yet, but I wonder if others have encountered this?
Any known workarounds or solutions?

In my case, I have a stack of libs that depend on each other. It seems to me that the libs should appear in reverse order of the build order; libs that want symbols from another lib need to appear before that lib on the command line. Libs with mutual dependencies often require that they appear twice to avoid mutual exclusion problems. Eg, `libx.a` and `liby.a` both refer to symbols in each other: `LIBS += out/libx.a out/liby.a out/libx.a`
These relationships are awkward to express...

**Comment by starkos** [comment]
Can we just use `--start-group` and `--end-group`? I am certain this has come up before.

**Comment by TurkeyMan** [comment]
Oh yeah, of course! I forgot about those (don't do a lot of linux dev).
Okay, so what we need to do is put all the explicit links to sibling projects between `--start-group` and `--end-group`, and then following that, the set of `-l`'s from the system (it's safe to say they don't depend on eachother).

I'll look into this when I get to it at work.

**Comment by tvandijck** [comment]
I have this change somewhere in our changelist actually... clang doesn't like it, so I had to split the gcc.getlinks and clang.getlinks... I'll make a pull for it...

**Comment by tvandijck** [comment]
it's in this change: https://github.com/Blizzard/premake-core/commit/de1ac289881b1328c09205d19c4121e79e1c974d

which unfortunately it intermingled with adding support for makefile/utility projects in gmake. I unfortunately don't really have the time today to pull that apart and make a pull request for it. That aside, there is another 'bug report' about someone complaining about makefiles not working in gmake.

**Comment by TurkeyMan** [comment]
I was trying it at work today, clang had no problem.
What were your problems with clang?

**Comment by tvandijck** [comment]
It gave me an error that the option (--start-group) is an unknown option and bailed... tested on OSX though.
