### ISSUE TITLE
Premake5 creates two target directories

### ISSUE THREAD

**Issue by archfrog** [premake/premake-core#258]
I am very new to Premake5.  I just tried a slightly modified version of the initial C project shown in the documentation.  I changed the targetdir to read:

     configurations { "SHIP", "TEST" }
     ...
     targetdir "../obj/%{cfg.buildcfg}"

In the hope that Premake5 would output the objects and binaries to ../obj (outside the source tree, "../src",, as I hate having a source tree littered with all sorts of build artifacts).

Premake5 seems to create both "obj/SHIP" and "../obj/SHIP".  There's no output due to errors in my sample program (which is far from ready to compile yet) so I can't tell where it is heading yet.

This on Windows 8.1 x64.

**Comment by archfrog** [comment]
I just studied the issue a bit more.  It seems that the generated GNU Makefile has these lines:

    TARGETDIR = ../obj/SHIP
    OBJDIR = obj/SHIP

So apparently Premake5 doesn't much care for out-of-tree builds?

**Comment by archfrog** [comment]
Sigh.  I just realized that there's probably an "objdir" command like there's a "targetdir" command.

A quick google confirmed my suspicions.  

CASE CLOSED DUE TO IT BEING A SIMPLE USER ERROR!  Sorry for any time wasted :-)

**Comment by starkos** [comment]
:) No problem!
