### ISSUE TITLE
premake5 failure on OSX still present

### ISSUE THREAD

**Issue by fastrgv** [premake/premake-core#270]
The issue discussed here still exists:

http://industriousone.com/topic/how-remove-flags-ldflags

I must manually edit the *.make file created by premake to remove the linker flags "-Wl,-x"
before it works.

From the inline comments it looks like a workaround for a problem in older [2006] versions of OSX  was never removed.  See ~/src/tools/gcc.lua and search for and replace "-Wl,-x" with "".

Thx, Rod

**Comment by fzwoch** [comment]
Use `toolset "clang"` as discussed in #133.

**Comment by fastrgv** [comment]
I don't use clang, I use g++ for my very complex OpenGL software
compilation.  I don't think this will solve my problem.  Rod

**Comment by fzwoch** [comment]
I think unless you have installed your own custom compiler set you end up with Apple's toolchain which I thought completely migrated to LLVM (maybe with a g++ interface - but I think thats not the crucial part). The linker is probably the same and results in the discussed error. Using `toolset "clang"` does exactly what you want - dropping the `Wl,-x` from the linker flags. Please try and report how it goes.

**Comment by fastrgv** [comment]
Florian,
I believe you are correct because it seems to work fine for me now.
Thanks,
Rod
