### ISSUE TITLE
Detokenize fails when command tokens is followed by other tokens.

### ISSUE THREAD

**Issue by JohannesMP** [premake/premake-core#280]
_(Using Premake 5.0.0-alpha5 for Mac)_

EDIT: here's a much more condensed look at the issue:

```
postbuildcommands
{
  "{MKDIR} {%cfg.system}"
}
```

Fails with the `gmake` action:

```
Running postbuild commands
{MKDIR} {%cfg.system}
/bin/sh: {MKDIR}: command not found 
```

It seems because premake fails to parse multiple tokens per command

This is odd because the token test <a href=https://github.com/premake/premake-core/blob/2d325bda81347569fd2ab21d6357ffa8620c469a/tests/base/test_detoken.lua#L44>is supposed to check for this scenario</a>.

Below is my original issue:

---

Playing around with various <a href=https://github.com/premake/premake-core/wiki/Tokens#command-tokens>command tokens</a> I noticed that the `{CHDIR}` command token currently seems to be somewhat useless with gmake projects.

Given these post build commands:

```
postbuildcommands
{
  "{MKDIR} dir_1",
  "{CHDIR} dir_1",
  "{MKDIR} dir_2",
  "{CHDIR} dir_2",
  "{MKDIR} dir_3",
}
```

I would assume that the resulting folder structure would be something like this:

```
| - dir_1
|   | - dir_2
|   |   | - dir_3
```

Since it would make sense for the act of changing a directory to persist for the next command. Otherwise what would the purpose of changing directory be at all? it would be pointless.

However the result I saw was the following folder structure:

```
| - dir_1
| - dir_2
| - dir_3
```

In other words, the `{CHDIR}` command token doesn't persist.

After poking around a bit I noticed that this behavior seems to be the result of how `gnu make` treats commands on separate lines. Because premake is writing the commands separated by newlines, we are getting this behavior.

---

I could get directory changes to persist if the commands were separated by semicolons instead of newlines.

For example, the following command works:

```
postbuildcommands
{
  "mkdir -p dir_1; cd dir_1; mkdir -p dir_2; cd dir_2; mkdir -p dir_3"
}
```

However it is non-portable, forgoing the whole reason why we have command tokens.

I figured, no problem, I can just use the token commands instead. The intuitive way of doing so would be:

```
postbuildcommands
{
  "{MKDIR} dir_1; {CHDIR} dir_1; {MKDIR} dir_2; {CHDIR} dir_2; {MKDIR} dir_3"
}
```

However unfortunately that results in premake not actually replacing _any_ of the command tokens, which causes `make` to get understandably confused:

```
Running postbuild commands
{MKDIR} dir_1; {CHDIR} dir_1; {MKDIR} dir_2; {CHDIR} dir_2; {MKDIR} dir_3
/bin/sh: {MKDIR}: command not found
/bin/sh: {CHDIR}: command not found
/bin/sh: {MKDIR}: command not found
/bin/sh: {CHDIR}: command not found
/bin/sh: {MKDIR}: command not found
```

---

Which brings me to the actual purpose of this issue report: It seems that currently command tokens, specifically the `{CHDIR}` token, are a bit useless.

As it stands, if I want to do **both** of the following:
- Run postbuild commands that have persisting directory changes
- Use command tokens for portability

It seems to currently be impossible. I need to use semicolons for make to allow `CHDIR` commands to persist, and premake only expects single command tokens.

There seem to be two possible fixes (not mutually exclusive):
1. Have the `gmake` action write commands to the make file separated by semicolons instead of newlines (or at least provide a way to toggle that behavior for the sake of not breaking older projects that expect the old behavior)
2. Change command token parsing to work for multiple tokens per string. 

I'd be interested to hear thoughts on the current behavior, or if there is another option that I am missing.

**Comment by starkos** [comment]
While this doesn't address the larger issue, I'll mention that `{MKDIR} dir_1/dir_2/dir_3` will automatically create any missing directories along that path, in case it helps you get moving again.
