### ISSUE TITLE
How to mimic old location behavior

### ISSUE THREAD

**Issue by rorydriscoll** [premake/premake-core#281]
Hi,

I'm upgrading to premake5, and I'm having quite a bit of trouble with the changes to location that mean that it propagates from the workspace down to the projects. 

Previously I had a premake file in each project directory, and just included them from another premake file to create a valid workspace. The old location behavior worked for me since it generated the projects in the same place for every different workspace.

e.g. For premake4 generating for vs2013 I would get:

    Stuff\premake4.lua
    Stuff\Stuff.sln
    Stuff\A\project.lua
    Stuff\A\premake4.lua
    Stuff\A\A.vcxproj
    Stuff\A\A.sln
    Stuff\B\project.lua
    Stuff\B\premake4.lua
    Stuff\B\B.vcxproj
    Stuff\B\B.sln

Where the premake4 files contain the solution description, and just use dofile to include the project descriptions from the relevant directories.

Stuff\premake4.lua:

    solution "Stuff"
        ...
        dofile "A/project.lua"
        dofile "B/project.lua"

Stuff\A\premake4.lua:

    solution "A"
        ...
        dofile "project.lua"

Stuff\B\premake4.lua:

    solution "B"
        ...
        dofile "project.lua"
        dofile "../A/project.lua"

My problem with premake5 is that each solution generates a copy of the vcxproj in the solution's directory, so I end up with something like this:

    Stuff\premake4.lua
    Stuff\Stuff.sln
    Stuff\A.vcxproj
    Stuff\B.vcxproj
    Stuff\A\project.lua
    Stuff\A\premake4.lua
    Stuff\A\A.vcxproj
    Stuff\A\A.sln
    Stuff\B\project.lua
    Stuff\B\premake4.lua
    Stuff\B\A.vcxproj
    Stuff\B\B.vcxproj
    Stuff\B\B.sln

I can set the location for each project using the location command, but to keep the old behavior I would need to know absolute paths to the desired directories which I don't have (the entire repo is relocatable based on an environment variable). 

Is there a way to use the location command to specify a location relative to the current script's directory?

**Comment by rorydriscoll** [comment]
I can work around the issue right now by resolving the environment variable and then making a path by using that. However it would be nice to have an easy way to use the old location behavior. Perhaps a symbol to specify the script directory or something?

    location "#"

**Comment by starkos** [comment]
> Is there a way to use the location command to specify a location relative to the current script's directory?

All paths in Premake are specified relative to the current script. If you see otherwise, it's a bug, and a small example that reproduces the problem would be helpful.

**Comment by rorydriscoll** [comment]
Now I feel stupid. I never tried that since I assumed that if the location is inherited, then "." would come to mean where ever the inherited location is. Thanks!
