### ISSUE TITLE
objdir not as expected

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#283]
Seeing some strange behaviour with `objdir`.

I set:

```
objdir "int/%{cfg.buildcfg}_%{cfg.platform}"
```

Then I have some rules like this (ie, I use `%{cfg.objpath}` in paths):

```
filter "files:script/**"
    buildcommands { '/text2c.sh "%{file.relpath}" "%{cfg.objdir}/script/%{file.basename}.inc"' }
    buildoutputs { '%{cfg.objdir}/script/%{file.basename}.inc' }
```

That rule produces an `.inc` file, so I also:

```
includedirs { "%{cfg.objdir}/script" }
```

And at the end of this, the compiler can't find the file that was generated.

Taking a look at the paths written to the project we see:

```
<IntDir>int\Debug_x64\x64\Debug\MyProject\</IntDir>
```

Note, this is NOT the path that we specified to `objdir`. Maybe that's intended behaviour; that these extra bits are implicitly added... but I think that's a bug. Still, it's not necessarily my problem here. Looking further:

```
      <Outputs Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">$(IntDir)/script/init.inc</Outputs>
      <Command Condition="'$(Configuration)|$(Platform)'=='Debug Clang|x64'">C:/ud2/udShell/kernel/text2c.sh "MyProject/script/init.lua" "$(IntDir)/script/init.inc"</Command>
```

This is the build rule for the `.inc` file, and it looks good. It has translated `%{cfg.objdir}` to `$(IntDir)`, which should be fine. Still looking:

```
<AdditionalIncludeDirectories>int\Debug_x64\script</AdditionalIncludeDirectories>
```

Bingo. It hasn't translated to `$(IntDir)` here, and it also hasn't emit that extra junk that I didn't specify as it did for `<IntDir>`.

So, I'm not sure exactly what the expected behaviour of `objdir` should be after seeing these extra directories appear out of nowhere?

Fix probably requires multiple actions:
- `<IntDir>` is emit exactly as specified, or if the extra directory spam is deliberate, it needs to appear everywhere (and be documented more clearly).
- Translate to `$(IntDir)` in this case too.

**Comment by starkos** [comment]
> `<IntDir>` is emit exactly as specified, or if the extra directory spam is deliberate, it needs to appear everywhere (and be documented more clearly).

You mean [like this](https://github.com/premake/premake-core/wiki/objdir)? ;)

It looks like token in `includedirs()` is getting evaluated before the baking pass has finished. Would be very curious to know why that is happening. If that gets fixed, then the `$(IntDir)` substitution should also work as expected.

**Comment by TurkeyMan** [comment]
> You mean like this? ;)

Haha! Ahhh, yeah. That's embarrassing!

Right, so both problems should be fixed at once. I'll dig at it when I get time, although I keep saying that lately ;)

**Comment by dannyNK** [comment]
Wanted to leave a note as we had an issue with this.

`objdir '!$(SolutionDir)../build/$(PlatformTarget)/$(Configuration)/'
outputs: 
`<IntDir>build\$(PlatformTarget)\$(Configuration)\</IntDir>

Looking at the code it will check for the exclamation anywhere not just as a prefix, so moving it to the end solves the issue:

`objdir '$(SolutionDir)../build/$(PlatformTarget)/$(Configuration)/!'
outputs: 
`<IntDir>$(SolutionDir)..\build\$(PlatformTarget)\$(Configuration)\</IntDir>

It looks like Lua is processing the '!' as a NOT, but I'm not too sure.

**Comment by starkos** [comment]
Interesting…the leading `!` is breaking the handling of the leading environment variable in the path. If it works to put it at the end (I'm kind of surprised about that, actually) perhaps we should change the docs and make it the standard.

**Comment by samsinsane** [comment]
@dannyNK @starkos #605 should fix the issue with `!`, very interesting issue. Additionally, from what I can see this issue can now be closed after that PR is merged in as the original issue was resolved by using the `!` prefix and the secondary issue is resolved in the PR.
