### ISSUE TITLE
custom platform results in invalid configurations

### ISSUE THREAD

**Issue by Trass3r** [premake/premake-core#296]
> We do concatenate the build configuration and platform to produce unique project configuration names, but there is a special case for the Win32 and x64 identifiers to skip that step

It's understandable that you'd need to do that for IDEs not having a separate platforms thing but why also for VS?

Anyway If I define an actually custom platform like

```
workspace "TestSln"
  configurations { "Debug", "Release" }
  platforms { "x64", "avr" }

  project "rerunpremake"
  files { "premake5.lua" }
  kind "Makefile"
```

The solution configs/platforms as expected, but a weird project with 2*2 configurations and Win32+x64 as platforms.
The only valid combinations then are "Win32 + avr configs" and "x64 + non-avr", with invalid ones set to Application instead of makefile.

**Comment by samsinsane** [comment]
Adding a new platform isn't as simple as `platforms { "avr" }`, this is just a friendly name for the end user. You will need to add the following to your Premake5.lua for it to work:
```lua
premake.api.addAllowed("architecture", "avr")
premake.vstudio.vs2010_architectures.avr = "avr" -- This value might need to be "AVR" depending on how the VS extension handles the platform name
```
