### ISSUE TITLE
Unable to generate solution for Xcode

### ISSUE THREAD

**Issue by ikryukov** [premake/premake-core#298]
Hi, I downloaded the latest source (premake5) and build it on Mac. But now I'm getting this error message:
premake-core/modules/xcode/xcode_common.lua:317: bad argument #1 to 'pairs' (table expected, got nil)
Could anyone provide premake5 that works on MacOS 10.10.
Thanks, Ilya.

Here is my premake lua file:

-- fluid.lua
workspace "Fluid"
configurations { "Debug", "Release" }
location "build/Fluid"
architecture "x86_64"

project "Fluid"
kind "ConsoleApp"
language "C++"
targetdir "../bin/%{cfg.buildcfg}"

files { "../src/*.h", "../src/.cpp" }

includedirs { "../3rdparty/GLFW/include"
, "../3rdparty/GLEW/include"
, "../3rdparty/glm/include"
, "../3rdparty/boost/include" }

libdirs { "../3rdparty/GLFW/lib"
, "../3rdparty/GLEW/lib"
, "../3rdparty/boost/lib" }

links { "glfw3", "glew32", "glu32", "opengl32" }

filter "configurations:Debug"
defines { "DEBUG" }
flags { "Symbols" }

filter "configurations:Release"
defines { "NDEBUG" }
optimize "On"

**Comment by samsinsane** [comment]
As referenced in premake/premake-xcode#20 this was fixed in the module, but the submodule reference hasn't been updated. Creating a PR for this now.
