### ISSUE TITLE
libdirs ignored in gmake of premake-5.0.0-alpha6

### ISSUE THREAD

**Issue by witchu** [premake/premake-core#308]
But it work on premake-5.0.0-alpha5

in premake5.lua
```
libdirs { "3rdparty/libs" }
```

output of 5.0.0 alpha6
```
ALL_LDFLAGS += $(LDFLAGS) -s
```

output of 5.0.0 alpha5
```
ALL_LDFLAGS += $(LDFLAGS) -L../3rdparty/libs -s
```

**Comment by starkos** [comment]
I'm seeing this on one of my projects as well.

**Comment by Geequlim** [comment]
I got the same issue on linux.

**Comment by tvandijck** [comment]
This might be because of a fix I made to the libdir calculation to support -F for frameworks... although I can't repro this here locally, so I must have some other fix somewhere in my changeset that "fixes" this... I'll have a look to see if I can find it...

**Comment by starkos** [comment]
PR #332 (now merged) rolls back Tom's framework code change to get the libdirs working again, and I added a new unit test to catch this in the future.

Tom, if you want to try to bring it forward again I can take a closer look at it, now that I know that there is virtual zero test coverage in that area.

**Comment by tvandijck** [comment]
Yeah, I'll revisit this one, we may not need it anymore... no worries.

**Comment by samsinsane** [comment]
Closing this as the original issue has been resolved. Frameworks should be handled differently now, `frameworkdirs` and adding `.Framework` to the end of the `link` values, if this doesn't work a new issue should be opened.
