### ISSUE TITLE
Debug Format for Visual Studio cannot be None.

### ISSUE THREAD

**Issue by j-a-y-c-e-e** [premake/premake-core#311]
This was previously raised in the bitbucket repository but remains unresolved, putting it here hoping it will be resolved in the future. A workaround will be helpful as well. Thank you very much in advance!

https://bitbucket.org/premake/premake-dev/issues/237/configuring-pdb-file-for-project#

**Comment by starkos** [comment]
In case BB goes away, the original issue is: 

vs2010, when project is being configured as release, (Symbols not enabled) .vcxproj does not get `<ProgramDataBaseFileName></ProgramDataBaseFileName>` tag, which for some reason is interpreted by visual studio 2010 as fallback to default, which is: 

`$(IntDir)vc$(PlatformToolsetVersion).pdb`.

If you tune it manually and project gets empty value ( `<ProgramDataBaseFileName></ProgramDataBaseFileName>` ) - then no pdb is produced anymore. (Works correctly). Missing pdb files can cause following linker warning to appear later on: `warning LNK4099: PDB 'vc100.pdb' was not found with …` which is impossible to disable properly (except to recompile library without pdb file).

**Comment by j-a-y-c-e-e** [comment]
Hi @starkos , 

Good day! 
This is getting kinda critical to our deployment since we need no debug info on release configs.
But the settings is too numerous to change manually, I will attempt to make some changes hopefully it will be a decent pull-request.

Can you hint me if there is a certain way you want to do this? I'd be happy to make my changes follow your way.

**Comment by starkos** [comment]
Is this still an issue, using the new [symbols() API](https://github.com/premake/premake-core/wiki/symbols)?

**Comment by samsinsane** [comment]
Closing as this seems to have been resolved.
