### ISSUE TITLE
bootstrap.mak should exclude or remove scripts.c before a the bootstrap build.

### ISSUE THREAD

**Issue by tvandijck** [premake/premake-core#318]
it's basically just including *.c, but if there is an old dangling scripts.c the bootstrap build may fail.

**Comment by akaStiX** [comment]
removing scripts.c should be enough - it solved my problem

**Comment by tvandijck** [comment]
This is actually rather easy to fix, we just did this locally...
instead of putting scripts.c in src/host/scripts.c, we put it into src/scripts.c

The bootstrap.mak file does not include any files in the src/ folder, but only src/host/*.c, so that way it will get automatically excluded.. I'll try to make a pull request for this, soon.
