### ISSUE TITLE
Bootstrapping on OSX fails for a number of reasons

### ISSUE THREAD

**Issue by jeremyong** [premake/premake-core#325]
I'm running into a number of problems.

1. The CoreServices framework might have been deprecated in favor of CoreFoundation?
2. The make command fails because it isn't selecting the right platform SDK.

Given that there are live bugs on the latest version (can't even generate an xcode solution), I'd appreciate it if either issue were addressed or if someone could bootstrap a binary for me and release it on a different platform.

**Comment by mversluys** [comment]
I've been successfully compiling and using master, albeit with a minor fix which there's a pull request in for related to start-group, end-group being passed to the linker, but no problems with CoreServices.

Which version of Xcode are you using? I'm using Xcode 7.1 with Yosemite 10.10.5.

**Comment by jeremyong** [comment]
The same as you actually. It seems like the make command that happens when I run `make -f Bootstrap.mak osx` tries to link against the ios9 sdk. Do you have to do something to make it link against the macosx sdk?

**Comment by mversluys** [comment]
I'm using the same command as you to run the bootstrapper. 

otool has the following output for the one that I built (the Security framework is a local change of mine)

    premake5:
    	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 62.0.0)
    	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57031.40.6)
    	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
    	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 283.0.0)
    	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1153.18.0)

I tried the v5.0.0-alpha6 tag, but it failed to compile pretty much immediately, but master is okay for me.

That release does have a prebuilt executable for osx that seems to work https://github.com/premake/premake-core/releases/download/v5.0.0-alpha6/premake-5.0.0-alpha6-macosx.tar.gz

**Comment by mversluys** [comment]
The premake5 in that release looks like this

    premake5:
    	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.4.0)
    	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
    	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 955.0.0)
    	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1253.0.0)

**Comment by jeremyong** [comment]
The premake5 in the current release has a bug preventing it from creating xcode solutions I believe.

**Comment by jeremyong** [comment]
I was able to get the bootstrap to work after fixing a configuration issue and applying your fix locally. What is your workflow like with Xcode 7.1? The workspace file it generates needs to be upgraded every time, and it also doesn't respect my include paths.

**Comment by mversluys** [comment]
Haven't been trying Xcode projects, have been using gmake.

**Comment by starkos** [comment]
I recently merged a PR which I think should get the bootstrapping working again (via `make -f Bootstrap.mak osx`).  Are you able to bootstrap a build from the master branch now?

(Xcode does have issues; feel free to open a separate ticket for those.)

**Comment by starkos** [comment]
Actually, I'm confident enough that the bootstrap is fixed that I'm going to go ahead and close this one. Feel free to reopen if you having trouble getting a working build via `Boostrap.mak`.
