### ISSUE TITLE
Premake5 xcode4 Action: bad argument #1 to 'pairs'

### ISSUE THREAD

**Issue by rhythmchicago** [premake/premake-core#330]
I'm newer to Premake, but I have used it successfully in Visual Studio projects on Windows. Now, I have a premake5 script that works fine for Visual Studio and Makefile projects, but xcode projects fail:

$ premake5 --verbose xcode4
Building configurations...
Running action 'xcode4'...
Error: [string "xcode/xcode_common.lua"]:201: bad argument #1 to 'pairs'
    (table expected, got nil)

I thought there might be something strange in my lua files, but I downloaded and installed Premake4.4 and the xcode4 action worked immediately. While this is obviously a workaround I can employ until corrected, I thought you should know of the bug.

My main Premake solution file: src/premake4.lua

    solution "LogicCore"
        -- set the major and minor build numbers
        VERSION_MAJOR = 1
        VERSION_MINOR = 0

        major = "VERSION_MAJOR=" .. VERSION_MAJOR; 
        minor = "VERSION_MINOR=" .. VERSION_MINOR; 

        defines { major, minor }

        configurations { "Debug", "Release" }

        configuration { "Debug" }
            targetdir "../bin/debug"

        configuration { "Release" }
            targetdir "../bin/release"

        if _ACTION == "clean" then
            os.rmdir("../bin")
        end

        -- PROJECT: Generic include and utility functions.
        include "lc"

My Premake sub-project file: src/lc/premake4.lua

    project "lc"
        kind "StaticLib"
        language "C"
        location "./"
        files { "**.h", "**.c" }

        configuration {"Debug"}
            targetsuffix "_d";
            defines { "DEBUG" };
            flags { "Symbols" };

        configuration {"Release"}
            defines { "NDEBUG" };
            flags { "Optimize" };

Versions:
 premake 5.0.0 alpha 6
 premake 4.4 beta 5

Please let know if there is any more information I can provide.

**Comment by starkos** [comment]
Thanks for letting us know! There are a number of bugs in alpha6 which I am trying to get addressed. I will look into this if I get a chance.

**Comment by rhythmchicago** [comment]
Thanks!

It’s a great project. I’d be happy to contribute, if you’re ever looking for help. I’ve been putting together a “Premake” manual for our projects intended to get people up and running quickly, and I’d be happy to share if anyone thinks it’s of any use.

Tom

**Comment by starkos** [comment]
We'd be happy for any improvements to [our wiki documentation](https://github.com/premake/premake-core/wiki)!

**Comment by rhythmchicago** [comment]
Happy to help. I’ll touch up the manual I wrote and turn it in for review.

Thanks!
Thomas C. Bitsky Jr. | Lead Developer
ADC | automateddesign.com<http://automateddesign.com/>

Follow ADC news and media:
Facebook<https://facebook.com/automateddesigncorp> | Twitter<https://twitter.com/ADCSportsLogic> | YouTube<https://www.youtube.com/user/ADCSportsLogic>

**Comment by samsinsane** [comment]
@starkos this particular issue has been fixed, the submodules were updated after the commit that alpha6 is based on.

**Comment by starkos** [comment]
Great. I'll push ahead with getting a new release done then.
