### ISSUE TITLE
Projects dosen't in workspace for codelite

### ISSUE THREAD

**Issue by Geequlim** [premake/premake-core#331]
If the `location` set to different directories betweent projects and workspace, the projects won't be added into codelite's workspace.

This issus appeared on `premake5 codelite` the version of Premake5 is 5.0.0-alpha6

**Comment by samsinsane** [comment]
This seems to be working correctly in master. If you're still having issues with this on the latest version of Premake5, alpha8, please feel free to reopen this issue.
