### ISSUE TITLE
Unable to Exclude from build for Visual studio

### ISSUE THREAD

**Issue by JohannesMP** [premake/premake-core#333]
In Visual Studio it's possible to exclude a file from the build, but it will still show up in the project.

To do so manually I would:

- In the Solution Explorer, right click the file and choose `Properties`
- In `Configuration Properties`/`General` set `Excluded From Build` to **`Yes`**

The file will now be ignored by the compiler, but will still show up in the Solution Explorer.

------

As far as I've been able to find out, this behavior is currently not possible to emulate in Premake5.

I've tried to use `removefiles` and `exclude` for files, but that results in a project where the files in question are not even shown in in the Solution Explorer.

Is there a way to include a file in my VS project, but also have its `Excluded From Build` property enabled?

**Comment by JohannesMP** [comment]
My bad, using filters and the `ExcludeFromBuild` flag I was able to get this behavior.

For example:

    -- Ignore os-specific files
    filter { "system:macosx", "files:**_windows.*" }
      flags { "ExcludeFromBuild" }
    filter { "system:windows", "files:**_macosx.*"}
      flags { "ExcludeFromBuild"}

**Comment by josephpattara** [comment]
How we could achieve this on premake-4? I could understand filter is available only on premake-5.
My requirement is similar I need to see the files in VS browser but do not want to build it.

**Comment by tdesveauxPKFX** [comment]
If I remember correctly, we did something like this in Premake4
```
configuration { "windows" }
    excludes {"**_linux.*"}	
```
