### ISSUE TITLE
Remove intermediate files in bootstrap build

### ISSUE THREAD

**Issue by starkos** [premake/premake-core#334]
I ran into an issue where I wasn't able to build Premake properly after an update. I tried to use the boostrap makefile to get things back to a working state but got flooded with a bunch of linker errors as it tried to link against the object files from the previous build. I was able to fix it by removing all of the `bin/` and `obj/` folders manually.

It would probably be a good idea to always clean those folders out when doing a bootstrap build, just to make sure we're getting a clean build with the latest code.

**Comment by starkos** [comment]
Oh, and I should also mention: I'm becoming a big fan of this bootstrap makefile. Kudos to all involved.

**Comment by samsinsane** [comment]
Should also remove/exclude scripts.c as suggested in #318
