### ISSUE TITLE
premake5 alpha6 vs2012 project reload problems.

### ISSUE THREAD

**Issue by dgregorycryptic** [premake/premake-core#335]
Since we started using the alpha6 version, if we leave Visual Studio 2012 running, and rerun premake5, Visual studio reloads only some of the projects.  Many projects end up being marked "unavailable".

We are also plagued by a new "Mixed Platform" platform that did not exist in the previous version.  Visual Studio helpfully adds this platform for you under certain circumstances, and I cannot figure out why we're getting it now vs. before.

**Comment by starkos** [comment]
The alpha6 version is very buggy and I am working to get a new release out as soon as I can (which unfortunately isn't terribly fast). If you could check against the latest master branch and let us know if the problem still exists there it would be a big help.

**Comment by samsinsane** [comment]
Does this problem still occur in alpha8?

**Comment by samsinsane** [comment]
Closing due to no response in over a month. If this problem still persists, please feel free to reopen this issue.
