### ISSUE TITLE
Visual Studio solution file not opened with correct Visual Studio version

### ISSUE THREAD

**Issue by utelle** [premake/premake-core#349]
If more than one version of Visual Studio is installed (for example, VS2010 and VS2015) and a solution file was generated by premake5 for VS2010, then double clicking on the solution file will open it in VS2015. The reason is that the file type .sln is associated with "Microsoft Visual Studio Version Selector" and the "Microsoft Visual Studio Version Selector" checks the file for an UTF-8 BOM (0xEF 0xBB 0xBF) at the beginning of the file. Only if the UTF-8 BOM is found, the version information in the solution file is used to launch the corresponding Visual Studio version. If it is not found, then the Visual Studio version, that was installed last, will be launched.

premake4 emitted the UTF-8 BOM in function sln2005.generate(sln) in file vs2005_solution.lua with the following code:

		_p('\239\187\191') 

This should be added to premake5's Visual Studio solution file generation, too, to fix the issue.

**Comment by utelle** [comment]
By closer inspecting the premake5 source code and the generated solution file, I detected that an UTF-8 BOM is in fact emitted by premake5. However, the "Microsoft Visual Studio Version Selector" correctly identifies the Visual Studio version to be launched only, if the UTF-8 BOM is placed on a separate empty line.

That is, all what's required is to emit a carriage return / line feed after the UTF-8 BOM.

**Comment by starkos** [comment]
I believe this has already been fixed in the latest premake-core. If you are using an alpha build, you may want to try pulling the latest code directly. (Thanks for the research though!)

**Comment by tvandijck** [comment]
Yes, this was fixed in https://github.com/premake/premake-core/commit/6c5c8c8180fd26b41175378a93f9f181b8c011fe

**Comment by utelle** [comment]
Yes, I was using the alpha release 6. Thanks for confirming that the issue is already fixed in premake-core.
