### ISSUE TITLE
Support TCC

### ISSUE THREAD

**Issue by purger** [premake/premake-core#350]
I'd like to request the support for tinyc (tcc) as it's gaining a lot of use lately for code generation.

**Comment by tvandijck** [comment]
I think we need a little more information on this, a few links etc would help. Doing a cursory search on google for tincy yields pictures of indian women, and a link to the urban dictionary for tincy...

I quote:
"tincy
noun - Often correlated to an has obsession with hijinx; known to serve animals of short stature; 
adj. - resembling a behavior of craziness and picking up royalty's poop
"

**Comment by samsinsane** [comment]
Do you mean [tinyc](http://bellard.org/tcc/)? It appears to be thoroughly dead, no updates in over 2 years and the main developer has officially dropped support for it. Is there an active fork or something?

**Comment by purger** [comment]
@samsinsane Yeah, sorry, I managed to misspell it :) The active fork is at http://repo.or.cz/w/tinycc.git

**Comment by purger** [comment]
I would like to add that in CMake/gmake etc, I can simply set CC=tcc and everything works. Is there anything similar I can do in premake5?

**Comment by TurkeyMan** [comment]
I actually did this last night... just didn't push cus I didn't test it properly ;)

**Comment by purger** [comment]
@TurkeyMan That was fast. Push and I will test :)

**Comment by TurkeyMan** [comment]
@purger https://github.com/TurkeyMan/premake-tcc

It makes makefiles that look okay... haven't tested it much more than that.
This is very niche; you're probably best to tweak it till it works right for you and submit PR's for fixes.
Don't consider this officially supported ;)

**Comment by purger** [comment]
Doesn't seem to work on Win

**Comment by TurkeyMan** [comment]
Never tried it on windows. What's the problem? Pathing?
tools/tcc.lua should be pretty self evident, you can tweak it til it works
and submit a PR if you like?
