### ISSUE TITLE
prebuildcommands in multiple projects leading to incorrect behavior

### ISSUE THREAD

**Issue by crafter2d** [premake/premake-core#352]
I am using Premake5 alpha 6 for my C++ project. I set up three projects in my solution, something like this:

```lua
solution "Crafter2D"
	configurations { "Debug", "Release" }

project "UnitTest"
	kind "ConsoleApp"
	prebuildcommands { "python <command>"  }

project "Game"
	kind "ConsoleApp"
	prebuildcommands { "" }
```

In the generated VS2013 solution now both projects get the *python <command>* prebuild command. Removing the empty *prebuildcommands* option from the Game project leads to the same result, where I would expect it to be empty in another project.

**Comment by starkos** [comment]
I'm unable to reproduce this with alpha6 or the current master branch. If you run just the project snippet you posted above, does the problem still happen?

**Comment by starkos** [comment]
Closing for now—feel free to reopen with additional information.

**Comment by crafter2d** [comment]
Sorry for the late reply. I found out that I was using solution() in a project, which obviously changed the active scope. So, moving the code to a proper location fixed the problem for me. Thanks!
