### ISSUE TITLE
vpaths not working for vstudio actions?

### ISSUE THREAD

**Issue by utelle** [premake/premake-core#354]
I build premake5 from the latest sources. I ran the test suite (results below). Since the test suite contains tests that check the "vpaths" function for vstudio actions, I got the impression that "vpaths" should be usable. I specified vpaths and files as follows:
```
vpaths {
    {["Header Files"] = { "**.h", "**.inc" }},
    {["Source Files"] = { "**.cpp" }}
}
files { "../src/*.cpp", "../src/*.inc", "../include/*.h" }
```
But in the generated project files the vpaths were not used. Instead the filters were "src" and "include".

The vpaths feature worked like a charm in premake4. Isn't it supported in premake5? Will this change? If so, when?

Regards,

Ulrich

*Output from "premake5 test":*
```
Running action 'test'...
xcode_project.XCBuildConfigurationTarget_OnInfoPlist: .../premake5/modules/xcode/tests/test_xcode_project.lua:1010: (8) expected:
                                INFOPLIST_FILE = "../../MyProject-Info.plist";
...but was:
                                INFOPLIST_FILE = "e:/MyProject-Info.plist";
stack traceback:
        .../premake5/modules/xcode/tests/test_xcode_project.lua:1010: in function <.../premake5/modules/xcode/tests/test_xcode_project.lua:992>
vstudio_vs2010_rule_vars.onPathVar: ...ake5/tests/actions/vstudio/vc2010/test_rule_vars.lua:108: (2) expected:
        <MyVar>..\..\path\to\file</MyVar>
...but was:
        <MyVar>e:\path\to\file</MyVar>
stack traceback:
        ...ake5/tests/actions/vstudio/vc2010/test_rule_vars.lua:108: in function
 <...ake5/tests/actions/vstudio/vc2010/test_rule_vars.lua:100>
running time : 0.78
1367 tests passed, 2 failed
```

**Comment by starkos** [comment]
I can reproduce this. It seems to have something to do the the leading ".." on the paths in `files()`. If I move the script up a level and specify `files { "src/*.cpp", "src/*.inc", "include/*.h" }` everything works as expected.

**Comment by utelle** [comment]
Thanks for investigating the issue. Indeed it's working as expected if the script is moved one level up. For now, I can live with this workaround.

It seems that method project.getvpath returns abspath in case of leading ".." in the files pattern. I found out that changing the vpaths specification to include the leading ".." delivers the expected results. That is, the following code works:

```
vpaths {
    {["Header Files"] = { "../**.h", "../**.inc" }},
    {["Source Files"] = { "../**.cpp" }}
}
files { "../src/*.cpp", "../src/*.inc", "../include/*.h" }
```

I'm not sure whether this can be called correct behaviour or not. I had expected that the vpaths patterns I used at first would match any filename with the corresponding extension, independent of the actual path. However, the absolute path, where the file premake5.lua is located, is prepended to the vpaths pattern, and therefore only files in or below this directory would match. And therefore no match was found for my original vpaths specification.

The question is whether
```
"**.cpp"
```
should be interpreted as "all files with extension .cpp in or below the current directory" or as "all files with extension .cpp in any directory". Probably it was just my mistake to assume the latter.

Maybe it would be helpful to add a note and/or example to the documentation of vpaths to make clear what to expect.

**Comment by starkos** [comment]
> The question is whether "`**.cpp"` should be interpreted as "all files with extension .cpp in or below the current directory"

Ah, I didn't catch that but you nailed it. Paths are always specified relative the script file in which they are specified, so you are in fact searching for "all files with extension .cpp at or below the script file location". Mystery solved.

I'm going to mark this as closed, but feel free to reopen if you still have questions!
