### ISSUE TITLE
busted wiki pages

### ISSUE THREAD

**Issue by AndrewMeadows** [premake/premake-core#358]
Some premake wiki pages are showing up empty.

For example this page:  https://github.com/premake/premake-core/wiki/Getting_Premake

Which is accessible from here:  https://github.com/premake/premake-core/wiki

Possibly related:  there was another page that wasn't showing up for me.  I first navigated here:

https://github.com/premake/premake-core

clicked on **Download Premake** link and got here:

http://premake.github.io/download.html

Clicked on the **get in touch** link and got to an **empty page**!

I updated the **get in touch** page with some very basic info but after I did I saw that according to the edit history I had just overwritten a valid page rather than an empty one.  I copied the previous contents back to page and now it shows up correctly (more or less).  This is probably a bug in the github wiki, but it is affecting the premake documentation so I figured you should be aware of it.

**Comment by tvandijck** [comment]
I fixed the "getting_Premake" link... the main page was just linking to the wrong location.
Should have been:
https://github.com/premake/premake-core/wiki/Getting-Premake

**Comment by tvandijck** [comment]
And I think the getting_help page is the same problem... should be "getting-help"

**Comment by samsinsane** [comment]
I fixed up the get in touch links on the github.io page, I'll also remove the extra wiki page you created. Cheers! :)
