### ISSUE TITLE
Premake5 Alpha 6 Precompiled Header broken

### ISSUE THREAD

**Issue by dgregorius** [premake/premake-core#360]
I am using Premake with VS 2013 Update 5 and the pre-compiled hearders are not working correctly. For the PCHSource the /Yc switch is not set for the specified source file and therefore the pch file cannot be found obviously.

**Comment by ccptleu** [comment]
You will have to set the path to the stdafx.cpp file in pchsource and also add the path to include directories and to files (if not already done) in order to setup /Yc correctly.  For example something like:

       pchheader "stdafx.h"
       pchsource "../src/Project/stdafx.cpp"

      files { 
          "../src/Project/stdafx.cpp",
           ...
      }

More information can also be found in this post:
http://industriousone.com/topic/problems-precompiled-headers

**Comment by dgregorius** [comment]
Thanks, this worked! It is not clear to me why Premake cannot figure this out. It might be good to add this example to the docs. This was very clear and helpful!

**Comment by starkos** [comment]
Like [this](https://github.com/premake/premake-core/wiki/Precompiled-Headers)? :)

Suggestions on how Premake can figure it out itself are welcomed; I don't have any great ideas myself.

**Comment by dgregorius** [comment]
The example above is better than the doc - in my opinion. Sorry, from the doc I had no idea what was wrong with my setup. The above example states that I need to use the same path as I use for the project files.

**Comment by ccptleu** [comment]
Glad i was able to help.  I initially ran into the same problem where it wasn't clear to me from the documentation how to set /Yc for the stdafx.cpp file.   Perhaps the documentation just needs to be updated to state how to set this up using an example similar to above.
