### ISSUE TITLE
Premake5 alpha 6 Problems setting “UseDebugLibraries=true” in VS2013 in debug mode

### ISSUE THREAD

**Issue by ccptleu** [premake/premake-core#363]
Issue originated from post here:

http://stackoverflow.com/questions/34168062/sharedlib-project-not-setting-usedebuglibraries-true-in-debug-mode

**Comment by samsinsane** [comment]
Closing this as the issue was resolved in the SO question. The `optimize` API needed to be called with the value `Off` or `Debug`, see the SO question for more details.
