### ISSUE TITLE
Copy buildaction doesn't appear to work with Visual Studio 2015

### ISSUE THREAD

**Issue by jasonericson** [premake/premake-core#364]
As the title says: I'm attempting to add files as content to copy to the build directory, using the Copy buildaction. Unfortunately it doesn't appear to have any effect on my Visual Studio 2015 project. Here's my premake script in full:

    workspace "HelloWorld"
       configurations { "Debug", "Release" }
    
    project "HelloWorld"
       kind "ConsoleApp"
       language "C"
       targetdir "bin/%{cfg.buildcfg}"
    
       files { "**.h", "**.c", "test.txt" }
       
       -- Salient line here:
       filter "files:test.txt"
          buildaction "Copy"
    
       filter "configurations:Debug"
          defines { "DEBUG" }
          flags { "Symbols" }
    
       filter "configurations:Release"
          defines { "NDEBUG" }
          optimize "On"

According to [test_files.lua](https://github.com/premake/premake-core/blob/b883c7f45f7e08b39effcf7d174833a67ee1133e/tests/actions/vstudio/cs2005/test_files.lua) there should be a Content tag added to the csproj, along with a CopyToOutputDirectory tag, but nothing about my csproj file is changed at all. Is this is a bug, or am I doing something wrong?

**Comment by jasonericson** [comment]
I just realized I was linking to a test file for an older VS, looks like the test for VS 2010 (the most recent version being tested) doesn't check for this functionality.

I haven't spent much time in the code base yet, but I might poke around and if it's as simple as just implementing the functionality, I could give it a shot.

**Comment by samsinsane** [comment]
`.csproj` is a C# project file and won't be generated by the above script. Unfortunately, the `buildaction` API is also only for C# projects and for C/C++ projects you'll need to use `buildcommands "{COPY} test.txt"` instead. Let me know if this solves your issues. :)

**Comment by JohannesMP** [comment]
Is it documented anywhere that the `buildaction` API is only for C# projects? It's not mentioned anywhere on https://github.com/premake/premake-core/wiki/buildaction as far as I can find.

**Comment by samsinsane** [comment]
It wasn't explicitly stated, I just assumed based on the terminology in the wiki. Thanks for updating it to say that it's only for C# projects! :)

**Comment by samsinsane** [comment]
Closing this as the `buildaction` wiki page has been updated to inform users that it's only supported by C# projects.

**Comment by starkos** [comment]
I added a line to the [feature compatibility matrix](https://github.com/premake/premake-core/wiki/Feature-Matrix) to point out that this hasn't been done for C++ yet.
