### ISSUE TITLE
Change 'solution' to 'workspace'

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#37]
As discussed on the forum, 'workspace' seems a more natural term for more users.
It would be good to switch this over at some point.

**Comment by aggsol** [comment]
:+1: I agree, solution is as very Visual Studio centric term.

**Comment by starkos** [comment]
This is now complete: the official term in all code and on the wiki is now "workspace". Support for "solution" has been left in place to avoid breaking pretty much everyone; we can talk about deprecating it someday.

**Comment by TurkeyMan** [comment]
What an effort! Congratulations on this one! :)

**Comment by starkos** [comment]
Thanks! I had a drink or seven…

**Comment by TurkeyMan** [comment]
Good plan!
