### ISSUE TITLE
Some problems when building alpha7

### ISSUE THREAD

**Issue by tarruda** [premake/premake-core#372]
When building premake alpha7 from the released source bundle(https://github.com/premake/premake-core/releases/download/v5.0.0-alpha7/premake-5.0.0-alpha7-src.zip) I get the following errors:

```
==== Building zip-lib (release) ====
Creating bin/Release
Creating obj/Release
mkstemp.c
cc: error: unrecognized command line option ‘-mmacosx-version-min=10.4’
make[2]: *** [obj/Release/mkstemp.o] Error 1
make[1]: *** [zip-lib] Error 2
```

Compiler is gcc 4.8.4 and OS is ubuntu 14.04. When switching to clang 3.6, I get a bunch of `clang: warning: argument unused during compilation: '-mmacosx-version-min=10.4'` warnings(one for each file being compiled) and the compilation eventually fails with:

```
In file included from ../lib/asyn-thread.c:60:
../lib/urldata.h:163:10: fatal error: 'Security/Security.h' file not found
#include <Security/Security.h>

```

**Comment by starkos** [comment]
If looks like you are getting the Mac OS X build instead of the Linux one. How are you building it? You should be using the makefiles in `build/gmake.linux` (or generating your own).

**Comment by tarruda** [comment]
In my project, I have a top-level makefile that automatically downloads and builds premake in a private directory. In the makefile I set some logic to detect the OS and use `gmake.unix` for linux and other unices and `gmake.macosx` for OSX.

**Comment by tarruda** [comment]
I just checked the unzipped directory of alpha7, and there no `gmake.linux`, only `gmake.unix` and `gmake.macosx`

**Comment by starkos** [comment]
Apologies, use `gmake.unix`.

**Comment by tarruda** [comment]
I did use `gmake.unix` and that's how I got the error.

**Comment by crafter2d** [comment]
I am having the same problem. It seems that the error is in the Makefile of the contrib/zlib package.

**Comment by RafaGago** [comment]
Replacing the /contrib folder with the one of alpha-6 fixes the zlib compilation, but then things start failing on premake5 compilatuion:

```
==== Building Premake5 (release) ====
buffered_io.c
In file included from ../../src/host/buffered_io.c:9:0:
../../src/host/premake.h:8:17: fatal error: lua.h: No such file or directory
compilation terminated.
make[1]: *** [obj/Release/buffered_io.o] Error 1
make: *** [Premake5] Error 2
```

**Comment by RafaGago** [comment]
Replacing the "/contrib" folder with the one contained on the alpha-6 release workarounds the issue.

**Comment by samsinsane** [comment]
Is this issue resolved in alpha8?

**Comment by tvandijck** [comment]
closing issue, we're at alpha 10 now...
please reopen if issue persist.
