### ISSUE TITLE
'premake5 --help' also runs a script

### ISSUE THREAD

**Issue by freegodsoul** [premake/premake-core#381]
Hello! I'm using the last version of the **premake5** and when I call `premake5 --help` from the command line, it also executes default script `premake5.lua` **(but shouldn't in common sense)** for my project and outputs an error:
`attempt to concatenate global '_ACTION' (a nil value)`
cause I'm using `_ACTION` variable in my configuration build.

**Comment by starkos** [comment]
As designed. Premake must run the script in order to discover [custom command line options](https://github.com/premake/premake-core/wiki/Command_Line_Arguments).

**Comment by freegodsoul** [comment]
Thanks, now it is clear to me.

**Comment by jmansion** [comment]
I suggest that in the presence of (just ) --help, then a syntax error in the script should not be fatal (and prevent --help output).  It might be by design, but it sucks at the moment.
