### ISSUE TITLE
using os.outputof directly in options adds a 0 character

### ISSUE THREAD

**Issue by NuclearCookie** [premake/premake-core#382]
Hi,
I just downloaded the latest binary version of premake5 ( for linux ).
I use the following commands:
```
buildoptions{ "-std=c++11", os.outputof( 'sdl2-config --cflags' ) }
linkoptions{ os.outputof('sdl2-config --static-libs' ) }
```
This results in 
`  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g -std=c++11 -I/usr/include/SDL2 -D_REENTRANT 0 ` in my makefile.

Note the `0` at the end of the line.. It should not be there

The issue is resolved by first saving the result of os.outputof in a local variable, and using that variable in the buildoptions.

```
local cflags = os.outputof( 'sdl2-config --cflags' )
buildoptions{ "-std=c++11", cflags }
local static_lib_flags = os.outputof( 'sdl2-config --static-libs' )
linkoptions{ lib }
```

What could cause this?

**Comment by samsinsane** [comment]
The function `os.outputof` has two return values, the second one being the return code. I believe you could also do `buildoptions { "-std=c++11", (os.outputof("sdl2-config --cflags")) }', wrapping the function in parentheses should select only the first parameter. Let me know if this resolves your issue. :)

**Comment by NuclearCookie** [comment]
That resolves it indeed. It's not listed in the wiki though. Could you update it and inform about the second return value? Thanks

**Comment by samsinsane** [comment]
No worries, the wiki has been updated to list the second return value.
