### ISSUE TITLE
files with tokens and "*"

### ISSUE THREAD

**Issue by tbasnoopy** [premake/premake-core#39]
**prerequisites**
```batch
mkdir testfiles
touch testfiles/{x64,win32}{bla,foo}
touch testfiles/{foo,baa}
```

premake5.lua:
```lua
solution "myTestSln"
  location "testfiles/sln"

  platforms { "x64", "win32" }
  configurations { "debug", "release" }

  project "myTestPrj1"
    kind "Utility"
    files "testfiles/%{cfg.platform}*"
```

**Problem**
No files are in the project.

**Cause**
The `files` function calls later in progress the `store` function (api.lua:765).
This function find a "*" and call `os.matchfiles`, which didn't find something. This is okay, because at this time we cannot detoken all tokens but we have to do this in such a case.

```Lua
		store = function(field, current, value, processor)
			print(value)
			if value:find("*") then
				print("glob detected")
				value = os.matchfiles(value)
				for i, file in ipairs(value) do
					value[i] = path.getabsolute(value[i])
				end
			else
				print("no glob detected")
				value = path.getabsolute(value)
			end
			return value
		end,
```

**Fix**
a) detokenize in the function above (in my opinion not a good idea)
b) make os.matchfiles later in the oven. But I have no clue if a complete fileliste is important before the oven runs.

I will do the fix if someone can answer me which solution is the best.

**Comment by starkos** [comment]
We can't expand the tokens until after the configurations have been baked, otherwise we could pick up incorrect or incomplete information. 

We don't, technically, need the complete file list before baking so moving the wildcard expansion would be fine. But we have to make sure that we process any remove…() patterns afterwards…but that's tricky because adds/removes have to be processed the correct order.

So now we've got a deadlock: tokens can't expand until after baking, but removes need to be processed during baking. 

Do we just turn off token support for wildcard fields? Other ideas?

**Comment by tbasnoopy** [comment]
Hm... I understand the problem.

Token support would be fine because we use a lot own tokens for things like version numbers or special debug extensions like "_d" or "_".

But I have no clue what's the best option.

**Comment by tbasnoopy** [comment]
Two Ideas:

***a)***
We resolve all files with "*" and without tokens like now.
All token based files with "*" will be resolved later while baking.

But this means that the removefiles will not work in all cases.

***b)***
The hard/complex way:
We create a queue with add/removes of files which is processed later while baking.

**Comment by starkos** [comment]
As at least a partial fix, I would suggest adding another wildcard expansion check after token replacement on path fields. Then we can address any problems which arise from that on separate tickets.

**Comment by Meoo** [comment]
Is there any update on that issue?
I am trying to do:
files { "src/%{cfg.platform}/**.cpp" }
which is something that could be fairly common in cross platform projects...

A quick fix would be to perform a new os.matchfiles pass in oven.bakeFiles, but that would only work for the files command, and we still have the removefiles problem.
If anyone have pointers on how we can solve this issue in a clean way, I could work on a fix.

**Comment by starkos** [comment]
No update. I've been trying to clear the open pull requests, and this one hasn't come up.

**Comment by namiestew** [comment]
I read the above thread and it mentioned some issues with _removefiles_. Was this resolved in the commit above or do tokens still not work well with _removefiles_ because I am encountering duplicate ClCompile files in my _vcxproj_ when _removefiles_ is used.
