### ISSUE TITLE
Question about setting working directory.

### ISSUE THREAD

**Issue by rxantos** [premake/premake-core#392]
Is there a way to set the working directory for debugging in visual studio on a premake5 script?

I usually place my exe in one directory and then debug in another directory where test data resides. This is done in order not to pollute the test directory. I can do it by hand every time I create the project, but I wonder if there is a setting for selecting the working directory for debugging. 

![screenshot - 1_2_2016 5_29_28 pm](https://cloud.githubusercontent.com/assets/4187649/12074151/7b350072-b176-11e5-876e-bfc3488af58b.png)

**Comment by tritao** [comment]
Try the https://github.com/premake/premake-core/wiki/debugdir command
