### ISSUE TITLE
Adding predefined property sheets to solution.

### ISSUE THREAD

**Issue by rxantos** [premake/premake-core#397]
Is there a way to add a predefined property sheet to a solution?

The property sheet is not a compiling one (aka not a rule with an output). It just sets the visual studio directories (binaries. includes, libraries) to other paths. Right now I Just manually add it to visual studio every time I recreate the solution with premake5. But I wonder if there is a way to add it to the premake5.lua file.

**Comment by tvandijck** [comment]
sysincludedirs and syslibdirs will allow you to set the IncludePath, LibraryPath properties.
bindirs will allow you to set the "ExecutablePath" property.

there is a couple more in visual studio, such as the source directory, etc... these are not exposed through premake currently, but I guess you could use overrides to emit additional data. So not impossible, just not very convenient right now..

a feature to add predefined propertysheets is not available, but again using an override you can do virtually anything...
