### ISSUE TITLE
Specifying link mode preference for external libraries on Linux

### ISSUE THREAD

**Issue by yuyoyuppe** [premake/premake-core#400]
So I saw [some discussion](https://groups.google.com/forum/#!searchin/premake-development/linking/premake-development/szEuw8GRjpY/4RNOOG1gBQAJ) about implementing this feature, but it's not in the alpha 7 yet. Any updates planned on that? Also `*:static"`/`*:shared"` is still prefered syntax, right?

**Comment by samsinsane** [comment]
Closing as #401 was merged.
