### ISSUE TITLE
Unable to copy files with buildaction

### ISSUE THREAD

**Issue by JohannesMP** [premake/premake-core#410]
I'm trying to do something like the following in a vs2015 project:

    filter { "files:"**.txt" }
      buildmessage "FILES TO COPY: %{file.relpath}, found at: {file.abspath}"
      buildaction "Copy"

But no matter where I place txt files, I am unable to get any files to get copied to the output directory, or show up in visual studio's log.

My whole premake5.lua file is in a <a href=https://gist.github.com/JohannesMP/aeab9e9bcbab49674174#file-premake5-lua-L63-L67>gist here</a>, and the entire project (just a single hello.world cpp file) as <a href=https://github.com/JohannesMP/Miscellaneous-Files/raw/master/Premake/CopyTest/copytest_0.1.zip>a zip here</a> - to build, run `/Build/build_vs2015.bat`, project will be at `/project_vs2015`

What am I missing here?

**Comment by JohannesMP** [comment]
It seems, according to a comment (https://github.com/premake/premake-core/issues/364#issuecomment-167118372) that the buildaction command is only designed for c# projects? Why is this not listed in the documentation? https://github.com/premake/premake-core/wiki/buildaction doesn't list that anywhere.

**Comment by starkos** [comment]
> Why is this not listed in the documentation?

Help with the documentation is always appreciated, and this sounds like a great addition.

**Comment by JohannesMP** [comment]
I'd be happy to help contribute, but I don't know the scope of which of these buildactions are, and arn't limited to c# projects. Where would I look to figure this out?

**Comment by JohannesMP** [comment]
@starkos: even ignoring the buildaction, should I be able to see the buildmessage somewhere when compiling, given the test project? It never seems to show up.

**Comment by starkos** [comment]
`buildmessage()` will only appear if there are `buildcommands()`, see [Custom Build Commands](https://github.com/premake/premake-core/wiki/Custom_Build_Commands).

**Comment by JohannesMP** [comment]
Should the following result in anything?

    filter { "files:**.txt" }
      prebuildcommands  { "touch %{file.name}_prebuild.txt" }
      prebuildmessage   "PRE BUILD MESSAGE %{file.name}"
      postbuildcommands { "touch %{file.name}_postbuild.txt" }
      postbuildmessage  "POST BUILD MESSAGE %{file.name}"

    filter { "files:**.cpp" }
      prebuildcommands  { "touch %{file.name}_prebuild.txt" }
      prebuildmessage   "PRE BUILD MESSAGE %{file.name}"
      postbuildcommands { "touch %{file.name}_postbuild.txt" }
      postbuildmessage  "POST BUILD MESSAGE %{file.name}"

I've gotten pre/post-buildcommands/message to work globally but not with filters.

**Comment by starkos** [comment]
No, it doesn't. That would be a nice syntax to have, and I'm sure we could apply to other inputs as well, but it wouldn't be a simple change.

**Comment by samsinsane** [comment]
Closing this as the `buildaction` wiki page has been updated to inform users that it's only supported by C# projects.
