### ISSUE TITLE
CodeLite workspace contains no projects.

### ISSUE THREAD

**Issue by rhythmchicago** [premake/premake-core#418]
The following works fine in Premake4, but generates an empty workspace in premake5.

The output when I run the command:

$ premake5 codelite
Building configurations...
Running action 'codelite'...
Generated LogicCore.workspace...
Generated lclib/lclib.project...
Generated lcmotion/lcmotion.project...
Generated lcrtlib/lcrtlib.project...
Generated lcrt/lcrt.project...
Generated lcxmake/lcxmake.project...
Generated lcxtest/lcxtest.project...
Generated lcmotionterm/lcmotionterm.project...
Done (80ms).

It appears to be parsing the project, but when I open the file in CodeLite, there is simply the workspace name listed in the tree; there are no projects listed beneath it. If I use premake4 instead, everything works perfectly without change.

Main solution:
solution "LogicCore"

	-- set the major and minor build numbers
	VERSION_MAJOR = 1
	VERSION_MINOR = 0
	
	major = "VERSION_MAJOR=" .. VERSION_MAJOR; 
	minor = "VERSION_MINOR=" .. VERSION_MINOR; 

	defines { major, minor }

	configurations { "Debug", "Release" }
 
	configuration { "Debug" }
		targetdir "../bin/debug"
 
	configuration { "Release" }
		targetdir "../bin/release"
 
	if _ACTION == "clean" then
		os.rmdir("../bin")
	end
	
	-- Public include directory
	include "lclib"
	include "lcmotion"
	
  	include "lcrtlib"	
  	include "lcrt"
	include "lcxmake"
	include "lcxtest"
	include "lcmotionterm"
	
One of the sub-projects:
project "lcrt"
	kind "ConsoleApp"
	language "C"
	location "./"
	files { "**.h", "**.c" }
	excludes { "./Deprecated/**" }

	includedirs{ "../../include", "../lcrtlib", 
		"/usr/local/src/ethercat/include" }

	libdirs{ "/opt/etherlab/lib" }

	links{ "lclib" }
	links{ "lcrtlib" }
	links{ "lcmotion" }

	links { "ethercat" }
	
	-- math libraries
	links { "m" }
	-- pthread libraries
	links { "pthread" }
	-- posix shm function
	links {"rt"}
	
	-- embeding lua
	includedirs{ "../lua/src" }
	libdirs{ "../lua/src" }
	links{ "lua" }	
	links{ "dl" }

	configuration {"Debug"}
		targetsuffix "_d";
		defines { "DEBUG" }
		flags { "Symbols" }
		
		
	configuration {"Release"}
		defines { "NDEBUG" }
		flags { "Optimize" }

Please let me know if there is any further information I can provide.

Thanks!

**Comment by crafter2d** [comment]
I have the same problem. For me the workspace is emptied each time that I run premake5.

**Comment by samsinsane** [comment]
I did some testing locally, and it appears if the `startproject` API isn't used, Premake doesn't emit the `Active` attribute on a `Project` element and then CodeLite fails to reload the project correctly. Can I get you both to test this out and let me know if that fixes it? If so, I'll submit a PR to fix this up. Thanks!

**Comment by rhythmchicago** [comment]
Samuel,

I’ll happily try out anything you like. I’m not familiar with the startproject API, or I’m simply not understanding. Please clarify what you need and I’ll get you feedback as quickly as possible.

Thanks!
Thomas C. Bitsky Jr. | Lead Developer
ADC | automateddesign.com<http://automateddesign.com/>
P: 630-783-1150 F: 630-783-1159 M: 630-632-6679

Follow ADC news and media:
Facebook<https://facebook.com/automateddesigncorp> | Twitter<https://twitter.com/ADCSportsLogic> | YouTube<https://www.youtube.com/user/ADCSportsLogic>

**Comment by starkos** [comment]
Just add a line to your solution's configuration like:

```
startproject "SomeProjectName"
```

…and then regenerate and see if everything loads as expected. Let us know what you find out and we can either make the fix or keep researching. Thanks!

**Comment by rhythmchicago** [comment]
Same results as before:


user@coredevel:~/srcroot/LogicCore/src$ premake5 --version
premake5 (Premake Build Script Generator) 5.0.0-dev

user@coredevel:~/srcroot/LogicCore/src$ premake5 codelite
Building configurations...
Running action 'codelite'...
Generated lcmotion/lcmotion.project...
Generated lclib/lclib.project...
Generated lcrtlib/lcrtlib.project...
Generated lcrt/lcrt.project...
Done (156ms).

However, opening the file in CodeLite, the Workspace shows the Workspace title only with no projects or subitems listed.

Please let me know if there is any more information I can provide.

Thanks!
Thomas C. Bitsky Jr. | Lead Developer
ADC | automateddesign.com<http://automateddesign.com/>
P: 630-783-1150 F: 630-783-1159 M: 630-632-6679

Follow ADC news and media:
Facebook<https://facebook.com/automateddesigncorp> | Twitter<https://twitter.com/ADCSportsLogic> | YouTube<https://www.youtube.com/user/ADCSportsLogic>

**Comment by crafter2d** [comment]
I just figured out what the problem was and also have a preliminary fix that someone with more knowledge should apply to the official Premake.

Premake5 put out for a CodeLite workspace like this (partial):

    ﻿<?xml version="1.0" encoding="UTF-8"?>
    <CodeLite_Workspace Name="Crafter2D" Database="" SWTLW="No">
      <Project Name="Core" Path="core\Core.project"/>

I compared this with the file that CodeLite generated when I re-added the Core project (as it was not added while loaded, hence the issue). The resulting file was:

    ﻿<?xml version="1.0" encoding="UTF-8"?>
    <CodeLite_Workspace Name="Crafter2D" Database="" SWTLW="No">
      <Project Name="Core" Path="core/Core.project"/>

Note that in the Path attribute of the Project element that the slash is forward instead of backward. After I manually replaced those in a newly generated workspace file, all my projects where loaded correctly in CodeLite.
In in Premake4 source code I pin-pointed the problem to be in the codelite_workspace.lua file:

    -- Build a relative path from the workspace file to the project file
    local prjpath = p.filename(prj, ".project")
    prjpath = path.translate(path.getrelative(prj.workspace.location, prjpath))

In the path_translate C file I noticed that the / where replaced by the \ characters when nothing is on the Lua stack. As I am running CodeLite in Linux I just removed the path.translate from the second line and the workspace was generated correctly. So, please have a look at this and see if something additional (I assume the slash) must be pushed on the stack or that the translate can be removed all together.

**Comment by starkos** [comment]
In theory, just remove `path.translate()` from that call and you should be good. I assume CodeLite is smart enough to do the right thing on whatever platform it happens to be running on.

**Comment by samsinsane** [comment]
@starkos you're giving CodeLite way more credit than it deserves there. I installed it on my Windows box, and it requires Linux path separators to work too. I think it would better to explicitly have `path.translate` use the Linux path separator instead, `prjpath = path.translate(path.getrelative(prj.workspace.location, prjpath), '/')`, thoughts?

**Comment by starkos** [comment]
Premake already uses the forward slash for all paths, so this:

    path.translate(path.getrelative(prj.workspace.location, prjpath), '/')

…is the same as this:

    path.getrelative(prj.workspace.location, prjpath)

**Comment by samsinsane** [comment]
Are the inputs from user scripts converted to use forward slashes too? I don't think I've ever seen the code for this, out of curiosity, where does this happen?

**Comment by starkos** [comment]
No. Paths in user scripts are, by convention, always specified with forward slashes.
