### ISSUE TITLE
Should I make a debian package/repo?

### ISSUE THREAD

**Issue by soccermitchy** [premake/premake-core#420]
Hello, I use Premake5 on many systems already, and I have a simple script that downloads premake5, untars it and puts it in /usr/bin, but how many people would be for/against me creating a Debian package and a Debian repo for premake5? If I do this, I will also set up scripts that, if the repo owner sets up a web hook, will auto-update the package on the Debian repo whenever there is an update (I can even filter it so it checks if smoething is in part of the commit message)

**Comment by soccermitchy** [comment]
Quick note: Just remembered I have a Gitlab server so I can just set it up with gitlab-ci and have a copy of this repo that, when pushed to, updates the package. Could be set up as an additional remote on the repo, and I'll allow contributors from here to push to it.

**Comment by tvandijck** [comment]
I think it would be great if we could have the  releases be packaged up on a debian/linux package server... anyone willing to take that effort is welcome to do so... and I can help setting up the proper webhooks if such a thing is needed.

**Comment by soccermitchy** [comment]
Sweet, I'll work on that when I get home.

**Comment by soccermitchy** [comment]
Just came up with an idea for something I may be able to do for this: I may
be able to make a premake5-git package that just pulls the latest premake5
and compiles it using a post-install script. Would anyone use it?

**Comment by soccermitchy** [comment]
Repo is now up, you can now install Premake5 5.0.0-alpha7 like this:
```
apt-key adv --keyserver keys.gnupg.net --recv-keys FFBA9E40
echo 'deb http://repo.nofla.me/ jessie main' >> /etc/apt/sources.list
apt-get update
apt-get install premake5
```

I would still like to hear people's opinions on a premake5-git package, to see if anyone would use it.

**Comment by starkos** [comment]
Can I add those instructions to the download page on [premake.github.io](https://premake.github.io)? (Or can you [submit a pull request there to add them](https://github.com/premake/premake.github.io))?

**Comment by soccermitchy** [comment]
Just woke up, I'll submit a PR in a few minutes

**Comment by soccermitchy** [comment]
I couldn't find a way to integrate my Gitlab CI server with Github, would you guys be OK with just having a separate git remote for CI builds? (this does have the added advantage of only having CI builds when you want them, also keep in mind that I'm going to be updating the package on the repo on every CI build...)

**Comment by starkos** [comment]
I think we should keep our Travis-CI setup, if that's what you are asking? But whatever system you want to put in place to manage your Debian repo is of course fine!

**Comment by soccermitchy** [comment]
Does Travis have sftp and Debian packaging tools on it? I was using equivs
to create the Debian packages, but if Travis has that (or lets you install
your own stuff) then I can set it up there probably

**Comment by starkos** [comment]
I'm not sure, I'm not the one who set it up. I'm sure [their website](http://travis-ci.org) should say though?

**Comment by meepdarknessmeep** [comment]
@starkos @soccermitchy the dns doesn't seem to resolve repo.nofla.me anymore, and it also seems the whole site is gone as well as the https certificate being broken.

It could be a security risk to keep having this information on the premake download page.

**Comment by meepdarknessmeep** [comment]
whoops, and @tvandijck

**Comment by soccermitchy** [comment]
Hey, sorry that the repo doesn't work anymore, other stuff on the repo was
using too much bandwidth so I just took down the whole repo, completely
forgot I was still hosting the repo for this though (my repo for premake
used almost no bandwidth, but stuff I was hosting for my friends used
nearly a constant 800mbps). If someone still has debs signed by me for it,
I'd be happy to host them again though and set up the repository again
(although I'm not entirely sure I still have my gpg key used for the old
repository still).

**Comment by starkos** [comment]
I've removed the links, thanks for pointing it out!

**Comment by ocornut** [comment]
@starkos Out of curiosity do you know if someone else has been hosting Premake5 packages? or Brew formulas? Or would you recommend against it, Premake5 being still in active alpha state?

**Comment by starkos** [comment]
Not that I know of. If someone wants to take that on and maintain it, we're happy to link to it and add it to the Download page. If it something that can be easily added to our release script, I'm happy to consider that as well.

**Comment by samsinsane** [comment]
> If it something that can be easily added to our release script, I'm happy to consider that as well.

I'd really like to see this happen, or at the very least a separate script that generates them. Either way, I want the repo to contain the instructions on how to generate the packages, it's a bit weird having the Debian package files but nothing indicating how you make the package.
