### ISSUE TITLE
VS2012 not reloading projects when premake is run in the background.

### ISSUE THREAD

**Issue by dgregorycryptic** [premake/premake-core#431]
It is currently the case that if you run premake, and you do not specific a uuid for a project, that premake will generate one for you.  This is good.

It is currently the case that if you run premake again with the same inputs, that premake may not keep the same uuid as it previously had.  This causes Visual Studio 2012 projects to not reload properly.

Is there anything we can do about it? (like perhaps check to see if the generated project already exists, read the uuid out of it, and use that instead of generating a new one)

-Dave

**Comment by starkos** [comment]
We already generate the UUID based on a hash of the project name (see `project.lua` line 31). It should not change unless you change the project's name.

**Comment by dgregorycryptic** [comment]
Whoops, I jumped the gun on this.
This was a theory, and apparently not proven.  We still definitely are having an issue that VS2012 will sometimes refuse to reload a project if premake is run while those projects/solutions are already loaded.

**Comment by samsinsane** [comment]
Does VS2012 prompt for reload and fail, or does it simply not prompt at all? Also, what changes between the runs of Premake?

I've noticed a few times that VS2013 and VS2015 haven't reloaded, and it seems that if the only thing that changes is the `.vcxproj.filters` files, then it won't reload. This seems more likely to be a limitation of VS rather than Premake.

**Comment by tvandijck** [comment]
Yeah, we've noticed the same thing... if the vcxproj.filters file changes, VS will not detect a change to reload. It's quite annoying..

**Comment by dgregorycryptic** [comment]
I have not investigated the actual differences, but anecdotally I have seen .vcxproj.filters files changes without the associated .vcxproj changing.  Perhaps that is the main issue.

Why are those files changing when the .vcxproj does not?

If the change is legit, we perhaps should "touch" the .vcxproj file to force it to reload also. That may fix it?

If the change is not legit (like the file that is generated is not stable from run to run), then we should fix that.

**Comment by tvandijck** [comment]
Well, if you change the "vpaths" the filter file will change, but the vcxproj will not.. I don't know of any other reason why the filter file should change, since all it does is create the virtual folder structure in the solution explorer.

other then that, if one of these files changes for other reasons, while it shouldn't... we should investigate.

**Comment by tvandijck** [comment]
One other thing I have noticed in the past is that "lua tables" are not stable, so if the order of a list of files changes, this file changes as well... but in that case the vcxproj should change as well, unless we sort there, and not for the filters file or something like that.

**Comment by dgregorycryptic** [comment]
I can 100% declare that we do not use vpaths.  We let the folders fall where they may, based on file location.

I think you may have hit on the difference.  Sorting.

I have seen between alpha6 and alpha7 differences in sorting for the .vcxproj itself.  In some cases, it was a regression (going from sorted to unsorted).  Project References were one place I definitely recall changing.  There were probably others.

I will investigate this and report back, unless someone beats me to it.

**Comment by starkos** [comment]
Any new information?

**Comment by starkos** [comment]
Closing this one for now; feel free to reopen with new information.
