### ISSUE TITLE
Support solution / workspace folders

### ISSUE THREAD

**Issue by neico** [premake/premake-core#447]
When you try to use this feature of VS (not sure if other IDE's support it as well) premake seems to handle it wrong.

When you do project( "MyFolder/MyProject" ) VS correctly puts MyProject into a Solution folder MyFolder.
It however also changes the targetname, root namespace etc.
What it also causes is that all files (cpp, hpp etc.) are listed correctly with the same path, but when you try to double-click open them it says that the file doesn't exist because the relative path to the file is out of sync. (it's one ../ less then it needs to be)

Another thing to mention is: if a solution folder name is the same as a project name ex. "MyTest/MyTestProject" and a singular project name: "MyTest"
then the "MyTest" project vanishes as VS apparently isn't smart enough to handle this case correctly.
"MyTest/MyTest" however fixes it.

Since I'm not sure how premake should correctly handle this I'll refrain from suggesting any solutions and rather leave it up to discussion.

**Comment by starkos** [comment]
That should be:

```lua
group "MyTest"
project "MyTestProject"
```

Closing…feel free to reopen with additional questions.

**Comment by neico** [comment]
Ah there we go, maybe put it on "See Also" on the project / workspace page?

PS: there's a "Project" in "See Also" on the Project page, copy paste error or was this supposed to be something else?

**Comment by starkos** [comment]
It's a wiki, feel free to edit!
