### ISSUE TITLE
os.outputof carries over newlines

### ISSUE THREAD

**Issue by fzwoch** [premake/premake-core#45]
Having custom buildoptions (and linkoptions) often require some *-config tools to be run for creating proper flags. I think this is supposed to be done with os.outputof(). However the final newline character gets carried over in the final Makefile. For example:

```
buildoptions { os.outputof("pkg-config --cflags jansson"), os.outputof("wx-config --cppflags") }
```

will result in an unwanted newline in the Makefile:

```
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g -I/usr/local/Cellar/jansson/2.7/include
 -I/usr/local/Cellar/wxmac/3.0.2/lib/wx/include/osx_cocoa-unicode-3.0 -I/usr/local/Cellar/wxmac/3.0.2/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__
```

causing gmake to fail with ```*** missing separator.  Stop.```

**Comment by starkos** [comment]
Trimming newlines is probably a good idea, but for a Posix makefile you might want to use something like this instead:

    buildoptions { "`pkg-config --cflags jansson`", "`wx-config --cppflags`" }

**Comment by fzwoch** [comment]
Thats true. But I was more looking in a way to make it work for as many output formats as possible.  The above will unfortunately not work for the Xcode module. Not sure about VS but I guess the same applies here too. Some of these library are very tricky to add to a project as they very much depend on the local machine's installation of these libraries - thats why these *-config tools exist in the first place :/

So white space trimming is very much welcome!
