### ISSUE TITLE
Migration path from CMake to Premake would be great :)

### ISSUE THREAD

**Issue by eyalsk** [premake/premake-core#454]
Hello,

I didn't know where to post this so sorry if it's the wrong place!

I've been using CMake for a new project I'm working on and then I heard about Premake and the moment I discovered it's based on Lua I didn't even think twice! and decided to migrate to Premake.

I understand Premake isn't quite where CMake is today and it isn't as large as CMake in terms of community but It would be a great idea if there was some sort of document that will do a side by side comparison and allow people that know CMake to migrate into Premake more easily.

What I imagine is have some sort of a table that for each given functionality in CMake will show people how to do the same in Premake.

P.S. I saw that there's a google group but it was really nice if there was an IRC channel too. :)

**Comment by starkos** [comment]
You are welcome to post this as an issue here, but I've never used CMake so I'm not qualified to author that matrix. If you would like to create one, [the premake-core wiki](https://github.com/premake/premake-core/wiki) would be the place for it.

Same goes for IRC…feel free to set up a channel, but I don't (currently) use it.

**Comment by eyalsk** [comment]
@starkos sure! once I'll have a bit more experience with Premake I'll do it! :)
