### ISSUE TITLE
Few days with Premake5 feedback and thoughts

### ISSUE THREAD

**Issue by eyalsk** [premake/premake-core#456]
**Disclaimer:** _I'm completely new to Premake so bear in mind that it's all from the perspective of a newbie._

I'm a CMake user, I never really liked CMake and it was always something I used because I had to and not because I wanted to and so recently I heard about Premake and decided to use it! _as I wrote in another post._

The learning curve of CMake is pretty shallow, it takes time to learn it and get used it but because the community is pretty big it makes things a lot easier but it also seems like there's also a lot less friction with the tool, for example to make the dependencies work it took me few days with Premake and when I posted the issue here and on [Stackoverflow](http://stackoverflow.com/questions/36234829/premake-doesnt-picking-up-dependencies/36248352) but no one replied.

So in order to remove some of the _friction points_ I had with Premake I wrote some stuff that _maybe_ can be incorporated into the core, I can probably send a pull requests for these stuff together with some tests but the question is whether these modifications make sense? :)

**Dependencies:**
With CMake I don't need to hard code my dependencies, it figures them out using the project name so I expected Premake to behave in the same way so to fix this I wrote the following function:
```Lua
function includedeps(workspace, ...) 
    local workspace = premake.global.getWorkspace(workspace)
    
    local args = { ... }
    local args_count = select("#", ...)
    local func = select(args_count, ...)

    if type(func) == "function" then
        args_count = args_count - 1
        args = table.remove(args, args_count)
    else
        func = nil
    end

    for i = 1, args_count do
        local projectName = select(i, ...)
        local project = premake.workspace.findproject(workspace, projectName)
        if project then
            local topIncludeDir, dirs = path.getdirectory(project.script)
            if func then 
                dirs = func(topIncludeDir)
            else
                dirs = os.matchdirs(topIncludeDir .. "/**")
                table.insert(dirs, topIncludeDir)
            end
            includedirs(dirs)
            if premake.project.iscpp(project) then
                libdirs(dirs)    
            end
            links(args)
        else
            error(string.format("project '%s' does not exist.", projectName), 3)
        end
    end
end
```
_I don't know whether it's a good idea or implemented correctly but it works for me and that's what I wanted to have._ I've provided more details about it at my [issue](http://stackoverflow.com/questions/36234829/premake-doesnt-picking-up-dependencies/36248352) at SO.

**Modules:**
I wrote few little modules for my project but because I put them at a directory named `.premake` at the root level of the project I had to use relative paths and it was annoying so to fix this I override `require`:
```Lua
local paths = {};

local function containSlashes(name)
    return string.contains(name, "/") or string.contains(name, "\\")
end

local function getDefaultModulePath(modulePath)
    return path.join(".premake", path.appendExtension(modulePath, ".lua"))
end

local function findModule(searchPath, defaultModulePath)
    local modulePath = path.join(searchPath, defaultModulePath)
    table.insert(paths, modulePath)
    if not os.isfile(modulePath) then
        searchPath = path.getdirectory(searchPath) 
        modulePath = searchPath ~= "." and findModule(searchPath, defaultModulePath) or searchPath
    end
    return modulePath
end

local function getRelativeModulePath(currentWorkingDir, modulePath)
    return modulePath ~= "." and path.getrelative(currentWorkingDir, modulePath) or modulePath
end

function resolveModule(originalModulePath)
    local modulePath = originalModulePath
    if not containSlashes(modulePath) then 
        local currentWorkingDir = os.getcwd();
        modulePath = getDefaultModulePath(modulePath)
        modulePath = findModule(currentWorkingDir, modulePath)
        modulePath = getRelativeModulePath(currentWorkingDir, modulePath)
        if modulePath == "." then
            error(string.format("module '%s' not found:\nLocations:\n\t%s", originalModulePath, table.concat(paths, "\n\t")), 2)
        end
    end
    return path.delextension(modulePath)
end

premake.override(_G, "require", function(base, modulePath, versions)
    local result, mod = pcall(resolveModule, modulePath)
    
    if not result then
        error(mod, 3)
    else
        result, mod, versions = pcall(base, mod, versions)
        if not result then
            error(mod, 3)
        end
    end

    return mod, versions
end)
```
_Again, I'm not sure whether it's implemented correctly and it probably can be improved but it works._

**Fixes:**
I had to fix `getextension` to work _correctly_ for my needs, seems like the default implementation naively gets the last period regardless to wherever it exists so I override it with the following:
```Lua
premake.override(path, "getextension", function(base, p)
    p = path.getname(p)
    local i = p:findlast(".", true)
    if (i) then
        return p:sub(i)
    else
        return ""
    end
end)
```
**Additions:**
I found no function to remove the extension so I added one:
```Lua
function path.delextension(p)
    local ext = path.getextension(p)

    if not ext then
        return p
    end

    return p:match("^(.*)" .. ext .. "$")
end
```

All in all I'm pretty satisfied with Premake but it's unfortunate that the community isn't as big as CMake and that the tool requires you to deal with paths rather than dependencies and when it comes to modules, it's better to have some default directory such as .premake at the root level that you can just put the files there and not think about paths at all...

Anyway, I'm really grateful for having Premake so thank you.

**Comment by starkos** [comment]
I appreciate the feedback, but the issue tracker is really for reporting a bug or making a feature request, and not for general discussions. We have [a developer forum](https://groups.google.com/forum/#!forum/premake-development) for more general discussions like this.

(Note: best to log one issue per bug or feature request, so they can be tracked and closed independently.)

If you search for "premake usages" you can find some past discussions on this topic, including some design ideas and patches.

Your fixes would be better submitted as pull requests, [here is GitHub's guide to creating one](https://help.github.com/articles/using-pull-requests/).

**Comment by tvandijck** [comment]
Thank you for the write up.... and I agree on many of these items.. The community is unfortunately not very big. CMake got most of it's momentum from LLVM/Clang, and popularity grew from there. It's a good tool, but I dislike their custom and somewhat adhoc 'scripting language', it's not as expressive as something like scons (python) or premake (lua). I would say in general the premake support system consists of about 3-4 people, many of who use premake at work, so at least for me I'm here during the week (when I have time), but in the weekend I'm not looking at this at all. Stackoverflow, I don't even have an account, find it a useless forum.

As for some of your additions and bugfixes, please submit pull request for those and I'll merge them as needed.. As for the "delextention", it's a good addition, but there is a "changeextension" method, which could probably be used as well... I think I ran into the bug with the getextension once as well, but seeing the code you replaced it with, is somewhat hard to compare outside of a pull request.

The .premake folder is a great idea, I don't know if the changes/additions you made are correct, but the only way to find out is to have them in a pull request and get CI to test it. Some unit-tests would be greatly appreciated I guess.

"includedeps" I like the idea, it does however have somewhat of an order dependency. You can't have an "includedeps" on a project that has not been defined yet. I'd say that that is not the biggest deal, but should be clearly documented if we included this API.

**Comment by eyalsk** [comment]
Okay, thanks! I'll try to send a pull requests asap for these things. 

I didn't notice that the google group is actually the dev forum, sorry! :)
