### ISSUE TITLE
Migrate use of "configuration" away in favor to "filter"

### ISSUE THREAD

**Issue by neico** [premake/premake-core#462]
premake 5.0 starts with filter being supported, so premake5.lua should always reflect the latest changes until it get's a final release (RTM), in which case I imagine it becoming harder to force new  best practices as there will be different versions in use at the same time, which shouldn't happen during alpha, beta and whatnot states.

The same probably goes for the test files, but I'm not sure in how much premake4.lua influences those.

Generally when I don't know how something's handled correctly (when the wiki isn't 100% clear about something) I end up looking at either the root premake file or the tests, and only resort to searching the entire source when there really is no other way (as the source gets really confusing the deeper you get with specific features).
And I imagine others doing it similar, so those should reflect the latest syntax and behaviour if possible. (as tests are fragmented regarding features it's hard to tell if they check for both configuration and filter, plus, searching for those keywords bring up 10+ pages worth of code to look trough)

**Comment by starkos** [comment]
I agree—I left the `configuration()` calls in there to give people a chance to upgrade to newer versions of Premake5, but enough time has probably passed by now to justify the switch.

Feel like making a pull request for it?

**Comment by neico** [comment]
Sure, are there other things and places that need cleaning up though?
I haven't been following all the changes and best practices

**Comment by starkos** [comment]
Smaller PRs are easier to review and approve, just changing to `filter()` would be a good one.
