### ISSUE TITLE
custom build rule: attempt to call global 'buildcommand' (a nil value)

### ISSUE THREAD

**Issue by rxantos** [premake/premake-core#470]
I tried to make a custom rule for doxygen documentation then stumbled into this error.
```bat
premake5.lua:6: attempt to call global 'buildcommand' (a nil value)
```
At first I thought it was my fault, so 

I tried to cut and paste the example of making a custom command into a different premake5.lua
Tried it alone, it didn't work.

Tried it in a small workspace.  Same result.

Tried before the workspace command.  Same result.

Tried after the workspace command. The result is the same. 

Removed the PREMAKE_PATH environment just in case something else was in conflict. Same result.

Downloaded the last binary, placed alone in the same directory as the script. Run that exact executable. Still the same result.

Below is the Hello world example combined with the custom build example. 

```lua
rule "MyCustomRule"
  display "My custom compiler"
  fileExtension ".xyz"

  buildmessage 'Compiling %(Filename) with MyCustomCC'
  buildcommand 'MyCustomCC.exe -c "%(FullPath)" -o "%(IntDir)/%(Filename).obj"'
  buildoutputs '%(IntDir)/%(Filename).obj"'

workspace "HelloWorld"
   configurations { "Debug", "Release" }

project "HelloWorld"
   kind "ConsoleApp"
   language "C"
   targetdir "bin/%{cfg.buildcfg}"

   files { "**.h", "**.c" }

   filter "configurations:Debug"
      defines { "DEBUG" }
      flags { "Symbols" }

   filter "configurations:Release"
      defines { "NDEBUG" }
      optimize "On"  
```

**Comment by starkos** [comment]
It's [buildcommands](https://github.com/premake/premake-core/wiki/buildcommands), with an "s". :)

**Comment by rxantos** [comment]
Then I suggesst you update your example
https://github.com/premake/premake-core/wiki/Custom-Rules

as its a CUT AND PAST from it.

**Comment by tvandijck** [comment]
I fixed the example in on the page you linked, thank you for noticing that.
