### ISSUE TITLE
buildtarget and linktarget tokens are inconsistent

### ISSUE THREAD

**Issue by eyalsk** [premake/premake-core#479]
So here are the tokens:

cfg.buildtarget.abspath => bin/Debug/Yalla.Library.dll
cfg.buildtarget.bundlepath => bin/Debug
cfg.buildtarget.directory => d:\Users\Eyal\Projects\Code\Yalla\lua_build\bin\Debug\
cfg.buildtarget.relpath => bin/Debug/Yalla.Library.dll
cfg.linktarget.abspath => bin/Debug/Yalla.Library.lib
cfg.linktarget.bundlepath => bin/Debug
cfg.linktarget.directory => bin/Debug
cfg.linktarget.relpath => bin/Debug/Yalla.Library.lib
file.abspath => d:\Users\Eyal\Projects\Code\Yalla\lua_build\Yalla.Library

**There are few weird issues here:**

1. Both `cfg.buildtarget.abspath` and `cfg.linktarget.abspath` return the relative path regardless to their names whereas `file.abspath` returns the full path so you would expect the same whenever the prefix _abs_ exist in the name of the token which makes sense.
2. `cfg.linktarget.directory` returns the relative path whereas `cfg.buildtarget.directory` returns the full path, also, the name is really confusing, should it return a relative path? absolute path? directory name? I'd change it to dirname or reldir for whatever it should stand for...
3. Some paths are returned with forward slashes whereas others are returned with backward slashes.

**Comment by ReeceSX** [comment]
How come this issue was closed? `cfg.buildtarget.abspath` alongside postbuildcommands wherein the targets path is required as an argument to some other external build script is one legitimate use of this token; not to mention this is a real bug.
