### ISSUE TITLE
"Symbols" flag not resolving properly on Visual Studio 2015

### ISSUE THREAD

**Issue by emruiz81** [premake/premake-core#483]
Hello,

I'm having this issue with premake5 alpha8, that addind the "flags { "Symbols" }" option generates a wrong parameter on the vcxproj file, where it should say `<GenerateDebugInformation>Debug</GenerateDebugInformation>`, it says `<GenerateDebugInformation>true</GenerateDebugInformation>`, and where it should say `<GenerateDebugInformation>No</GenerateDebugInformation>`, it says `<GenerateDebugInformation>false</GenerateDebugInformation>`. 

It is really easy to reproduce, I always get the same wrong output on VS2015. I didn't try it on other visual studio versions.
Thank you in advance for your feedback! 

Ezequiel

**Comment by tvandijck** [comment]
I noticed this too, but this is actually unique to VS2015... it's correct for prior version of VS2015, and is because in VS2015 there is now an option "DebugFastLink" in addition to "Debug" and "No". We need to revisit the "Symbols" flag an make proper API for it, so we can expose these additional options.

**Comment by emruiz81** [comment]
You're right, the new DebugFastLink option makes this parameter more complex than just a "true or false" flag. Maybe as a quick workaround it should just resolve "No" and "Debug" for now, and in the future implement a more customizable API. Thanks for your comments!

**Comment by tvandijck** [comment]
We could indeed, feel free to make a pull request for that... I don't think I have time today to get to that.

**Comment by emruiz81** [comment]
I've checked out the pull request #490 . It seams to do the job properly. But it didn't make it to the alpha 9 right? 
Thanks a lot for you patch @g012 , it solved my problem instantly!

**Comment by starkos** [comment]
Confirmed, it did not make it to alpha 9.
