### ISSUE TITLE
Broken XML Codelite projectfile generated

### ISSUE THREAD

**Issue by emruiz81** [premake/premake-core#484]
Hello,

After generating the following premake5 LUA project for visual studio 2015 and Codelite (for both Linux and Windows), I'm getting the Codelite for Windows project file broken (any XML validator complains about unfinished tags). I've found that the problem is in the "Linker" tag, more specifically here:

`<Linker Required="yes" Options="-s;-shared;-Wl,--out-implib="../../bin/gcc/orion_dyn_r.lib"">`

The **"../../bin/gcc/orion_dyn_r.lib"** is being generated with quotes, which is illegal inside an XML attribute. This doesn't happen on the Linux build, just in windows.

Please find attached the LUA script and the generated *.project file:

[build.zip](https://github.com/premake/premake-core/files/234519/build.zip)

**Comment by tvandijck** [comment]
I submitted a fix that properly escapes quotes and < > characters here
https://github.com/premake/premake-codelite/pull/14

Just not sure if it completely fixes this for all tags...

**Comment by emruiz81** [comment]
It works perfectly well on my environment, thanks a lot for your patch!
