### ISSUE TITLE
gmake link order

### ISSUE THREAD

**Issue by thelink2012** [premake/premake-core#492]
Seems like premake doesn't resolve the linking order for the picky thing that GCC linker is?

I notice this when writing a unit test for my project, such unit `test` links (statically) with `common` and `abc`, both also projects on my workspace. The linking on the `test` project looks like this:

    links { "common", "abc" }

The generated makefile looks like this

    LIBS += common.lib abc.lib

Once I try to compile the `test` project, I get undefined references of symbol that are on `common`. If I change the order of linking (either on the makefile or on premake5.lua), everything works fine.

### Meta
```
PS C:\Yey> ./premake5 --version
premake5 (Premake Build Script Generator) 5.0.0-alpha8
PS C:\Yey> mingw32-make --version
GNU Make 4.1
Built for i686-w64-mingw32
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
PS C:\Yey> g++ --version
g++.exe (i686-win32-dwarf-rev3, Built by MinGW-W64 project) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
PS C:\Yey> ld --version
GNU ld (GNU Binutils) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by starkos** [comment]
The latest master branch now wraps the GCC link commands with `--start-group` and `--end-group`; will be in the next alpha release, which I will branch next week (though might take a few days for me to put it all together).

**Comment by TurkeyMan** [comment]
This isn't fixed properly.
The solution was a hack in `gcc.getlinks`, and `clang.getlinks` used to call that function, but now it's this:
```lua
	function clang.getlinks(cfg, systemOnly)
		-- Just pass through to GCC for now
		return gcc.getlinksonly(cfg, systemOnly)
	end
```
So, it seems the clang version has deliberately subverted the hack in the GCC function, which means `toolset=clang` causes linking to fail.

**Comment by TurkeyMan** [comment]
I'm noticing some other differences too. My old makefile was:
```
LIBS += -Wl,--start-group projectLib1.a projectLib2.a -Wl,--end-group -lpcre -lassimp-ep -ldl -lpthread -lrt -lQt5Core -lQt5Qml -lQt5Quick -lQt5Gui -lQt5Widgets
```
The new one is:
```
LIBS += -Wl,--start-group projectLib1.a projectLib2.a -lpcre -lassimp-ep -ldl -lpthread -lrt -lQt5Core -lQt5Qml -lQt5Quick -lQt5Gui -lQt5Widgets -Wl,--end-group
```
(Notice, `-Wl,--end-group` is moved to the end to include all libs, rather to the end of the user-built/solution libs where I originally put it)
The new line doesn't work; fails to resolve Qt symbols...

**Comment by tvandijck** [comment]
```lua
linkgroups 'on'
```
https://github.com/premake/premake-core/wiki/linkgroups

it is no longer automatic based on gcc vs clang... 
this new API allows you to turn it on/off.

That said, 
```lua
function clang.getlinks(cfg, systemOnly)
        -- Just pass through to GCC for now
        return gcc.getlinksonly(cfg, systemOnly)
    end
```

if that is committed, that would be a bug, it should have been modified to just pass though, so it should be:
```lua
function clang.getlinks(cfg, systemOnly)
        -- Just pass through to GCC for now
        return gcc.getlinks(cfg, systemOnly)
    end
```

**Comment by TurkeyMan** [comment]
Ah, I missed that new API. Does it put the start/end-group in the right place? You can see from my file above that the end-group is in the wrong place compared to my original code that inserted those.

Actually, I didn't do a build of master. I built the last release (a9) and cherry picked the new parts I needed; `symbols` and `symbolspath`.
I'll get latest again and see how this grouping code looks, maybe there were other related changes that I didn't cherrypick.

Incidentally, I tried building master first before a9, but our companies projects are completely broken with current master, and I don't have any time available to look into it. Something has happened in master recently which has obliterated compatibility with all our projects here >_<

**Comment by TurkeyMan** [comment]
I'm a close this again, part of my problem was that I didn't test current master (it didn't work). Other problems have separate issues raised.
