### ISSUE TITLE
table.insertsorted use lua 5.2 bit32 library....

### ISSUE THREAD

**Issue by noresources** [premake/premake-core#502]
... where current premake is built against 5.1

This function is not used in premake-core, only in blizzard/premake-xcode module

**Comment by starkos** [comment]
I'm afraid I don't understand what you're asking for here?

**Comment by noresources** [comment]
Sorry, I mean that table.insertsorted use an API that does not exists in Lua 5.1 (only 5.2+) and will produce an error at run-time. This function was added by @tvandijck (https://github.com/premake/premake-core/commit/58b60aa23240b3bd26b4b5823c45c06e17edec97). I suppose he is using a custom Lua version.

**Comment by tvandijck** [comment]
Interesting, and yes you are absolutely right... 
funny thing however is that in Lua 5.3 they deprecated bit32 again, and just use the << >> operators.

We can probably safely remove this from master, and just add it into the premake-xcode module, or use some other formula to find the split point for the binary search.

And yes, we are using Lua 5.3 in premake, it gave us significant performance gains.
