### ISSUE TITLE
Table.tostring attempt to compare number with boolean

### ISSUE THREAD

**Issue by PaulVisscher** [premake/premake-core#512]
In the premake-5.0.0-alpha9 release converting a table to string recursively according to the documention requires a boolean to recurse. However in https://github.com/premake/premake-core/commit/8f95eaaba907e1899c93792ba0f4bff51a97c147 this behaviour broke.

Try for yourself:
`print(table.tostring({ foo = { bar = true } }, true))`

**Comment by tvandijck** [comment]
Yeah, I should have updated the documentation...

The problem I was trying to fix was that "true" alone isn't really very helpful when a table has cycles in it... So I changed this into an integer where you can specify the depth of recursion, which seems a lot more useful, but indeed broke this...

**Comment by tvandijck** [comment]
I updated the documentation 
https://github.com/premake/premake-core/wiki/table.tostring
