### ISSUE TITLE
premake5 alpha 2 on OS/X fails with xcode module not found error

### ISSUE THREAD

**Issue by gpnuma** [premake/premake-core#52]
```shell
$ ./premake5
Error: [string "src/_premake_main.lua"]:45: module 'xcode' not found:
	no field package.preload['xcode']
	no file './xcode.lua'
	no file '/usr/local/share/lua/5.1/xcode.lua'
	no file '/usr/local/share/lua/5.1/xcode/init.lua'
	no file '/usr/local/lib/lua/5.1/xcode.lua'
	no file '/usr/local/lib/lua/5.1/xcode/init.lua'
	no file './xcode.so'
	no file '/usr/local/lib/lua/5.1/xcode.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by starkos** [comment]
I did accidentally upload a broken build initially. Can you try the download again (http://premake.github.io/download.html#v5)?

**Comment by gpnuma** [comment]
Hello, I just tried again with this link : http://sourceforge.net/projects/premake/files/5.0/premake-5.0-alpha2-macosx.tar.gz/download and got the same error.

**Comment by starkos** [comment]
Hmm, works okay here. Maybe we're hitting different mirrors? I will make a new set of releases.

**Comment by starkos** [comment]
Before I make the release, can you test this? http://cl.ly/1R2T2h2n071w

**Comment by gpnuma** [comment]
This one works !
I also tested building with a source package and it worked as well.

**Comment by starkos** [comment]
Great—I've pushed an alpha3 release, which should be making its way to the mirrors now.
