### ISSUE TITLE
Fails to build on Ubuntu: error in CURL_CA_BUNDLE macro expansion

### ISSUE THREAD

**Issue by starkos** [premake/premake-core#520]
On a stock Ubuntu installation:

```
contrib/curl/lib/url.c: In function ‘Curl_init_userdefined’:
<command-line>:0:16: error: expected expression before ‘/’ token
contrib/curl/lib/url.c:593:61: note: in expansion of macro ‘CURL_CA_BUNDLE’
   result = setstropt(&set->str[STRING_SSL_CAFILE], (char *) CURL_CA_BUNDLE);
                                                             ^
```

The value of `CURL_CA_BUNDLE` on this system is `/etc/ssl/certs/ca-certificates.crt`. 

Suggestions?

**Comment by tritao** [comment]
From the error, it looks like there might be some problem with the CURL_CA_BUNDLE value, maybe it's missing quotes somehow and hence the compiler erroring on the `‘/’` token?

**Comment by tritao** [comment]
From the setup script it looks like the value is being correctly wrapped in quotes (see https://github.com/premake/premake-core/blob/ef03d2a475d7629ea1b3694d114712d3f11628fe/contrib/curl/premake5.lua#L38) so this might be a Premake backend bug. I suppose you are using the Make backend, Jason?

I don't currently have any Linux VM setup to check why this is the case.

**Comment by tritao** [comment]
There seems to have been a recent change related to this: https://github.com/premake/premake-core/commit/1dbc1ea784d368d6b695c9d2774db13854e426d4

**Comment by starkos** [comment]
> There seems to have been a recent change related to this

Nice spot! I just retried a build with the latest master branch and it does indeed work. Thanks, closing!
