### ISSUE TITLE
Missing 'platforms' produces bad error

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#530]
I have projects that never called `platforms`, which no longer seem to work.
It's no problem to add the call, but it wasn't immediately obvious what the problem is, and since this is a breaking change that probably breaks lots of peoples existing scripts, a resolution message needs to be clearly presented.

I see this:
```
Error: Token returned nil, it may not exist: cfg.platform
```
What that means is; "you didn't call `platforms`".

The sample solution/workspaces in the wiki/docs need to be updated to reflect this requirement to call `platforms`; my boss was following the docs yesterday to try and make a clean project, and was getting this error. Also this change broke all our existing scripts.

I think the wiki also needs to advise a good 'default' platform name. `x86`/`x64` aren't good defaults, they're arch specific. Some name that means "this computer, whatever it happens to be", and doesn't affect the default options in any way.

**Comment by starkos** [comment]
I have projects here that do not call `platforms()` and still work fine. Can you provide a sample project or more info on how you're calling Premake?

It should not be necessary to call `platforms()` to get a script to work, definitely a bug somewhere.

**Comment by TurkeyMan** [comment]
Okay, I'll check it out.
None of our projects work anymore without `platforms()`, so it should be easy enough to isolate.

**Comment by TurkeyMan** [comment]
This is effectively resolved.
