### ISSUE TITLE
--start/end-group

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#531]
Starting a separate topic here to debate this specific behaviour.

My original code used to produce:
```
LIBS += -Wl,--start-group workspacelib1.a workspacelib2.a -Wl,--end-group -lsyslib1 -lsyslib2
```
The logic was that cross-dependencies may exist between the users libs within the workspace, and the system libs would appear after (ie, not having cross-dependencies).

The new behaviour with `linkgroups 'On'` produces:
```
LIBS += -Wl,--start-group workspacelib1.a workspacelib2.a -lsyslib1 -lsyslib2 -Wl,--end-group
```
And this new link line causes our build to fail for some reason. In our case, Qt libs are among those system libs, and they don't seem to like being bundled into the link group. We just see unresolved externals for all Qt symbols.

I think my original behaviour was correct. Is there a reason it was changed to wrap everything?

**Comment by TurkeyMan** [comment]
For reference, my original implementation: https://github.com/premake/premake-core/pull/273/files
The code has been restructured (`getlinksonly`) to make that awkward now.

**Comment by TurkeyMan** [comment]
https://github.com/premake/premake-core/pull/532

**Comment by starkos** [comment]
Agree that your original implementation is preferred.
