### ISSUE TITLE
Calling project() does not work in certain scopes

### ISSUE THREAD

**Issue by amc522** [premake/premake-core#54]
In premake 4 I was doing something like the following:
```lua
for i, platform in ipairs(solution().platforms) do
    configuration {platform}
        targetdir ("build/" .. platform .. "/" .. project().name)
end
```
Now in premake 5, I get the following error when trying to call project():
> Error: no project in scope

project().name still works everywhere else. It only seems to be a problem when I am iterating over the list of platforms or configurations from the solution object. I have also replaced my configuration call with filter.

Also, is there a better or more preferred way, in premake 5, to iterate over platforms and configurations?

**Comment by tvandijck** [comment]
With the introduction of tokens you can just remove that entire loop and just do:

targetdir "build/%{cfg.platform}/%{prj.name}"

should result in exactly the same project setup.

**Comment by amc522** [comment]
That! I like that! Exactly the functionality I was looking for. Thanks.

**Comment by tvandijck** [comment]
more on tokens here: https://github.com/premake/premake-core/wiki/Tokens
