### ISSUE TITLE
prebuildcommands and postbuildcommands don't preserve duplicate commands

### ISSUE THREAD

**Issue by dgregorycryptic** [premake/premake-core#540]
If I generate a project with this block:

`prebuildcommands`
`{`
`"call foo.bat",`
`"if errorlevel 1 exit 1",`
`"call bar.bat",`
`"if errorlevel 1 exit 1",`
`"call baz.bat",`
`}`

when output using vs2012, I get in the .vcxproj file:

`<PreBuildEvent>`
`<Command>call foo.bat`
`call bar.bat`
`if errorlevel 1 exit 1`
`call baz.bat</Command>`
`</PreBuildEvent>`

It seems like the string list removes duplicates.

**Comment by dgregorycryptic** [comment]
This seems to be a language feature of lua, in that that "array" of strings is actually a table, and those are keys, and hash tables naturally eliminate dupes.

The [[ ]] syntax doesn't seem to help either as I don't get newlines in the generated vcxproj file.

`[[`
`call foo.bat`
`if errorlevel 1 exit 1`
`call bar.bat`
`if errorlevel 1 exit 1`
`call baz.bat`
`]]`

Working on this still.  Got to be a workaround.

**Comment by starkos** [comment]
> This seems to be a language feature of lua

No, Premake is doing this, search `base/api.lua` for `storeListItem`.

**Comment by dgregorycryptic** [comment]
I see.  Lists are ordered sets.
That seems inherently wrong for this particular thing, which is a procedure and not a set.
What would you propose doing to fix it?  (I'm not trying to make this your problem - looking for recommendations)

**Comment by starkos** [comment]
I think we probably want to have an `allowDuplicateValues` flag on the API definitions (in `_premake_init.lua`) to override the default behavior for specific API calls.

**Comment by dgregorycryptic** [comment]
I'm wondering if I can add this functionality locally without rebuilding premake.

**Comment by dgregorycryptic** [comment]
For now, I've worked around this problem by calling an external .bat file for the prebuild and postbuild.  I can convert back when this is fixed.
