### ISSUE TITLE
Broken links on the wiki

### ISSUE THREAD

**Issue by GuildMasterInfinite** [premake/premake-core#557]
On the "[Who Uses Premake?](https://github.com/premake/premake-core/wiki/Who-Uses-Premake)" page, there are a few broken links, such as:
* Fresh3D: the link freshengine.net redirects to http://www.fresh3d.com/
* Xample: xample.ch redirects to airnavigation.aero
* 0 A.D. links to http://wildfiregames.com/0ad/, which says "Nothing to see here"; the new link is https://play0ad.com/
* The TinyXML link is for http://code.google.com/p/ticpp/, but the active repo is https://github.com/rjpcomputing/ticpp since Google Code closed down
* OOLua is a link to a 404 page, I think the new homepage is https://oolua.org/
* The "Learning Modern Graphics eBook" link links to www.arcsynthesis.org, which is an unregistered domain, redirecting to ww1.arcsynthesis.org.

My question is: is it alright to **replace** the links with the new ones, and **remove** the links that link to non existing websites (while keeping the actual names there)?

**Comment by samsinsane** [comment]
I don't see an issue with this, the wiki should be accurate. Thank you for taking the time to find the new locations!

**Comment by GuildMasterInfinite** [comment]
Alright, I've updated the links. I also removed the SDL Utility Library, since they stopped using Premake (according to [this document](https://bitbucket.org/sdlu/sdlu/src/48586d77ec6e6fd01dcdcd3f5fec046dedf33994/INSTALL?fileviewer=file-view-default) they use CMake now).
