### ISSUE TITLE
path.getdirectory does not work with DOS-style path separators

### ISSUE THREAD

**Issue by Spacebrain** [premake/premake-core#558]
`path.getdirectory` does not work with paths uisng DOS-style path separators.
Is this a wanted behaviour? Because other APIs in Premake handle DOS path separators just fine.

**Comment by starkos** [comment]
We do say that all paths should use forward slashes. Is there some reason you can't run it through `path.translate()` before making the call?

**Comment by Spacebrain** [comment]
Actually I used paths contained in environment variables but I wasn't aware of `path.translate()` API.
