### ISSUE TITLE
CodeLite / GCC problem with generating projects for SharedLibs

### ISSUE THREAD

**Issue by GuildMasterInfinite** [premake/premake-core#565]
I have a problem trying to generated files for CodeLite, using the GCC toolset (MinGW64, to be specific). 

* I have a ConsoleApp in my workspace, it works well, loads, etc
* I also have a SharedLib project and the problem is: it is not loaded in the workspace. When I try to load it, it says **"Corrupted project file '... MyProject.project'"**

I opened the .project file and found the problem, I found this snippet twice:
```xml
<Linker Required="yes"
 Options="-m64;-s;-shared;-Wl,--out-implib="... MyProject.lib"">
</Linker>
```
As you can see, it doesn't properly escapes the quotes: if I replace **"... MyProject.lib"** with **'... MyProject.lib'** it works.

~~I tried searching the source code, and I think the problem might be [at this line](https://github.com/premake/premake-core/blob/master/src/tools/gcc.lua#L216), but I'm not familiar enough with Lua to find any workaround.~~

**Comment by GuildMasterInfinite** [comment]
I've added a pull request #566, but I've only tested it on Windows (it does work now).

**Comment by samsinsane** [comment]
I believe this was fixed in the CodeLite repository but looks like the submodule reference wasn't updated in core. @tvandijck it looks like you fixed this, can you confirm? Also, can you fix up the submodule reference?

**Comment by tvandijck** [comment]
I pushed the submodule update to master...
