### ISSUE TITLE
Configuring debug options (Windows)

### ISSUE THREAD

**Issue by tapika** [premake/premake-core#567]
It should be possible to configure generation of debugging - 
attach to process in *.vcxproj.user file:

`  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <LocalDebuggerCommand>acad.exe</LocalDebuggerCommand>
    <DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>
    <LocalDebuggerAttach>true</LocalDebuggerAttach>
    <LocalDebuggerDebuggerType>NativeOnly</LocalDebuggerDebuggerType>
  </PropertyGroup>
`

Or completely disable generation of *.user file (so developer can configure this on his own).

Also it's should be possible 
1. to specify executable name without path (e.g. acad.exe in here)
2. specify debug type (native / mixed / other...)

**Comment by tvandijck** [comment]
```lua
debugcommand 'acad.exe'
debuggertype 'NativeOnly'
```

will take care or that... the only property premake is not writting out is the ```<LocalDebuggerAttach>true</LocalDebuggerAttach>```

but that appears to be the default anyway...

in addition to the above two properties, there is also:
[debugenvs](https://github.com/premake/premake-core/wiki/debugenvs)
[debugdir](https://github.com/premake/premake-core/wiki/debugdir)
[debugargs](https://github.com/premake/premake-core/wiki/debugargs)

**Comment by tvandijck** [comment]
Oh, and if you don't want to generate the user file at all... you could override the generateUser(prj) method, and make it do nothing, like this:

```lua
premake.override(premake.vstudio.vc2010, "generateUser", function(base, prj)
end)
```

**Comment by starkos** [comment]
> Or completely disable generation of *.user file (so developer can configure this on his own).

Premake should only output a .user file if there is a setting that requires it (e.g. `debugcommand`).

**Comment by tapika** [comment]
1. debugcommand 'acad.exe' will make full path instead of executable only. That full path will include path to project as well. I want to get only acad.exe.

2. What about being able to attach to process ?

As walkaround - premake.override works ok, so can survive with that one for timebeing, but it what if I want to disable generation only of one project, but I have 5 of them in same solution ?
