### ISSUE TITLE
Missing edge case in deprecated value handling

### ISSUE THREAD

**Issue by starkos** [premake/premake-core#572]
Here is a unit test to demonstrate the problem:

```lua

local suite = test.declare("api_deprecations")
local api = premake.api

local sln, prj, cfg

function suite.setup()
	sln, prj = test.createWorkspace()
end

local function prepare(platform)
	cfg = test.getconfig(prj, "Debug", platform)
end


function suite.setsNewValue_whenOldValueIsRemovedViaWildcard_inSubConfig()
	filter { "configurations:Debug" }
		flags { "Symbols" }

	filter { "*" }
		removeflags { "*" }

	prepare()

	test.isequal("Off", cfg.Symbols)
end
```

The `Symbols` flag is set for the "Debug" configuration. Then, all flags are removed from the project in the next block.

The `Symbols` flag has been deprecated in favor of the new `symbols("On")` and `symbols("Off")` syntax. When the flag is set in the first block, the deprecation handler runs, showing a warning message and calling `symbols("On")` to translate the flag to the new approach.

When the flag is removed via the wildcard in the next block, some logic is run to try and match any existing flags and run the appropriate deprecation logic for them. But because the flag was originally set with a different filter, it isn't picked up. As a result, `symbols("Off")` never gets called.

I've spent several hours trying to come up with a fix for this, but I don't think I can do it without a major rewrite or a huge performance hit. If anyone has any ideas I would love to hear them!

**Comment by tvandijck** [comment]
very interesting... I don't really have a good idea for this one... never used this pattern.. but I have a slew of bugs for premake to look at tomorrow here, so I might as well take a stab at this one too.

**Comment by tvandijck** [comment]
OK... if I change line 565 of api.lua from 
```lua
local current = configset.fetch(target, field)
```
to 
```lua
local current = field.allowed
```

I actually get it to return "Symbols == Default"... rather then "Off"...
But Default is the initial value we start with... so maybe that is actually what we're expecting..

Basically what the change does, is instead of fetching the flags, I just explicitly remove all of them.

The alternative is we're looking at flags that have been previously set in any block that matches the current blocks filter...

**Comment by starkos** [comment]
I posted this on the PR too, but for completeness: My concern with this approach is that there are a number of deprecated flags out there now (and I have even more over here). If a project has switched over to the new APIs (which most will have done), this will step on those values:

```lua
floatingpoint "Fast"
removeflags "*"
-- floatingpoint is now "Default"
```
