### ISSUE TITLE
Script not found due to two or more consecutive dots in folder name

### ISSUE THREAD

**Issue by icedream** [premake/premake-core#579]
I found out that when you try to execute Premake 5 with a premake5.lua in a folder that contains at least two consecutive dots (..), Premake will not be able to find the Lua script and fail to run any tasks in it.

However if you use a folder name with only single dots in it, Premake is able to find the premake5.lua file, as much as with folder names without any dots.

Examples:

- `testabc` -> works
- `test.abc` -> works
- `test.abc.def` -> works
- `test..abc` -> will not work
- `test...abc` -> will not work

Jenkins CI uses consecutive dots when creating workspace folders for feature branches in Pipelines whenever the branch names become too long.

This was tested on Windows, I don't know if the same issue exists on Linux.

**Comment by samsinsane** [comment]
I've created a PR for this, let me know if that sorts out your issues.
