### ISSUE TITLE
link error on mac os

### ISSUE THREAD

**Issue by lailongwei** [premake/premake-core#582]
Hello, I found a link error on mac os, like this:
![image](https://cloud.githubusercontent.com/assets/15770958/18703358/2995f872-8018-11e6-9c73-3471896c8d02.png)

I  found the error reason is ld -x command option trigger, -x option is tell linker do not put non-global symbols in the output file's symbol table. In my project, if add the -x option at link stage, will trigger above error! so my question is how to remove -x option in premake script? for not I have not found methods to remove -x option. for this error, I suggess premake tool add -x(mac), -s(linux) flag open to control by premake script.

for test this error, can clone llbc project: [llbc](https://github.com/lailongwei/llbc.git) in mac platform to test, step:
1. checkout premake-core and build it.
2. copy premake-core/bin/release/premake5 -> llbc/tool/premake/premake5_osx(old premake5_osx is modified, so must override it).
3. run <make core_lib>, it can retrigger this error.

**Comment by starkos** [comment]
The `-x` flag on Mac, and the `-s` flag on Linux, is controlled by the `symbols` API in Premake. If you set `symbols("Off")` Premake will try to strip symbol information from the final binary. If you would like to keep the symbols, set `symbols("On")`.

**Comment by starkos** [comment]
(Feel free to reopen if you have more information or another, related question.)

**Comment by lailongwei** [comment]
@starkos  symbols() is useful, thanks :+1: :100:
