### ISSUE TITLE
Found a problem in linux/macos platform(about -Og command)

### ISSUE THREAD

**Issue by lailongwei** [premake/premake-core#584]
Hello, I found a problem in linux/macos, language is c++, if I use <optimize "Debug"> to set project, the output makefile included "-Og" option in compile command, If you try to build your project, compiler prompt error: "cc1plus: error: invalid option argument ‘-Og’", Is this a bug?

I search g++ and clange command line options documantation, not found about -Og command description. so I report this problem, I hope you can help to solve:)

**Comment by samsinsane** [comment]
This should only be used for GCC, you can find documentation about -Og [here](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html).

Do you have this problem on Linux, or just OSX?

**Comment by lailongwei** [comment]
Yes, the problem occurred at Linux OS

**Comment by lailongwei** [comment]
premake script:
![image](https://cloud.githubusercontent.com/assets/15770958/18772006/1bdb1172-8176-11e6-9caf-f047a9c93529.png)
test c++ code file(main.cpp):
![image](https://cloud.githubusercontent.com/assets/15770958/18772018/28930c6c-8176-11e6-85e8-9e53a763a109.png)
premake tool generated makefile(partial):
![image](https://cloud.githubusercontent.com/assets/15770958/18772042/4739469a-8176-11e6-8db7-ce26f8b01585.png)


when run command <make -f Ogtest.make config=debug>, will trigger this error report:
![image](https://cloud.githubusercontent.com/assets/15770958/18772066/5db0ad1e-8176-11e6-8540-0692a0004e5e.png)

I test again at g++ 5.2.0, -Og command supported, but at g++ 4.4.7, -Og command not support, Premake can determine g++ version to generate -Og(5.2.0) or -ggdb(4.7.0) when generate makefile?
Thanks:)

**Comment by lailongwei** [comment]
For now, my solution is use <buildoptions  { "-ggdb"  }> to replace <optimize "Debug">

**Comment by samsinsane** [comment]
This check would need to occur in the actual makefile, otherwise you wouldn't be able to copy the makefile to other machines, which is a design goal of Premake. You could use `optimize "Off"` instead, I believe this is how it used to work.

@starkos is there a plan for situations like this? A `toolsetversion` API or something?

**Comment by lailongwei** [comment]
@samsinsane The makefile I have not copy to other machine, In gcc 4.4.7 environment machine generate, and I test in the same machine. I feel you can add like toolsetversion api to resolve this bug, the -Og command not support on gcc 4.4.7, bug the premake tool generated makefile has -Og define. Thanks:)

**Comment by tvandijck** [comment]
Yeah, we got the same here on Centos 5 machines... just basically really old versions of GCC didn't support -Og... I think some of the code in the "Autoconf" tools I wrote could help with this, as it could run "cc --version", and figure out what version of GCC we're on... automatically select the correct set of arguments.

**Comment by lailongwei** [comment]
@tvandijck Hello, I don't really known what you mean with this sentence  **I think some of the code in the "Autoconf" tools I wrote could help with this**, For now how  should I do to solve the problem?
Thanks:)

**Comment by tvandijck** [comment]
I was just referring to this pull request: https://github.com/premake/premake-core/pull/550 which detects features of the compiler by trying out little pieces of code... In a similar way we could detect the version of gcc/clang to figure out particular sets of options that are supported or not, and premake could potentially then respond to that when generating the makefile...

This is obviously a lot more work, so as for how to proceed to get you going right now?

Take this change, that is what we did:
   https://github.com/Blizzard/premake-core/commit/98aa18cc8064e2e628afd36268fe2eb9824c1629

**Comment by tvandijck** [comment]
At the same time however... you might consider taking a more recent version of gcc.
4.4.7 was released in 2012... we're in 2016... it's going to be harder and harder to support old versions with the limited resources we have.

**Comment by lailongwei** [comment]
@tvandijck Haha, I know, in today, I have been upgraded my gcc version to 5.2, thank you for your help:)

**Comment by starkos** [comment]
Would it be worth investigating separate toolsets for different versions of GCC? A `gcc4` toolset, `gcc3`, etc. with the `gcc` toolset just pointing to the newest one? Not sure if it is worth the effort…

**Comment by lailongwei** [comment]
@starkos I have tow centos machines, One gcc version is4 .4.7,another version already upgraded to 5.2 at tomorrow,3.x version's gcc I have not try
