### ISSUE TITLE
Disabling --start-group for macosx

### ISSUE THREAD

**Issue by jvtrudel** [premake/premake-core#585]
Is it possible to disable the use of --(start/end)-group. It seems that it is not supported by macosx's ld... 

```
ld: unknown option: --start-group
```

**Comment by samsinsane** [comment]
This functionality is controlled via the `linkgroups` API (default is "Off"), this is how you should use it:
```lua
filter { "system:not macosx" }
  linkgroups "On"
```

**Comment by starkos** [comment]
But why are we emitting those flags for Mac in the first place? I thought that had been sorted?

**Comment by tvandijck** [comment]
because some versions of osX do need it... it's why we went to an API to turn it on/off, because we couldn't figure out a way to detect whether a particular version of ld needs it or not...
