### ISSUE TITLE
Add support for additional manifest files (VS)

### ISSUE THREAD

**Issue by Jusonex** [premake/premake-core#586]
At the moment, I can't find a way to specify additional manifest files.

Manifests seem to be specified in `*.vcxproj` using the `Manifest`-block, e.g.:
```
<Link>
      ...
</Link>
<Manifest>
    <AdditionalOptions>/manifest "my-manifest.manifest" %(AdditionalOptions)</AdditionalOptions>
</Manifest>
```

Further information about manifests: https://msdn.microsoft.com/en-us/library/aa374191(v=vs.85).aspx

**Comment by samsinsane** [comment]
You should be able to just add them via the `files` API and they will automatically populate in to that location, as long as their extension is `.manifest`. I've never used this functionality but you can view the code that handles manifests [here](https://github.com/premake/premake-core/blob/master/src/actions/vstudio/vs2010_vcxproj.lua#L458-L478).

**Comment by Jusonex** [comment]
Great, works flawlessly. Thank you!
