### ISSUE TITLE
5.0.0-alpha10 does not contain `vectorextensions` value "IA32"

### ISSUE THREAD

**Issue by manxorist** [premake/premake-core#592]
https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-src.zip mentions

> - New: `vectorextensions` value "IA32"

in `CHANGES.txt`, but does not actually contain the corresponding feature.

**Comment by samsinsane** [comment]
Closing this as alpha11 is out, and should contain this.
