### ISSUE TITLE
5.0.0-alpha10 still does not provide VS2015 project files

### ISSUE THREAD

**Issue by manxorist** [premake/premake-core#596]
https://github.com/premake/premake-core/releases/download/v5.0.0-alpha10/premake-5.0.0-alpha10-src.zip does not contain `build/vs2015/` folder, although VS2015 project file generation had been merged 2 months ago.
See https://github.com/premake/premake-core/pull/562

Why was this not included in the alpha10 release?

**Comment by starkos** [comment]
Because I had already branched for an alpha-10 release, and was only accepting bug fixes at that stage (of which I received zero, BTW). Announcement was [here](https://groups.google.com/forum/#!topic/premake-development/owLgcnqIhKI).
