### ISSUE TITLE
Web page on 'flags' is missing NoEditAndContinue

### ISSUE THREAD

**Issue by doughodson** [premake/premake-core#599]

**Comment by samsinsane** [comment]
The flag `NoEditAndContinue` is deprecated by the API: `editandcontinue "Off"`. I believe this isn't documented to discourage usage of the flag, other deprecated flags are also not on the list.

**Comment by doughodson** [comment]
excellent -- I'm 'converting' an earlier version of a premake5 script to 
alpha10 -- things like "Symbol" used in flags displayed a message to 
indicate change.  I didn't see any similar output when used, and 
seemingly working.

Thanks again.

Doug
