### ISSUE TITLE
permake5 and codeblocks ?

### ISSUE THREAD

**Issue by ucacaxm** [premake/premake-core#601]
hi,

premake5 will not support codeblocks ?

Is there a possibility to test the version of premake in the premake.lua file ?

Thanks,
alex

**Comment by samsinsane** [comment]
Premake5 currently doesn't support codeblocks, and it doesn't look like [anybody in the community](https://github.com/premake/premake-core/wiki/Modules) has created a module for it. There's some documentation in the wiki and plenty of modules to use as examples, if you'd like to write a module to add codeblocks support.

You can use a combination of `premake.checkVersion` and `_PREMAKE_VERSION` to check the version of Premake. For example, if you want to ensure that you're running Premake5: `premake.checkVersion(_PREMAKE_VERSION, ">=5.0")`.

**Comment by DPSLynix** [comment]
Hey,

I recently ported CodeBlocks to premake5 for my own project, look at #616 for the source code.

**Comment by samsinsane** [comment]
I'm going to close this as the original questions were answered, the linked issue above provides more information regarding how to emit CodeBlocks files with Premake5.
