### ISSUE TITLE
MonoDevelop action doesn't work

### ISSUE THREAD

**Issue by samsinsane** [premake/premake-core#604]
The MonoDevelop action emits this when run:

```
Building configurations...
Running action 'monodevelop'...
Error: ...github/premake-core/modules/monodevelop/_preload.lua:36: attempt to call field 'generateWorkspace' (a nil value)
```

The function it's attempting to call has never existed, and this change was made over a year ago.

@starkos, @tvandijck, @TurkeyMan: Should we remove this module from core? I find it hard to justify keeping it in core when it hasn't worked in over a year and we've had no issues logged about it. Thoughts?

**Comment by tvandijck** [comment]
I have no use for it, at Blizzard we removed it from our distribution, and I have no intention of ever touching it, seeing that Microsoft is largely been moving msbuild to .NET Core..

**Comment by tritao** [comment]
MonoDevelop backend is for MD's C project system so it has nothing to do with .NET. For .NET projects the VS backend can be used to generate MD compatible project files.

I just asked a co-worker (on MD team) and he tells me the C project system has been removed from the default MD package and has been moved to a separate repository: https://github.com/mhutch/cbinding

+1 for removing it.

**Comment by mhutch** [comment]
The C project system in MD is long gone. The MD project system was revamped to better support MSBuild in MD 6.0, and the C/C++ build support wasn't it wasn't ported over, so the addin was removed.

My fork of the addin switches the C/C++ build system over to CMake. I thought that made more sense than trying to build/maintain a build engine.

Btw, .NET Core is moving to MSBuild now - MSBuild is the future. But there aren't MSBuild tasks/targets for C/C++ outside of Windows, and I didn't particularly want to build/maintain them :)

**Comment by samsinsane** [comment]
Thanks for the input @tritao and @mhutch! @tvandijck do you happen to have a patch that removes MonoDevelop handy?

**Comment by tvandijck** [comment]
Not really... our commit in our repo also removed dlang and adds our versions of xcode and the blizzard module... all at once.

it's here just in case,
https://github.com/Blizzard/premake-core/commit/9ead9f7eb1b09c765c5669fb88c93012bc51334f
but that is likely not very useful.

**Comment by samsinsane** [comment]
Tried to quickly throw together a PR to remove the module, unfortunately the dlang module requires it. I'll have another go at doing this later, I'm just going to remove all the code that extends monodevelop.

**Comment by tvandijck** [comment]
dlang depends on monodevelop?? interesting...

**Comment by samsinsane** [comment]
Yeah, it extends the gmake, VS and monodevelop generators.

**Comment by TurkeyMan** [comment]
> Btw, .NET Core is moving to MSBuild now - MSBuild is the future. But there aren't MSBuild tasks/targets for C/C++ outside of Windows, and I didn't particularly want to build/maintain them :)

I think there are actually loads of MSBuild tasks/targets for not-windows (I presume by this you mean the MSC toolset?) scattered around the landscape... and VS2015 finally integrated some themselves with the Android support (GCC), and also the 'Clang with MS codegen' tools. They're slightly platform-specific, but the templates are there to be adapted into generated build targets. There are also loads of VS extensions that integrate GCC or Clang into msbuild tasks, which should theoretically work just as well in MD in not-windows as it does in windows? (I haven't looked at MD's MSBuild support, but it sounds great!)

**Comment by samsinsane** [comment]
Closing this as it's no longer in core.
