### ISSUE TITLE
Specifying base directory for 'files' function

### ISSUE THREAD

**Issue by armata** [premake/premake-core#606]
I have a dependency stored in a certain subfolder. I have to repeat the full path of each file when adding them to my project using the 'files' function.

Can I somehow set the base directory so that I can just specify the file names (+ extension), without their 'full' path when adding the source files?

Example:
```
...
files {
  'path/to/dep/src/file1.c',
  'path/to/dep/src/file2.c',
  'path/to/dep/src/file3.c',
  'path/to/dep/src/file4.h',
  'path/to/dep/src/file5.h',
  ...
}
...
```

**Comment by tvandijck** [comment]
can't you just use:

```files {  'path/to/dep/src/*.c', 'path/to/dep/src/*.h'  }```

other then that, there is no way to set the base directory for the files method, you could however do something like:

```lua
local function myfiles(base, table)
    local newtable = <code to prefix base to every entry in table>
    files(newtable)
end

myfiles ("path/to/dep/src", {"file1.c", "file2.c", etc})
```

**Comment by armata** [comment]
Unfortunately I can't because I have to include specific files. Not even a RegExp would help.

However I do know about the function trick you wrote, but I was looking for a nicer solution.

I guess such function does not exist yet :/
