### ISSUE TITLE
premake4.lua is broken

### ISSUE THREAD

**Issue by z3moon** [premake/premake-core#615]
I'm using CentOS 6.8 and trying to generate gmake script using premake4.
While doing that, I found the premake4.lua is compromised.

First, the path to 'src/host/lua/src' in the premake4.lua is no longer available and seems to be moved to contrib/lua/src.
And others might need to be adjusted as well.

**Comment by tvandijck** [comment]
The recommended path for generating premake's own build scripts is through the bootstrap.mak as described here: https://github.com/premake/premake-core/wiki/Building-Premake#using-the-git-code-repository

the premake4.lua script I don't think we have maintained very well... if you have any fixes, feel free to submit a pull request for that... but I honestly think using the bootstrap is a lot more reliable and easier.

**Comment by z3moon** [comment]
Yep, it looks like premake4.lua is no longer maintained. I compiled the project with bootstrap.mak though. If we don't think the lua script is not subject to be maintained, we'd better remove it not to make any confusion even though the build instruction recommends to use the .mak file.

**Comment by tvandijck** [comment]
either remove, or make it work... I agree.. I'll leave this issue open, until such time we take actual action on this.

**Comment by tvandijck** [comment]
fixed here: https://github.com/premake/premake-core/pull/653
