### ISSUE TITLE
subprojects and subworkspaces

### ISSUE THREAD

**Issue by d-sviridov** [premake/premake-core#621]
When using project structure like that:
```
./premake5.lua  
   has workspace and project "main"
./libA/premake5.lua
  has its own workspace and project "libA"
```
the `./premake5.lua` has `include "libA"`

after `premake5 gmake` in the root, it generates the `main.make` under `./libA` instead of at the root.
if `./libA/premake5.lua` does not have its own workspace, everything is fine, and `main.make` is generated at root and `libA.make` under `./libA/`

**Comment by samsinsane** [comment]
Just through together a quick test for this, I don't appear to be experiencing this issue. Are you able to provide the scripts that you're using, so we can narrow down what's causing this issue?

**Comment by d-sviridov** [comment]
Here i've made a quick test
[premake-test.zip](https://github.com/premake/premake-core/files/577875/premake-test.zip)

**Comment by samsinsane** [comment]
Ok, here's the issue:
```lua
workspace "main"
configurations { "release", "debug" }
  
include "libA"
project "main"
```

Is the same as:
```lua
workspace "main"
configurations { "release", "debug" }
  
workspace "libA"
configurations { "release", "debug" }

project "libA"
  kind "StaticLib"
  language "C++"
  files {
     "*.h",
     "*.c++"
  }
project "main"
```

What you really want is the `include "libA"` to be either at the top or bottom of the "main" premake5.lua. :)

**Comment by d-sviridov** [comment]
so `include` basically just includes the other file into this one?
i thought it kind of pushes the current workspace, gets projects from another file, and pops the current one back again.
ok, ill just make separate files for workspaces and projects. to be able to include only the projects.
