### ISSUE TITLE
Subcontainers/filters

### ISSUE THREAD

**Issue by john-chapman** [premake/premake-core#626]
Hi,

I don't see a way to control how premake builds vcxproj.filters files - it's largely cosmetic but I find that for large solutions it can be useful to be able to group projects and source files, not necessarily in the way that they are arranged on disc. Perhaps such a feature could work by specifying arbitrary sub-containers within a workspace/project:

```
workspace "BigSolution"
   group "Libs"
      project "LibFoo"
      project "LibBar"
   group "Tools"
      project "ToolFoo"
      project "ToolBar"
```

**Comment by samsinsane** [comment]
We already have a `group` API which allows you to specify the workspace level virtual folder structure. As well as the `vpaths` API which allows you to control the project level filters. You can find the documentation for them [here](https://github.com/premake/premake-core/wiki/group) and [here](https://github.com/premake/premake-core/wiki/vpaths). Let me know if you need any more information.

**Comment by john-chapman** [comment]
Ah great - my bad for not searching the wiki hard enough. Maybe a note  in the top-level documentation would be nice!

Thanks for the response 👍
