### ISSUE TITLE
symbolspath does not work properly

### ISSUE THREAD

**Issue by tapika** [premake/premake-core#630]
Continuation to https://github.com/premake/premake-core/issues/151

symbolspath does not work correctly.

Currently symbolspath generates xml tag:
`<ProgramDataBaseFileName>$(OutDir)$(TargetName)_exe.pdb</ProgramDataBaseFileName>`
 

While visual studio (2015) uses ProgramDatabaseFile, like this:

`<ProgramDatabaseFile>$(OutDir)$(TargetName)_exe.pdb</ProgramDatabaseFile>`

Tested with kind "ConsoleApp" and with kind "SharedLib" - bug in both cases.

**Comment by tapika** [comment]
Btw - there is more to this.

By default Visual studio 2015 splits out .ilk file next to target. And that file cannot be overridden or configured. So if .exe and .dll targetnames are identical - will cause vs conflict.

But I have used 
`flags { "NoIncrementalLink" }`
- then .ilk file is not generated.

Simplifies things when there is some smaller tool which you're using.
Also bug is vs2015 specific, not applicable to previous versions of Visual studio.

**Comment by samsinsane** [comment]
This looks to be fixed in master from PR #600, this isn't in alpha10, but should be in the next release.

As for the .ilk file, are you saying this cannot be overridden or configured in Visual Studio, or just Premake?

**Comment by tapika** [comment]
Cannot be configured in Visual studio itself. When next release is coming out btw ?
Is it written somewhere ?

**Comment by starkos** [comment]
When I can get to it. They are not, at this point, automated.

**Comment by samsinsane** [comment]
The fix should be in alpha11.

**Comment by Faykarta** [comment]
Still not working.

**Comment by samsinsane** [comment]
@Faykarta could you please elaborate on this?
- What version of premake are you using?
- What element and value are being emit to your vcxproj?
- What version of VS are you using? If VS2017, which patch? Apparently, this matters now. :(
- If you manually configure it in VS and save the project files, what does the vcxproj contain instead?

Anything else you think might be of value as well would be great.
