### ISSUE TITLE
Xcode: App that "dependson" a SharedLib creates "links" relationship instead

### ISSUE THREAD

**Issue by macsforme** [premake/premake-core#631]
We have a repository that has several executables as well as a bunch of dynamic libraries which can be dynamically loaded by one of the executables at runtime using dlopen(). I want to set it up so that building the main executable builds the other executables and all the dynamic libraries as well. However, in the exported Xcode project, when I specify that an executable `dependson` the shared libraries, it `links` the executable to them as well, which is not what we want (it causes the executable to fail to load if the libraries are unavailable).

Example:

    workspace "test"
    configurations "Debug"
    language "C"

    project "test"
    kind "ConsoleApp"
    files "test.c"
    dependson "testlib"

    project "testlib"
    kind "SharedLib"
    files "testlib.c"

This exports the following:

![screen shot 2016-11-19 at 10 00 44 pm](https://cloud.githubusercontent.com/assets/4955448/20460546/b4a2ec54-aea3-11e6-9cab-2ab5e8c05ef4.png)

The "Target Dependencies" section is correct, but I don't want to actually link to that library. When I check the executable, I do see a link dependency:

    $ otool -L test
    test:
        /usr/local/lib/libtestlib.dylib (compatibility version 1.0.0, current version 1.0.0)

If I correctly understand the difference between `links` and `dependson`, a built library should not be linked if the relationship is `dependson`. A workaround for us might be to create a dummy executable that `dependson` the dynamic library, then the executable we build would not be affected. However, if this is in fact unexpected behavior, then perhaps others would benefit from a fix as well.

**Comment by starkos** [comment]
Definitely a bug, `dependson()` should not link.

**Comment by macsforme** [comment]
I also tried putting a removelinks() right after the dependson() to see if that would eliminate the link relationship while maintaining the dependency, but the removelinks() had no effect at all.
