### ISSUE TITLE
ld: warning: directory not found for option '-L/usr/lib64' (MacOS)

### ISSUE THREAD

**Issue by speeder** [premake/premake-core#647]
I am using Premake5 alpha 10, and I am getting this error:

ld: warning: directory not found for option '-L/usr/lib64'

**Comment by starkos** [comment]
This fixed in [PR 543](https://github.com/premake/premake-core/pull/543), which will appear in the next alpha release (or you can [build from the latest master branch](https://github.com/premake/premake-core/wiki/Building-Premake)).
