### ISSUE TITLE
gmake: unable to override build command for .c file

### ISSUE THREAD

**Issue by resetnow** [premake/premake-core#652]
I need to run a set of custom commands for every C file in my project. I'm trying to use `filter` and `buildcommands` with gmake action, but it doesn't work:

```lua
project "test-project"
	files {
		"./src/file.c"
	}
	filter "files:**.c"
		buildmessage 'processing file: %{file.relpath}'
		buildcommands {
			gcc_prefix .. 'cpp -o "%{cfg.objdir}/%{file.basename}.i" "%{file.relpath}"'
		}
```

Is there a way to specify a custom command for this project?

**Comment by tvandijck** [comment]
gmake currently does not support per file configuration settings, this pull request refactors the gmake backend to support that and some other features:

https://github.com/premake/premake-core/pull/516

any help getting it production ready would be appreciated.

**Comment by tvandijck** [comment]
use gmake2 module: https://github.com/premake/premake-core/pull/803

**Comment by samsinsane** [comment]
I'm going to close this as `gmake2` replaces `gmake` and it supports per-file filters.
