### ISSUE TITLE
C++/CLI support? 

### ISSUE THREAD

**Issue by inkadnb** [premake/premake-core#655]
I'm using CppSharp to generate C++/CLI code from C++ but I need to be able to then generate a C++/CLI project from that output with premake. 

I can't seem to find anything in the documentation regarding C++/CLI support. Is this supported?

**Comment by tritao** [comment]
You can see how C++/CLI projects are setup in CppSharp:
https://github.com/mono/CppSharp/blob/master/build/Tests.lua#L157-L158

Basically you only need to do `flags { Managed }`.

**Comment by inkadnb** [comment]
Excellent, thank you!
