### ISSUE TITLE
how to create many groups

### ISSUE THREAD

**Issue by MacroGu** [premake/premake-core#657]
group "contrib"
		include "contrib/lua"
		if not _OPTIONS["no-zlib"] then
			include "contrib/zlib"
			include "contrib/libzip"
		end
		if not _OPTIONS["no-curl"] then
			include "contrib/curl"
		end

this is a group in premake source code in visual_studio 
i need to create many groups , for example ,
group one is : contrib1
group two is : contrib2
i write lua code such as:
	group "contrib1"
		include "contrib/lua"
		if not _OPTIONS["no-zlib"] then
			include "contrib/zlib"
			include "contrib/libzip"
		end
		if not _OPTIONS["no-curl"] then
			include "contrib/curl"
		end
	group "contrib2"
		include "contrib/lua"
		if not _OPTIONS["no-zlib"] then
			include "contrib/zlib"
			include "contrib/libzip"
		end
		if not _OPTIONS["no-curl"] then
			include "contrib/curl"
		end
but it does not work , in visual studio , i can not find two groups, just only one group is group1.

think you .

**Comment by samsinsane** [comment]
I'm not quite sure what you're trying to achieve here, do you want the same projects to be in multiple groups? Or do you want each call to `include` to generate a unique project for that group?

**Comment by MacroGu** [comment]
![image](https://cloud.githubusercontent.com/assets/8192020/21447929/0fb93a66-c917-11e6-9eac-a169de786792.png)

i just want to create many groups , how could i write code in premake5.lua. thank you.

**Comment by samsinsane** [comment]
What you had above is not what you have in that picture. Try this instead:
```lua
group "contrib1"
  include "contrib/lua"
  if not _OPTIONS["no-zlib"] then
    include "contrib/zlib"
    include "contrib/libzip"
  end

group "contrib2"
  if not _OPTIONS["no-curl"] then
    include "contrib/curl"
  end
```

**Comment by MacroGu** [comment]
thanks

**Comment by samsinsane** [comment]
No worries, glad I could help.
