### ISSUE TITLE
XCode4 includedirs added to "User Header Search Paths", not simply "Header Search Paths"

### ISSUE THREAD

**Issue by AberrantWolf** [premake/premake-core#676]
In building a project that uses Premake5 (https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK) on Mac OS, I ran into the issue where referenced include paths (e.g. `/usr/local/include`) were always added to the "User Header Search Paths" option in the resulting Xcode project rather than "Header Search Paths", which in-turn required that any `#include` commands had to be quoted rather than using their intended angle brackets.

Am I missing something, or is it impossible to add paths to the non-user search paths from Premake at the moment?

The relevant premake lua code is:
```
    if os.is("macosx") then
        includedirs {"../3rdparty/oiio16/include", "/usr/local/include"}
        libdirs {"../3rdparty/oiio16/lib/x64", "/usr/local/lib"}
        linkoptions{ "-framework OpenGL", "-framework GLUT" }
        buildoptions "-std=c++11 -stdlib=libc++"
        links {"OpenImageIO"}
    end
```

**Comment by starkos** [comment]
Does [sysincludedirs()](https://github.com/premake/premake-core/wiki/sysincludedirs) help?

**Comment by AberrantWolf** [comment]
I just tried it, and it looks like it's being treated the same as `includedirs`.

**Comment by AberrantWolf** [comment]
There is a setting in Xcode "Always Search User Paths" which is being set to "No", but if I set it to "Yes" it appears to use the user paths even when searching for angle bracket includes. Not sure how correct this behaviour is, but it appears to work.

**Comment by AberrantWolf** [comment]
To make sure I was being thorough, I checked the script that includes the header files in the Xcode project and it looks like the fix for this is newer than the version included by the project I mentioned. I'll try to rebuild the latest premake and see if that fixes the problem.

**Comment by AberrantWolf** [comment]
Downloaded latest alpha (to save time) and it works. Sorry for the waste of time; but thanks for the help (I somehow missed the sysincludedirs method).
