### ISSUE TITLE
Output disabled for custom rule command line templates

### ISSUE THREAD

**Issue by nsprljan** [premake/premake-core#698]
There’s an extra “@echo off” in custom rule command line templates (.props files), which prevents build output to be displayed. Now, I understand some commands can be quite noisy, but having a total silence is not helpful when debugging builds. Perhaps some option could be added to switch the echo off, but I think by default it should be on. Seems to have been introduced in 8b7b4c1139c7051c3a09123a03ca4f116f20fee

**Comment by starkos** [comment]
Tom—that looks like one of yours. Any objection to removing the `@echo off`?

**Comment by tvandijck** [comment]
no objection at all...
