### ISSUE TITLE
enable /Wall in msc

### ISSUE THREAD

**Issue by RicoP** [premake/premake-core#709]
For my project I would like to crank the warning level up to the maximum with /Wall. it seems like that `warnings { "Extra" } ` only activates  [warning level 4](https://github.com/premake/premake-core/blob/master/src/tools/msc.lua#L85) and I have to manually bump the warning level in my project properties. 

I tried to override the warning level with the command 

`buildoptions { "/Wall" }` 

in my project, but it doesn't seem to work. 

Are there other ways to set the /Wall flag?

**Comment by leeonix** [comment]
I need this too. msdn noted:
```
/Wall	Displays all warnings displayed by /W4 and all other warnings that /W4 does not include—for example, warnings that are off by default. For more information, see Compiler Warnings That Are Off By Default.
```
`/Wall` give information more than warning level 4.

**Comment by starkos** [comment]
Can you submit a PR to change the mapping for `warnings { "Extra" }`?  I don't believe `/Wall` existed at the time that flag was originally implemented.

**Comment by leeonix** [comment]
@starkos what reason you don't believe `/Wall`. I am not using `/Wall` for a long time. but recently use. so I comment this issue.

**Comment by amc522** [comment]
If you do this please do not make the only options /W0 and /Wall. Most projects do not need /Wall. The msvc STL is only tested so that it doesn't emit /W4 errors. The visual c++ team generally recommends that you don't use /Wall all the time. Only occasionally when you need extra checks. I suggest the following options:

- 'Off' which maps to '/W0'
- 'Extra' which maps to '/W4'
- 'All' which maps to '/Wall'

/W4 is similar to gcc's -Wall, and /Wall is similar to gcc's -Wextra.

**Comment by amc522** [comment]
Also, theres the /permissive- option in VS2017 which makes the compiler standards conformant, and produces errors for microsoft specific extensions to c++

[https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/](https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/)

**Comment by leeonix** [comment]
@amc522 NO, `/Wall` is not exist in premake5.

**Comment by amc522** [comment]
@leeonix I understand that /Wall is currently not in premake 5. I was just saying that if it does get added, please keep /W4 available.

**Comment by leeonix** [comment]
@amc522 OK.

**Comment by RicoP** [comment]
@leeonix: thank you. This workaround is working~
