### ISSUE TITLE
http.download need proxy option.

### ISSUE THREAD

**Issue by leeonix** [premake/premake-core#711]
@tvandijck Hi tom.
I'm Chinese Developer.
As we all know what's the problem.
I need proxy option.
I push and pull source code use proxy.
even now, visit GitHub use socks5 proxy.
If I download zip file from `github` or `amazon`. it is very unstable.
please add the feature, thank you.

**Comment by tvandijck** [comment]
feel free to submit a pull request...

**Comment by starkos** [comment]
I'm going to reopen this so other people will be able to see that this is yet to be implemented. And yes, a pull request for it would be appreciated.

**Comment by tvandijck** [comment]
@starkos oops... clicked the wrong button I think... did not intent to close it...

**Comment by samsinsane** [comment]
I've opened a PR for this, I don't have access to a proxy to test this out with, so if there's any changes required let me know.
