### ISSUE TITLE
Build failing on macOS

### ISSUE THREAD

**Issue by starkos** [premake/premake-core#715]
As of commit 7d7266656ef4cd9209977a4a41918146db4a76a2. Can't investigate right now, capturing for future reference:

```
Undefined symbols for architecture x86_64:
  "_Curl_sasl_ntlm_cleanup", referenced from:
      _Curl_http_ntlm_cleanup in libcurl-lib.a(curl_ntlm.o)
      _Curl_sasl_create_ntlm_type1_message in libcurl-lib.a(curl_ntlm_msgs.o)
      _Curl_sasl_create_ntlm_type3_message in libcurl-lib.a(curl_ntlm_msgs.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by tvandijck** [comment]
```
scripts.c
Linking Premake5
tvandijck-mbp:premake tdijck$ bin/release/premake5 --help
Premake 5.0.0-dev, a build script generator
Copyright (C) 2002-2017 Jason Perkins and the Premake Project
Lua 5.1 Copyright (C) 1994-2008 Lua.org, PUC-Rio
...
```

Not sure, what you are seeing, master as of right now seems to build fine on macOS Sierra for me, both through the bootstrap as well as through premake itself... TravisCI seems to agree too...

**Comment by starkos** [comment]
Hmm…happening on both my machines today, but certainly could be something local. I will close and investigate when I can. Thanks!
