### ISSUE TITLE
Dependency management module

### ISSUE THREAD

**Issue by saschagrunert** [premake/premake-core#720]
Hey 👋🏻,

I just thought about a possible module for pre-built dependency management (like artifacts from an continuous integration system).

The idea is that premake downloads a file (zip, single header, tar.gz) and searches for pre built binaries and headers inside. premake could assemble a vendor directory which then contains all needed libraries and headers.

What do you think?

**Comment by saschagrunert** [comment]
Ah I see the ghp module does something like that already

**Comment by tvandijck** [comment]
there is in addition to the ghp module, also several other efforts ongoing:
- https://packagesrv.com/   (see this discussion: https://groups.google.com/forum/#!topic/premake-development/U9fLftNY4Vg)
- http://premake-ghp.com/
- http://zpm.zefiros.eu/   (see this discussion: https://groups.google.com/forum/#!topic/premake-development/1bo-xKHnBD4)

As well as "Blizzard' their package management system, which is in their fork:
- https://github.com/blizzard/premake-core

**Comment by saschagrunert** [comment]
Ah thank you very much for the input here. :)
