### ISSUE TITLE
_OS overwritten by action.

### ISSUE THREAD

**Issue by tvandijck** [premake/premake-core#722]
in action.lua
```
		if act then
			_OS = act.os or _OS
		end
```

both the xcode and vs200x set the os variable, which causes those actions to always run as if they run on those platforms... 'macosx' and 'windows' respectively...

The problem is... we then have code like this:
```
			-- Identify the system
			local arch
			if _OS == "windows" then
				arch = os.getenv("PROCESSOR_ARCHITECTURE")
			elseif _OS == "macosx" then
				arch = os.outputof("echo $HOSTTYPE")
			else
				arch = os.outputof("uname -m")
			end
```
such as in os.is64bit(), which assumes that the _OS variable is correctly identifying the platform we're actually running on, which is not the case... and hence this method just returns incorrect results.

usage of _OS, os.is, os.get()... they are basically returning the OS the action is targetting, not what we are executing on.

**Comment by starkos** [comment]
Oops.

A quick code search makes it seem like the majority of the time we are really interested in the target OS, rather than the one we are currently on, i.e. most of the uses of `_OS` are correct as is. So it probably makes sense to add a new method like `os.current()` or `os.real()` to get the actual system identifier? Does that seem reasonable?

**Comment by tvandijck** [comment]
yeah... I was thinking of a similar approach.. it seems a bit of a bandaid though...

I'd rather switch it around....
```os.target()``` is what the action is targeting... 

basically:
```os.get()``` -> ```os.target()```
```os.is()``` -> ```os.targetting()```
```_OS``` -> ```_TARGET_OS```

and then add:
```os.current()```

Then deprecate the old API entirely. We can keep it around, but basically add a ```p.warnonce()``` in it.
The harder one is the _OS variable, so I don't think you can really get away from that one, but we can at least just not use it anywhere in premake-core code.

I'm not sure though....

**Comment by starkos** [comment]
I agree, this is a better long term approach. I'm not opposed to deprecating the `_OS` global too…we could probably catch it and warn via a metatable on _G?
