### ISSUE TITLE
Windows SDK Version mismatch when generating for "vs2017"

### ISSUE THREAD

**Issue by grasmanek94** [premake/premake-core#723]
When generating with `premake5 vs2017` on windows 7, you cannot build the solution unless you open the properties of each project and change the SDK version from the forced 8.1 to 10.xxx.xxx.xxx (xxx.xxx.xxx needs to be replaced by whatever Visual Studio 2017 installed at the date of installation).

I cannot find any documentation on forcing/detecting the WinSDK version from `premake5`.

`premake5 --version`: `premake5 (Premake Build Script Generator) 5.0.0-alpha11`

**Comment by MoodyMoon** [comment]
Add `systemversion("10.0.14393.0")` to your `premake5.lua`.

**Comment by grasmanek94** [comment]
Neat, didn't know it was possible, thanks!
