### ISSUE TITLE
Cannot make VS project with characterset 'Not Set'

### ISSUE THREAD

**Issue by grasmanek94** [premake/premake-core#724]
VS2017 + Premake5 default to Unicode, which leaves me with either MBCS or Unicode. Some libraries are not written to be compatible with MBCS/Unicode from VS and need the option to be "Not Set". Adding 'None' would be ideal.

**Comment by tvandijck** [comment]
see https://github.com/premake/premake-core/pull/718

**Comment by grasmanek94** [comment]
Oh good to see that there is a PR which fixes this! Thank you.
