### ISSUE TITLE
'&&' gets translated to '&amp;amp;&amp;amp;' in VS projects

### ISSUE THREAD

**Issue by grasmanek94** [premake/premake-core#725]
Hello again.

I needed to define the following expression for one of my projects:

    defines
    {
        "DOCTOPT_USE_BOOST_REGEX=(  _DEBUG && _WIN64 && _ITERATOR_DEBUG_LEVEL != 0 )"
    }

This got translated to the following in the vcxproj file (I see this code is located [here](https://github.com/premake/premake-core/blob/1b776d8f6bf32bbbbb0237dd8e6b27a7c9762321/src/actions/vstudio/vs2010.lua#L100) ):

(newlines added only to separate each definition / for easier reading)

    <PreprocessorDefinitions>
        WIN64;
        DEBUG;
        WINDOWS;
        WIN32;
        DOCTOPT_USE_BOOST_REGEX=( _DEBUG &amp;
        amp;
        &amp;
        amp;
        _WIN64 &amp;
        amp;
        &amp;
        amp;
        _ITERATOR_DEBUG_LEVEL != 0 );
        %(PreprocessorDefinitions)
    </PreprocessorDefinitions>`

As we can see each `&&` got translated into `&amp;amp;&amp;amp;`, when it should be `&amp;&amp;`.

So, ofcourse I rewrote my expression to something that would not be translated:

    defines
    {
        "DOCTOPT_USE_BOOST_REGEX=!( !_DEBUG || !_WIN64 || _ITERATOR_DEBUG_LEVEL == 0 )"
    }

But people might say that this is not readable, to which I agree.
However it works nicely as a temporary workaround for now.

**Comment by tvandijck** [comment]
I wonder why it translates it with a ```\n``` in it... the newline should definitely not be added, but the ```&amp;``` is needed in XML typically, so that is why it does the translation.

**Comment by grasmanek94** [comment]
The newline is just for formatting! Sorry about that.
