### ISSUE TITLE
Error: cannot open contrib/lua: No such file or directory (Windows 10)

### ISSUE THREAD

**Issue by josegarciaclm95** [premake/premake-core#727]
I wanted to generate a VS2015 solution, so I downloaded premake5 (the exe)  but it doesn't work.

![image](https://cloud.githubusercontent.com/assets/14859356/24586289/f05be27a-179c-11e7-9966-3cd7053644ce.png)

I downloaded the exe file, and after discovering it didn't work, I download the source code and tried to set the lua file manually (premake5 --file=premake5.lua). It didn't work either. The only way I could made it run was by putting it inside the source code folder, but then I cannot made it to compile what I really want.
Any help?

**Comment by starkos** [comment]
Not able to reproduce this. You downloaded [from the official site](http://premake.github.io/download.html#v5)? Is there a `premake5.lua` script in that folder? Does it try to reference a folder called `contrib/lua`?

**Comment by josegarciaclm95** [comment]
> You downloaded from the official site?

Yes, the zip file for windows, an exe inside a zip

> Is there a premake5.lua script in that folder?

No there wasn't. I added it to the folder after some searching on the internet, but the error kept the same. 

> Does it try to reference a folder called contrib/lua?

That's what it seems, so I downloaded the Source Code and put the exe on that folder, that was the only way to make it work.

**Comment by starkos** [comment]
I'm unable to reproduce this. I see…

    C:\Users\Jason\Downloads> unzip premake-5.0.0-alpha11-windows.zip
     Archive:  premake-5.0.0-alpha11-windows.zip
         inflating: premake5.exe

     C:\Users\Jason\Downloads> premake5.exe
     Type 'premake5 --help' for help

     C:\Users\Jason\Downloads> premake5.exe --version
     premake5 (Premake Build Script Generator) 5.0.0-alpha11

**Comment by neico** [comment]
Could it be that you enabled `--scripts` behavior somewhere? (ex. system premake file, or debug build)?

Do you have a premake executable somewhere in your PATH? (try to use `.\premake5` to use the local copy)

I can't think of any other reason why premake would look for the contrib folders

**Comment by josegarciaclm95** [comment]
Hi , I tried the application again. I can't reproduce the error either, maybe it was a problem of the unzipping, or something weirder.
Thank you for your attention and help.

**Comment by aed22** [comment]
`Error: cannot open Hazel/vendor/GLFW: No such file or directory`

I'm getting the same error need help please
