### ISSUE TITLE
Let's use the "github project" thingie..

### ISSUE THREAD

**Issue by tvandijck** [premake/premake-core#759]
https://github.com/premake/premake-core/projects

seems like it might help us organize issues/task/roadmap a bit more.

**Comment by samsinsane** [comment]
Sounds good to me! Perhaps using the labels too will be helpful? It looks like @starkos went to the effort to create a bunch of them, but we haven't used any that I can see. :)

**Comment by starkos** [comment]
I'm using these with a client and they work well but it is hard to get people to keep them up to date. Kind of like those labels I may or may not have created and never use… :) But I'm willing to give it a go, it would help increase visibility. Not sure how I'd title the issue for what I'm working on now though…maybe "Make configuration queries suck less".

**Comment by samsinsane** [comment]
> "Make configuration queries suck less"

Ha, that sounds very interesting, is this to replace `filter`? Or is it more of a backend extension to `filter`?

**Comment by samsinsane** [comment]
I've added labels to all of the open issues, some might be a bit off. I won't be offended in the slightest if anyone changes them. :)

**Comment by tvandijck** [comment]
I created two project, just to try things out... closing this issue...

**Comment by starkos** [comment]
This is a good start. I have been sketching out a "roadmap"—really just a list of want-to-haves—for a final v5.0 release. If I get a chance I'll see if I can set up a board for it, and tie it to the existing issues.
