### ISSUE TITLE
CompileAs breaks mixed projects

### ISSUE THREAD

**Issue by Jusonex** [premake/premake-core#766]
In our project, we have third party dependencies that consist of both C and C++ source files (extension `.c` and `.cc`).

Unfortunately, 5b688cac93a2b1ab50ab851e7ccfeb7b5ac9b970 changes the default behavior (based on the extension) to a fixed behavior only based on the `language` property.

In our case VS' default behavior is obviously the correct one. As an alternative to fully reverting 5b688cac93a2b1ab50ab851e7ccfeb7b5ac9b970, I'd suggest a `compileAs` option for premake which accepts the same values as the `language` property.

**Comment by tvandijck** [comment]
This is affecting us too, so I made the following PR:
https://github.com/premake/premake-core/pull/771

**Comment by Jusonex** [comment]
The PR fixed it 👍
