### ISSUE TITLE
newoption 'category' field?

### ISSUE THREAD

**Issue by tvandijck** [premake/premake-core#77]
I've been thinking about this one for a while, and wonder if we can add a "catagory" field to the newoption API, so that we can distinguish between "vanilla premake", "blizzard " and "buildfile" specific options...

right now, everything gets clumped together in the --help output under "OPTIONS", but I would like to have that display "OPTION", with a list of stuff, then "OPTIONS - Blizzard", with a bunch of our own stuff, and then "OPTIONS - SC2_Game", or something like that...

any suggestions? objections? ideas?

**Comment by tvandijck** [comment]
Oh, and while I'm at it.... I want default values too....

so I can do:

	newoption {
		trigger = "to",
		value   = "path",
                default = "build"
		description = "Set the output location for the generated files"
	}

instead of having to add...

	if not _OPTIONS["to"] then
	    _OPTIONS["to"] = "build"
	end

**Comment by starkos** [comment]
Can this one be considered resolved now?

**Comment by tvandijck** [comment]
yes,
