### ISSUE TITLE
Project tries to link on sibling project's static lib instead of shared lib

### ISSUE THREAD

**Issue by Scylardor** [premake/premake-core#773]
Hello,

here's my issue: I have a library project that I want to compile as either static or shared library, according to the current platform.

And I have another project that links against it, basically when the platform is DLL I want to link with the DLL and when the platform is Static I want to link the static lib.

However on VS 2015, when I'm on DLL platform and I try to build the solution, it seems the second project tries to link with the static lib no matter what (and it fails because it will have generated a DLL). So the static platform is working fine but the DLL one is not.

Here is the script I use:
```
-- premake5.lua
workspace "Test"
	
	-- Initial config
	location "Workspace" -- The directory of generated files - .sln, etc.
	configurations { "Diagnostic", "Debug", "Release", "Profile", "Shipping" }
	platforms { "Windows Static", "Windows DLL", "Linux Static", "Linux DLL" }

	filter "platforms:*Static"
		kind "StaticLib"
	
	filter "platforms:*DLL"
		kind "SharedLib"

-- Projects
project "Lib"
	language "C++"
	targetdir "Build/%{cfg.platform}/%{cfg.buildcfg}"

	files { "Source/**.cpp", "Source/**.h", "Source/**.hpp" }
	includedirs { "Source/**/Include" }


project "TestProject"
	language "C++"
	kind "ConsoleApp"
	links { "Lib" }
	targetdir "Build/%{cfg.platform}/%{cfg.buildcfg}"

	files { "TestProject/**.cpp", "TestProject/**.h", "TestProject/**.hpp" }
	includedirs { "Source/**/Include" }

```

I generate my solution using premake5 vs2015.
I'm using Visual Studio Community 2015 (14.0.25431.01 Update 3), with premake 5.0.0-alpha11.

This is what I get in VS when building the solution with the Windows DLL platform for example:
```
1>------ Rebuild All started: Project: Lib, Configuration: Debug Windows DLL Win32 ------
1>  Source.cpp
1>  Lib.vcxproj -> C:\Users\atan\Project\Workspace\..\Build\Windows DLL\Debug\Lib.dll
1>  Lib.vcxproj -> ..\Build\Windows DLL\Debug\Lib.pdb (Full PDB)
2>------ Rebuild All started: Project: TestProject, Configuration: Debug Windows DLL Win32 ------
2>  hello.cpp
2>LINK : fatal error LNK1104: cannot open file 'C:\Users\atan\Project\Build\Windows DLL\Debug\Lib.lib'
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
```
whereas as I said, Windows Static works fine. In fact, *sometimes* it seems to work, but I couldn't tell why or how. When I switch platforms and back again, it's broken again, and I can't make it work reliably.

I tried a couple of things like swapping the platform filters or putting them under the Lib project, but to no effect. And I'd like to avoid that, since ultimately there will be multiple library projects, so I'd like to keep those filters global to not copy/paste them everywhere.

I don't understand why it isn't working. Could it be a bug ?

**Comment by Scylardor** [comment]
Howdy!

I kept on researching this issue because I had the feeling I was somewhat missing the obvious here.

In that particular case, I think I know what's going on and fortunately, Premake has nothing to do with it (AFAIK).

I forgot to include the __declspec( dllexport / dllimport ) defines in the declaration of my DLL's symbols (as a test there are only a couple of them).
As a result, the .lib file that usually comes along the DLL wasn't generated by VS (because no symbols were exported), but the .dll was.

Hence, my setup consisting of both a static lib and DLL modes, I mistook the linker error "cannot open file blabla.lib etc." for the linker complaining it didn't find the Static Lib .lib file it would have generated in Static mode, whereas actually it wasn't finding the .lib that should have been generated even in DLL mode (which is not the same file but happens to have the same name).

I think there's no problem with Premake on this. I just forgot the declspec and then have been misled by the linker error.

Closing the issue

**Comment by JesseChisholm** [comment]
Excellent that you found the resolution to your issue.
(: Good on you for sharing the resolution as well. :)

BTW: Probably clearer to read if you move the

```lua
	filter "platforms:*Static"
		kind "StaticLib"
	
	filter "platforms:*DLL"
		kind "SharedLib"
```

out of the `workspace` level and into the `project "Lib"` level.
As is, it applies to every project that doesn't override it with its own `kind`..
