### ISSUE TITLE
Favor a compiler on premake5

### ISSUE THREAD

**Issue by gpnuma** [premake/premake-core#78]
Hello,
I'm not sure this could be an improvement as it might already be possible although i don't know how to do it.

Put simply, on premake 4, I wanted to favor clang if it was present on the platform, rather than gcc, and here is the script I used :
```
if os.execute("clang -v") == 0 then
	premake.gcc.cc  = 'clang'
	premake.gcc.cxx = 'clang++'
elseif ...
```

Now on premake5 the *premake.gcc* value doesn't exist anymore, I tried setting *premake.cc* and *premake.cxx* instead of *premake.gcc.cc* and *premake.gcc.cxx* but it doesn't work.

Is it possible to do this the proper way ? If not, that would be a very interesting new feature to add.

**Comment by starkos** [comment]
You can do it like this:

```lua
if os.execute("clang -v") then
   toolset "clang"
end
```

Does that work for you?

**Comment by gpnuma** [comment]
That's perfect ! Thanks a lot ^^
