### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by RevoluPowered** [premake/premake-core#782]
I've just noticed that you've closed your forums, wanted to know why this was the case?

I really liked the forums for looking up some quick premake tips, it's probably a beneficial thing to run.

Please, can you reopen them?

**Comment by starkos** [comment]
No, I have no interest in maintaining the old forums, and in fact most of that site is going away in the near future.

**Comment by tvandijck** [comment]
Could we import the content into some static site, or to the google group forum?

**Comment by RevoluPowered** [comment]
Better yet would you let someone else maintain a forum for you?

**Comment by tvandijck** [comment]
Well, we have the google group forum... having two forums doesn't seem beneficial, and would split all the content. I wouldn't be in favor of that... but if the old database still exists somewhere, then I'm sure we can convert it into posts on the google forum

https://groups.google.com/forum/#!forum/premake-development

**Comment by RevoluPowered** [comment]
The only issue I have with that is, It looks like a bad email client from the 90's and is as ergonomic as those clients used to be. My eyes bleed when I go into a post.

Two forums is not a good Idea I agree, but surely we could come up with a good solution, as opposed to running one that makes people want to tear out their eyes.

**Comment by tvandijck** [comment]
That's a purely a personal issue. Functionally it's all there, and it works. To you it may look like the 90's as a negative thing, to me it looks like the 90's, simple, functional, no bells and whistles.

**Comment by starkos** [comment]
There isn't a lot of traffic on the Google forums, and if someone wanted to move it somewhere else I would have an open mind about it. But it would have to be somewhere it will stick around…Google isn't going anywhere.

The database that backs the original forums does still exist, and I will keep an archive even after I take them down.

**Comment by tvandijck** [comment]
I wish @github made a forum integrated, that way everything would simply be here.
