### ISSUE TITLE
When "FastLink" option is used, "/ MTd" becomes "/ MT".

### ISSUE THREAD

**Issue by qatnonoil** [premake/premake-core#784]
When "FastLink" option is used, "/ MTd" becomes "/ MT".

filter "configurations:Debug"
 symbols {"On"} -- "/MTd"

filter "configurations:Debug"
 symbols {"FastLink"} -- "/MT"

Can I use FastLink with debugging?
Thanks.

**Comment by samsinsane** [comment]
Premake attempts to guess what kind of runtime library it should use based on your settings. If you'd like to use the debug runtime library with `FastLink`, you can use `runtime "Debug"` documented [here](https://github.com/premake/premake-core/wiki/runtime).
