### ISSUE TITLE
Missing base functions

### ISSUE THREAD

**Issue by edgarasf123** [premake/premake-core#792]
Trying to call `os.target()` for instance, and it throws an error that it's not defined. But it is clearly defined 
[here](https://github.com/premake/premake-core/blob/master/src/base/os.lua#L141).

```
> os.target()
stdin:1: attempt to call field 'target' (a nil value)
stack traceback:
        stdin:1: in main chunk
        [C]: in function 'prompt'
        [string "src/_premake_main.lua"]:108: in function '?'
        [string "src/base/_foundation.lua"]:55: in function 'callArray'
        [string "src/_premake_main.lua"]:207: in function <[string "src/_premake_main.lua"]:206>
```

**Comment by tvandijck** [comment]
What version of premake are you using? or did you build you own from master? The alpha 11 binaries do not have this yet, since it was build from a earlier version of master. These new functions were introduced only 2 weeks ago orso..

**Comment by edgarasf123** [comment]
Oh ok, my bad then. I didn't built them, but instead downloaded the latest compiled binaries. I was able to get it working.
