### ISSUE TITLE
C# NuGet target framework issue

### ISSUE THREAD

**Issue by cosmy1** [premake/premake-core#796]
The code below need to be refactored as some packages uses **lib\\net** folder without any numerical informations.

```lua
--[[
Snippet took from:
https://github.com/premake/premake-core/blob/863b89625f0adf137bd9d5cb93694bd0689548de/src/actions/vstudio/vs2005_csproj.lua#L412-L424
--]]

local folder = file:match("^lib\\net(%d+)\\")

if folder and path.hasextension(file, ".dll") then
    files[folder] = files[folder] or {}
    table.insert(files[folder], file)

    local version = makeVersionComparable(file:match("lib\\net(%d+)\\"))

    if version <= targetVersion and (not bestVersion or version > bestVersion) then
        bestVersion = version
        bestFolder = folder
    end
end
```
According to NuGet  **lib\\net** is valid and I think it is used for lower .NET Framework versions which are compatible with _* all *_ of them (typically <= 2.0): 
https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Core.Tests/NuGet.Frameworks.Test/NuGetFrameworkParseTests.cs#L206

Example of NuGet package that uses **lib\\net** folder:
![example](https://cloud.githubusercontent.com/assets/1329119/26525595/45a98fd0-435c-11e7-9842-79bd1b04f9f1.png)
https://www.nuget.org/packages/JetBrains.Annotations
https://www.nuget.org/packages/MetroModernUI

**Comment by cosmy1** [comment]
Just found another special case:
![example](https://cloud.githubusercontent.com/assets/1329119/26525714/c58fcc2e-4360-11e7-8eb0-e7c684cb732a.png)
https://www.nuget.org/packages/SharpZipLib

At this point I guess the most consistent solution is to handle properly all these .NET Framework cases:
```
10, 11, ..., 45
1.0, 1.1, ..., 4.5
net, net10 ..., net45
```

For more references:
https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Core.Tests/NuGet.Frameworks.Test/NuGetFrameworkParseTests.cs

**Comment by aleksijuvani** [comment]
Thanks for the detailed bug report. I'll take a stab at this while I'm working on other NuGet related stuff on Premake.

Do you know of any other packages besides SharpZipLib that use the "11", "20" scheme for folders? It looks like the NuGet API doesn't provide a file listing for SharpZipLib so we can't use that package for the unit tests.
