### ISSUE TITLE
When is alpha12 coming?

### ISSUE THREAD

**Issue by DrLynix** [premake/premake-core#797]
It's been four month now since the last premake5 alpha, when is alpha12 coming?

(Btw, what is premake lacking for a stable release?)

**Comment by tvandijck** [comment]
We don't really have any kind of schedule, so things are typically released when @starkos feels like it, and has the time to go through a bunch of tests etc.

As for what is holding off a stable release?
- GMake refactor, and a few other PR's.
- A new query system that is in the works.
- Most contributors have full time jobs that are not premake.
- Discussions around language/dialect.

**Comment by starkos** [comment]
What Tom said. I was trying to release every 8-12 weeks, but I've been swamped. Starting to dig myself back out a little though.

As for the stable release, I would add a rework of the toolset API. Basically, we want to get major APIs to a point of stability, where module authors can trust them.

**Comment by data-man** [comment]
Please, integrate Lua 5.3 to new alpha.
I'm using Premake5 from Blizzard (thanks **tvandijck**!), and everything works fine.

**Comment by starkos** [comment]
5.0-alpha12 is [now released](https://github.com/premake/premake-core/releases/tag/v5.0.0-alpha12), closing.
