### ISSUE TITLE
{{COPY}} token doesn't copy single files

### ISSUE THREAD

**Issue by Jusonex** [premake/premake-core#819]
```lua
workspace "TestWorkspace"
  configurations { "Debug", "Release" }

  project "TestProject"
    language "C++"
    kind "ConsoleApp"
		
    postbuildcommands {
      "{COPY} %{wks.location}premake5.lua %{wks.location}premake6.lua"
    }
```
results in an error as Windows asks whether the destination is a file or directory.
I.e.:
```
> xcopy /Q /Y /I premake5.lua premake6.lua
Does premake6.lua specify a file name
or directory name on the target
(F = file, D = directory)?
```

Instead, it should assume that the destination is a file, unless there is a folder with the same name (that's what Linux does too).

**Comment by samsinsane** [comment]
Closing this off as we've deprecated `{COPY}` in favour of `{COPYFILE}` and `{COPYDIR}`.
