### ISSUE TITLE
Consider adding ObjectiveC flag

### ISSUE THREAD

**Issue by xgalaxy** [premake/premake-core#845]
Hello,

It would be nice if there was a flag that could be used as an easy configuration option for objective-c code in place of having to remember the clumsy `buildoptions { "-x objective-c++" }`

**Comment by natrist** [comment]
What would said flag achieve? Be specific for the people not familiar with the language, thanks.

**Comment by xgalaxy** [comment]
The `objective-c` and `objective-c++` flags allow compiling C & C++ code with Objective-C and Objective-C++.
