### ISSUE TITLE
how to make virtual folder in project?

### ISSUE THREAD

**Issue by jeckbjy** [premake/premake-core#85]
I have a solution contain a project, the source directory like 
engine
--include
--src
i want to generate vs project like
engine
--core
----*.h,*.cpp
--math
----*.h,*.cpp
so how can i create the virtual folder such as core,math and find files?

**Comment by starkos** [comment]
Look at the vpaths() function. The wiki documentation is [here](https://github.com/premake/premake-core/wiki/vpaths).
