### ISSUE TITLE
debugenvs not working for Makefile project?

### ISSUE THREAD

**Issue by Filiecs** [premake/premake-core#852]
In my premake5.lua script I define my environment variables:
environmentVariables = 
  { 
    "PATH=" .. outputdir .. ";%PATH%;",
    "MYAPP_DATA=" .. outputdir .. "/Data",
    "MYAPP_TEST=" .. outputdir .. "/Test",
    "MYAPP_BUILD_ROOT=" .. outputdir
  }
I then call 'debugenvs(environmentVariables)' when I define the rest of the project properties.
However, these environment variables do not show up in the 'Configuration Properties -> Debugging -> Environment` property of the Makefile project.

Am I missing something or is this a bug?

**Comment by tvandijck** [comment]
Those environment variables should show up in the `vcxproj.user` file, and it looks like premake is generating that file unconditionally... 

Can copy your premake5.lua script here? and can you  check the vcxproj.user file and see if anything shows up there at all??

**Comment by Filiecs** [comment]
Ok, it turns out that I simply needed to re-open the .sln as Visual Studio failed to prompt me that anything had changed... even though it had.

Thanks for your help.
