### ISSUE TITLE
path.translate always translates to \

### ISSUE THREAD

**Issue by tvandijck** [premake/premake-core#86]
if (lua_gettop(L) == 1) {
		sep = "\\";
	}

Shouldn't that be dependent on the OS that path.translate is called on?

**Comment by starkos** [comment]
Since %99 of the time I'm translating to Windows, I made it the default. If there's a way to check the OS that maintains the current behavior everywhere its used in the core code, I'm good with that. Otherwise maybe another input like "*" or something?

**Comment by tvandijck** [comment]
> Since %99 of the time I'm translating to Windows,
in path.translate you did... but all other path functions use '/' instead... path.normalize, join, etc.

I think honestly using a / instead of a \ would be an option, since that works on all platforms including windows. but I can figure out if we're on posix or not, and use a / only then..

**Comment by starkos** [comment]
Sorry, I didn't really understand that last comment?
