### ISSUE TITLE
ExcludedFromBuild set unexpectedly when trying to specify per-platform targetsuffix

### ISSUE THREAD

**Issue by Maximus5** [premake/premake-core#869]
Premake version: 5.0.0-alpha11

I'm trying to generate vs2017 project which would build Win32 and x64 binaries into one folder. So I need to specify different target name for each platform. I try to do this via `targetsuffix`. And it do the trick, but all source files are unexpectedly marked as `ExcludedFromBuild`. Why?

### Steps to reproduce

1. One source file `main.cpp`.
2. In the same directory file `premake5.lua` (below)
3. Run `premake5 vs2017`

```lua
-- premake5.lua
workspace "test"
  configurations { "Release", "Debug" }
  platforms { "Win32", "x64" }
  location "build"

  filter "platforms:Win32"
    architecture "x32"

  filter "platforms:x64"
    architecture "x64"

project "main"
  kind "ConsoleApp"
  language "C++"

  filter "platforms:x64"
    targetsuffix "64"

  files { "*.cpp" }
```

### Unexpected result

```xml
  ...
  <ItemGroup>
    <ClCompile Include="..\main.cpp">
      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">true</ExcludedFromBuild>
      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">true</ExcludedFromBuild>
    </ClCompile>
  </ItemGroup>
  ...
```

**Comment by tvandijck** [comment]
Because you really wrote:
```
project "main"
kind "ConsoleApp"
language "C++"

filter "platforms:x64"
targetsuffix "64"
files { "*.cpp" }
```

scope, does not exist in lua... just adding a 'tab' does not create scope like in phyton.
So if you don't want files to be filtered, you need to reset the filter, or do files first... 

either do:
```
project "main"
kind "ConsoleApp"
language "C++"

filter "platforms:x64"
targetsuffix "64"
filter {}
files { "*.cpp" }
```
or
```
project "main"
kind "ConsoleApp"
language "C++"

files { "*.cpp" }
filter "platforms:x64"
targetsuffix "64"
```

**Comment by Maximus5** [comment]
Thanks, it works!
