### ISSUE TITLE
Unable to use "links" to link with .obj files in VS2010

### ISSUE THREAD

**Issue by falconjt** [premake/premake-core#87]
I'm using premake 5.0-alpha3 to create a VS2010 project where I need to link to an .obj file.
I'm unable to use the "links" command as premake adds the ".lib" suffix, eg:
`links { "something.obj" }`
will add "something.obj.lib" to the project dependencies.

Is it possible to make the links function check for .obj and not add the lib suffix?
(The workaround for the moment is to use "linkoptions" to link with the obj)

**Comment by leeonix** [comment]
didn't you think link this .obj file to a lib??? it's too easy.

**Comment by starkos** [comment]
> Is it possible to make the links function check for .obj and not add the lib suffix?

Yes, we should be doing that, you're right.

**Comment by TurkeyMan** [comment]
Just a note; I've had this same issue with .o files on linux/gcc too. I think it's a good idea.
