### ISSUE TITLE
vpaths and overlapping filter conditions

### ISSUE THREAD

**Issue by Maximus5** [premake/premake-core#871]
I can't understand how to configure vpaths properly. Please help

For example, I have files:

```
src/project/about.cpp
src/project/project.rc
src/project/SetPgMain.cpp
src/project/SetPgMain.h
src/project/update.h
```

Successfully added them to project

```
files {
    "src/project/*.cpp",
    "src/project/*.h",
}
```

Now I want to put in `Settings` all `SetPg*.*`, and other files to `Headers`, `Resources` and `Sources`. Tried the following:

```
vpaths {
    ["Resources"] = {"**/*.rc", "**/*.manifest", "**/*.bmp", "**/*.cur", "**/*.ico"},
    ["Settings"]  = {"**/SetPg*.*"},
    ["Headers"]   = {"**/*.h"},
    ["Sources"]   = {"**/*.cpp"},
}
```

`Resources` and `Headers` - OK. But in the `Settings` I see only headers `src/project/SetPgMain.h`, the `src/project/SetPgMain.cpp` unexpectedly appears in `Sources`.
I tried to reorder vpaths - no effects. I tried to create two vpaths blocks - only first one is accepted.

**Comment by starkos** [comment]
Lua key-value tables do not have a deterministic ordering. Try turning your `vpaths` block into an array so it will be evaluated in the order you specified:

```
vpaths {
    { ["Resources"] = {"**/*.rc", "**/*.manifest", "**/*.bmp", "**/*.cur", "**/*.ico"} },
    { ["Settings"]  = {"**/SetPg*.*"} },
    { ["Headers"]   = {"**/*.h"} },
    { ["Sources"]   = {"**/*.cpp"} },
}
```

**Comment by Maximus5** [comment]
Yes. Array is working, thanks!

**Comment by tvandijck** [comment]
oehh.. that's a neat trick ;)
