### ISSUE TITLE
Get error LNK2001 after updated from alpha11

### ISSUE THREAD

**Issue by mercury233** [premake/premake-core#890]
I just updated premake5 to alpha12, but i get:
```
     4>LIBCMT.lib(exe_winmain.obj) : error LNK2001: unresolved external symbol _WinMain@16 [C:\projects\ygopro\build\ygopro.vcxproj]
     4>..\bin\release\ygopro.exe : fatal error LNK1120: 1 unresolved externals [C:\projects\ygopro\build\ygopro.vcxproj]
```
https://ci.appveyor.com/project/mercury233/ygopro/build/43#L1350

The same script works on alpha11 :
https://ci.appveyor.com/project/mercury233/ygopro/build/44

My premake5.lua is at 
https://github.com/mercury233/ygopro/blob/f3b68154b26e38ab0c140a21db4d322949c2ea38/premake5.lua

The entry point is at
https://github.com/mercury233/ygopro/blob/f3b68154b26e38ab0c140a21db4d322949c2ea38/gframe/gframe.cpp#L35

**Comment by samsinsane** [comment]
Premake no longer sets the entry point by default, you should only need to add the following to your premake5.lua to fix this issue:
```lua
filter { "system:windows", "kind:WindowedApp or ConsoleApp" }
  entrypoint "mainCRTStartup"
```
Let me know if that doesn't resolve your issue.

**Comment by mercury233** [comment]
It works now, thank you!
