### ISSUE TITLE
[Proposal] Automatically included library include directories

### ISSUE THREAD

**Issue by SE2Dev** [premake/premake-core#893]
I've been tossing around the idea of having certain include directories for library projects automatically be added to a project's include directories when specified as a dependency using links(). Essentially, a project (usually a library or something) can specify *public* includedirs which are automatically inherited if you reference that project using links() - this is particularly useful for libraries like [Google's benchmark library](https://github.com/google/benchmark) where the public include directory is separate from the rest of the project's source code (a convention which is often followed libraries with precompiled distributions).

I believe that this feature would be best suited as an extension of includedirs(), for example:
```lua
includedirs {
   {"mylib/include", "public"}, -- Automatically inherited by any project that links this one
   {"mylib/src/headers", "default"} -- Not inherited
}
```

I did, however, notice that any tables that are using as arguments for includedirs() are implicitly flattened, which may be somewhat problematic.

I threw together a quick & dirty sample script that users can use to enable a generic demonstration of this proposal, which adds a new function `includedirs_public()` that can be used to specify publicly available include directories.
```lua
local p = premake
local api = p.api

-- Register the includedirs_public function
api.register {
    name = "includedirs_public",
    scope = "config",
    kind = "list:directory",
    tokens = true
}

-- Hook buildtargetinfo to provide includedirs_public info
premake.override(
    premake.config,
    "buildtargetinfo",
    function(base, cfg, kind, field)
        local info = base(cfg, kind, field)
        info.includedirs_public = cfg.includedirs_public
        return info
    end
)

-- Hook preAction to append includedirs_public info for dependencies to a given project config
premake.override(
    premake.main,
    "preAction",
    function(base)
        -- Run the default behavior
        base()

        -- Add the includedirs_publics for each dep
        for wks in p.global.eachWorkspace() do
            for prj in p.workspace.eachproject(wks) do
                for cfg in p.project.eachconfig(prj) do
                    -- Add a configs own includedirs_public to its includedirs
                    cfg.includedirs = table.merge(cfg.includedirs, cfg.includedirs_public)

                    -- Get the config for each of the dependencies
                    local dep_cfgs = p.config.getlinks(cfg, "dependencies", "object")

                    for k, v in ipairs(dep_cfgs) do
                        -- Append the dependency public include dirs to this config
                        cfg.includedirs = table.merge(cfg.includedirs, v.includedirs_public)
                    end
                end
            end
        end
    end
)
```

**Comment by starkos** [comment]
When using a library, you actually need a lot more than include directories. We've been calling this concept "usages". I just threw [together a wiki page](https://github.com/premake/premake-core/wiki/Usages) to capture the basic idea; check out [Tim Wharton's usage module](https://github.com/moomalade/premake-usage) for an actual implementation.

Marking this as closed, but feel free to reopen with new information or questions.

**Comment by SE2Dev** [comment]
Yeah, I definitely like the concept of "usages" a lot more; It's a much more elegant and functional alternative to what I was trying to do. I'd love to see something like that adopted into core!
