### ISSUE TITLE
Premake Alpha 12 Reported as Virus

### ISSUE THREAD

**Issue by playmer** [premake/premake-core#899]
Hey folks, I don't have a heck of a lot of info, but I'm on Windows 10 version: 10.0.15063 Build 15063

When I download this latest build (https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-windows.zip) via Chrome (61.0.3163.100) I see this message:

![chromevirus](https://user-images.githubusercontent.com/1740806/30985962-d1099660-a446-11e7-8ccd-768e17423f6e.PNG)

When I download via Firefox Nightly and then scan the zip via Windows defender I get the following:

![defendervirus](https://user-images.githubusercontent.com/1740806/30986105-40c2f078-a447-11e7-9335-1f2fc7b4e4c9.PNG)

Thanks for looking into this!

**Comment by Elejdor** [comment]
Same with Google Chrome

**Comment by samsinsane** [comment]
It also occurs with Edge and IE.

I managed to grab the prebuilt binaries a week or two after they went up without any issues. The downloaded zip is now problematic, so I'm guessing it was an update to Windows Defender. Unfortunately, the window that comes up (screenshot above) seems to contain more information but is cut off and can't be resized, and clicking "Learn more" leads to a broken link (amazing). So not a great deal of information to go off from Microsoft.

Based on a quick google search, it looks like we can apply [here](https://www.microsoft.com/en-us/wdsi/filesubmission) to have the false positive fixed. @starkos I can do the submission if you'd like, but if you're the one creating the releases, this might become part of the process if Alpha13 also ends up being flagged as a virus.

**Comment by starkos** [comment]
I submitted it; not sure what happens next?

**Comment by samsinsane** [comment]
Based on what I saw, you'll get a response either saying "This is definitely a virus" which requires more communications or a "Woops, fixed!" which is the end of the process. Alpha13 might require this all over again, which will be kind of annoying.

**Comment by starkos** [comment]
Microsoft has responded with "Not malware". The report shows "Definition version" 1.253.231.0. 

We'll see what happens with alpha13. If it also gets flagged, then I will add this step to the release process. In that case, we'll probably also have to report to Google as well?

**Comment by samsinsane** [comment]
Cool, I just managed to download it successfully.

> In that case, we'll probably also have to report to Google as well?

I don't think so, it's Windows defender that has the issue.

**Comment by doughodson** [comment]
I had the same problem with Chrome the other day.  Strangely, I didn't notice this as a problem until just the other day.  Defender had to be turned off to avoid automatic download file deletion.

**Comment by tommitytom** [comment]
Hey, this has popped up for me today, while trying to download `premake-5.0.0-alpha13-windows.zip`

**Comment by starkos** [comment]
I now need the [Detection name](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus#detection-history) in order to log the request. Can you provide that?

**Comment by tommitytom** [comment]
It no longer appears as a virus when I download it now.  This may have been because I allowed it in Windows Defender in the past (it doesn't list it there now, either).  Maybe the false positive was automatically fixed?  Wait and see if it pops up for anyone else I guess!

**Comment by doughodson** [comment]
FYI: Just tried downloading with Chrome and didn't have any issues.  I 
haven't in the past as well. Doug

**Comment by Cortablo** [comment]
Windows Defender recognized Alpha 14 as a virus! (Trojan:Win32/Fuery:B!cl)

**Comment by Cortablo** [comment]
Update: Windows Defender no longer recognizes premake5.exe as Trojan, sent it to Microsoft.
https://www.microsoft.com/en-us/wdsi/submission/634082b2-a971-4fcb-9081-5e000dfd8a4d

**Comment by didgerihorn** [comment]
Same issue here. Premake ran fine for a few weeks, but starting today, Windows Defender classifies premake5.exe (SHA1: f081fe1f6c990b2eb01ef5f3143857176e479bcf)

**Comment by nickclark2016** [comment]
@starkos I ran Windows Defender against 5.0.0-alpha-16 and it came back clean.

```
Antimalware Client Version: 4.18.2108.7
Engine Version: 1.1.18500.10
Antivirus Version: 1.349.1576.0
Antispyware Version: 1.349.1576.0
```

**Comment by starkos** [comment]
Yes, thanks for bringing this to my attention. We've added a "send to Microsoft" step to the release script to help prevent this from happening in the future. Closing…
