### ISSUE TITLE
(premake5) It seems that in visual studio, "Additional Include Directories" is not generated properly

### ISSUE THREAD

**Issue by doyoubi** [premake/premake-core#90]
`includedirs { "src" }` in premake config file will generate `..\src;%(AdditionalIncludeDirectories)` for Additional Include Directories in visual studio 2013. But `..\src` seems only relative to the current code source file, not relative to `$(ProjectDir)`. Should premake add `$(ProjectDir)`before `..\src` ?

**Comment by tvandijck** [comment]
No.. it should not use the $(ProjectDir) at all, since they already are relative to the vcxproj, adding $(ProjectDir) would be completely redundant...

**Comment by starkos** [comment]
I've never had a problem with this. Can you provide a small sample that demonstrates the problem you're seeing?

**Comment by doyoubi** [comment]
@tvandijck you are right, later I found it work. Maybe I made some mistakes at the first time.
But in my vs2013, without `$(ProjectDir)`, after typing `include ""` there is no prompt for the files and directories under the `Additional Include Directories`, while with `$(ProjectDir)` added, the prompt works well.
My file list looks like this:

    | premake5.lua
    |
    | -- src/ 
    |     | header/ 
    |     |   |
    |     |   | header.h
    |     |
    |     | main/
    |       | 
    |       | main.cpp
    |
    | -- build/
          |
          | files generated by premake, including .sln and .vcxproj

and my premake5.lua is :

    solution "TestSln"
        location "build"
        includedirs { "src" }
        configurations { "DEBUG" }
    
    project "proj1"
        kind "ConsoleApp"
        language "C++"
        files { "src/**.h", "src/**.cpp" }

Without `$(ProjectDir)`, after typing `include ""` in the main.cpp, there is no prompt for `header` and `main` directories.
Should we add `$(ProjectDir)` explicitly to get around it?

**Comment by TurkeyMan** [comment]
So, you've specified the include path as a solution property, and also specified that the solution should be located in build/. `location` is the path that the include dir is relative to, which explains the `../` present in the path. Just move the `includedirs` statement into the project, and you should be fine.

**Comment by TurkeyMan** [comment]
I doubt many people try to do this, but it does raise questions about this (and other) options being specified at the solution scope...

**Comment by doyoubi** [comment]
@TurkeyMan Thanks for your explanation. 
But for this premake config file, since the project `proj1` inherits the `location` from solution, specifying the `includedirs` in the solution scope and project scope seems to give the same `Additional Include Directories` for the `proj1`.
Now I can't reproduce the problem that compiler said it can't find the header.h file. But without the `$(ProjectDir)`, prompt for #include in my vs2013 doesn't works. After changing `..\src;%(AdditionalIncludeDirectories)` to `$(ProjectDir)\..\src;%(AdditionalIncludeDirectories)` manually, the prompt works again.

**Comment by starkos** [comment]
> But without the $(ProjectDir), prompt for #include in my vs2013 doesn't works

What is this "prompt for #include"?

**Comment by tvandijck** [comment]
For what it is worth however... this is not unique behavior to just includedirs, this is the same with vpaths, which is why we needed support for tokens in there, so we could setup global vpaths in the solution, but still use %{prj.basedir} as the basedirectory... it's somewhat cumbersome, and maybe a food for thought.

**Comment by starkos** [comment]
Premake converts all paths to absolute at the time they are received from the script, and then to project relative at export time. If that isn't working transparently, regardless of at which scope the paths were specified, then it should be considered a bug. Small examples that demonstrate the problem would be helpful.
