### ISSUE TITLE
Disable PCH on a specific file

### ISSUE THREAD

**Issue by Asubayo** [premake/premake-core#909]
I would like to disable the use of pch on some specific files in my project.
I read that we should just need to do : 
```
filter { 'files:myfile.cpp' }
   flags { 'NoPCH' }
```
But sadly it seems that the filter on a specific file doesn't work at all for me
First, I have :

```
pchheader "project/StdAfx.h"
pchsource "../project/source/project/StdAfx.cpp"
```
And I think it is correct because when I don't try to disable pch on specific files, the project's precompiled header property is "Use" and on the StdAfx.cpp, the value is "Create"

But as soon as I use :

```
files { "../project/source/tool/myfile.cpp"}
filter { 'files:../project/source/tool/myfile.cpp' }
   flags { 'NoPCH' }
```
Everything is set to "Not Using" (on the project settings, on every files, on StdAfx.cpp)
It is like the filter doesn't work and the NoPCH flag is applied to the whole project. I don't get it, any idea ?

**Comment by Asubayo** [comment]
My mistake, I come from a build script made for premake 4 and I try to now use premake 5.
The pch disabling was made before the setting of pchsource and pchheader. By now setting it before the filtering of some files to disable pch, it fixed my issue.

**Comment by fishingGrapes** [comment]
Hey! Can you specify how you did this? Would be really Helpful!

**Comment by ccwanggl** [comment]
in my case, I put the all filter section at the end of the `premake5.lua` file, like follows:
```lua
 filter "files:**.c"
    flags {"NoPCH"}
```
it worked well.
