### ISSUE TITLE
(premake4) "vstudio" not exist while generating vs2013 solution

### ISSUE THREAD

**Issue by doyoubi** [premake/premake-core#91]
when generating vs2013 solution using premake4, an exception raised and give the following error message:

    Building configurations...
    Running action 'vs2013'...
    [string "newaction..."]:14: attempt to index global 'vstudio' (a nil value)

**Comment by starkos** [comment]
Premake 4.x issues should be logged [over on the premake-4.x repository](https://github.com/premake/premake-4.x), but this one appears to have been fixed in the latest code anyway.
