### ISSUE TITLE
Reference to a project in an other solution

### ISSUE THREAD

**Issue by Asubayo** [premake/premake-core#910]
I am updating a build script from premake4 to an older version of premake5 with no "workspace" concept, but still the "solution" one.

When I run premake, I have custom options to build two vs2015 solutions A and B : 

> premake5.exe --A --B vs2015

I would like the project in B to have a reference on a project in A (ProjectReference). 
But it seems to do not find any project A and I am wondering if it because the project A is only searched inside the solution B, and not also A.

With premake4, we also had the function "vc2010.projectReferences" which called
"premake.getdependencies" with premake.findproject inside. 

But with premake5, the "findproject" seems to be called on the scope of our current solution/workspace (premake.solution(/workspace).findproject(cfg.solution, depproj))

Does that mean that I can't link my project B with a project A if there are not in the same solution ?
Do I have to use the "external" api ?

**Comment by starkos** [comment]
If they are not in the same solution, then yes, you should use `external`. Or you can define the project in each solution, in which case `links` will work as expected. I'm pretty sure Premake4 worked in much the same way, and didn't allow cross-solution links?
