### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by doughodson** [premake/premake-core#911]
First off, I absolutely love premake!  The biggest challenge is learning how to fully exercise it's capabilities to write proper scripts, which means a few documentation tweaks.

Here is one 'small' update that I think would help in the area of 'filters'.  If the following points are correct, then I think posting it would be useful.

1) When a 'filter' is invoked, all previous filters in effect are removed.  Meaning, using filter is equivalent to saying filter {}, followed by the filter you are now setting.

2) When a project is invoked, all previous filters are reset.

3) Filters act as a scoping concept, after invoked, they affect subsequent operations until reset (Much like a C/C++ end brace). Resetting can occur by setting another filter or invoking project.

For the page with 'project' -- this text is not entirely clear: "Creates a new project, and makes it the active configuration scope."  I think the word 'configuration' is confusing, maybe just stating it "Creates a new project within the scope of a workspace with no active filters."

**Comment by tritao** [comment]
Hey @doughodson, these look like good clarifications to the docs to me and I think would be good additions (not a member of the core team though so don't take my word as official). You can add them yourself since it is a wiki.

**Comment by doughodson** [comment]
I wouldn't want to add something that is actually incorrect.  If correct, I'll add.  Can someone verify that my 'filter' points are in fact correct?  Thanks!

**Comment by tvandijck** [comment]
They are absolutely correct, feel free to amend the documentation, and thank you for your contribution.

**Comment by doughodson** [comment]
ok, will do!

**Comment by doughodson** [comment]
Pages for 'filter', 'project' and 'workspace' have been edited.  Only very minor edits to 'project' and 'workspace.'

**Comment by starkos** [comment]
Thanks for this!
