### ISSUE TITLE
Error: [string "d/actions/gmake.lua"]:159: attempt to call a nil value (field 'getversions')

### ISSUE THREAD

**Issue by FraMecca** [premake/premake-core#912]
premake5.lua:

`
workspace "HelloWorld"
   configurations { "Debug", "Release" }

	project "lucene"
   	   language "C++"

   	   files { "source/lucenebridge.cpp", "source/clucene/bin/*.a" }
   	   cppdialect "C++11"
   	   kind "Utility"

   	   filter "configurations:Debug"
      	  defines { "NOMAIN" }
      	  symbols "On"

   	   filter "configurations:Release"
      	  defines { "NOMAIN" }
      	  optimize "On"

	project "Dbend"
   	   language "D"

   	   files { "source/app.d" , "/home/user/.dub/packages/**.a" }
   	   links { "lucene", "stdc++", "m", "z", "pthreads" }
   	   kind "ConsoleApp"

   	   filter "configurations:Debug"
      	  symbols "On"

   	   filter "configurations:Release"
	  	  kind "Utility"
      	  optimize "On"
`

**Comment by samsinsane** [comment]
There aren't really any D experts active on the project at the moment, but I'm guessing that none of the D compilers are set as the default toolset. Try adding `toolset "dmd"` to your `Dbend` project?

**Comment by FraMecca** [comment]
sorry, can't reproduce anymore
