### ISSUE TITLE
configmap with external projects - visual studio

### ISSUE THREAD

**Issue by Asubayo** [premake/premake-core#914]
I am building a visual studio solution with a project which has references to projects in other solutions. 
By using the "external" api, I can have those project inside my solution. 

But those projects have lot of custom configurations. 
I need specific config for each of those project to successfully build my solution.
Is there a way to define a "configuration mapping" between my solution and external projects ?
With this mapping : when I will manually change the configuration of my solution, I could have the correct active configuration automatically changed for the external projects.

**Comment by samsinsane** [comment]
Does [`configmap`](https://github.com/premake/premake-core/wiki/configmap) work for you?

**Comment by starkos** [comment]
@samsinsane has got it: set up a configmap:

```
external "SomeProject"

    configmap { 
       "Debug" = "Debug_DLL",
       "Release" = "Release_DLL"
    }
```

I'm going to close this issue as solved, but feel free to reopen if you have questions about setting up the map.
