### ISSUE TITLE
Specify Windows SDK version when building a premake project via command line

### ISSUE THREAD

**Issue by maxw** [premake/premake-core#915]
Heyo,

When running the premake5 command, is it possible to specify the Windows SDK version to use? I'm using premake5 to generate a visual studio project. When using the vs2017 action, it seems to always default to Windows 8.1. Which means each time I generate the visual studio project, I need to open it and retarget it for Windows 10 before I can use it elsewhere.

I know it's possible to set this in your premake5.lua file, but I don't control the repo that's using premake5, and therefore do not want to make any modifications. In addition, this is a setting that I'd imagine would change depending on what platform the project is being built for.

Max

**Comment by samsinsane** [comment]
[`systemversion`](https://github.com/premake/premake-core/wiki/systemversion) is what you're looking for, there's an example on how to specify the Windows SDK version on there.

**Comment by maxw** [comment]
I had found that previously, but if I understand it correctly, that would require me to make changes to the premake5.lua file correct? Or is there a way I can pass that as a command-line argument?

Max

**Comment by samsinsane** [comment]
Anything you want to pass via a command line argument is going to require changes to premake5.lua in some way. You can create a [`newoption`](https://github.com/premake/premake-core/wiki/newoption) and then use it as described [here](https://github.com/premake/premake-core/wiki/Command-Line-Arguments).

**Comment by maxw** [comment]
See that's the issue. I don't control the project, and therefore cannot make changes to the premake5.lua file. I was hoping I could specify it like I do when specifying which visual studio version. ie "premake5 vs2017-Win10". I think I'm just now realizing that "premake5 vs2017" must just be referencing a built-in action...

**Comment by starkos** [comment]
What about wrapping the project's `premake5.lua` in one of your own? That is, create a new `premake5.lua` (or call it something else):

```
dofile("original_project/premake5.lua")

-- reconfigure things here to suit
```

I've had to do this myself a time or two.

**Comment by maxw** [comment]
Oh snap that's awesome! I didn't know that was an option. I'll give that a shot. Thanks for the tip!

**Comment by starkos** [comment]
Going to close this as solved for now then…feel free to reopen if you have questions!

**Comment by maxw** [comment]
Sounds good. Thanks again :)
