### ISSUE TITLE
[Premake5] DebugCommand and DebugDir not working correctly in VS 2013

### ISSUE THREAD

**Issue by dgregorius** [premake/premake-core#92]
I am using Premake5 Alpha3. DebugCommand and DebugDir are not working properly for me. The command and directory are set in the project settings but using relative paths and VS complaints about this. When I convert everything to absolute path in the project settings of VS everything works. I think the paths need to be extended to absolute for this to work.

Thanks!
-Dirk

**Comment by TurkeyMan** [comment]
This has come up before... I recall a patch, was it already merged @starkos / @tvandijck ?

**Comment by tvandijck** [comment]
I think that was fixed in this pull request: https://github.com/premake/premake-core/pull/59

**Comment by amc522** [comment]
Yeah, that was the same problem I was having. My patch fixed the debugcommand. I dont recall seeing the same issue with debugdir.

**Comment by TurkeyMan** [comment]
@dgregorius Can you test with the latest build? I'll close this, and you can reopen if your problem persists.
