### ISSUE TITLE
'runtime' api is kinda shit

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#929]
So, I've been upset about this for years, and keep thinking I should do something about it... problem is, it's probably a breaking change.

My bugbear is `runtime "debug"/"release"`.  
To me, 'runtime' suggests more about runtime selection than whether it has debug symbols or not. On Windows for instance, I think 'runtime' should rather select static/dynamic CRT, on OSS systems, you might choose between 'glibc'/'newlib'/etc.
I also feel like the existing debug/release selection should be referred to some other API, which is useful in many more situations by many pieces of tooling to set the high-level 'debug-ness' of the project; and in this case, that debug-ness setting could influence the runtime to select debug/release runtime.

So, that is to say, if I had my way, `runtime` would mean something completely different than it does now... do others also feel the current definition of 'runtime' is kinda nonsense?

**Comment by samsinsane** [comment]
> problem is, it's probably a breaking change.

Still being an alpha, this can happen. It's not ideal, but it's not the worst thing in the world.

> Windows for instance, I think 'runtime' should rather select static/dynamic CRT, on OSS systems, you might choose between 'glibc'/'newlib'/etc.

These sounds like two different things to me - "linking method" vs "implementation". Could OSS systems utilize the "linking method" options too? Is there a way to use a different implementation of the CRT on Windows? It doesn't look like it within MSVC, but perhaps there are alternatives when not using MSVC?

I find it weird that MSVC allows you to use the DLL options, but we only allow that in [one particular case](https://github.com/premake/premake-core/blob/378c074424acfe5e335820720a42b5138c3fff27/src/base/config.lua#L331-L333). I don't think anyone has requested that it be changed, but it's very strange regardless.

**Comment by starkos** [comment]
I haven't thought about this in a while, but I agree this could be improved. I kind of developed all of this reactively rather than proactively…I didn't know enough about the different runtimes on non-Windows systems, so I tried to keep it very general.

I think @samsinsane might be right as well, and multiple APIs might be needed to handle this fully. I wonder if it could also be used/abused to specify the .NET compatibility level (i.e. PCL or .NET Standard version) for C# projects?

**Comment by TurkeyMan** [comment]
Yeah, Sam's right on that for sure.
So there are 3 concepts here:
- Runtime-debug-ness (or rather; I would actually like to see a general high-level-debug-ness api which is useful to lots of things)
- Static/dynamic runtime linkage
- Actual runtime to use

Care to throw out some suggested names for each of these concepts? My feeling is that `runtime` should probably be the last item.

I feel like .NET standard version is a different thing; especially considering .NET programs are often developed in conjunction with C/C++ apps via some managed C++ interop layer (which still requires a C runtime specification).

**Comment by TurkeyMan** [comment]
@samsinsane: Yeah, that hack there you found is SO not okay, and that's actually one of the specific reasons motivating this thread.

I've had a bit of a discussion with Tom offline.
I suggested:
> I’m thinking:
> ‘runtime’ == mscrt/glibc/newlib/etc  (probably completely unused by MSVC)
> ‘staticruntime’ == ‘default/on/off’
> And something more high-level and general like ‘debugbuild’ or something, which can be used to toggle whether the build is intended for debugging (in this case, CRT selection).
There are often a few options related to debugging, and they are almost always synchronised, this gives us a good API to control them all. All toolchains have some different related stuff, but they are always synchronised regardless.

His immediate reaction was "don't break it", and suggested folding them into a single API.
> ->	‘staticruntime’ == ‘default/on/off’
> Should just be folded into runtime… for visual studio there is 4 options.
> Right now you get the following:
> runtime ‘debug’ + flags { ‘staticruntime’ }              -> /MTd
> runtime ‘release’ + flags { ‘staticruntime’ }            -> /MT
> runtime ‘debug’                                                                -> /MDd
> runtime ‘release’                                                              -> /MD
> 
> it should just become
> runtime ‘debugstatic’                     -> /MTd
> runtime ‘releasestatic’                   -> /MT
> runtime ‘debugdynamic’               -> /MDd
> runtime ‘releasedynamic’             -> /MD

My response was:
> “runtime” is a selection that possibly least affects visual studio, since it has an implicit connection to its runtime.
> All runtimes come in static/dynamic form, and they often come in debug/release form too… so it’s a 3d matrix, and I don’t think it’s reasonable to collapse a 3d matrix into a single linear list of options, especially when context for selection is dependent on multiple independent variables.
> 
> Like, you want to set the runtime’s debug-ness according to whether it’s a debug/release configuration… the static-ness is unrelated to that, and will have different selection criteria. That’s why it’s super-inconvenient to have both concepts folded into a single API, otherwise you need premake code somewhere that filters on each combination of criteria to call the single API properly.
> 
> filter ( “configuration:debug”, “other:criteria” }
>  runtime “staticdebug” 
> filter ( “configuration:release”, “other:criteria” }
>  runtime “staticrelease” 
> filter ( “configuration:debug”, “other:criteria2” }
>  runtime “dynamicdebug” 
> filter ( “configuration:release”, “other:criteria2” }
>  runtime “dynamicrelease” 
> 
> That sort of code is necessary with the runtime attributes folded into a single API, and people often have >2 configurations.
> Also, if the matrix is 3D (ie, any environment other than VS), it’s completely explosive.
> 
> I think they must be separated.

I expect a deprecation path would naturally be in place; calls to `runtime "Debug"` would emit a message suggesting to use the new api.
My feeling is that this is a fairly drastic, and potentially breaking change, I want buy in before I do it and certainty that my suggestion is reasonable/correct.

**Comment by tvandijck** [comment]
FWIW, a lot of our 'debug' code uses the 'static' & 'release' versions of the microsoft libraries... Because most of the time, I'm not really interested in debugging microsofts code, and like to have their libraries simply be the fast release versions... 

So I don't think 'runtime' should be dependent on 'configuration'.. more specifically, a lot of our games don't have a "debug" or "release" configuration, but rather configurations like DebugSlow, and DebugFast, ReleaseProfile, ReleaseCandidate, ReleaseLTCG, etc..  So having to select the runtime through filters is already something we have to do, simply because we're not using any kind of default names.

I also don't think it's a matrix... it's a list in visual studio, so I'm not sure where the matrix idea comes from.

**Comment by TurkeyMan** [comment]
It doesn't matter specifically what set of configurations you have, I was just trying to give an example. What I'm saying is that you're almost certainly going to want to set the static-ness and the debug-ness according to independent variables (ie, set them under different/unrelated filters) and I used configuration as a (common) example.

I say matrix because there are multiple dimensions related to runtime selection; runtime x static-ness x debug-ness. it's an Nx2x2 matrix, where N depends on the platform. In windows case N=1, which leaves us with a quite manageable 2x2 matrix, but that's the simplest possible case. I think even in that case though, you're still likely to want to set the debug-ness and static-ness according to independent variables...

**Comment by tvandijck** [comment]
OK... so right now they are two separate settings. we got runtime for "debug-ness" and the flag for "static-ness". So you want to add a configuration value for what 'base-libraries' to use, like glibc vs newlib, etc.

I think I finally kind of understand what you are aiming for, and somewhat agree that the current API names may not really be ideal. For static-ness, I indeed rather see a proper API. I can see that runtime isn't the best name for 'debug-ness', although it is very specific to the runtime libraries visual studio links against, and has really nothing to do with 'debug' vs 'release' configuration. Like I said, release can very well select the debug runtime, and debug can very well select the release runtime to link against. And this particular setting is VERY unique to visual studio. In my opinion selecting debug vs release runtime is more akin to selecting 'glibc' vs 'newlib', in that they are  different implementations of libc.

This is also why I think that a list for "debug-ness" is a better option, while leaving static-ness a flag or proper API I can totally agree with... I'm assuming on the linux side you can also link against glibc statically vs dynamically... 

And honestly, that is what we currently have... runtime is either 'release' or 'debug', which has NOTHING to do with my code being optimized or not, it's just selecting what runtime we're linking against, and so adding the "newlib", "glibc", etc options would totally be fine. We just have to validate it, and maybe rename 'release/debug' to have a microsoft prefix or something. But other then that things are kind of the way you are proposing them to be.

**Comment by starkos** [comment]
FYI, I am watching this conversation, but my experience with alternate libc implementations is pretty limited. I don't recall ever linking against a debug runtime on macOS or Linux though, so perhaps @tvandijck is right and that is primarily a Windows/VS concept?

**Comment by TurkeyMan** [comment]
It's true that Microsoft really rubs this thing in your face (by making the debug/release libs NOT binary compatible), whereas others don't make such a fuss about it. It's possible to link debug libs on *nix platforms. Many *nix packages present a `-dbg` package in addition to the usual `-dev` package, so you can link against debug libs for development. CRT is no exception here.

But you're effectively arguing that because `|N|==1` on msvc, and `|debug-ness|==1` on not-msvc, we have a 1x2x2 or Nx1x2 matrix, and so we might as well just treat this as a 2d matrix where one axis takes on a different meaning according to the "msvc-ness" :P ... I mean, I get the practical value of the argument, it just feels like a bit of a logical contortion to me, but I could be persuaded to accept it in my mind for simplicity ;)

So, if you're building windows and want to link glibc or newlib or whatever? They need to appear alongside "debug"/"release", so I can get on-board with 'runtime' == "mscrt-debug"/"mscrt-release"/"glibc"/etc.. (and then map the existing "debug"/"release" keys for backward compatibility).

Then the action item is to make `StaticRuntime` into an API... I think we all agree on that.

**Comment by starkos** [comment]
I'm not familiar with the process…if I wanted to link against a debug version of the runtimes on Linux, how do I do that? Is it just a linker switch or is there more to it?

**Comment by TurkeyMan** [comment]
The `-dbg' packages typically put the debug binaries in `/usr/lib/debug`. I'm pretty sure you just `-L/usr/lib/debug` when linking (which will override the default path), or more globally you could set `LD_LIBRARY_PATH=/usr/lib/debug`, which is probably more useful for dynamic libs.

Unlike windows where DEBUG/NDEBUG libs are generally binary incompatible (thanks STL!), linux debug binaries are compatible, so for shared libs you can switch without rebuilding your app. Static libs obviously require linking different binaries.

**Comment by starkos** [comment]
So far it sounds like MSC really is the only case (currently) where it is necessary to choose the debug-ness of the runtime up front. But if we did have a separate value for it, maybe like:

    runtime "glibc"
    runtimesymbols "On"

…what would that actually do on a non-Windows system? It kind of depends on how the system is configured, doesn't it? 

I'm leaning in favor of @tvandijck solution right now.

**Comment by TurkeyMan** [comment]
Yeah, I think I've come around.
On a linux system I'd expect that code to link glibc with `-L/usr/lib/debug`, but i guess you might as well give that lib path manually... only difference is, that wouldn't represent uniform behaviour across platforms. But I thinking there's not need for uniform behaviour here.

Do we agree that in addition to "debug"/"release" used by MSC, we'll also add the runtime selection to the existing `runtime` api in the future?

I've pushed a patch to add `staticruntime` API internally, I'll make it public when I show it works here.

**Comment by TurkeyMan** [comment]
Patch submit.
