### ISSUE TITLE
premake5 alpha 3 generate vs2010 project on vs2013 solution

### ISSUE THREAD

**Issue by scardin** [premake/premake-core#93]
Hello,

I've just created 3 project calling "premake5 vs2013" 

in the solution I have 2 project which works perfectly fine and one which have the platform toolset option set to visual 2010 (not installed on my machine).

Has anyone seen this issue? Is there a work around?

**Comment by Meoo** [comment]
We had this problem where we replaced a "configuration" by a "filter" where we did not specify prefixes (so it used the default "configuration:" prefix instead of the "options:" which we needed)
Maybe this can help you...

**Comment by scardin** [comment]
Ok it is really wierd since the premake5.lua file in the root directory sets the configuration

solution "mm"
	configurations {"Debug", "Release"}
	location "build"
	platforms {"Win32","Win64"}
	
	filter { "platforms:Win32" }
		system "Windows"
		architecture "x32"
		
	filter { "platforms:Win64" }
		system "Windows"
		architecture "x64"
		
	filter "configurations:Debug"
      defines { "DEBUG" }
      flags { "Symbols" }

    filter "configurations:Release"
      defines { "NDEBUG" }
      optimize "On"

And the premake file in the local directory looks like this for the 2 project that works:

project "mmlog"
	kind "StaticLib"
	language "C++"
	files {"mmlog.h", "mmlog.cpp"}
	links {"mmbase"}
	targetdir (build_path .. lib_folder)
	

project "mmlog_usage"
	kind "ConsoleApp"
	language "C++"
	files {"mmlog_usage.cpp"}
	links {"mmlog"}
	targetdir (build_path .. bin_folder)

and like this for the one that cause the issue:

project "mmbase"
	kind "StaticLib"
	language "C++"
	files {"mmbase.h"}
	targetdir (build_path .. lib_folder)

**Comment by Meoo** [comment]
Well, this is unrelated then, sorry

**Comment by starkos** [comment]
Is it related to [this issue](https://bitbucket.org/premake/premake-dev/issue/266/invalid-project-type-for-empty-projects)?

**Comment by scardin** [comment]
Yes it is exactly this

The main issue was my lib currently only contain .h file, I added a dummy cpp file and it solved the problem.

Thanks
