### ISSUE TITLE
Question: premake5 or just plain premake?

### ISSUE THREAD

**Issue by jjatria** [premake/premake-core#933]
I recently came across premake while trying to build a project I am not at all involved with. In doing so, I realised that the binary for premake is called `premake5` or `premake4`, instead of plain `premake`. Am I to take from this that the two versions are incompatible?

Obviously, a project that uses features from version 5 would not be buildable with version 4. But is there any guarantee that projects that were configured to use premake4 will remain buildable with version 5, or 6, or whatever comes next? *

### Background

I came across this question while writing a Perl module to install premake and wondering if I should name the module `Alien::premake` or `Alien::premake5` (the `Alien::` family of modules installs packages or libraries that are _alien_ to Perl).

If future versions are supposed to be backwards compatible, then I'd think plain `premake` is better. But if different versions break that, then that would not work. What do you think?

Thank you for the help, and apologies if this is not the right place to ask.

---

\* Perhaps... 7? :open_mouth:

**Comment by starkos** [comment]
> is there any guarantee that projects that were configured to use premake4 will remain buildable with version 5, or 6, or whatever comes next?

No, there is no guarantee, though we do our best.

**Comment by jjatria** [comment]
Thanks!
