### ISSUE TITLE
Value Tokens not evaluating in os.execute

### ISSUE THREAD

**Issue by JohannesMP** [premake/premake-core#942]
Should [value tokens](https://github.com/premake/premake-core/wiki/Tokens#value-tokens) expand in commands such as os.execute? Currently it seems that, while [command tokens](https://github.com/premake/premake-core/wiki/Tokens#command-tokens) expand correctly, value tokens do not.

premake5.lua Example:

````lua
workspace "test_wks"
  location("wks")
  configurations { "Debug", "Release" }
  
  project "test_proj"
    location("%{wks.location}/proj")
    kind "ConsoleApp"
    language "C++"
    targetdir("%{proj")
    
    os.execute("{ECHO} location: %{wks.location}")
````

When run with `premake5 vs2015`, it will echo out `location:  %{wks.location}`

I think it would be useful to be able to use value tokens anywhere that command tokens are permitted.

**Comment by starkos** [comment]
No, that's not possible. Command tokens are fixed, constant values so it is possible to apply them during script execution. But value tokens only get their final value after the script has completed execution and the results are collated.

**Comment by JohannesMP** [comment]
What about in if placed inside a `filter("action:...")`? is there a way to get it to run post-action? something like a `postactioncommand`?

**Comment by starkos** [comment]
You could hook into `premake.main.postBake`? Untested, but something like:

    local p = premake

    p.override(p.main, 'postBake', function(base)
        local wks = p.global.getWorkspace('test_wks')
        local location = wks.location
        os.execute('{ECHO} location: ' .. location)

        base()
    end)
