### ISSUE TITLE
'install' action should be emit to makefiles

### ISSUE THREAD

**Issue by TurkeyMan** [premake/premake-core#95]
If the premake script defines an `install` action, it would be nice to emit an `install` rule to makefiles which just executes `premake5 install`... only trouble is, knowing the path/command to execute premake.
Ideas?
Possible to capture the binary being run for the `gmake` action and use the same command?

**Comment by starkos** [comment]
`_PREMAKE_COMMAND` will get you the path the executable, but you will also need to capture the command line flags, which may or may not apply correctly to the install action?

**Comment by TurkeyMan** [comment]
True. Do you reckon this is worth considering?

**Comment by starkos** [comment]
Once upon a time I tried to have the generated makefiles regenerate themselves in any of the source project scripts changed. I could never get it working reliably and ended up pulling ti out; this looks like a very similar problem.

One way to get this now would be using makesettings() to write out the exact install rule you wanted. A better long term solution would be to define a new API like maybe "installcommands" that can be executed by Premake or output for tools that support them, like makefiles. The new command tokens (e.g. "{COPY"}) should help with that.

**Comment by TurkeyMan** [comment]
Yeah, I prefer your ideas. I'll abandon this idea.
