### ISSUE TITLE
How to generate the iOS project？

### ISSUE THREAD

**Issue by panhaowen** [premake/premake-core#972]
I found that I could only use premake to generate the MacOS project.

Because I'm on a cross-platform development, I want to generate vs2017 and Android and iOS.

**Comment by samsinsane** [comment]
`system "ios"` *should* generate the iOS project for the `xcode4` action.

**Comment by panhaowen** [comment]
I tried the [system "ios" _ACTION= "xcode4"], and the runtime would report the Error [Error: invalid value 'ios' for system"]

**Comment by samsinsane** [comment]
You might need to update Premake, the `system` API definitely has `ios` in [the list](https://github.com/premake/premake-core/blob/08c768d20e931953b80907381cc0b0bd64286892/src/_premake_init.lua#L1140).

**Comment by samsinsane** [comment]
Closing this as there hasn't been any feedback, assuming that updating Premake resolved the issue. Please feel free to reopen if there's still an issue.
