### ISSUE TITLE
change old links to industriousone.com

### ISSUE THREAD

**Issue by catb0t** [premake/premake-core#973]
https://github.com/premake/premake-core/blob/5a3593a8243494596b3a84eb8b64a5ec82c98979/src/base/help.lua#L72

https://github.com/premake/premake-core/blob/7a1ffeff7c53f5c8c8ec00ed8f284e72a2def368/modules/gmake/gmake_workspace.lua#L95

https://github.com/premake/premake-core/blob/02f5a75fc908a56a7d0f67c749514ac8b6a084e4/modules/gmake2/gmake2_workspace.lua#L109

The last two of these lines cause `premake gmake{,2}; make help` to say 

`For more information, see http://industriousone.com/premake/quick-start`

In fact, this link is broken, as the IndustriousOne page says "What you seek, I cannot find." and then gives you a link to https://premake.github.io. The quick-start page is not forthcoming. 

Perhaps it should link to the wiki? 

I think the first one, `premake --help`, should link to http://premake.github.io.

I'd be happy to create a pull request like this, but to where should the new links go?

**Comment by starkos** [comment]
I agree: I would send the first to https://premake.github.io, and the others to to https://github.com/premake/premake-core/wiki.
