### ISSUE TITLE
Makefile projects broken with gmake2 generator

### ISSUE THREAD

**Issue by catb0t** [premake/premake-core#974]
premake5.lua

```lua
workspace "hello"
  configurations { "dbg", "dist" }
  language "C"

  project "prog"
    kind "ConsoleApp"
    files { "*.c" }

  project "clobber"
    kind "Makefile"

    cleancommands {
      "(rm bin obj *.make Makefile -r 2>/dev/null; echo)" -- this can be anything
    }
```

```sh
$ premake gmake2
Building configurations...
Running action 'gmake2'...
Generated prog.make...
Generated hello.make...

Error: [string "src/base/_foundation.lua"]:61: attempt to get length of a function value (local 'array')

$ premake --version
premake5 (Premake Build Script Generator) 5.0.0-alpha12
```

https://github.com/premake/premake-core/blob/release-5.0-alpha12/src/base/_foundation.lua#L61

are lua files minified before being compiled? in the unminified code there's nothing on this line. after [being minified](https://mothereff.in/lua-minifier#---%0A--%20Base%20definitions%20required%20by%20all%20the%20other%20scripts.%0A--%20%40copyright%202002-2015%20Jason%20Perkins%20and%20the%20Premake%20project%0A---%0A%0A%09premake%20%3D%20premake%20or%20%7B%7D%0A%09premake.%5fVERSION%20%3D%20%5fPREMAKE%5fVERSION%0A%09package.loaded%5B%22premake%22%5D%20%3D%20premake%0A%0A%09premake.modules%20%3D%20%7B%7D%0A%09premake.extensions%20%3D%20premake.modules%0A%0A%09local%20semver%20%3D%20dofile%28%27semver.lua%27%29%0A%09local%20p%20%3D%20premake%0A%0A%0A--%20Keep%20track%20of%20warnings%20that%20have%20been%20shown%2C%20so%20they%20don%27t%20get%20shown%20twice%0A%0A%09local%20%5fwarnings%20%3D%20%7B%7D%0A%0A--%20Keep%20track%20of%20aliased%20functions%2C%20so%20I%20can%20resolve%20to%20canonical%20names%0A%0A%09local%20%5faliases%20%3D%20%7B%7D%0A%0A--%0A--%20Define%20some%20commonly%20used%20symbols%2C%20for%20future-proofing.%0A--%0A%0A%09premake.C%20%20%20%20%20%20%20%20%20%20%20%3D%20%22C%22%0A%09premake.C7%20%20%20%20%20%20%20%20%20%20%3D%20%22c7%22%0A%09premake.CLANG%20%20%20%20%20%20%20%3D%20%22clang%22%0A%09premake.CONSOLEAPP%20%20%3D%20%22ConsoleApp%22%0A%09premake.CPP%20%20%20%20%20%20%20%20%20%3D%20%22C%2B%2B%22%0A%09premake.CSHARP%20%20%20%20%20%20%3D%20%22C%23%22%0A%09premake.GCC%20%20%20%20%20%20%20%20%20%3D%20%22gcc%22%0A%09premake.HAIKU%20%20%20%20%20%20%20%3D%20%22haiku%22%0A%09premake.LINUX%20%20%20%20%20%20%20%3D%20%22linux%22%0A%09premake.MACOSX%20%20%20%20%20%20%3D%20%22macosx%22%0A%09premake.MAKEFILE%20%20%20%20%3D%20%22Makefile%22%0A%09premake.MBCS%20%20%20%20%20%20%20%20%3D%20%22MBCS%22%0A%09premake.NONE%20%20%20%20%20%20%20%20%3D%20%22None%22%0A%09premake.DEFAULT%20%20%20%20%20%3D%20%22Default%22%0A%09premake.ON%20%20%20%20%20%20%20%20%20%20%3D%20%22On%22%0A%09premake.OFF%20%20%20%20%20%20%20%20%20%3D%20%22Off%22%0A%09premake.POSIX%20%20%20%20%20%20%20%3D%20%22posix%22%0A%09premake.PS3%20%20%20%20%20%20%20%20%20%3D%20%22ps3%22%0A%09premake.SHAREDLIB%20%20%20%3D%20%22SharedLib%22%0A%09premake.STATICLIB%20%20%20%3D%20%22StaticLib%22%0A%09premake.UNICODE%20%20%20%20%20%3D%20%22Unicode%22%0A%09premake.UNIVERSAL%20%20%20%3D%20%22universal%22%0A%09premake.UTILITY%20%20%20%20%20%3D%20%22Utility%22%0A%09premake.WINDOWEDAPP%20%3D%20%22WindowedApp%22%0A%09premake.WINDOWS%20%20%20%20%20%3D%20%22windows%22%0A%09premake.X86%20%20%20%20%20%20%20%20%20%3D%20%22x86%22%0A%09premake.X86%5f64%20%20%20%20%20%20%3D%20%22x86%5f64%22%0A%09premake.ARM%20%20%20%20%20%20%20%20%20%3D%20%22ARM%22%0A%09premake.XBOX360%20%20%20%20%20%3D%20%22xbox360%22%0A%0A%0A%0A---%0A--%20Provide%20an%20alias%20for%20a%20function%20in%20a%20namespace.%20Calls%20to%20the%20alias%20will%0A--%20invoke%20the%20canonical%20function%2C%20and%20attempts%20to%20override%20the%20alias%20will%0A--%20instead%20override%20the%20canonical%20call.%0A--%0A--%20%40param%20scope%0A--%20%20%20%20The%20table%20containing%20the%20function%20to%20be%20overridden.%20Use%20%5fG%20for%0A--%20%20%20%20global%20functions.%0A--%20%40param%20canonical%0A--%20%20%20%20The%20name%20of%20the%20function%20to%20be%20aliased%20%28a%20string%20value%29%0A--%20%40param%20alias%0A--%20%20%20%20The%20new%20alias%20for%20the%20function%20%28another%20string%20value%29.%0A---%0A%0A%09function%20p.alias%28scope%2C%20canonical%2C%20alias%29%0A%09%09scope%2C%20canonical%20%3D%20p.resolveAlias%28scope%2C%20canonical%29%0A%09%09if%20not%20scope%5Bcanonical%5D%20then%0A%09%09%09error%28%22unable%20to%20alias%20%27%22%20..%20canonical%20..%20%22%27%3B%20no%20such%20function%22%2C%202%29%0A%09%09end%0A%0A%09%09%5faliases%5Bscope%5D%20%3D%20%5faliases%5Bscope%5D%20or%20%7B%7D%0A%09%09%5faliases%5Bscope%5D%5Balias%5D%20%3D%20canonical%0A%0A%09%09scope%5Balias%5D%20%3D%20function%28...%29%0A%09%09%09return%20scope%5Bcanonical%5D%28...%29%0A%09%09end%0A%09end%0A%0A%0A%0A---%0A--%20Call%20a%20list%20of%20functions.%0A--%0A--%20%40param%20funcs%0A--%20%20%20%20The%20list%20of%20functions%20to%20be%20called%2C%20or%20a%20function%20that%20can%20be%20called%0A--%20%20%20%20to%20build%20and%20return%20the%20list.%20If%20this%20is%20a%20function%2C%20it%20will%20be%20called%0A--%20%20%20%20with%20all%20of%20the%20additional%20arguments%20%28below%29.%0A--%20%40param%20...%0A--%20%20%20%20An%20optional%20set%20of%20arguments%20to%20be%20passed%20to%20each%20of%20the%20functions%20as%0A--%20%20%20%20as%20they%20are%20called.%0A---%0A%0A%09function%20premake.callArray%28funcs%2C%20...%29%0A%09%09if%20type%28funcs%29%20%3D%3D%20%22function%22%20then%0A%09%09%09funcs%20%3D%20funcs%28...%29%0A%09%09end%0A%09%09if%20funcs%20then%0A%09%09%09for%20i%20%3D%201%2C%20%23funcs%20do%0A%09%09%09%09funcs%5Bi%5D%28...%29%0A%09%09%09end%0A%09%09end%0A%09end%0A%0A%0A%09--%20TODO%3A%20THIS%20IMPLEMENTATION%20IS%20GOING%20AWAY%0A%0A%09function%20premake.callarray%28namespace%2C%20array%2C%20...%29%0A%09%09local%20n%20%3D%20%23array%0A%09%09for%20i%20%3D%201%2C%20n%20do%0A%09%09%09local%20fn%20%3D%20namespace%5Barray%5Bi%5D%5D%0A%09%09%09if%20not%20fn%20then%0A%09%09%09%09error%28string.format%28%22Unable%20to%20find%20function%20%27%25s%27%22%2C%20array%5Bi%5D%29%29%0A%09%09%09end%0A%09%09%09fn%28...%29%0A%09%09end%0A%0A%09end%0A%0A%0A%0A---%0A--%20Compare%20a%20version%20string%20that%20uses%20semver%20semantics%20against%20a%0A--%20version%20comparision%20string.%20Comparisions%20take%20the%20form%20of%20%22%3E%3D5.0%22%20%285.0%20or%0A--%20later%29%2C%20%225.0%22%20%285.0%20or%20later%29%2C%20%22%3E%3D5.0%20%3C6.0%22%20%285.0%20or%20later%20but%20not%206.0%20or%0A--%20later%29.%0A--%0A--%20%40param%20version%0A--%20%20%20%20The%20version%20to%20be%20tested.%0A--%20%40param%20checks%0A--%20%20%20%20The%20comparision%20string%20to%20be%20evaluated.%0A--%20%40return%0A--%20%20%20%20True%20if%20the%20comparisions%20pass%2C%20false%20if%20any%20fail.%0A---%0A%0A%09function%20p.checkVersion%28version%2C%20checks%29%0A%09%09if%20not%20version%20then%0A%09%09%09return%20false%0A%09%09end%0A%0A%09%09--%20try%20to%20parse%20semver%2C%20if%20it%20fails%2C%20it%27s%20not%20semver%20compatible%20and%20we%20cannot%20compare%2C%20in%20which%20case%0A%09%09--%20we%27re%20going%20to%20ignore%20the%20checkVersion%20entirely%2C%20but%20warn.%0A%09%09if%20not%20premake.isSemVer%28version%29%20then%0A%09%09%09p.warn%28%22%27%22%20..%20version%20..%20%22%27%20is%20not%20semver%20compatible%2C%20and%20cannot%20be%20compared%20against%20%27%22%20..%20checks%20..%20%22%27.%22%29%3B%0A%09%09%09return%20true%0A%09%09end%0A%0A%09%09--%20now%20compare%20the%20semver%20against%20the%20checks.%0A%09%09local%20function%20eq%28a%2C%20b%29%20return%20a%20%3D%3D%20b%20end%0A%09%09local%20function%20le%28a%2C%20b%29%20return%20a%20%3C%3D%20b%20end%0A%09%09local%20function%20lt%28a%2C%20b%29%20return%20a%20%3C%20b%20%20end%0A%09%09local%20function%20ge%28a%2C%20b%29%20return%20a%20%3E%3D%20b%20end%0A%09%09local%20function%20gt%28a%2C%20b%29%20return%20a%20%3E%20b%20%20end%0A%09%09local%20function%20compat%28a%2C%20b%29%20return%20a%20%5E%20b%20%20end%0A%0A%09%09version%20%3D%20semver%28version%29%0A%09%09checks%20%3D%20string.explode%28checks%2C%20%22%20%22%2C%20true%29%0A%09%09for%20i%20%3D%201%2C%20%23checks%20do%0A%09%09%09local%20check%20%3D%20checks%5Bi%5D%0A%09%09%09local%20func%0A%09%09%09if%20check%3Astartswith%28%22%3E%3D%22%29%20then%0A%09%09%09%09func%20%3D%20ge%0A%09%09%09%09check%20%3D%20check%3Asub%283%29%0A%09%09%09elseif%20check%3Astartswith%28%22%3E%22%29%20then%0A%09%09%09%09func%20%3D%20gt%0A%09%09%09%09check%20%3D%20check%3Asub%282%29%0A%09%09%09elseif%20check%3Astartswith%28%22%3C%3D%22%29%20then%0A%09%09%09%09func%20%3D%20le%0A%09%09%09%09check%20%3D%20check%3Asub%283%29%0A%09%09%09elseif%20check%3Astartswith%28%22%3C%22%29%20then%0A%09%09%09%09func%20%3D%20lt%0A%09%09%09%09check%20%3D%20check%3Asub%282%29%0A%09%09%09elseif%20check%3Astartswith%28%22%3D%22%29%20then%0A%09%09%09%09func%20%3D%20eq%0A%09%09%09%09check%20%3D%20check%3Asub%282%29%0A%09%09%09elseif%20check%3Astartswith%28%22%5E%22%29%20then%0A%09%09%09%09func%20%3D%20compat%0A%09%09%09%09check%20%3D%20check%3Asub%282%29%0A%09%09%09else%0A%09%09%09%09func%20%3D%20ge%0A%09%09%09end%0A%0A%09%09%09check%20%3D%20semver%28check%29%0A%09%09%09if%20not%20func%28version%2C%20check%29%20then%0A%09%09%09%09return%20false%0A%09%09%09end%0A%09%09end%0A%0A%09%09return%20true%0A%09end%0A%0A%0A%0A%09function%20premake.clearWarnings%28%29%0A%09%09%5fwarnings%20%3D%20%7B%7D%0A%09end%0A%0A%0A%0A--%0A--%20Raise%20an%20error%2C%20with%20a%20formatted%20message%20built%20from%20the%20provided%0A--%20arguments.%0A--%0A--%20%40param%20message%0A--%20%20%20%20The%20error%20message%2C%20which%20may%20contain%20string%20formatting%20tokens.%0A--%20%40param%20...%0A--%20%20%20%20Values%20to%20fill%20in%20the%20string%20formatting%20tokens.%0A--%0A%0A%09function%20premake.error%28message%2C%20...%29%0A%09%09error%28string.format%28%22%2a%2a%20Error%3A%20%22%20..%20message%2C%20...%29%2C%200%29%0A%09end%0A%0A%0A--%0A--%20Finds%20the%20correct%20premake%20script%20filename%20to%20be%20run.%0A--%0A--%20%40param%20fname%0A--%20%20%20%20The%20filename%20of%20the%20script%20to%20run.%0A--%20%40return%0A--%20%20%20%20The%20correct%20location%20and%20filename%20of%20the%20script%20to%20run.%0A--%0A%0A%09function%20premake.findProjectScript%28fname%29%0A%09%09return%20os.locate%28fname%2C%20fname%20..%20%22.lua%22%2C%20path.join%28fname%2C%20%22premake5.lua%22%29%2C%20path.join%28fname%2C%20%22premake4.lua%22%29%29%0A%09end%0A%0A%0A---%0A--%20%22Immediate%20If%22%20-%20returns%20one%20of%20the%20two%20values%20depending%20on%20the%20value%0A--%20of%20the%20provided%20condition.%20Note%20that%20both%20the%20true%20and%20false%20expressions%0A--%20will%20be%20evaluated%20regardless%20of%20the%20condition%2C%20even%20if%20only%20one%20result%0A--%20is%20returned.%0A--%0A--%20%40param%20condition%0A--%20%20%20%20A%20boolean%20condition%2C%20determining%20which%20value%20gets%20returned.%0A--%20%40param%20trueValue%0A--%20%20%20%20The%20value%20to%20return%20if%20the%20condition%20is%20true.%0A--%20%40param%20falseValue%0A--%20%20%20%20The%20value%20to%20return%20if%20the%20condition%20is%20false.%0A--%20%40return%0A--%20%20%20%20One%20of%20trueValue%20or%20falseValue.%0A---%0A%0A%09function%20iif%28condition%2C%20trueValue%2C%20falseValue%29%0A%09%09if%20condition%20then%0A%09%09%09return%20trueValue%0A%09%09else%0A%09%09%09return%20falseValue%0A%09%09end%0A%09end%0A%0A%0A%0A---%0A--%20Override%20an%20existing%20function%20with%20a%20new%20implementation%3B%20the%20original%0A--%20function%20is%20passed%20as%20the%20first%20argument%20to%20the%20replacement%20when%20called.%0A--%0A--%20%40param%20scope%0A--%20%20%20%20The%20table%20containing%20the%20function%20to%20be%20overridden.%20Use%20%5fG%20for%0A--%20%20%20%20global%20functions.%0A--%20%40param%20name%0A--%20%20%20%20The%20name%20of%20the%20function%20to%20override%20%28a%20string%20value%29.%0A--%20%40param%20repl%0A--%20%20%20%20The%20replacement%20function.%20The%20first%20argument%20to%20the%20function%0A--%20%20%20%20will%20be%20the%20original%20implementation%2C%20followed%20by%20the%20arguments%0A--%20%20%20%20passed%20to%20the%20original%20call.%0A---%0A%0A%09function%20premake.override%28scope%2C%20name%2C%20repl%29%0A%09%09scope%2C%20name%20%3D%20p.resolveAlias%28scope%2C%20name%29%0A%0A%09%09local%20original%20%3D%20scope%5Bname%5D%0A%09%09if%20not%20original%20then%0A%09%09%09error%28%22unable%20to%20override%20%27%22%20..%20name%20..%20%22%27%3B%20no%20such%20function%22%2C%202%29%0A%09%09end%0A%0A%09%09scope%5Bname%5D%20%3D%20function%28...%29%0A%09%09%09return%20repl%28original%2C%20...%29%0A%09%09end%0A%0A%09%09--%20Functions%20from%20premake.main%20are%20special%20in%20that%20they%20are%20fetched%0A%09%09--%20from%20an%20array%2C%20which%20can%20be%20modified%20by%20system%20and%20project%20scripts%2C%0A%09%09--%20instead%20of%20a%20function%20which%20would%20have%20already%20been%20called%20before%0A%09%09--%20those%20scripts%20could%20have%20run.%20Since%20the%20array%20will%20have%20already%0A%09%09--%20been%20evaluated%20by%20the%20time%20override%28%29%20is%20called%2C%20the%20new%20value%0A%09%09--%20won%27t%20be%20picked%20up%20as%20it%20would%20with%20the%20function-fetched%20call%0A%09%09--%20lists.%20Special%20case%20the%20workaround%20for%20that%20here%20so%20everyone%20else%0A%09%09--%20can%20just%20override%20without%20having%20to%20think%20about%20the%20difference.%0A%09%09if%20scope%20%3D%3D%20premake.main%20then%0A%09%09%09table.replace%28premake.main.elements%2C%20original%2C%20scope%5Bname%5D%29%0A%09%09end%0A%09end%0A%0A%0A%0A---%0A--%20Find%20the%20canonical%20name%20and%20scope%20of%20a%20function%2C%20resolving%20any%20aliases.%0A--%0A--%20%40param%20scope%0A--%20%20%20%20The%20table%20containing%20the%20function%20to%20be%20overridden.%20Use%20%5fG%20for%0A--%20%20%20%20global%20functions.%0A--%20%40param%20name%0A--%20%20%20%20The%20name%20of%20the%20function%20to%20resolve.%0A--%20%40return%0A--%20%20%20%20The%20canonical%20scope%20and%20function%20name%20%28a%20string%20value%29.%0A---%0A%0A%09function%20p.resolveAlias%28scope%2C%20name%29%0A%09%09local%20aliases%20%3D%20%5faliases%5Bscope%5D%0A%09%09if%20aliases%20then%0A%09%09%09while%20aliases%5Bname%5D%20do%0A%09%09%09%09name%20%3D%20aliases%5Bname%5D%0A%09%09%09end%0A%09%09end%0A%09%09return%20scope%2C%20name%0A%09end%0A%0A%0A%0A--%0A--%20Display%20a%20warning%2C%20with%20a%20formatted%20message%20built%20from%20the%20provided%0A--%20arguments.%0A--%0A--%20%40param%20message%0A--%20%20%20%20The%20warning%20message%2C%20which%20may%20contain%20string%20formatting%20tokens.%0A--%20%40param%20...%0A--%20%20%20%20Values%20to%20fill%20in%20the%20string%20formatting%20tokens.%0A--%0A%0A%09function%20premake.warn%28message%2C%20...%29%0A%09%09message%20%3D%20string.format%28message%2C%20...%29%0A%09%09if%20%5fOPTIONS.fatal%20then%0A%09%09%09error%28message%29%0A%09%09else%0A%09%09%09term.pushColor%28term.warningColor%29%0A%09%09%09io.stderr%3Awrite%28string.format%28%22%2a%2a%20Warning%3A%20%22%20..%20message%20..%20%22%5Cn%22%2C%20...%29%29%0A%09%09%09term.popColor%28%29%3B%0A%09%09end%0A%09end%0A%0A%0A--%0A--%20Displays%20a%20warning%20just%20once%20per%20run.%0A--%0A--%20%40param%20key%0A--%20%20%20%20A%20unique%20key%20to%20identify%20this%20warning.%20Subsequent%20warnings%20messages%0A--%20%20%20%20using%20the%20same%20key%20will%20not%20be%20shown.%0A--%20%40param%20message%0A--%20%20%20%20The%20warning%20message%2C%20which%20may%20contain%20string%20formatting%20tokens.%0A--%20%40param%20...%0A--%20%20%20%20Values%20to%20fill%20in%20the%20string%20formatting%20tokens.%0A--%0A%0A%09function%20premake.warnOnce%28key%2C%20message%2C%20...%29%0A%09%09if%20not%20%5fwarnings%5Bkey%5D%20then%0A%09%09%09%5fwarnings%5Bkey%5D%20%3D%20true%0A%09%09%09premake.warn%28message%2C%20...%29%0A%09%09end%0A%09end%0A%0A%0A--%0A--%20Display%20information%20in%20the%20term.infoColor%20color.%0A--%0A--%20%40param%20message%0A--%20%20%20%20The%20info%20message%2C%20which%20may%20contain%20string%20formatting%20tokens.%0A--%20%40param%20...%0A--%20%20%20%20Values%20to%20fill%20in%20the%20string%20formatting%20tokens.%0A--%0A%0A%09function%20premake.info%28message%2C%20...%29%0A%09%09message%20%3D%20string.format%28message%2C%20...%29%0A%09%09term.pushColor%28term.infoColor%29%0A%09%09io.stdout%3Awrite%28string.format%28%22%2a%2a%20Info%3A%20%22%20..%20message%20..%20%22%5Cn%22%2C%20...%29%29%0A%09%09term.popColor%28%29%3B%0A%09end%0A%0A%0A%0A--%0A--%20A%20shortcut%20for%20printing%20formatted%20output.%0A--%0A%0A%09function%20printf%28msg%2C%20...%29%0A%09%09print%28string.format%28msg%2C%20...%29%29%0A%09end%0A%0A--%0A--%20A%20shortcut%20for%20printing%20formatted%20output%20in%20verbose%20mode.%0A--%0A%09function%20verbosef%28msg%2C%20...%29%0A%09%09if%20%5fOPTIONS.verbose%20then%0A%09%09%09print%28string.format%28msg%2C%20...%29%29%0A%09%09end%0A%09end%0A%0A%0A--%0A--%20make%20a%20string%20from%20debug.getinfo%20information.%0A--%0A%09function%20filelineinfo%28level%29%0A%09%09local%20info%20%3D%20debug.getinfo%28level%2B1%2C%20%22Sl%22%29%0A%09%09if%20info%20%3D%3D%20nil%20then%0A%09%09%09return%20nil%0A%09%09end%0A%09%09if%20info.what%20%3D%3D%20%22C%22%20then%0A%09%09%09return%20%22C%20function%22%0A%09%09else%0A%09%09%09local%20sep%20%3D%20iif%28os.ishost%28%27windows%27%29%2C%20%27%5C%5C%27%2C%20%27%2F%27%29%0A%09%09%09return%20string.format%28%22%25s%28%25d%29%22%2C%20path.translate%28info.short%5fsrc%2C%20sep%29%2C%20info.currentline%29%0A%09%09end%0A%09end%0A%0A%0A---%0A--%20check%20if%20version%20is%20semver.%0A---%0A%0A%09function%20premake.isSemVer%28version%29%0A%09%09local%20sMajor%2C%20sMinor%2C%20sPatch%2C%20sPrereleaseAndBuild%20%3D%20version%3Amatch%28%22%5E%28%25d%2B%29%25.%3F%28%25d%2a%29%25.%3F%28%25d%2a%29%28.-%29%24%22%29%0A%09%09return%20%28type%28sMajor%29%20%3D%3D%20%27string%27%29%0A%09end), the file is 1 line, and replacing all the semicolons `;` with newlines results in only 49 lines.

**Comment by catb0t** [comment]
(by the way, [the wiki](https://github.com/premake/premake-core/wiki/Makefile-Projects) isn't right, Makefile projects work with `gmake` generator)

**Comment by samsinsane** [comment]
Hmm looks like the code in `gmake2_makefile.lua` is just cactus. [This](https://github.com/premake/premake-core/blob/117fc82f8168f86443bf2b5409d3aaa3c4cf8e38/modules/gmake2/gmake2_makefile.lua#L37) and [this](https://github.com/premake/premake-core/blob/117fc82f8168f86443bf2b5409d3aaa3c4cf8e38/modules/gmake2/gmake2_makefile.lua#L60) are wrong. They should be in the form of `p.callarray(namespace.with.multiple.levels, "singlelevelkey", ...)` or `p.callarray(namespace.with.multiple.levels.singlelevelkey, ...)`, apparently the former is deprecated according to [this](https://github.com/premake/premake-core/blob/3708b49d54dad9bd4a3c479cfe52503477229694/src/base/_foundation.lua#L105-L129)(this is where the error you're getting comes from - second function, first line).
