### ISSUE TITLE
cross-platform scandir or listdir function in os

### ISSUE THREAD

**Issue by catb0t** [premake/premake-core#975]
instead of writing 
```lua
for dir in io.popen("find src/lib/ -maxdepth 1 -type d | tail -1"):lines() do print(dir) end 
```

i'd like to write 
```lua
for dir in os.scandir(path.join("src", "lib")) do print(dir) end
```

because then it wouldn't rely on unix-like tools, like `find(1)` and `tail(1)`, and would work on Windows (etc).

**Comment by samsinsane** [comment]
You could do:
```lua
local m = os.matchstart(path.join("src", "lib"))
while os.matchnext(m) do
  if not os.matchisfile(m) then
    print(os.matchname(m)
  end
end
os.matchdone(m)
```

Not 100% sure if that will run, didn't test, just grabbed it from [here](https://github.com/premake/premake-core/blob/5a0b07cd45aeb0d3a90a28a34744c2f610655abc/src/base/os.lua#L360-L367) and slightly adapted it.

**Comment by catb0t** [comment]
Here's the function after some R&D:

```lua
function os.scandir(pth)
  local m = os.matchstart(pth .. "/*")
  local dirs = {}

  while os.matchnext(m) do
    if not os.matchisfile(m) then
      table.insert(dirs, os.matchname(m))
    end
  end

  os.matchdone(m)

  return dirs
end
```

use it like 
```lua
for k,v in next, os.scandir(path.join("src", "lib") .. "/*") do print(k,v) end
1	lib
2	object
3	compile
4	lex
5	stack
```

**Comment by ratzlaff** [comment]
We use [os.matchdirs](https://github.com/premake/premake-core/wiki/os.matchdirs)

    for _,dir in ipairs(os.matchdirs("../src/*")) do
        print(dir)
    end

**Comment by samsinsane** [comment]
I knew we had something, I couldn't find it though - my bad.

**Comment by starkos** [comment]
In hindsight, it might have been nice to have written the `match*` functions as iterators, but @ratzlaff shows how to bridge the gap. Is more work needed here, or can this one be closed?

**Comment by catb0t** [comment]
thanks for the help :)
