### ISSUE TITLE
filter: express "and"

### ISSUE THREAD

**Issue by catb0t** [premake/premake-core#976]
the wiki has 
```lua
configuration { "linux", "gmake" }
```

as an example. `configuration` will not be supported much longer, so we have to use `filter`. how to express `filter "system:linux and action:gmake*"` for example? 

a `filter` inside a `filter` would be nice except `filter`s cannot be nested.

**Comment by samsinsane** [comment]
The same was as it's handled in `configurations`:
```lua
filter { "system:linux", "action:gmake" }
```
The [wiki for `filter`](https://github.com/premake/premake-core/wiki/filter) does mention this, way way way down the page very casually:
> When multiple keywords are listed, an implicit __and__ is assumed between them.

Let's leave this open until we make it more obvious how to `and`, given that it states `or` and `not` frequently on both [`filter`](https://github.com/premake/premake-core/wiki/filter) and [Filter](https://github.com/premake/premake-core/wiki/Filters). Quite strange.

**Comment by starkos** [comment]
The wiki is open to edit—would you mind making that change?

**Comment by catb0t** [comment]
it's changed, i forgot to close this :)
