### ISSUE TITLE
%{cfg.architecture} and %{cfg.platform} resolve to empty strings in Makefile

### ISSUE THREAD

**Issue by SanderMertens** [premake/premake-core#978]
I'm trying to set the target directory for a project based on the platform I'm generating for. So far, I've tried:
```lua
targetdir "%{cfg.platform}"
```
In my makefile (generated with `premake5 gmake`), this yields `TARGETDIR = `.

```lua
targetdir "%{cfg.architecture}-%{cfg.system}"
```
This yields `TARGETDIR = -linux`.

Is this the right way to include architecture in the target directory? I am using premake5, alpha 12.

The `%{cfg.platform}` token was used in this tutorial: https://github.com/JohannesMP/Premake-for-Beginners/blob/master/Build/premake5.lua

Trying to figure out where my code is different, but must be glancing over it.

For clarity, I cannot use `if os.is64bit then` because the Makefile needs to be portable between `x86` and `x64` architectures.

**Comment by samsinsane** [comment]
Can you provide a larger snippet of your Premake script? I don't see any reason why `cfg.architecture` would fail but not `cfg.system`, my initial guess would be that you're not specifying a platform at all and the defaults aren't working properly.

Do you have the following snippets from that tutorial? [This](https://github.com/JohannesMP/Premake-for-Beginners/blob/3857049d54953e58dccb99eff9e8f0068fd8fc68/Build/premake5.lua#L11) and [this](https://github.com/JohannesMP/Premake-for-Beginners/blob/master/Build/premake5.lua#L31-L32)? I'm not sure if the latter is required, but perhaps it is.

**Comment by SanderMertens** [comment]
You're right, when I add `platforms { "x64", "x32" }`, `x86_64` is filled out for the platform.

I may have misunderstood this feature, as it is not exactly what I am looking for. I was trying to generate a makefile that based on the platform that it is executed on, puts objects in a different directory. This option hardcodes the platform on which the _makefile is generated_ in the Makefile, which isn't what I need..

If you know of any featurs to achieve what I'm looking for, that'd be super helpful!

**Comment by starkos** [comment]
As you can see, Premake variables are only available at the time that Premake is run, not when the generated Makefile is executed.

The only solution I can think of would be to put a shell command in [makesettings](https://github.com/premake/premake-core/wiki/makesettings) that would detect the platform and assign it to a Make variable, and then use that variable in your target path.

**Comment by starkos** [comment]
I don't think so. VS is much more strict about its definition of target architectures. I'm not sure if a "we'll wing it when we get there" approach is going to work in that environment. If you are planning to be portable across toolsets, it will make your life a lot easier if you define your target platforms explicitly up front, rather than trying to deduce them at build time.

**Comment by starkos** [comment]
I'm going to go ahead and close this issue, as the original question has been answered. Feel free to open a new issue to discuss configuring VS if you like though!
