### ISSUE TITLE
cppdialect generates wrong option.

### ISSUE THREAD

**Issue by qatnonoil** [premake/premake-core#984]
Hi.

"cppdialect "C++14"" and "flags { "C++14" }" on premake5 alpha12 generates "-std=C++14", and build fails. Is it "-std=c++14"?(case differ)

thanks.

**Comment by samsinsane** [comment]
I'm fairly certain that this has already been patched, it looks that way from [here](https://github.com/premake/premake-core/blob/ef9b341d6f9cb1208d60d2dcdea399adf2014b8b/src/tools/gcc.lua#L136-L151).

**Comment by samsinsane** [comment]
I'm going to close this as I believe it is fixed in master, please feel free to reopen if it is occurring in master too.

**Comment by qatnonoil** [comment]
Hi.

Sorry for late reply.
I still have same probrem.
Version is "5.0.0-alpha12".

```
require("premake", ">=5.0.0-alpha12")
solution "Test"
   location "generated"
   configurations { "Debug", "Release" }
   platforms {"x64"}

project "Test"
   kind "ConsoleApp"
   language "C++"
   characterset "MBCS"
   cppdialect "C++14"
```

And command are..
```
$> ./premake5 xcode4
```

Thanks.

**Comment by samsinsane** [comment]
I believe this was patched *after* the release of alpha 12, so you'd need to use latest master to get the fix.
