### ISSUE TITLE
Premake.override() works with 5.0.0 alpha11, but NOT with 5.0.0 alpha12

### ISSUE THREAD

**Issue by Ryan-Moon** [premake/premake-core#985]
The following "override" code works with 5.0.0 alpha11, but NOT with latest 5.0.0 alpha12. Could you have a look this issue please?

*The error message is something like: 

Error: [string "src/base/_foundation.lua"]:135: attempt to index a nil value (local 'scope')

*My code is something like:

premake.override(premake.vstudio.vc200x, "programDataBaseFileName", function(base, cfg, toolset)
	if cfg.symbolspath and cfg.symbols == premake.ON and cfg.debugformat ~= "c7" then
		premake.w('ProgramDataBaseFileName="$(IntDir)\\"')
	end
end)

premake.override(premake.vstudio.vc200x, "programDatabaseFile", function(base, cfg, toolset)
	if cfg.symbolspath and cfg.symbols == premake.ON and cfg.debugformat ~= "c7" then
		premake.w('ProgramDataBaseFile="$(OutDir)\\$(TargetName).pdb"')
	end
end)

**Comment by starkos** [comment]
We're stretched pretty thin over here. Having more information about exactly what's breaking would be a help.

**Comment by tdesveauxPKFX** [comment]
I had the same issue when upgrading to alpha 12.

vstudio is now a module in alpha 12 and you need to do a `require ('vstudio')` before any override.

**Comment by starkos** [comment]
Thanks @tdesveauxPKFX! This has come up before, I should have remembered. Going to close this for now, but feel free to reopen as needed @Ryan-Moon.

**Comment by Ryan-Moon** [comment]
Thanks @tdesveauxPKFX! It works well.
