### ISSUE TITLE
Wrong parent workspace location

### ISSUE THREAD

**Issue by cosmy1** [premake/premake-core#987]
The below code snippet fails under Visual Studio. (I tested it with Visual Studio 2017)
```lua
workspace ("Test")
    location (".generated")
    configurations { "Release", "Debug" }
    project "Client"
        kind "ConsoleApp"
        targetdir ("%{wks.location}/../Build")
```
I expect the binary output at "../Build" but instead it gets located at "../../Build".

Replacing
```lua
location (".generated")
```
with
```lua
location ("generated")
```
works as expected.

**Comment by samsinsane** [comment]
@cosmy1 did you want to try using my PR to see if it fixes your issue?

**Comment by cosmy1** [comment]
The PR fixes the issue. Thank you!
