### ISSUE TITLE
In some cases, create precompiled headers fails.

### ISSUE THREAD

**Issue by panhaowen** [premake/premake-core#989]
In vs2017, I use the 'pchheader(path/ A.h) 'and 'pchsource(path/A.cpp)' to create precompiled headers, and my 'premake. lua' file location is successful if it happens to be in 'path', and if my 'premake. lua 'is in XXX /path/premake. Lua, I use includedir('.../../path') to include the path of A.h and A.cpp, and then use the 'pchheader(A.h) 'and 'pchheader(A.cpp)' to create the failure.

It looks like this:
[
/myroot/mywork/myproj/src/path/A.h
/myroot/mywork/myproj/src/path/A.cpp
/myroot/mywork/myproj/src/premake.lua
][
pchheader(path/A.h) 
pchsource(path/A.cpp)
]==>OK(Has <ClCompile Include="xxx\path\A.cpp">
      <PrecompiledHeader>Create</PrecompiledHeader>
    </ClCompile>)

[
/myroot/mywork/myproj/mycfg/premake.lua
/myroot/mywork/myproj/src/path/A.h
/myroot/mywork/myproj/src/path/A.cpp
][
local local_path=_WORKING_DIR .. "/../path"
includedirs(local_path)
pchheader(A.h) 
pchsource(A.cpp)
]
or
[
local local_path=_WORKING_DIR .. "/../"
includedirs(local_path)
pchheader(path/A.h) 
pchsource(path/A.cpp)
]
or
[
local local_path=_WORKING_DIR .. "/../"
includedirs(local_path)
pchheader(path/A.h) 
pchsource(local_path .. path/A.cpp)
]==>FAILED

I looked at the source code, but I didn't quite understand the meaning of "prjcfg.pchsource == filecfg.abspath".

function m.precompiledHeader(cfg, condition)
		prjcfg, filecfg = p.config.normalize(cfg)
		if filecfg then
			if prjcfg.pchsource == filecfg.abspath and not prjcfg.flags.NoPCH then
				m.element('PrecompiledHeader', condition, 'Create')
			elseif filecfg.flags.NoPCH then
				m.element('PrecompiledHeader', condition, 'NotUsing')
			end
		else
			if not prjcfg.flags.NoPCH and prjcfg.pchheader then
				m.element("PrecompiledHeader", nil, "Use")
				m.element("PrecompiledHeaderFile", nil, "%s", prjcfg.pchheader)
			else
				m.element("PrecompiledHeader", nil, "NotUsing")
			end
		end
	end

**Comment by samsinsane** [comment]
> I looked at the source code, but I didn't quite understand the meaning of "prjcfg.pchsource == filecfg.abspath".

It's checking if the current file (`filecfg`) has the same path (`abspath`) as the `pchsource` specified in the current configuration (`prjcfg` - "Release x64", "Debug x64", et al). In the event that they're the same, it emits the element `<PrecompiledHeader condition="Release x64">Create</PrecompiledHeader>`, more or less.

Given the file layout:
```
/myroot/mywork/myproj/mycfg/premake.lua
/myroot/mywork/myproj/src/path/A.h
/myroot/mywork/myproj/src/path/A.cpp
```
You said you tried:
```lua
local local_path=_WORKING_DIR .. "/../path" -- see below, this might need to be "/../src/path"
includedirs(local_path)
pchheader(A.h)
pchsource(A.cpp)
```
It looks like your `includedirs` will be `/myroot/mywork/myproj/path` instead of `/myroot/mywork/myproj/src/path`, perhaps this is your issue?

**Comment by panhaowen** [comment]
I actually want to separate the premake file and the source file into a different folder, and the precompiled header file exists separately in a file, so my file layout is the following.
/myroot/mywork/myproj/mycfg/premakeA.lua
/myroot/mywork/myproj/mycfg/premakeB.lua
/myroot/mywork/myproj/src/moduleA/PCH/A.h
/myroot/mywork/myproj/src/moduleA/PCH/A.cpp
/myroot/mywork/myproj/src/moduleAOtherFiles/**.cpp and **.h
/myroot/mywork/myproj/src/moduleB/PCH/A.h
/myroot/mywork/myproj/src/moduleB/PCH/A.cpp
/myroot/mywork/myproj/src/moduleBOtherFiles/**.cpp and **.h
So I wrote this in premakeA.lua :
local source_path =_WORKING_DIR .. "/../src/moduleA/"
includedirs(source_path)
pchheader(PCH/A.h)
pchsource(PCH/A.cpp)
The result 'pchheader' went into effect, but 'pchsource' didn't work.
I don't know how to solve this problem. Thank you very much for helping me.

**Comment by panhaowen** [comment]
Typing error
/myroot/mywork/myproj/src/moduleB/PCH/B.h
/myroot/mywork/myproj/src/moduleB/PCH/B.cpp

**Comment by samsinsane** [comment]
> pchheader(PCH/A.h)
pchsource(PCH/A.cpp)

To my understanding these need to be `A.h` and `A.cpp` respectively, with `source_path` having `PCH/` appended on the end.

**Comment by tdesveauxPKFX** [comment]
it's been some time since I looked at pch but here is how I managed to make it work for us.

For a project like:
```
- root
    premake.lua
  - include
  - src
  - precompiled
      precompiled.h
      precompiled.cpp
```

your `pchheader` should be the same as the `#include` in your source files.
So we have `#include "precompiled.h"` and in our lua, `pchheader "precompiled.h"`
For this to work you need to add the path to your precompiled header with `includedirs`
I do not remember why it needs to be this way so maybe it is not necessary but it probably has something to do with visual studio.

Then you set `pchsource` with the full path to the .cpp file.

Which would give something like:

```
projectRoot = "./"
project "prj"

    includedirs(projectRoot.."precompiled")

    pchheader("precompiled.h")
    pchsource(projectRoot.."precompiled/precompiled.cpp")
```

> local source_path =_WORKING_DIR .. "/../src/moduleA/"
> includedirs(source_path)
> pchheader(PCH/A.h)
> pchsource(PCH/A.cpp)

I think this does not work as `_WORKING_DIR/PCH/A.cpp` does not exists.
`PCH/A.h` is found because you told premake to look for it in `source_path`.

I hope this helps.

**Comment by panhaowen** [comment]
Thank you. I solved my problem.
Under Windows, it must be a path relative to 'premake.lua'(LocalSourceDir )

Here is my example of success.
local AbsSourceDir = Hulua.SourceDir .. "Authoring/AssetCooking/"
local LocalSourceDir = "../../../Source/Authoring/AssetCooking/"

Hulua.Project "AssetCooking"

	kind "ConsoleApp" 
	language "C++"

	includedirs {
		AbsSourceDir,
	}

	files {
		AbsSourceDir .. "**.h",
		AbsSourceDir .. "**.cpp",
	}

if Hulua.Build_Platform == Hulua.Windows then
	pchheader(
		"PCH/ACPrivatePCH.h"
	)
	pchsource(
		LocalSourceDir .. "PCH/ACPrivatePCH.cpp"
	)
elseif Hulua.Build_Platform == Hulua.iOS or Hulua.Build_Platform == Hulua.MacOS then
	pchheader(
		AbsSourceDir .. "PCH/ACPrivatePCH.h"
	)
	pchsource(
		AbsSourceDir .. "PCH/ACPrivatePCH.cpp"
	)
end

**Comment by starkos** [comment]
Cool…I'm going to mark this as closed. If you run into any other trouble, be sure to read [the wiki page on precompiled headers](https://github.com/premake/premake-core/wiki/Precompiled-Headers), and then feel free to reopen if you're still stuck.
