### ISSUE TITLE
import existing project into workspace

### ISSUE THREAD

**Issue by Sairony** [premake/premake-core#991]
I use a setup where I have multiple workspaces. Regenerating the master workspace & letting VS reload everything is kind of slow, and overall the master workspace contains more than is needed when you're working on a specific project & its dependencies. Something like:

`importproject 'WorkspaceWhichDefinesIt/SomeProject'` would be nice. Don't know if it's portable across different platforms, but it's possible with VS at least.

**Comment by starkos** [comment]
Have a look at [externalproject](https://github.com/premake/premake-core/wiki/externalproject). You can generate the master workspace once, and then when you generate a more specific workspace, you can just reference the already created projects.

I'm going to mark this as closed, but feel free to reopen if you have questions, or if I've misunderstood your use case!

**Comment by ratzlaff** [comment]
At my company we also have a master workspace that contains build solutions for *everything*

What we have found that works well is to unload the projects that we are not actively developing/debugging, VS won't try to reload them when they get regenerated. 

To help with the unloading process, we use [group](https://github.com/premake/premake-core/wiki/group) to collect the optional (ie: plugins and tools) build artifacts into an easy-to-unload folder within the solution explorer.

**Comment by Sairony** [comment]
Thanks for the help & suggestions. The problem with externalproject is that it seems to be a bit clunky when referencing projects already defined in a workspace somewhere. Since one needs to deduce UUID, kind etc. I have a working `importproject` which works as I mentioned before, but it's for an old version of premake5, if I port it over to the current head do you think it would be possible to get it in? It's a pain to maintain it on the side since we usually only upgrade once we need support for a new toolset version.
