### ISSUE TITLE
Premake self-test fails if libm is static, no static lib finding?

### ISSUE THREAD

**Issue by ikirker** [premake/premake-core#995]
For context: I'm very new to Premake, just looking at trying it out for the first time.

I followed the "Building Premake" guide, ran the test, and got:
```
Running action 'test'...
base_os.findlib_FindSystemLib: ...iki/premake/premake-5.0.0-alpha12/tests/base/test_os.lua:31: expected true but was false
1602 tests passed, 1 failed in 1.98 seconds
```

Some investigation shows that that's this test:
```lua
test.istrue(os.findlib("m"))
```

Now, I do *have* a libm, but it's a static `libm.a`, not `libm.so`, in `/usr/lib/libm.a`. My system behaves perfectly normally for building various software with GCC regardless. (Unless that software strictly requires glibc instead of Alpine's MUSL, but I haven't run into that yet.)

I had a look through the wiki, and there doesn't seem to be any separate mention of static libraries, so I took a look in the source, and it looks like there's no facility for finding static `lib*.a` libraries. Is this correct? It seems a bit odd.

**Comment by starkos** [comment]
Well…in order to validate the `findlib()` feature we have two look for *something* on the system, and since Premake links against `libm` anyway, it seemed a likely candidate. We can certainly switch it to something else.

> I took a look in the source, and it looks like there's no facility for finding static lib*.a libraries. Is this correct? It seems a bit odd.

It is correct. Apparently, no one has needed that feature enough to write it?

I'm going to mark this as closed, since that technically answers your question. But please feel free to reopen if you want to continue the discussion, or have any interest in exploring a static library finder further!

**Comment by ikirker** [comment]
@starkos I'll give it some thought, and investigate Premake some more to see how it works and what sort of form a static library finder would take, relative to the dynamic one. I guess it could be a bit of a can of worms given that then someone could probably want some kind of option to find either and default and express preference one way or the other.

I admit I was surprised to find that I didn't have a `libm.so`, and my build of Premake is only dynamically linked against the core `/lib/ld-musl-x86_64.so.1`. It's good to be sure that my build isn't failing its tests because something with *it* is wrong, at least. A little more investigation suggests Alpine only installs a dynamic libm with a compatibility package `libc6-compat`.

Thank you for the helpful response, in any case!

(Sorry if this re-opens the issue unnecessarily.)
